begin;
-- Swedish-gifi.sql
INSERT  INTO gifi (accno,description) VALUES ('200','Kassa och bank ');
INSERT  INTO gifi (accno,description) VALUES ('202','Aktier och andelar ');
INSERT  INTO gifi (accno,description) VALUES ('203','Övriga kortfristiga placeringar');
INSERT  INTO gifi (accno,description) VALUES ('204','Kundfordringar');
INSERT  INTO gifi (accno,description) VALUES ('205','Förutbetalda kostnader och upplupna intäkter');
INSERT  INTO gifi (accno,description) VALUES ('206','Övriga skattefordringar');
INSERT  INTO gifi (accno,description) VALUES ('207','Momsfordran');
INSERT  INTO gifi (accno,description) VALUES ('219','Varulager och pågående arbeten');
INSERT  INTO gifi (accno,description) VALUES ('220','Övriga kortfristiga fordringar');
INSERT  INTO gifi (accno,description) VALUES ('230','Aktier och andelar i svenska koncern- och intresseföretag ');
INSERT  INTO gifi (accno,description) VALUES ('231','Aktier och andelar i utländska koncern- och intresseföretag');
INSERT  INTO gifi (accno,description) VALUES ('233','Finansiella anläggningstillgångar');
INSERT  INTO gifi (accno,description) VALUES ('234','Immateriella anläggningstillgångar');
INSERT  INTO gifi (accno,description) VALUES ('235','Mark och andra tillgångar som inte är avskrivningsbara (skattemässigt)');
INSERT  INTO gifi (accno,description) VALUES ('236','Maskiner och inventarier');
INSERT  INTO gifi (accno,description) VALUES ('237','Byggnader och övrig fast egendom');
INSERT  INTO gifi (accno,description) VALUES ('241','Fordringar på koncern- och intresseföretag');
INSERT  INTO gifi (accno,description) VALUES ('299','Summa tillgångar');
INSERT  INTO gifi (accno,description) VALUES ('300','Leverantörsskulder');
INSERT  INTO gifi (accno,description) VALUES ('301','Övriga skatteskulder');
INSERT  INTO gifi (accno,description) VALUES ('302','Övriga avsättningar');
INSERT  INTO gifi (accno,description) VALUES ('304','Avsättningar för garantier');
INSERT  INTO gifi (accno,description) VALUES ('305','Upplupna kostnader och förutbetalda intäkter');
INSERT  INTO gifi (accno,description) VALUES ('307','Momsskuld');
INSERT  INTO gifi (accno,description) VALUES ('310','Förskott från kunder');
INSERT  INTO gifi (accno,description) VALUES ('319','Övriga kortfristiga skulder');
INSERT  INTO gifi (accno,description) VALUES ('320','Avsättningar för pensioner');
INSERT  INTO gifi (accno,description) VALUES ('321','Lån från aktieägare (lång- och kortfristiga)');
INSERT  INTO gifi (accno,description) VALUES ('329','Långfristiga skulder');
INSERT  INTO gifi (accno,description) VALUES ('330','Ackumulerade överavskrivningar');
INSERT  INTO gifi (accno,description) VALUES ('339','Övriga obeskattade reserver ');
INSERT  INTO gifi (accno,description) VALUES ('340','Periodiseringsfond vid 2000 års taxering');
INSERT  INTO gifi (accno,description) VALUES ('341','Periodiseringsfond vid 2001 års taxering');
INSERT  INTO gifi (accno,description) VALUES ('343','Periodiseringsfond vid 2003 års taxering');
INSERT  INTO gifi (accno,description) VALUES ('344','Periodiseringsfond vid 2004 års taxering');
INSERT  INTO gifi (accno,description) VALUES ('345','Periodiseringsfond vid 2005 års taxering');
INSERT  INTO gifi (accno,description) VALUES ('342','Periodiseringsfond vid 2002 års taxering');
INSERT  INTO gifi (accno,description) VALUES ('350','Aktiekapital/Insatskapital');
INSERT  INTO gifi (accno,description) VALUES ('351','Övrigt bundet eget kapital');
INSERT  INTO gifi (accno,description) VALUES ('354','Fritt eget kapital');
INSERT  INTO gifi (accno,description) VALUES ('360','Ingående kapital (vid kapitalbrist anges minus)');
INSERT  INTO gifi (accno,description) VALUES ('362','Delägarnas uttag');
INSERT  INTO gifi (accno,description) VALUES ('363','Delägarnas tillskott');
INSERT  INTO gifi (accno,description) VALUES ('364','Kontanta uttag');
INSERT  INTO gifi (accno,description) VALUES ('365','Övriga uttag');
INSERT  INTO gifi (accno,description) VALUES ('366','Kontanta tillskott');
INSERT  INTO gifi (accno,description) VALUES ('367','Övriga tillskott');
INSERT  INTO gifi (accno,description) VALUES ('368','Årets redovisade vinst');
INSERT  INTO gifi (accno,description) VALUES ('369','Årets redovisade förlust');
INSERT  INTO gifi (accno,description) VALUES ('370','Utgående kapital');
INSERT  INTO gifi (accno,description) VALUES ('399','Summa eget kapital och skulder');
INSERT  INTO gifi (accno,description) VALUES ('400','Rörelsens huvudintäkter (nettoomsättning)');
INSERT  INTO gifi (accno,description) VALUES ('401','Övriga rörelseintäkter');
INSERT  INTO gifi (accno,description) VALUES ('402','Aktiverat arbete för egen räkning');
INSERT  INTO gifi (accno,description) VALUES ('500','Handelsvaror inkl. lagerförändring, råvaror, material m.m.');
INSERT  INTO gifi (accno,description) VALUES ('501','Legoarbeten och underentreprenörer');
INSERT  INTO gifi (accno,description) VALUES ('509','Förändring av lager (inte handelsvaror) och pågående arbeten (ökning)');
INSERT  INTO gifi (accno,description) VALUES ('510','Förändring av lager (inte handelsvaror) och pågående arbeten (minskning)');
INSERT  INTO gifi (accno,description) VALUES ('511','AMF-avgifter ');
INSERT  INTO gifi (accno,description) VALUES ('512','Löner och andra ersättningar');
INSERT  INTO gifi (accno,description) VALUES ('514','Kostnadsersättningar och kostnader för förmåner till anställda');
INSERT  INTO gifi (accno,description) VALUES ('520','Övriga sociala avgifter');
INSERT  INTO gifi (accno,description) VALUES ('524','Pensionskostnader (inklusive ITP-avgifter)');
INSERT  INTO gifi (accno,description) VALUES ('526','Reparation och underhåll av fastighet');
INSERT  INTO gifi (accno,description) VALUES ('527','Övriga personalkostnader');
INSERT  INTO gifi (accno,description) VALUES ('528','Övriga lokal- och fastighetskostnader');
INSERT  INTO gifi (accno,description) VALUES ('529','Hyra av anläggningstillgångar');
INSERT  INTO gifi (accno,description) VALUES ('530','Övriga kostnader');
INSERT  INTO gifi (accno,description) VALUES ('531','Förbrukningsinventarier');
INSERT  INTO gifi (accno,description) VALUES ('536','Bilkostnader (inkl. billeasing)');
INSERT  INTO gifi (accno,description) VALUES ('538','Övriga transportmedels- kostnader och rese- kostnader ');
INSERT  INTO gifi (accno,description) VALUES ('541','Reklam och PR');
INSERT  INTO gifi (accno,description) VALUES ('550','Vinst vid avyttring av värdepapper ');
INSERT  INTO gifi (accno,description) VALUES ('551','Förlust vid avyttring av värdepapper');
INSERT  INTO gifi (accno,description) VALUES ('552','Vinst vid avyttring av anläggningstillgångar (ej finansiella) ');
INSERT  INTO gifi (accno,description) VALUES ('553','Nedskrivning av anläggningstillgångar (ej finansiella)');
INSERT  INTO gifi (accno,description) VALUES ('554','Återföring av nedskrivning av anläggningstillgångar (ej finansiella)');
INSERT  INTO gifi (accno,description) VALUES ('556','Förlust vid avyttring av anläggningstillgångar (ej finansiella)');
INSERT  INTO gifi (accno,description) VALUES ('559','Maskiner och inventarier');
INSERT  INTO gifi (accno,description) VALUES ('560','Byggnader och övrig fast egendom');
INSERT  INTO gifi (accno,description) VALUES ('561','Immateriella anläggningstillgångar');
INSERT  INTO gifi (accno,description) VALUES ('564','Utdelning på aktier och andelar i koncern- och intresseföretag');
INSERT  INTO gifi (accno,description) VALUES ('565','Utdelning på aktier och andelar i övriga företag');
INSERT  INTO gifi (accno,description) VALUES ('566','Valutakursvinster');
INSERT  INTO gifi (accno,description) VALUES ('567','Valutakursförluster');
INSERT  INTO gifi (accno,description) VALUES ('568','Ränteintäkter m.m.');
INSERT  INTO gifi (accno,description) VALUES ('569','Räntekostnader m.m.');
INSERT  INTO gifi (accno,description) VALUES ('570','Nedskrivning av finansiella tillgångar');
INSERT  INTO gifi (accno,description) VALUES ('571','Återföring av nedskrivning av finansiella tillgångar');
INSERT  INTO gifi (accno,description) VALUES ('578','Bokförd avskrivning utöver plan ');
INSERT  INTO gifi (accno,description) VALUES ('586','Avsättning till periodiseringsfond ');
INSERT  INTO gifi (accno,description) VALUES ('589','Återföring från periodiseringsfond ');
INSERT  INTO gifi (accno,description) VALUES ('590','Upplösning av ackumulerade överavskrivningar');
INSERT  INTO gifi (accno,description) VALUES ('593','Övriga tillkommande bokslutsdispositioner m.m. ');
INSERT  INTO gifi (accno,description) VALUES ('594','Övriga avgående bokslutsdispositioner m.m.');
INSERT  INTO gifi (accno,description) VALUES ('596','Redovisad förlust enligt bokföringen');
INSERT  INTO gifi (accno,description) VALUES ('598','Skatter');
INSERT  INTO gifi (accno,description) VALUES ('599','Redovisad vinst enligt bokföringen');
commit;
