begin;
-- contribué par Jens-Ingo Brodesser, jens-ingo@all2all.org, Moving Art Studio ASBL, ALL2ALL The Independent Network
-- le 15/07/2003

INSERT INTO gifi (accno,description) VALUES ('10','Capital');
INSERT INTO gifi (accno,description) VALUES ('30','Approvisionnements - Matières premières');
INSERT INTO gifi (accno,description) VALUES ('11','Primes d''émission');
INSERT INTO gifi (accno,description) VALUES ('12','Plus-values de réévaluation');
INSERT INTO gifi (accno,description) VALUES ('13','Réserves');
INSERT INTO gifi (accno,description) VALUES ('14','Bénéfice reporté [ou Perte reportée (-)]');
INSERT INTO gifi (accno,description) VALUES ('15','Subsides en capital');
INSERT INTO gifi (accno,description) VALUES ('16','Provisions pour risques et charges et impôts différés');
INSERT INTO gifi (accno,description) VALUES ('17','Dettes à plus d''un an');
INSERT INTO gifi (accno,description) VALUES ('40','Créances commerciales');
INSERT INTO gifi (accno,description) VALUES ('20','Frais d''établissement');
INSERT INTO gifi (accno,description) VALUES ('21','Immobilisations incorporelles');
INSERT INTO gifi (accno,description) VALUES ('22','Terrains et constructions');
INSERT INTO gifi (accno,description) VALUES ('23','Installations, machines et outillage');
INSERT INTO gifi (accno,description) VALUES ('24','Mobilier et matériel roulant');
INSERT INTO gifi (accno,description) VALUES ('25','Immobilisations détenues en location-finac. et droits similaires');
INSERT INTO gifi (accno,description) VALUES ('31','Approvis. - Fournitures');
INSERT INTO gifi (accno,description) VALUES ('27','Autres immobilisations corporelles en cours et acompts versés');
INSERT INTO gifi (accno,description) VALUES ('26','Autres immobilisations corporelles');
INSERT INTO gifi (accno,description) VALUES ('28','Immobilisations financières');
INSERT INTO gifi (accno,description) VALUES ('29','Créances à plus d''un an');
INSERT INTO gifi (accno,description) VALUES ('4115','TVA DUE TOTAL');
INSERT INTO gifi (accno,description) VALUES ('33','Produits finis');
INSERT INTO gifi (accno,description) VALUES ('32','Encours fabrication');
INSERT INTO gifi (accno,description) VALUES ('34','Marchandises');
INSERT INTO gifi (accno,description) VALUES ('35','Immeubles déstinés à la vente');
INSERT INTO gifi (accno,description) VALUES ('36','Acomptes s/achats stocks');
INSERT INTO gifi (accno,description) VALUES ('37','Commandes en cours d''exécution');
INSERT INTO gifi (accno,description) VALUES ('41','Autres créances');
INSERT INTO gifi (accno,description) VALUES ('42','Dettes à plus d''un an échéant dans l''année');
INSERT INTO gifi (accno,description) VALUES ('43','Dettes financières');
INSERT INTO gifi (accno,description) VALUES ('44','Dettes commerciales');
INSERT INTO gifi (accno,description) VALUES ('45','Dettes fiscales, salariales et sociales');
INSERT INTO gifi (accno,description) VALUES ('46','Acomptes réçus s/commandes');
INSERT INTO gifi (accno,description) VALUES ('48','Dettes diverses');
INSERT INTO gifi (accno,description) VALUES ('47','Dettes découlants de l''affectation du résultat');
INSERT INTO gifi (accno,description) VALUES ('49','Comptes de régularisation et comptes d''attente');
INSERT INTO gifi (accno,description) VALUES ('50','Actions propres');
INSERT INTO gifi (accno,description) VALUES ('51','Actions et parts');
INSERT INTO gifi (accno,description) VALUES ('52','Titres à revenu fixe');
INSERT INTO gifi (accno,description) VALUES ('53','Dépôts à terme');
INSERT INTO gifi (accno,description) VALUES ('54','Valeurs échues à l''encaissement');
INSERT INTO gifi (accno,description) VALUES ('55','Etablissements de crédit');
INSERT INTO gifi (accno,description) VALUES ('56','Office des chèques postaux');
INSERT INTO gifi (accno,description) VALUES ('57','Caisses');
INSERT INTO gifi (accno,description) VALUES ('58','Virements internes');
INSERT INTO gifi (accno,description) VALUES ('60','Approvis. et marchandises');
INSERT INTO gifi (accno,description) VALUES ('61','Services et biens divers');
INSERT INTO gifi (accno,description) VALUES ('62','Rémunérations, charges sociales, pensions');
INSERT INTO gifi (accno,description) VALUES ('63','Amortissements, réductions valeur, provisions risques et charges');
INSERT INTO gifi (accno,description) VALUES ('64','Autres charges d''exploitation');
INSERT INTO gifi (accno,description) VALUES ('65','Charges financières');
INSERT INTO gifi (accno,description) VALUES ('66','Charges exceptionnelles');
INSERT INTO gifi (accno,description) VALUES ('67','Impôts sur le résultat');
INSERT INTO gifi (accno,description) VALUES ('68','Transferts aux réserves immunisées et aux impôts différés');
INSERT INTO gifi (accno,description) VALUES ('69','Affectations et prélèvements');
INSERT INTO gifi (accno,description) VALUES ('70','Chiffre d''affaires');
INSERT INTO gifi (accno,description) VALUES ('71','Variation de stock et des commandes en cours d''éxécution');
INSERT INTO gifi (accno,description) VALUES ('72','Production immobilisée');
INSERT INTO gifi (accno,description) VALUES ('74','Autres produits d''exploitation');
INSERT INTO gifi (accno,description) VALUES ('75','Produits financiers');
INSERT INTO gifi (accno,description) VALUES ('76','Produits exceptionnels');
INSERT INTO gifi (accno,description) VALUES ('77','Régularisations d''impôts et reprises provisions fiscales');
INSERT INTO gifi (accno,description) VALUES ('78','Prélèvements s/réserves immunisées et impôts différés');
INSERT INTO gifi (accno,description) VALUES ('79','Affectations et prélèvements');
commit;
