-- Paraguay GIFI
-- Plan de Cuentas Fiscal para Paraguay
--
INSERT INTO gifi (accno,description) VALUES ('1','ACTIVOS');
INSERT INTO gifi (accno,description) VALUES ('1-01','ACTIVO CORRIENTE');
INSERT INTO gifi (accno,description) VALUES ('1-01-01','DISPONIBILIDADES');
INSERT INTO gifi (accno,description) VALUES ('1-01-01-01','Caja');
INSERT INTO gifi (accno,description) VALUES ('1-01-01-02','Recaudaciones a Depositar');
INSERT INTO gifi (accno,description) VALUES ('1-01-01-03','Bancos');
INSERT INTO gifi (accno,description) VALUES ('1-01-01-04','Otros valores');
INSERT INTO gifi (accno,description) VALUES ('1-01-02','INVERSIONES TEMPORARIAS');
INSERT INTO gifi (accno,description) VALUES ('1-01-02-01','Valores');
INSERT INTO gifi (accno,description) VALUES ('1-01-03','CRÉDITOS');
INSERT INTO gifi (accno,description) VALUES ('1-01-03-01','Clientes');
INSERT INTO gifi (accno,description) VALUES ('1-01-03-10','Menos: Previsión para incobrables');
INSERT INTO gifi (accno,description) VALUES ('1-01-03-11','Deudores varios');
INSERT INTO gifi (accno,description) VALUES ('1-01-03-12','Documentos / Cuentas a cobrar a Directores y Funcionarios');
INSERT INTO gifi (accno,description) VALUES ('1-01-03-13','Intereses a vencer');
INSERT INTO gifi (accno,description) VALUES ('1-01-03-14','Tarjetas de Créditos');
INSERT INTO gifi (accno,description) VALUES ('1-01-03-20','Menos: Previsión para Incobrables');
INSERT INTO gifi (accno,description) VALUES ('1-01-10','INVENTARIOS');
INSERT INTO gifi (accno,description) VALUES ('1-01-10-01','Mercaderías - Productos Terminados');
INSERT INTO gifi (accno,description) VALUES ('1-01-10-02','Productos en proceso');
INSERT INTO gifi (accno,description) VALUES ('1-01-10-03','Materias primas - Materiales');
INSERT INTO gifi (accno,description) VALUES ('1-01-10-04','Menos: Previsión por Obsolencia');
INSERT INTO gifi (accno,description) VALUES ('1-01-15','ANTICIPOS');
INSERT INTO gifi (accno,description) VALUES ('1-01-15-01','Importaciones en curso');
INSERT INTO gifi (accno,description) VALUES ('1-01-15-02','Proveedores');
INSERT INTO gifi (accno,description) VALUES ('1-01-20','OTROS ACTIVOS');
INSERT INTO gifi (accno,description) VALUES ('1-01-20-01','Gastos no devengados');
INSERT INTO gifi (accno,description) VALUES ('1-02','ACTIVO NO CORRIENTE');
INSERT INTO gifi (accno,description) VALUES ('1-02-01','CRÉDITOS');
INSERT INTO gifi (accno,description) VALUES ('1-02-01-01','Fondos con destino especial');
INSERT INTO gifi (accno,description) VALUES ('1-02-01-02','Documentos / Cuentas a cobrar a Directores y Funcionarios');
INSERT INTO gifi (accno,description) VALUES ('1-02-01-03','Documentos por cobrar');
INSERT INTO gifi (accno,description) VALUES ('1-02-01-04','Deudores varios');
INSERT INTO gifi (accno,description) VALUES ('1-02-01-05','Créditos en Gestión de Cobro');
INSERT INTO gifi (accno,description) VALUES ('1-02-01-06','Menos: Previsiones para incobrables');
INSERT INTO gifi (accno,description) VALUES ('1-02-10','PROPIEDAD, PLANTA Y EQUIPO');
INSERT INTO gifi (accno,description) VALUES ('1-02-10-01','Bienes en operación');
INSERT INTO gifi (accno,description) VALUES ('1-02-10-02','Depreciación acumulada');
INSERT INTO gifi (accno,description) VALUES ('1-02-10-03','Bienes fuera de operación');
INSERT INTO gifi (accno,description) VALUES ('1-02-20','ACTIVOS INTANGIBLES');
INSERT INTO gifi (accno,description) VALUES ('1-02-20-01','Licencia de manufactura');
INSERT INTO gifi (accno,description) VALUES ('1-02-20-02','Marcas');
INSERT INTO gifi (accno,description) VALUES ('1-02-20-03','Gastos de desarrollo');
INSERT INTO gifi (accno,description) VALUES ('1-02-20-04','Amortización Acumulada');
INSERT INTO gifi (accno,description) VALUES ('2','PASIVOS Y PATRIMONIO NETO');
INSERT INTO gifi (accno,description) VALUES ('2-01','PASIVO CORRIENTE');
INSERT INTO gifi (accno,description) VALUES ('2-01-01','CUENTAS A PAGAR');
INSERT INTO gifi (accno,description) VALUES ('2-01-01-01','Proveedores Locales');
INSERT INTO gifi (accno,description) VALUES ('2-01-01-02','Proveedores del Exterior');
INSERT INTO gifi (accno,description) VALUES ('2-01-01-03','Intereses a Vencer');
INSERT INTO gifi (accno,description) VALUES ('2-01-01-04','Acreedores varios');
INSERT INTO gifi (accno,description) VALUES ('2-01-05','PRÉSTAMOS FINANCIEROS');
INSERT INTO gifi (accno,description) VALUES ('2-01-05-01','Sobregiros en cuenta corriente');
INSERT INTO gifi (accno,description) VALUES ('2-01-05-02','Documentos a pagar');
INSERT INTO gifi (accno,description) VALUES ('2-01-05-03','Porción circulante de préstamos a largo plazo');
INSERT INTO gifi (accno,description) VALUES ('2-01-05-04','Intereses a devengar');
INSERT INTO gifi (accno,description) VALUES ('2-01-10','PROVISIONES');
INSERT INTO gifi (accno,description) VALUES ('2-01-10-01','Impuesto a la Renta a pagar');
INSERT INTO gifi (accno,description) VALUES ('2-01-10-02','IVA a pagar');
INSERT INTO gifi (accno,description) VALUES ('2-01-10-03','Retenciones de Impuestos');
INSERT INTO gifi (accno,description) VALUES ('2-01-10-04','Para pago de planes de beneficios para empleados');
INSERT INTO gifi (accno,description) VALUES ('2-01-10-05','Aportes y Retenciones a Pagar');
INSERT INTO gifi (accno,description) VALUES ('2-01-10-06','Gastos Acumulados a Pagar');
INSERT INTO gifi (accno,description) VALUES ('2-01-20','OTROS PASIVOS');
INSERT INTO gifi (accno,description) VALUES ('2-01-20-01','Préstamos de Terceros');
INSERT INTO gifi (accno,description) VALUES ('2-01-20-02','Anticipo de Clientes');
INSERT INTO gifi (accno,description) VALUES ('2-01-40','GANANCIAS DIFERIDAS');
INSERT INTO gifi (accno,description) VALUES ('2-01-40-01','Ingresos no realizados');
INSERT INTO gifi (accno,description) VALUES ('2-01-40-02','Costos y gastos aplicables a los ingresos no realizables');
INSERT INTO gifi (accno,description) VALUES ('2-02','PASIVOS NO CORRIENTES');
INSERT INTO gifi (accno,description) VALUES ('2-02-01','PRÉSTAMOS FINANCIEROS');
INSERT INTO gifi (accno,description) VALUES ('2-02-01-01','Préstamos en Bancos');
INSERT INTO gifi (accno,description) VALUES ('2-02-05','PREVISIONES');
INSERT INTO gifi (accno,description) VALUES ('2-02-05-01','Previsión para indemnización');
INSERT INTO gifi (accno,description) VALUES ('2-02-05-02','Otras Contingencias');
INSERT INTO gifi (accno,description) VALUES ('2-03','PATRIMONIO NETO');
INSERT INTO gifi (accno,description) VALUES ('2-03-01','CAPITAL');
INSERT INTO gifi (accno,description) VALUES ('2-03-01-01','Capital suscripto');
INSERT INTO gifi (accno,description) VALUES ('2-03-01-02','Capital a integrar');
INSERT INTO gifi (accno,description) VALUES ('2-03-01-03','Capital realizado');
INSERT INTO gifi (accno,description) VALUES ('2-03-02','RESERVAS');
INSERT INTO gifi (accno,description) VALUES ('2-03-02-01','Reserva Legal');
INSERT INTO gifi (accno,description) VALUES ('2-03-02-02','Reservas facultativas');
INSERT INTO gifi (accno,description) VALUES ('2-03-02-03','Reserva de revalúo');
INSERT INTO gifi (accno,description) VALUES ('2-03-03','RESULTADOS');
INSERT INTO gifi (accno,description) VALUES ('2-03-03-01','Resultados Acumulados');
INSERT INTO gifi (accno,description) VALUES ('2-03-03-02','Resultado del Ejercicio');
INSERT INTO gifi (accno,description) VALUES ('3-01','Ventas Netas. Sector Público');
INSERT INTO gifi (accno,description) VALUES ('3-02','Ventas Netas. Sector Privado');
INSERT INTO gifi (accno,description) VALUES ('3-10','Más otros ingresos');
INSERT INTO gifi (accno,description) VALUES ('3-10-01','Intereses ganados');
INSERT INTO gifi (accno,description) VALUES ('3-10-02','Otros (indicar naturaleza)');
INSERT INTO gifi (accno,description) VALUES ('3-20','Menos:');
INSERT INTO gifi (accno,description) VALUES ('3-20-01','Gastos financieros');
INSERT INTO gifi (accno,description) VALUES ('3-30-01','Ganancias');
INSERT INTO gifi (accno,description) VALUES ('4-01','Costo de Mercaderías (productos o servicios vendidos');
INSERT INTO gifi (accno,description) VALUES ('4-10','Menos:');
INSERT INTO gifi (accno,description) VALUES ('4-11','Gastos operacionales');
INSERT INTO gifi (accno,description) VALUES ('4-12','Gastos de ventas');
INSERT INTO gifi (accno,description) VALUES ('4-13','Gastos de administración');
INSERT INTO gifi (accno,description) VALUES ('4-20','Otros (indicar naturaleza)');
INSERT INTO gifi (accno,description) VALUES ('4-30','Pérdidas');
INSERT INTO gifi (accno,description) VALUES ('5-10','Más: (o menos) efectos de los precios cambiantes');
INSERT INTO gifi (accno,description) VALUES ('5-20','Más: (o menos) ajuste de ejercicios anteriores');
INSERT INTO gifi (accno,description) VALUES ('5-50','Impuesto a la Renta');
