--
INSERT INTO gifi (accno,description) VALUES ('1','AKTIVEN');
INSERT INTO gifi (accno,description) VALUES ('2','PASSIVEN');
INSERT INTO gifi (accno,description) VALUES ('4','AUFWAND FÜR MATERIAL, WAREN UND DIENSTLEISTUNGEN');
INSERT INTO gifi (accno,description) VALUES ('5','PERSONALAUFWAND');
INSERT INTO gifi (accno,description) VALUES ('10000','ANLAGEVERMÖGEN');
INSERT INTO gifi (accno,description) VALUES ('11000','Forderungen');
INSERT INTO gifi (accno,description) VALUES ('11100','Bank');
INSERT INTO gifi (accno,description) VALUES ('11110','MWST Vorsteuer auf Investitionen');
INSERT INTO gifi (accno,description) VALUES ('11120','Angefangene Arbeiten');
INSERT INTO gifi (accno,description) VALUES ('14150','Büromaschinen, EDV');
INSERT INTO gifi (accno,description) VALUES ('18000','Gründungsaufwand');
INSERT INTO gifi (accno,description) VALUES ('20000','FREMDKAPITAL LANGFRISTIG');
INSERT INTO gifi (accno,description) VALUES ('21000','Kurzfristige Finanzverbindlichkeiten');
INSERT INTO gifi (accno,description) VALUES ('21200','Sozialversicherungen');
INSERT INTO gifi (accno,description) VALUES ('21210','Gesellschafter');
INSERT INTO gifi (accno,description) VALUES ('21220','MWST (3,6)');
INSERT INTO gifi (accno,description) VALUES ('21230','Passive Rechnungsabgrenzung');
INSERT INTO gifi (accno,description) VALUES ('24000','Gesellschafter');
INSERT INTO gifi (accno,description) VALUES ('28000','Stammkapital');
INSERT INTO gifi (accno,description) VALUES ('28290','Gewinnvortrag');
INSERT INTO gifi (accno,description) VALUES ('30000','ÜBRIGER ERTRAG');
INSERT INTO gifi (accno,description) VALUES ('31000','Computer');
INSERT INTO gifi (accno,description) VALUES ('32000','Software kommerz.');
INSERT INTO gifi (accno,description) VALUES ('34000','Beratung');
INSERT INTO gifi (accno,description) VALUES ('36000','Essen');
INSERT INTO gifi (accno,description) VALUES ('37000','Eigenleistungen');
INSERT INTO gifi (accno,description) VALUES ('38000','Bestandesänderungen');
INSERT INTO gifi (accno,description) VALUES ('39000','Rabatte, Preisnachlässe');
INSERT INTO gifi (accno,description) VALUES ('40000','AUFWANDMINDERUNGEN');
INSERT INTO gifi (accno,description) VALUES ('41000','Übrige Produkte');
INSERT INTO gifi (accno,description) VALUES ('42000','Software kommerz.');
INSERT INTO gifi (accno,description) VALUES ('44000','Aufwand für Drittleistungen');
INSERT INTO gifi (accno,description) VALUES ('47000','Einkaufsspesen');
INSERT INTO gifi (accno,description) VALUES ('48000','Bestandesänderungen');
INSERT INTO gifi (accno,description) VALUES ('49000','Aufwandminderungen');
INSERT INTO gifi (accno,description) VALUES ('50000','Löhne und Gehälter');
INSERT INTO gifi (accno,description) VALUES ('57000','FAK');
INSERT INTO gifi (accno,description) VALUES ('58000','Spesen');
INSERT INTO gifi (accno,description) VALUES ('60000','VERWALTUNGS- UND INFORMATIKAUFWAND');
INSERT INTO gifi (accno,description) VALUES ('61000','Reinigung');
INSERT INTO gifi (accno,description) VALUES ('61900','Unterhalt');
INSERT INTO gifi (accno,description) VALUES ('62000','Fahrzeugaufwand');
INSERT INTO gifi (accno,description) VALUES ('63000','Betriebsversicherungen');
INSERT INTO gifi (accno,description) VALUES ('65000','Übriger Verwaltungsaufwand');
INSERT INTO gifi (accno,description) VALUES ('66000','Werbeaufwand');
INSERT INTO gifi (accno,description) VALUES ('67000','Produkteentwicklung');
INSERT INTO gifi (accno,description) VALUES ('68000','Finanzaufwand');
INSERT INTO gifi (accno,description) VALUES ('69000','Abschreibungen');
INSERT INTO gifi (accno,description) VALUES ('80000','AUSSERORDENTLICHER UND BETRIEBSFREMDER ERFOLG, STEUERN');
INSERT INTO gifi (accno,description) VALUES ('90000','ABSCHLUSS');
INSERT INTO gifi (accno,description) VALUES ('91000','ERFOLGSRECHNUNG');
INSERT INTO gifi (accno,description) VALUES ('92000','BILANZ');
INSERT INTO gifi (accno,description) VALUES ('93000','GEWINNVERWENDUNG');
INSERT INTO gifi (accno,description) VALUES ('99000','SAMMEL- UND FEHLBUCHUNGEN');
