INSERT INTO gifi (accno, description) VALUES ('1&(6a)', 'Line 1 & (6a)');
INSERT INTO gifi (accno, description) VALUES ('1', 'Line 1');
INSERT INTO gifi (accno, description) VALUES ('10', 'Line 10');
INSERT INTO gifi (accno, description) VALUES ('11', 'Line 11');
INSERT INTO gifi (accno, description) VALUES ('12', 'Line 12');
INSERT INTO gifi (accno, description) VALUES ('13', 'Line 13');
INSERT INTO gifi (accno, description) VALUES ('14', 'Line 14');
INSERT INTO gifi (accno, description) VALUES ('15', 'Line 15');
INSERT INTO gifi (accno, description) VALUES ('16', 'Line 16');
INSERT INTO gifi (accno, description) VALUES ('2', 'Line 2');
INSERT INTO gifi (accno, description) VALUES ('21&27', 'Line 21 & 27');
INSERT INTO gifi (accno, description) VALUES ('22', 'Line 22');
INSERT INTO gifi (accno, description) VALUES ('23', 'Line 23');
INSERT INTO gifi (accno, description) VALUES ('24', 'Line 24');
INSERT INTO gifi (accno, description) VALUES ('26', 'Line 26');
INSERT INTO gifi (accno, description) VALUES ('3', 'Line 3');
INSERT INTO gifi (accno, description) VALUES ('4', 'Line 4');
INSERT INTO gifi (accno, description) VALUES ('5a', 'Line 5a');
INSERT INTO gifi (accno, description) VALUES ('5b', 'Line 5b');
INSERT INTO gifi (accno, description) VALUES ('6a', 'Line 6a');
INSERT INTO gifi (accno, description) VALUES ('8', 'Line 8');
INSERT INTO gifi (accno, description) VALUES ('capitalized', 'capitalized');
