begin;
-- French Canadian GIFI
-- Céline des Ligneris
-- checked DS. March 3, 2004
--
INSERT INTO gifi (accno,description) VALUES ('1000','Encaisse et dépôts');
INSERT INTO gifi (accno,description) VALUES ('1001','Encaisse');
INSERT INTO gifi (accno,description) VALUES ('1002','Dépôts dans des banques et des institutions canadiennes ­ monnaie canadienne');
INSERT INTO gifi (accno,description) VALUES ('1003','Dépôts dans des banques et des institutions canadiennes ­ devises étrangères');
INSERT INTO gifi (accno,description) VALUES ('1004','Dépôts dans des banques étrangères ­ monnaie canadienne');
INSERT INTO gifi (accno,description) VALUES ('1005','Dépôts dans des banques étrangères ­ devises étrangères');
INSERT INTO gifi (accno,description) VALUES ('1006','Caisse de crédit ­ dépôt central');
INSERT INTO gifi (accno,description) VALUES ('1007','Autres éléments de l''actif assimilables à de l''encaisse');
INSERT INTO gifi (accno,description) VALUES ('1060','Comptes clients');
INSERT INTO gifi (accno,description) VALUES ('1061','Provision pour créances douteuses');
INSERT INTO gifi (accno,description) VALUES ('1062','Comptes clients commerciaux');
INSERT INTO gifi (accno,description) VALUES ('1063','Provision pour mauvaises créances ­ comptes clients commerciaux');
INSERT INTO gifi (accno,description) VALUES ('1064','Comptes clients de personnes apparentées');
INSERT INTO gifi (accno,description) VALUES ('1065','Provision pour mauvaises créances ­ personnes apparentées');
INSERT INTO gifi (accno,description) VALUES ('1066','Impôts à recevoir');
INSERT INTO gifi (accno,description) VALUES ('1067','Intérêts à recevoir');
INSERT INTO gifi (accno,description) VALUES ('1068','Retenues de garantie à recevoir');
INSERT INTO gifi (accno,description) VALUES ('1069','Créances au titre de baux');
INSERT INTO gifi (accno,description) VALUES ('1070','Provision pour éléments douteux contenus dans certaines créances au titre de baux');
INSERT INTO gifi (accno,description) VALUES ('1071','Comptes à recevoir d''employés');
INSERT INTO gifi (accno,description) VALUES ('1072','Provision pour mauvaises créances ­ employés');
INSERT INTO gifi (accno,description) VALUES ('1073','Montants à recevoir de membres d''OSBL');
INSERT INTO gifi (accno,description) VALUES ('1120','Stocks');
INSERT INTO gifi (accno,description) VALUES ('1121','Stock de marchandises à vendre');
INSERT INTO gifi (accno,description) VALUES ('1122','Pièces et fournitures en stock');
INSERT INTO gifi (accno,description) VALUES ('1123','Biens immobiliers figurant dans un inventaire');
INSERT INTO gifi (accno,description) VALUES ('1124','Stocks d''agrégats');
INSERT INTO gifi (accno,description) VALUES ('1125','Travaux en cours');
INSERT INTO gifi (accno,description) VALUES ('1126','Matières premières');
INSERT INTO gifi (accno,description) VALUES ('1127','Titres figurant dans un inventaire');
INSERT INTO gifi (accno,description) VALUES ('1180','Placements à court terme');
INSERT INTO gifi (accno,description) VALUES ('1181','Dépôts à terme canadiens');
INSERT INTO gifi (accno,description) VALUES ('1182','Actions de sociétés canadiennes');
INSERT INTO gifi (accno,description) VALUES ('1183','Obligations canadiennes');
INSERT INTO gifi (accno,description) VALUES ('1184','Bonds du Trésor canadien');
INSERT INTO gifi (accno,description) VALUES ('1185','Titres acquis avec entente de rachat');
INSERT INTO gifi (accno,description) VALUES ('1186','Autres placements canadiens à court terme');
INSERT INTO gifi (accno,description) VALUES ('1187','Placements étrangers à court terme');
INSERT INTO gifi (accno,description) VALUES ('1240','Prêts et effets à recevoir');
INSERT INTO gifi (accno,description) VALUES ('1241','Prêts remboursables sur demande');
INSERT INTO gifi (accno,description) VALUES ('1242','Autres prêts non remboursés');
INSERT INTO gifi (accno,description) VALUES ('1243','Effets à recevoir');
INSERT INTO gifi (accno,description) VALUES ('1244','Hypothèques à recevoir');
INSERT INTO gifi (accno,description) VALUES ('1300','Sommes exigibles d''actionnaire(s)/d''administrateur(s)');
INSERT INTO gifi (accno,description) VALUES ('1301','Sommes exigibles d''actionnaire(s) (particuliers)');
INSERT INTO gifi (accno,description) VALUES ('1302','Sommes exigibles d''actionnaire(s) (sociétés)');
INSERT INTO gifi (accno,description) VALUES ('1303','Sommes exigibles d''administrateur(s)');
INSERT INTO gifi (accno,description) VALUES ('1360','Placements dans une(des) coentreprise(s)/ société(s) de personnes');
INSERT INTO gifi (accno,description) VALUES ('1380','Sommes exigibles de coentreprise(s)/société(s) de personnes');
INSERT INTO gifi (accno,description) VALUES ('1400','Sommes exigibles des personnes apparentées/placements dans des personnes apparentées');
INSERT INTO gifi (accno,description) VALUES ('1401','Billets à demande de personnes apparentées');
INSERT INTO gifi (accno,description) VALUES ('1402','Intérêts à recevoir de personnes apparentées');
INSERT INTO gifi (accno,description) VALUES ('1403','Prêts/avances à des personnes apparentées');
INSERT INTO gifi (accno,description) VALUES ('1460','Dettes des clients pour acceptation');
INSERT INTO gifi (accno,description) VALUES ('1480','Autres éléments d''actif à court terme');
INSERT INTO gifi (accno,description) VALUES ('1481','Impôts sur le revenu reportés');
INSERT INTO gifi (accno,description) VALUES ('1482','Revenus de placements accumulés');
INSERT INTO gifi (accno,description) VALUES ('1483','Impôts recouvrables/remboursables');
INSERT INTO gifi (accno,description) VALUES ('1484','Dépenses payées d''avance');
INSERT INTO gifi (accno,description) VALUES ('1485','Avances de forage');
INSERT INTO gifi (accno,description) VALUES ('1486','Cautionnement/dépôts sur soumissions');
INSERT INTO gifi (accno,description) VALUES ('1599','Total de l''actif à court terme');
INSERT INTO gifi (accno,description) VALUES ('1600','Terrains');
INSERT INTO gifi (accno,description) VALUES ('1601','Frais d''amélioration des terrains');
INSERT INTO gifi (accno,description) VALUES ('1602','Amortissement cumulé de l''amélioration des terrains');
INSERT INTO gifi (accno,description) VALUES ('1620','Biens épuisables');
INSERT INTO gifi (accno,description) VALUES ('1621','Amortissement cumulé des biens épuisables');
INSERT INTO gifi (accno,description) VALUES ('1622','Biens en ressources pétrolifères et en gaz naturel');
INSERT INTO gifi (accno,description) VALUES ('1623','Amortissement cumulé des biens en ressources');
INSERT INTO gifi (accno,description) VALUES ('1624','Biens miniers');
INSERT INTO gifi (accno,description) VALUES ('1625','Amortissement cumulé des biens miniers');
INSERT INTO gifi (accno,description) VALUES ('1626','Frais d''exploration et d''exploitation reportés');
INSERT INTO gifi (accno,description) VALUES ('1627','Amortissement cumulé des frais d''exploration et d''exploitation reportés');
INSERT INTO gifi (accno,description) VALUES ('1628','Carrières');
INSERT INTO gifi (accno,description) VALUES ('1629','Amortissement cumulé des carrières');
INSERT INTO gifi (accno,description) VALUES ('1630','Carrières de gravier');
INSERT INTO gifi (accno,description) VALUES ('1631','Amortissement cumulé des carrières de gravier');
INSERT INTO gifi (accno,description) VALUES ('1632','Concessions forestières');
INSERT INTO gifi (accno,description) VALUES ('1633','Amortissement cumulé des concessions forestières');
INSERT INTO gifi (accno,description) VALUES ('1680','Bâtiments');
INSERT INTO gifi (accno,description) VALUES ('1681','Amortissement cumulé des bâtiments');
INSERT INTO gifi (accno,description) VALUES ('1682','Installations de fabrication et de traitement');
INSERT INTO gifi (accno,description) VALUES ('1683','Amortissement cumulé des installations de fabrication et de traitement');
INSERT INTO gifi (accno,description) VALUES ('1684','Bâtiments en construction');
INSERT INTO gifi (accno,description) VALUES ('1740','Machines, matériel, meubles et accessoires');
INSERT INTO gifi (accno,description) VALUES ('1741','Amortissement cumulé des machines, du matériel, des meubles et des accessoires');
INSERT INTO gifi (accno,description) VALUES ('1742','Véhicules automobiles');
INSERT INTO gifi (accno,description) VALUES ('1743','Amortissement cumulé des véhicules automobiles');
INSERT INTO gifi (accno,description) VALUES ('1744','Outils et matrices');
INSERT INTO gifi (accno,description) VALUES ('1745','Amortissement cumulé sur les outils et les matrices');
INSERT INTO gifi (accno,description) VALUES ('1746','Matériel de construction et d''excavation');
INSERT INTO gifi (accno,description) VALUES ('1747','Amortissement cumulé du matériel de construction et d''excavation');
INSERT INTO gifi (accno,description) VALUES ('1748','Matériel d''exploitation forestière');
INSERT INTO gifi (accno,description) VALUES ('1749','Amortissement cumulé du matériel d''exploitation forestière');
INSERT INTO gifi (accno,description) VALUES ('1750','Filets et matériel de pêche');
INSERT INTO gifi (accno,description) VALUES ('1751','Amortissement cumulé des filets et du matériel de pêche');
INSERT INTO gifi (accno,description) VALUES ('1752','Matériel d''exploitation minière');
INSERT INTO gifi (accno,description) VALUES ('1753','Amortissement cumulé du matériel d''exploitation minière');
INSERT INTO gifi (accno,description) VALUES ('1754','Réseaux pétroliers et gaziers');
INSERT INTO gifi (accno,description) VALUES ('1755','Amortissement cumulé des réseaux pétroliers et gaziers');
INSERT INTO gifi (accno,description) VALUES ('1756','Matériel de production pour les industries de ressources naturelles');
INSERT INTO gifi (accno,description) VALUES ('1757','Amortissement cumulé du matériel de production de ressources naturelles');
INSERT INTO gifi (accno,description) VALUES ('1758','Matériel de production autre que pour les industries de ressources naturelles');
INSERT INTO gifi (accno,description) VALUES ('1759','Amortissement cumulé du matériel de production autre que pour les industries des ressources  naturelles');
INSERT INTO gifi (accno,description) VALUES ('1760','Matériel d''exploration');
INSERT INTO gifi (accno,description) VALUES ('1761','Amortissement cumulé du matériel d''exploration');
INSERT INTO gifi (accno,description) VALUES ('1762','Matériel d''expédition');
INSERT INTO gifi (accno,description) VALUES ('1763','Amortissement cumulé du matériel d''expédition');
INSERT INTO gifi (accno,description) VALUES ('1764','Navires et bateaux');
INSERT INTO gifi (accno,description) VALUES ('1765','Amortissement cumulé des navires et des bateaux');
INSERT INTO gifi (accno,description) VALUES ('1766','Aéronefs');
INSERT INTO gifi (accno,description) VALUES ('1767','Amortissement cumulé des aéronefs');
INSERT INTO gifi (accno,description) VALUES ('1768','Panneaux indicateurs');
INSERT INTO gifi (accno,description) VALUES ('1769','Amortissement cumulé des panneaux indicateurs');
INSERT INTO gifi (accno,description) VALUES ('1770','Petits outils');
INSERT INTO gifi (accno,description) VALUES ('1771','Amortissement cumulé des petits outils');
INSERT INTO gifi (accno,description) VALUES ('1772','Matériel de radio et de communication');
INSERT INTO gifi (accno,description) VALUES ('1773','Amortissement cumulé du matériel de radio et de communication');
INSERT INTO gifi (accno,description) VALUES ('1774','Matériel informatique/logiciels');
INSERT INTO gifi (accno,description) VALUES ('1775','Amortissement cumulé du matériel informatique / logiciels');
INSERT INTO gifi (accno,description) VALUES ('1776','Instruments de musique');
INSERT INTO gifi (accno,description) VALUES ('1777','Amortissement cumulé des instruments de musique');
INSERT INTO gifi (accno,description) VALUES ('1778','Satellites');
INSERT INTO gifi (accno,description) VALUES ('1779','Amortissement cumulé des satellites');
INSERT INTO gifi (accno,description) VALUES ('1780','Stations terrestres');
INSERT INTO gifi (accno,description) VALUES ('1781','Amortissement cumulé des stations terrestres');
INSERT INTO gifi (accno,description) VALUES ('1782','Machines et matériel en cours de fabrication');
INSERT INTO gifi (accno,description) VALUES ('1783','Matériel de transport');
INSERT INTO gifi (accno,description) VALUES ('1784','Amortissement cumulé du matériel de transport');
INSERT INTO gifi (accno,description) VALUES ('1785','Autres machines et matériel');
INSERT INTO gifi (accno,description) VALUES ('1786','Amortissement cumulé des autres machines et d''autre matériel');
INSERT INTO gifi (accno,description) VALUES ('1787','Meubles et accessoires');
INSERT INTO gifi (accno,description) VALUES ('1788','Amortissement cumulé des meubles et des accessoires');
INSERT INTO gifi (accno,description) VALUES ('1900','Autres immobilisations');
INSERT INTO gifi (accno,description) VALUES ('1901','Amortissement cumulé des autres immobilisations');
INSERT INTO gifi (accno,description) VALUES ('1902','Chemins d''exploitation forestière');
INSERT INTO gifi (accno,description) VALUES ('1903','Amortissement cumulé des chemins d''exploitation forestière');
INSERT INTO gifi (accno,description) VALUES ('1904','Aires asphaltées et parcs de stationnement');
INSERT INTO gifi (accno,description) VALUES ('1905','Amortissement des aires asphaltées et des parcs de stationnement');
INSERT INTO gifi (accno,description) VALUES ('1906','Quais');
INSERT INTO gifi (accno,description) VALUES ('1907','Amortissement cumulé des quais');
INSERT INTO gifi (accno,description) VALUES ('1908','Clôtures');
INSERT INTO gifi (accno,description) VALUES ('1909','Amortissement cumulé des clôtures');
INSERT INTO gifi (accno,description) VALUES ('1910','Contrats de location ­ acquisition (bâtiments)');
INSERT INTO gifi (accno,description) VALUES ('1911','Amortissement cumulé des contrats de location - acquisition (bâtiments)');
INSERT INTO gifi (accno,description) VALUES ('1912','Contrats de location ­ acquisition (matériel)');
INSERT INTO gifi (accno,description) VALUES ('1913','Amortissement cumulé des contrats de location ­ acquisition (matériel)');
INSERT INTO gifi (accno,description) VALUES ('1914','Contrats de location ­ acquisition (véhicules)');
INSERT INTO gifi (accno,description) VALUES ('1915','Amortissement cumulé des contrats de location ­ acquisition (véhicules)');
INSERT INTO gifi (accno,description) VALUES ('1916','Contrats de location ­ acquisition (autres)panneaux');
INSERT INTO gifi (accno,description) VALUES ('1917','Amortissement cumulé des contrats de location ­ acquisition (autres)');
INSERT INTO gifi (accno,description) VALUES ('1918','Améliorations locatives');
INSERT INTO gifi (accno,description) VALUES ('1919','Amortissement cumulé des améliorations locatives');
INSERT INTO gifi (accno,description) VALUES ('1920','Autres immobilisations en construction');
INSERT INTO gifi (accno,description) VALUES ('1921','Aires de campings');
INSERT INTO gifi (accno,description) VALUES ('1922','Amortissement cumulé des aires de campings');
INSERT INTO gifi (accno,description) VALUES ('2008','Total des immobilisations');
INSERT INTO gifi (accno,description) VALUES ('2009','Total de l''amortissement cumulé des immobilisations');
INSERT INTO gifi (accno,description) VALUES ('2010','Actif incorporel');
INSERT INTO gifi (accno,description) VALUES ('2011','Amortissement cumulé de l''actif incorporel');
INSERT INTO gifi (accno,description) VALUES ('2012','Achalandage');
INSERT INTO gifi (accno,description) VALUES ('2013','Amortissement cumulé de l''achalandage');
INSERT INTO gifi (accno,description) VALUES ('2014','Contingents');
INSERT INTO gifi (accno,description) VALUES ('2015','Amortissement cumulé des contingents');
INSERT INTO gifi (accno,description) VALUES ('2016','Permis');
INSERT INTO gifi (accno,description) VALUES ('2017','Amortissement cumulé des permis');
INSERT INTO gifi (accno,description) VALUES ('2018','Frais de constitution en société');
INSERT INTO gifi (accno,description) VALUES ('2019','Amortissement cumulé des frais de constitution en société');
INSERT INTO gifi (accno,description) VALUES ('2020','Marques de commerce et brevets');
INSERT INTO gifi (accno,description) VALUES ('2021','Amortissement cumulé des marques de commerce et des brevets');
INSERT INTO gifi (accno,description) VALUES ('2022','Listes de clients');
INSERT INTO gifi (accno,description) VALUES ('2023','Amortissement cumulé des listes de clients');
INSERT INTO gifi (accno,description) VALUES ('2024','Droits');
INSERT INTO gifi (accno,description) VALUES ('2025','Amortissement cumulé des droits');
INSERT INTO gifi (accno,description) VALUES ('2026','Recherche et développement');
INSERT INTO gifi (accno,description) VALUES ('2027','Amortissement cumulé de la recherche et du développement');
INSERT INTO gifi (accno,description) VALUES ('2070','Droits relatifs à des ressources');
INSERT INTO gifi (accno,description) VALUES ('2071','Amortissement cumulé des droits relatifs à des ressources');
INSERT INTO gifi (accno,description) VALUES ('2072','Droits de coupe');
INSERT INTO gifi (accno,description) VALUES ('2073','Amortissement cumulé des droits de coupe');
INSERT INTO gifi (accno,description) VALUES ('2074','Droits miniers');
INSERT INTO gifi (accno,description) VALUES ('2075','Amortissement cumulé des droits miniers');
INSERT INTO gifi (accno,description) VALUES ('2076','Droits pétroliers et gaziers');
INSERT INTO gifi (accno,description) VALUES ('2077','Amortissement cumulé des droits pétroliers et gaziers');
INSERT INTO gifi (accno,description) VALUES ('2178','Total de l''actif incorporel');
INSERT INTO gifi (accno,description) VALUES ('2179','Total de l''amortissement cumulé de l''actif incorporel');
INSERT INTO gifi (accno,description) VALUES ('2180','Sommes exigibles d''actionnaire(s)/ d''administrateur(s)');
INSERT INTO gifi (accno,description) VALUES ('2181','Sommes exigibles d''actionnaire(s) (particuliers)');
INSERT INTO gifi (accno,description) VALUES ('2182','Sommes exigibles d''actionnaire(s) (sociétés)');
INSERT INTO gifi (accno,description) VALUES ('2183','Sommes exigibles d''administrateur(s)');
INSERT INTO gifi (accno,description) VALUES ('2190','Sommes exigibles des membres');
INSERT INTO gifi (accno,description) VALUES ('2200','Placements dans une(des) coentreprise(s)/société(s) de personnes');
INSERT INTO gifi (accno,description) VALUES ('2220','Sommes exigibles de coentreprise(s)/société(s)de personnes');
INSERT INTO gifi (accno,description) VALUES ('2240','Sommes exigibles des personnes apparentées/');
INSERT INTO gifi (accno,description) VALUES ('2241','Sommes exigibles de/placements dans des personnes canadiennes apparentées');
INSERT INTO gifi (accno,description) VALUES ('2242','Actions dans des sociétés canadiennes apparentées');
INSERT INTO gifi (accno,description) VALUES ('2243','Prêts/avances à des sociétés canadiennes apparentées');
INSERT INTO gifi (accno,description) VALUES ('2244','Placements dans des sociétés canadiennes apparentées à la valeur d''acquisition');
INSERT INTO gifi (accno,description) VALUES ('2245','Placements dans des sociétés canadiennes apparentées à la valeur de consolidation');
INSERT INTO gifi (accno,description) VALUES ('2246','Sommes exigibles de/placements dans des parties étrangères apparentées');
INSERT INTO gifi (accno,description) VALUES ('2247','Actions dans des sociétés étrangères apparentées');
INSERT INTO gifi (accno,description) VALUES ('2248','Prêts/avances à des sociétés étrangères apparentées');
INSERT INTO gifi (accno,description) VALUES ('2249','Placements dans des sociétés étrangères apparentées à la valeur d''acquisition');
INSERT INTO gifi (accno,description) VALUES ('2250','Placements dans des sociétés étrangères apparentées à la valeur de consolidation');
INSERT INTO gifi (accno,description) VALUES ('2280','Placements dans des locations en partenariat');
INSERT INTO gifi (accno,description) VALUES ('2300','Placements à long terme');
INSERT INTO gifi (accno,description) VALUES ('2301','Actions dans des sociétés étrangères');
INSERT INTO gifi (accno,description) VALUES ('2302','Autres genres de placements à l''étranger');
INSERT INTO gifi (accno,description) VALUES ('2303','Actions dans des sociétés canadiennes');
INSERT INTO gifi (accno,description) VALUES ('2304','Titres de créances du gouvernement du Canada');
INSERT INTO gifi (accno,description) VALUES ('2305','Titres de créances des gouvernements provinciaux et des administrations municipales du Canada');
INSERT INTO gifi (accno,description) VALUES ('2306','Obligations et débentures de sociétés canadiennes');
INSERT INTO gifi (accno,description) VALUES ('2307','Titres de créances');
INSERT INTO gifi (accno,description) VALUES ('2308','Titres de participation');
INSERT INTO gifi (accno,description) VALUES ('2309','Titres acquis à la suite d''une entente de rachat');
INSERT INTO gifi (accno,description) VALUES ('2310','Actions de la caisse de crédit centrale');
INSERT INTO gifi (accno,description) VALUES ('2311','Autres placements canadiens à long terme');
INSERT INTO gifi (accno,description) VALUES ('2360','Prêts à long terme');
INSERT INTO gifi (accno,description) VALUES ('2361','Prêts hypothécaires');
INSERT INTO gifi (accno,description) VALUES ('2362','Prêts personnels et prêts sur carte de crédit');
INSERT INTO gifi (accno,description) VALUES ('2363','Prêts au gouvernement et prêts commerciaux');
INSERT INTO gifi (accno,description) VALUES ('2364','Marge de crédit');
INSERT INTO gifi (accno,description) VALUES ('2420','Autres éléments d''actif à long terme');
INSERT INTO gifi (accno,description) VALUES ('2421','Impôts sur le revenu reportés');
INSERT INTO gifi (accno,description) VALUES ('2422','Frais du régime de pension reportés');
INSERT INTO gifi (accno,description) VALUES ('2423','Pertes de change non matérialisées reportées');
INSERT INTO gifi (accno,description) VALUES ('2424','Autres éléments/frais reportés');
INSERT INTO gifi (accno,description) VALUES ('2425','Amortissement cumulé des frais reportés');
INSERT INTO gifi (accno,description) VALUES ('2426','Fonds de réserve');
INSERT INTO gifi (accno,description) VALUES ('2427','Valeur de rachat de l''assurance-vie');
INSERT INTO gifi (accno,description) VALUES ('2589','Total de l''actif à long terme');
INSERT INTO gifi (accno,description) VALUES ('2590','Actif détenu en fiducie');
INSERT INTO gifi (accno,description) VALUES ('2599','Total de l''actif');
INSERT INTO gifi (accno,description) VALUES ('2600','Découvert bancaire');
INSERT INTO gifi (accno,description) VALUES ('2620','Montants et charges à payer');
INSERT INTO gifi (accno,description) VALUES ('2621','Effets commerciaux à payer');
INSERT INTO gifi (accno,description) VALUES ('2622','Effets commerciaux à payer à des personnes apparentées');
INSERT INTO gifi (accno,description) VALUES ('2623','Retenues de garantie à payer');
INSERT INTO gifi (accno,description) VALUES ('2624','Salaires à payer');
INSERT INTO gifi (accno,description) VALUES ('2625','Frais de gestion à payer');
INSERT INTO gifi (accno,description) VALUES ('2626','Gratifications à payer');
INSERT INTO gifi (accno,description) VALUES ('2627','Retenues salariales à payer');
INSERT INTO gifi (accno,description) VALUES ('2628','Retenues d''impôts et de taxes à payer');
INSERT INTO gifi (accno,description) VALUES ('2629','Intérêts à payer');
INSERT INTO gifi (accno,description) VALUES ('2630','Montants à payer aux membres d''OSBL');
INSERT INTO gifi (accno,description) VALUES ('2680','Taxes et impôts à payer');
INSERT INTO gifi (accno,description) VALUES ('2700','Dettes à court terme');
INSERT INTO gifi (accno,description) VALUES ('2701','Emprunts auprès de banques canadiennes');
INSERT INTO gifi (accno,description) VALUES ('2702','Élément de passif pour les titres vendus à découvert');
INSERT INTO gifi (accno,description) VALUES ('2703','Élément de passif pour les titres vendus à la suite d''une entente de rachat');
INSERT INTO gifi (accno,description) VALUES ('2704','Titres sur l''or et sur l''argent');
INSERT INTO gifi (accno,description) VALUES ('2705','Chèques et autres items en circulation');
INSERT INTO gifi (accno,description) VALUES ('2706','Billets garantis');
INSERT INTO gifi (accno,description) VALUES ('2770','Revenus reportés');
INSERT INTO gifi (accno,description) VALUES ('2780','Sommes dues à un(des) actionnaire(s)/administrateur(s)');
INSERT INTO gifi (accno,description) VALUES ('2781','Sommes dues à un(des) actionnaire(s) (particuliers)');
INSERT INTO gifi (accno,description) VALUES ('2782','Sommes dues à un(des) actionnaire(s) (sociétés)');
INSERT INTO gifi (accno,description) VALUES ('2783','Sommes dues à un(des) administrateur(s)');
INSERT INTO gifi (accno,description) VALUES ('2840','Sommes dues à une(des) coentreprise(s)/ société(s) de personnes');
INSERT INTO gifi (accno,description) VALUES ('2860','Sommes dues à des personnes apparentées');
INSERT INTO gifi (accno,description) VALUES ('2861','Billets à demande dus à des personnes apparentées');
INSERT INTO gifi (accno,description) VALUES ('2862','Intérêts à payer à des personnes apparentées');
INSERT INTO gifi (accno,description) VALUES ('2863','Avances à payer à des personnes apparentées');
INSERT INTO gifi (accno,description) VALUES ('2920','Portion à court terme du passif à long terme');
INSERT INTO gifi (accno,description) VALUES ('2940','Acceptations de banque');
INSERT INTO gifi (accno,description) VALUES ('2960','Autres éléments du passif à court terme');
INSERT INTO gifi (accno,description) VALUES ('2961','Sommes reçues en dépôts');
INSERT INTO gifi (accno,description) VALUES ('2962','Dividendes à payer');
INSERT INTO gifi (accno,description) VALUES ('2963','Impôts sur le revenu reportés');
INSERT INTO gifi (accno,description) VALUES ('2964','Réserve pour garanties et indemnités');
INSERT INTO gifi (accno,description) VALUES ('2965','Provisions et réserves générales');
INSERT INTO gifi (accno,description) VALUES ('2966','Parts des membres de l''équipage');
INSERT INTO gifi (accno,description) VALUES ('3139','Total du passif à court terme');
INSERT INTO gifi (accno,description) VALUES ('3140','Dette à long terme');
INSERT INTO gifi (accno,description) VALUES ('3141','Hypothèques');
INSERT INTO gifi (accno,description) VALUES ('3142','Emprunts d''une société de crédit agricole');
INSERT INTO gifi (accno,description) VALUES ('3143','Emprunt d''une banque à charte');
INSERT INTO gifi (accno,description) VALUES ('3144','Emprunt d''une caisse populaire/d''une coopérative de crédit');
INSERT INTO gifi (accno,description) VALUES ('3145','Emprunt du gouvernement provincial');
INSERT INTO gifi (accno,description) VALUES ('3146','Emprunt d''un fournisseur');
INSERT INTO gifi (accno,description) VALUES ('3147','Prêt personnel');
INSERT INTO gifi (accno,description) VALUES ('3148','Emprunts d''une fédération, d''une centrale ou de');
INSERT INTO gifi (accno,description) VALUES ('3149','Marge de crédit');
INSERT INTO gifi (accno,description) VALUES ('3150','Élément de passif pour les titres vendus à');
INSERT INTO gifi (accno,description) VALUES ('3151','Élément de passif pour les titres vendus à la suite d''une entente de rachat');
INSERT INTO gifi (accno,description) VALUES ('3152','Billets garantis');
INSERT INTO gifi (accno,description) VALUES ('3200','Cautionnement des institutions financières');
INSERT INTO gifi (accno,description) VALUES ('3210','Obligations et débentures');
INSERT INTO gifi (accno,description) VALUES ('3220','Revenus reportés');
INSERT INTO gifi (accno,description) VALUES ('3240','Impôts sur le revenu reportés');
INSERT INTO gifi (accno,description) VALUES ('3260','Sommes dues à un(des) actionnaire(s)/ administrateur(s)');
INSERT INTO gifi (accno,description) VALUES ('3261','Sommes dues à un(des) actionnaire(s) (particuliers)');
INSERT INTO gifi (accno,description) VALUES ('3262','Sommes dues à un(des) actionnaire(s) (sociétés)');
INSERT INTO gifi (accno,description) VALUES ('3263','Sommes dues à un(des) administrateur(s)');
INSERT INTO gifi (accno,description) VALUES ('3270','Sommes dues à des membres');
INSERT INTO gifi (accno,description) VALUES ('3280','Sommes dues à une(des) coentreprise(s)/société(s) de personnes');
INSERT INTO gifi (accno,description) VALUES ('3300','Sommes dues à des personnes apparentées');
INSERT INTO gifi (accno,description) VALUES ('3301','Sommes dues à des personnes canadiennes apparentées');
INSERT INTO gifi (accno,description) VALUES ('3302','Sommes dues à des personnes étrangères apparentées');
INSERT INTO gifi (accno,description) VALUES ('3320','Autres éléments de passif à long terme');
INSERT INTO gifi (accno,description) VALUES ('3321','Obligations, engagements et location-acquisition à long terme');
INSERT INTO gifi (accno,description) VALUES ('3322','Réserves pour garanties et indemnités');
INSERT INTO gifi (accno,description) VALUES ('3323','Provision pour la restauration des sites d''exploitation');
INSERT INTO gifi (accno,description) VALUES ('3324','Contribution à une fiducie pour l''environnement');
INSERT INTO gifi (accno,description) VALUES ('3325','Provisions et réserves générales');
INSERT INTO gifi (accno,description) VALUES ('3326','Redressement pour les actions privilégiées');
INSERT INTO gifi (accno,description) VALUES ('3327','Répartition aux membres');
INSERT INTO gifi (accno,description) VALUES ('3328','Revenus différés de contrats incomplets');
INSERT INTO gifi (accno,description) VALUES ('3450','Total du passif à long terme');
INSERT INTO gifi (accno,description) VALUES ('3460','Dettes de second rang');
INSERT INTO gifi (accno,description) VALUES ('3470','Sommes détenues en fiducie');
INSERT INTO gifi (accno,description) VALUES ('3499','Total du passif');
INSERT INTO gifi (accno,description) VALUES ('3500','Actions ordinaires');
INSERT INTO gifi (accno,description) VALUES ('3520','Actions privilégiées');
INSERT INTO gifi (accno,description) VALUES ('3540','Surplus d''apport et autres surplus');
INSERT INTO gifi (accno,description) VALUES ('3541','Surplus d''apport');
INSERT INTO gifi (accno,description) VALUES ('3542','Surplus d''expertise');
INSERT INTO gifi (accno,description) VALUES ('3543','Réserve générale');
INSERT INTO gifi (accno,description) VALUES ('3570','Compte du siège social');
INSERT INTO gifi (accno,description) VALUES ('3600','Bénéfices non répartis/déficit');
INSERT INTO gifi (accno,description) VALUES ('3620','Total des capitaux propres');
INSERT INTO gifi (accno,description) VALUES ('3640','Total du passif et des capitaux propres');
INSERT INTO gifi (accno,description) VALUES ('3680','Revenu net/perte nette');
INSERT INTO gifi (accno,description) VALUES ('3700','Dividendes déclarés');
INSERT INTO gifi (accno,description) VALUES ('3701','Dividendes en espèces');
INSERT INTO gifi (accno,description) VALUES ('3702','Ristournes');
INSERT INTO gifi (accno,description) VALUES ('3720','Redressements sur exercices antérieurs');
INSERT INTO gifi (accno,description) VALUES ('3740','Autres éléments touchant les bénéfices non répartis');
INSERT INTO gifi (accno,description) VALUES ('3741','Rachat d''actions');
INSERT INTO gifi (accno,description) VALUES ('3742','Réserves spéciales');
INSERT INTO gifi (accno,description) VALUES ('3743','Redressements relatifs aux devises');
INSERT INTO gifi (accno,description) VALUES ('3744','Éléments inhabituels de revenus');
INSERT INTO gifi (accno,description) VALUES ('3745','Transferts interfonds');
INSERT INTO gifi (accno,description) VALUES ('3849','Bénéfices non répartis/déficit ­ fin de l''exercice');
INSERT INTO gifi (accno,description) VALUES ('8000','Ventes commerciales de biens et services');
INSERT INTO gifi (accno,description) VALUES ('8020','Ventes de biens et de services à des personnes apparentées');
INSERT INTO gifi (accno,description) VALUES ('8030','Ventes entre divisions');
INSERT INTO gifi (accno,description) VALUES ('8040','Ventes de ressources naturelles');
INSERT INTO gifi (accno,description) VALUES ('8041','Ventes de pétrole et de gaz naturel');
INSERT INTO gifi (accno,description) VALUES ('8042','Ventes de pétrole et de gaz naturel à des personnes apparentées');
INSERT INTO gifi (accno,description) VALUES ('8043','Commercialisation du gaz');
INSERT INTO gifi (accno,description) VALUES ('8044','Revenus de traitement');
INSERT INTO gifi (accno,description) VALUES ('8045','Revenus de transport par pipeline');
INSERT INTO gifi (accno,description) VALUES ('8046','Ventes reliées à l''exploration séismique');
INSERT INTO gifi (accno,description) VALUES ('8047','Revenus provenant de l''exploitation minière');
INSERT INTO gifi (accno,description) VALUES ('8048','Revenus provenant du charbon');
INSERT INTO gifi (accno,description) VALUES ('8049','Revenus de sables bitumineux');
INSERT INTO gifi (accno,description) VALUES ('8050','Revenus provenant des redevances');
INSERT INTO gifi (accno,description) VALUES ('8051','Revenus/pertes d''une société de personnes/coentreprise ­ pétrole et gaz');
INSERT INTO gifi (accno,description) VALUES ('8052','Revenus/pertes d''une société de personnes/coentreprise ­ mines');
INSERT INTO gifi (accno,description) VALUES ('8053','Autres revenus de production');
INSERT INTO gifi (accno,description) VALUES ('8089','Total des ventes de biens et services');
INSERT INTO gifi (accno,description) VALUES ('8090','Revenus de placements');
INSERT INTO gifi (accno,description) VALUES ('8091','Intérêt de sources étrangères');
INSERT INTO gifi (accno,description) VALUES ('8092','Intérêt d''obligations et de débentures canadiennes');
INSERT INTO gifi (accno,description) VALUES ('8093','Intérêt de prêts hypothécaires canadiens');
INSERT INTO gifi (accno,description) VALUES ('8094','Intérêt d''autres sources canadiennes');
INSERT INTO gifi (accno,description) VALUES ('8095','Revenus de dividendes');
INSERT INTO gifi (accno,description) VALUES ('8096','Dividendes de sources canadiennes');
INSERT INTO gifi (accno,description) VALUES ('8097','Dividendes de sources étrangères');
INSERT INTO gifi (accno,description) VALUES ('8100','Revenus d''intérêt (institutions financières)');
INSERT INTO gifi (accno,description) VALUES ('8101','Intérêt de prêts');
INSERT INTO gifi (accno,description) VALUES ('8102','Intérêt de valeurs mobilières');
INSERT INTO gifi (accno,description) VALUES ('8103','Intérêt des dépôts en banque');
INSERT INTO gifi (accno,description) VALUES ('8120','Revenus de commissions');
INSERT INTO gifi (accno,description) VALUES ('8121','Revenus de commissions sur les transactions immobilières');
INSERT INTO gifi (accno,description) VALUES ('8140','Revenus de location');
INSERT INTO gifi (accno,description) VALUES ('8141','Revenus de location immobilière');
INSERT INTO gifi (accno,description) VALUES ('8142','Revenus de location de films');
INSERT INTO gifi (accno,description) VALUES ('8150','Contrats de location de véhicules');
INSERT INTO gifi (accno,description) VALUES ('8160','Revenus provenant de la pêche');
INSERT INTO gifi (accno,description) VALUES ('8161','Ventes de poisson');
INSERT INTO gifi (accno,description) VALUES ('8162','Autres produits marins');
INSERT INTO gifi (accno,description) VALUES ('8163','Subventions, crédits et dégrèvements de pêche');
INSERT INTO gifi (accno,description) VALUES ('8164','Subventions de pêche');
INSERT INTO gifi (accno,description) VALUES ('8165','Indemnité pour perte d''un revenu ou d''un bien de pêche');
INSERT INTO gifi (accno,description) VALUES ('8166','Revenu de pêcheur à la part');
INSERT INTO gifi (accno,description) VALUES ('8210','Profits/pertes sur la disposition d''éléments d''actif');
INSERT INTO gifi (accno,description) VALUES ('8211','Profits/pertes sur la vente de placements');
INSERT INTO gifi (accno,description) VALUES ('8212','Profits/pertes sur la disposition d''avoir minier');
INSERT INTO gifi (accno,description) VALUES ('8220','Montants reçus d''OSBL');
INSERT INTO gifi (accno,description) VALUES ('8221','Frais d''adhésion');
INSERT INTO gifi (accno,description) VALUES ('8222','Cotisations');
INSERT INTO gifi (accno,description) VALUES ('8223','Dons');
INSERT INTO gifi (accno,description) VALUES ('8224','Ventes et recettes brutes provenant d''activités de l''organisme');
INSERT INTO gifi (accno,description) VALUES ('8230','Autres revenus');
INSERT INTO gifi (accno,description) VALUES ('8231','Gains/pertes sur devises étrangères');
INSERT INTO gifi (accno,description) VALUES ('8232','Revenus/pertes de filiales/de sociétés affiliées');
INSERT INTO gifi (accno,description) VALUES ('8233','Revenus/pertes d''autres divisions');
INSERT INTO gifi (accno,description) VALUES ('8234','Revenus/pertes des coentreprises');
INSERT INTO gifi (accno,description) VALUES ('8235','Revenus/pertes des sociétés de personnes');
INSERT INTO gifi (accno,description) VALUES ('8236','Réalisation de revenus différés');
INSERT INTO gifi (accno,description) VALUES ('8237','Revenus de redevances autres que l''exploitation des ressources naturelles');
INSERT INTO gifi (accno,description) VALUES ('8238','Crédits d''impôts pour redevances de l''Alberta');
INSERT INTO gifi (accno,description) VALUES ('8239','Honoraires de gestion et d''administration');
INSERT INTO gifi (accno,description) VALUES ('8240','Revenus de télécommunications');
INSERT INTO gifi (accno,description) VALUES ('8241','Honoraires de consultation');
INSERT INTO gifi (accno,description) VALUES ('8242','Subventions et octrois');
INSERT INTO gifi (accno,description) VALUES ('8243','Ventes de sous-produits');
INSERT INTO gifi (accno,description) VALUES ('8244','Frais d''administration provenant du service des dépôts');
INSERT INTO gifi (accno,description) VALUES ('8245','Frais d''administration provenant du service du crédit');
INSERT INTO gifi (accno,description) VALUES ('8246','Frais d''administration provenant du service des cartes bancaires');
INSERT INTO gifi (accno,description) VALUES ('8247','Ristournes');
INSERT INTO gifi (accno,description) VALUES ('8248','Recouvrement d''assurance');
INSERT INTO gifi (accno,description) VALUES ('8249','Recouvrement de frais');
INSERT INTO gifi (accno,description) VALUES ('8250','Recouvrement des mauvaises créances');
INSERT INTO gifi (accno,description) VALUES ('8299','Total des revenus');
INSERT INTO gifi (accno,description) VALUES ('8300','Stock d''ouverture');
INSERT INTO gifi (accno,description) VALUES ('8301','Stock d''ouverture ­ produits finis');
INSERT INTO gifi (accno,description) VALUES ('8302','Stock d''ouverture ­ matières premières');
INSERT INTO gifi (accno,description) VALUES ('8303','Stock d''ouverture ­ produits en cours de fabrication');
INSERT INTO gifi (accno,description) VALUES ('8320','Achats/coût des matériaux');
INSERT INTO gifi (accno,description) VALUES ('8340','Salaires directs');
INSERT INTO gifi (accno,description) VALUES ('8350','Avantages sociaux relatifs aux salaires directs');
INSERT INTO gifi (accno,description) VALUES ('8360','Fournisseurs et sous-traitants');
INSERT INTO gifi (accno,description) VALUES ('8370','Coûts de production (autres que ressources naturelles)');
INSERT INTO gifi (accno,description) VALUES ('8400','Coûts de production des ressources naturelles');
INSERT INTO gifi (accno,description) VALUES ('8401','Exploitation des pipelines');
INSERT INTO gifi (accno,description) VALUES ('8402','Forage');
INSERT INTO gifi (accno,description) VALUES ('8403','Coûts de restauration des sites d''exploitation');
INSERT INTO gifi (accno,description) VALUES ('8404','Redevances dérogatoires brutes');
INSERT INTO gifi (accno,description) VALUES ('8405','Redevances de propriété franche');
INSERT INTO gifi (accno,description) VALUES ('8406','Paiements de location de concessions publiques');
INSERT INTO gifi (accno,description) VALUES ('8407','Prospection/travaux de géologie');
INSERT INTO gifi (accno,description) VALUES ('8408','Exploitation des puits, carburant et matériel');
INSERT INTO gifi (accno,description) VALUES ('8409','Abandon de puits et puits secs');
INSERT INTO gifi (accno,description) VALUES ('8410','Autres paiements de location');
INSERT INTO gifi (accno,description) VALUES ('8411','Frais d''exploration');
INSERT INTO gifi (accno,description) VALUES ('8412','Frais d''aménagement');
INSERT INTO gifi (accno,description) VALUES ('8435','Sommes exigées par la Couronne');
INSERT INTO gifi (accno,description) VALUES ('8436','Redevances à la Couronne');
INSERT INTO gifi (accno,description) VALUES ('8437','Frais de location de la Couronne');
INSERT INTO gifi (accno,description) VALUES ('8438','Impôts sur le minerai de propriété franche');
INSERT INTO gifi (accno,description) VALUES ('8439','Impôts miniers');
INSERT INTO gifi (accno,description) VALUES ('8440','Frais de location des sables bitumineux');
INSERT INTO gifi (accno,description) VALUES ('8441','Surtaxe de la Saskatchewan sur les ressources');
INSERT INTO gifi (accno,description) VALUES ('8450','Autres coûts directs');
INSERT INTO gifi (accno,description) VALUES ('8451','Location et exploitation de matériel');
INSERT INTO gifi (accno,description) VALUES ('8452','Cour à bois');
INSERT INTO gifi (accno,description) VALUES ('8453','Coûts d''exploitation forestière');
INSERT INTO gifi (accno,description) VALUES ('8454','Coûts des chemins forestiers');
INSERT INTO gifi (accno,description) VALUES ('8455','Droits de coupe');
INSERT INTO gifi (accno,description) VALUES ('8456','Coûts des redevances');
INSERT INTO gifi (accno,description) VALUES ('8457','Frais de transport à l''achat et droits');
INSERT INTO gifi (accno,description) VALUES ('8458','Moins-value de l''inventaire');
INSERT INTO gifi (accno,description) VALUES ('8459','Coût direct de l''amortissement des biens corporels');
INSERT INTO gifi (accno,description) VALUES ('8460','Coût direct de l''amortissement des biens constitués');
INSERT INTO gifi (accno,description) VALUES ('8461','Autres frais indirects attribués au coût des ventes');
INSERT INTO gifi (accno,description) VALUES ('8500','Stock de fermeture');
INSERT INTO gifi (accno,description) VALUES ('8501','Stock de fermeture ­ produits finis');
INSERT INTO gifi (accno,description) VALUES ('8502','Stock de fermeture ­ matières premières');
INSERT INTO gifi (accno,description) VALUES ('8503','Stock de fermeture ­ travaux en cours de fabrication');
INSERT INTO gifi (accno,description) VALUES ('8518','Coût des ventes');
INSERT INTO gifi (accno,description) VALUES ('8519','Profit brut/perte brute');
INSERT INTO gifi (accno,description) VALUES ('8520','Publicité et promotion');
INSERT INTO gifi (accno,description) VALUES ('8521','Publicité');
INSERT INTO gifi (accno,description) VALUES ('8522','Dons');
INSERT INTO gifi (accno,description) VALUES ('8523','Repas et frais de représentation');
INSERT INTO gifi (accno,description) VALUES ('8524','Promotion');
INSERT INTO gifi (accno,description) VALUES ('8570','Amortissement de biens incorporels');
INSERT INTO gifi (accno,description) VALUES ('8590','Créances irrécouvrables');
INSERT INTO gifi (accno,description) VALUES ('8610','Pertes sur prêts');
INSERT INTO gifi (accno,description) VALUES ('8611','Provision pour les pertes sur prêts');
INSERT INTO gifi (accno,description) VALUES ('8620','Avantages sociaux');
INSERT INTO gifi (accno,description) VALUES ('8621','Assurances collectives');
INSERT INTO gifi (accno,description) VALUES ('8622','Partie de l''employeur des avantages sociaux');
INSERT INTO gifi (accno,description) VALUES ('8623','Cotisations aux régimes de revenus différés');
INSERT INTO gifi (accno,description) VALUES ('8650','Amortissement des biens constitués par des ressources naturelles');
INSERT INTO gifi (accno,description) VALUES ('8670','Amortissement des biens corporels');
INSERT INTO gifi (accno,description) VALUES ('8690','Assurances');
INSERT INTO gifi (accno,description) VALUES ('8691','Assurance sur la vie des dirigeants');
INSERT INTO gifi (accno,description) VALUES ('8710','Intérêts et frais bancaires');
INSERT INTO gifi (accno,description) VALUES ('8711','Intérêts sur les dettes à court terme');
INSERT INTO gifi (accno,description) VALUES ('8712','Intérêts sur les obligations et les débentures');
INSERT INTO gifi (accno,description) VALUES ('8713','Intérêts sur les prêts hypothécaires');
INSERT INTO gifi (accno,description) VALUES ('8714','Intérêts sur les dettes à long terme');
INSERT INTO gifi (accno,description) VALUES ('8715','Frais bancaires');
INSERT INTO gifi (accno,description) VALUES ('8716','Frais de cartes de crédit');
INSERT INTO gifi (accno,description) VALUES ('8717','Frais de recouvrement et de crédit');
INSERT INTO gifi (accno,description) VALUES ('8740','Intérêts payés (institutions financières)');
INSERT INTO gifi (accno,description) VALUES ('8741','Intérêts payés sur dépôts');
INSERT INTO gifi (accno,description) VALUES ('8742','Intérêts payés sur les obligations et les débentures');
INSERT INTO gifi (accno,description) VALUES ('8760','Taxes d''affaires, droits d''adhésion et licences');
INSERT INTO gifi (accno,description) VALUES ('8761','Droits d''adhésion');
INSERT INTO gifi (accno,description) VALUES ('8762','Taxes d''affaires');
INSERT INTO gifi (accno,description) VALUES ('8763','Frais de franchise');
INSERT INTO gifi (accno,description) VALUES ('8764','Frais à verser aux gouvernements');
INSERT INTO gifi (accno,description) VALUES ('8780','Taxe des grandes sociétés du Nouveau-Brunswick');
INSERT INTO gifi (accno,description) VALUES ('8790','Taxe des grandes sociétés de la Nouvelle-Écosse');
INSERT INTO gifi (accno,description) VALUES ('8810','Frais de bureau');
INSERT INTO gifi (accno,description) VALUES ('8811','Papeterie et fournitures de bureau');
INSERT INTO gifi (accno,description) VALUES ('8812','Services de bureau');
INSERT INTO gifi (accno,description) VALUES ('8813','Traitement des données');
INSERT INTO gifi (accno,description) VALUES ('8860','Honoraires professionnels');
INSERT INTO gifi (accno,description) VALUES ('8861','Frais légaux');
INSERT INTO gifi (accno,description) VALUES ('8862','Frais comptables');
INSERT INTO gifi (accno,description) VALUES ('8863','Honoraires d''experts-conseils');
INSERT INTO gifi (accno,description) VALUES ('8864','Honoraires d''architectes');
INSERT INTO gifi (accno,description) VALUES ('8865','Frais d''évaluation');
INSERT INTO gifi (accno,description) VALUES ('8866','Frais de laboratoire');
INSERT INTO gifi (accno,description) VALUES ('8867','Honoraires médicaux');
INSERT INTO gifi (accno,description) VALUES ('8868','Frais de vétérinaire');
INSERT INTO gifi (accno,description) VALUES ('8869','Frais de courtage');
INSERT INTO gifi (accno,description) VALUES ('8870','Frais de transfert');
INSERT INTO gifi (accno,description) VALUES ('8871','Frais de gestion et d''administration');
INSERT INTO gifi (accno,description) VALUES ('8872','Affinage et dosage');
INSERT INTO gifi (accno,description) VALUES ('8873','Droits d''enregistrement et frais d''agents de transfert');
INSERT INTO gifi (accno,description) VALUES ('8874','Coûts de restructuration');
INSERT INTO gifi (accno,description) VALUES ('8875','Commissions sur les titres et les valeurs mobilières');
INSERT INTO gifi (accno,description) VALUES ('8876','Frais de formation');
INSERT INTO gifi (accno,description) VALUES ('8877','Studio et enregistrement');
INSERT INTO gifi (accno,description) VALUES ('8910','Frais de location');
INSERT INTO gifi (accno,description) VALUES ('8911','Loyer de biens immobiliers');
INSERT INTO gifi (accno,description) VALUES ('8912','Frais d''occupation');
INSERT INTO gifi (accno,description) VALUES ('8913','Frais de copropriété');
INSERT INTO gifi (accno,description) VALUES ('8914','Location de matériel');
INSERT INTO gifi (accno,description) VALUES ('8915','Location de véhicules motorisés');
INSERT INTO gifi (accno,description) VALUES ('8916','Amarrage (bateau)');
INSERT INTO gifi (accno,description) VALUES ('8917','Entreposage');
INSERT INTO gifi (accno,description) VALUES ('8918','Location de contingents');
INSERT INTO gifi (accno,description) VALUES ('8960','Réparations et entretien');
INSERT INTO gifi (accno,description) VALUES ('8961','Réparations et entretien ­ bâtiments');
INSERT INTO gifi (accno,description) VALUES ('8962','Réparations et entretien ­ véhicules');
INSERT INTO gifi (accno,description) VALUES ('8963','Réparations et entretien ­ bateaux');
INSERT INTO gifi (accno,description) VALUES ('8964','Réparations et entretien ­ machines et matériel');
INSERT INTO gifi (accno,description) VALUES ('9010','Autres frais de réparation et d''entretien');
INSERT INTO gifi (accno,description) VALUES ('9011','Dépense d''usinage');
INSERT INTO gifi (accno,description) VALUES ('9012','Frais relatifs aux routes');
INSERT INTO gifi (accno,description) VALUES ('9013','Sécurité');
INSERT INTO gifi (accno,description) VALUES ('9014','Enlèvement des déchets');
INSERT INTO gifi (accno,description) VALUES ('9060','Salaires et traitements');
INSERT INTO gifi (accno,description) VALUES ('9061','Commissions');
INSERT INTO gifi (accno,description) VALUES ('9062','Part de l''équipage');
INSERT INTO gifi (accno,description) VALUES ('9063','Gratifications');
INSERT INTO gifi (accno,description) VALUES ('9064','Jetons de présence des administrateurs');
INSERT INTO gifi (accno,description) VALUES ('9065','Salaires des cadres');
INSERT INTO gifi (accno,description) VALUES ('9066','Salaires des employés');
INSERT INTO gifi (accno,description) VALUES ('9110','Contrats de sous-traitance');
INSERT INTO gifi (accno,description) VALUES ('9130','Fournitures');
INSERT INTO gifi (accno,description) VALUES ('9131','Petit outillage');
INSERT INTO gifi (accno,description) VALUES ('9132','Frais d''atelier');
INSERT INTO gifi (accno,description) VALUES ('9133','Uniformes');
INSERT INTO gifi (accno,description) VALUES ('9134','Blanchissage');
INSERT INTO gifi (accno,description) VALUES ('9135','Alimentation et restauration');
INSERT INTO gifi (accno,description) VALUES ('9136','Matériel de pêche');
INSERT INTO gifi (accno,description) VALUES ('9137','Filets et pièges');
INSERT INTO gifi (accno,description) VALUES ('9138','Sel, appâts et glace');
INSERT INTO gifi (accno,description) VALUES ('9139','Fournitures de camp');
INSERT INTO gifi (accno,description) VALUES ('9150','Dépenses liées à l''informatique');
INSERT INTO gifi (accno,description) VALUES ('9151','Améliorations et modernisations');
INSERT INTO gifi (accno,description) VALUES ('9152','Internet');
INSERT INTO gifi (accno,description) VALUES ('9180','Taxes foncières');
INSERT INTO gifi (accno,description) VALUES ('9200','Frais de déplacement');
INSERT INTO gifi (accno,description) VALUES ('9220','Services publics');
INSERT INTO gifi (accno,description) VALUES ('9221','Électricité');
INSERT INTO gifi (accno,description) VALUES ('9222','Eau');
INSERT INTO gifi (accno,description) VALUES ('9223','Chauffage');
INSERT INTO gifi (accno,description) VALUES ('9224','Frais de carburant');
INSERT INTO gifi (accno,description) VALUES ('9270','Autres dépenses');
INSERT INTO gifi (accno,description) VALUES ('9271','Écarts de caisse');
INSERT INTO gifi (accno,description) VALUES ('9272','Remboursement de frais de la société mère');
INSERT INTO gifi (accno,description) VALUES ('9273','Frais de vente');
INSERT INTO gifi (accno,description) VALUES ('9274','Frais de transport et d''entreposage');
INSERT INTO gifi (accno,description) VALUES ('9275','Livraison, fret et messageries');
INSERT INTO gifi (accno,description) VALUES ('9276','Frais de garantie');
INSERT INTO gifi (accno,description) VALUES ('9277','Frais de redevances ­ résidents');
INSERT INTO gifi (accno,description) VALUES ('9278','Frais de redevances ­ non-résidents');
INSERT INTO gifi (accno,description) VALUES ('9279','Frais de déchargement');
INSERT INTO gifi (accno,description) VALUES ('9280','Frais d''enfouissement');
INSERT INTO gifi (accno,description) VALUES ('9281','Frais de véhicules');
INSERT INTO gifi (accno,description) VALUES ('9282','Recherche et développement');
INSERT INTO gifi (accno,description) VALUES ('9283','Retenues d''impôts');
INSERT INTO gifi (accno,description) VALUES ('9284','Frais d''administration et frais généraux');
INSERT INTO gifi (accno,description) VALUES ('9285','Dépenses entre divisions');
INSERT INTO gifi (accno,description) VALUES ('9286','Transferts interfonds');
INSERT INTO gifi (accno,description) VALUES ('9367','Total des frais d''exploitation');
INSERT INTO gifi (accno,description) VALUES ('9368','Total des dépenses');
INSERT INTO gifi (accno,description) VALUES ('9369','Revenu non agricole net');
INSERT INTO gifi (accno,description) VALUES ('9370','Grains et oléagineux');
INSERT INTO gifi (accno,description) VALUES ('9371','Blé');
INSERT INTO gifi (accno,description) VALUES ('9372','Avoine');
INSERT INTO gifi (accno,description) VALUES ('9373','Orge');
INSERT INTO gifi (accno,description) VALUES ('9374','Grains mixtes');
INSERT INTO gifi (accno,description) VALUES ('9375','Maïs');
INSERT INTO gifi (accno,description) VALUES ('9376','Canola');
INSERT INTO gifi (accno,description) VALUES ('9377','Graine de lin');
INSERT INTO gifi (accno,description) VALUES ('9378','Fèves soya');
INSERT INTO gifi (accno,description) VALUES ('9379','Paiements de la Commission canadienne du blé');
INSERT INTO gifi (accno,description) VALUES ('9420','Revenus d''autres récoltes');
INSERT INTO gifi (accno,description) VALUES ('9421','Fruits');
INSERT INTO gifi (accno,description) VALUES ('9422','Pommes de terre');
INSERT INTO gifi (accno,description) VALUES ('9423','Légumes');
INSERT INTO gifi (accno,description) VALUES ('9424','Tabac');
INSERT INTO gifi (accno,description) VALUES ('9425','Produits de serre et de pépinière');
INSERT INTO gifi (accno,description) VALUES ('9426','Récolte de fourrage');
INSERT INTO gifi (accno,description) VALUES ('9470','Revenus du bétail et des produits d''origine');
INSERT INTO gifi (accno,description) VALUES ('9471','Bovins');
INSERT INTO gifi (accno,description) VALUES ('9472','Porcins');
INSERT INTO gifi (accno,description) VALUES ('9473','Volaille');
INSERT INTO gifi (accno,description) VALUES ('9474','Ovins');
INSERT INTO gifi (accno,description) VALUES ('9475','Urine de jument gravide (UJG)');
INSERT INTO gifi (accno,description) VALUES ('9476','Lait et crème (à l''exclusion des subventions pour');
INSERT INTO gifi (accno,description) VALUES ('9477','OEufs pour la consommation');
INSERT INTO gifi (accno,description) VALUES ('9478','Couvaison des oeufs');
INSERT INTO gifi (accno,description) VALUES ('9479','Aquaculture (couvée et élevage)');
INSERT INTO gifi (accno,description) VALUES ('9480','Chevaux (reproduction et viande)');
INSERT INTO gifi (accno,description) VALUES ('9520','Autres produits');
INSERT INTO gifi (accno,description) VALUES ('9521','Produits de l''érable');
INSERT INTO gifi (accno,description) VALUES ('9522','Insémination artificielle');
INSERT INTO gifi (accno,description) VALUES ('9523','Production de sperme');
INSERT INTO gifi (accno,description) VALUES ('9524','Production d''embryon');
INSERT INTO gifi (accno,description) VALUES ('9540','Revenus des paiements de programmes');
INSERT INTO gifi (accno,description) VALUES ('9541','Subventions laitières');
INSERT INTO gifi (accno,description) VALUES ('9542','Assurance-récolte');
INSERT INTO gifi (accno,description) VALUES ('9543','Paiements du CSRN');
INSERT INTO gifi (accno,description) VALUES ('9544','Paiements provenant du programme d''aide en cas de catastrophe');
INSERT INTO gifi (accno,description) VALUES ('9570','Remises');
INSERT INTO gifi (accno,description) VALUES ('9571','Remises ­ carburant');
INSERT INTO gifi (accno,description) VALUES ('9572','Remises ­ intérêt');
INSERT INTO gifi (accno,description) VALUES ('9573','Remises ­ taxes foncières');
INSERT INTO gifi (accno,description) VALUES ('9574','Reventes, Remises de la TPS pour les dépenses');
INSERT INTO gifi (accno,description) VALUES ('9575','Remises de la TPS pour les dépenses non');
INSERT INTO gifi (accno,description) VALUES ('9600','Autres revenus/pertes agricoles');
INSERT INTO gifi (accno,description) VALUES ('9601','Travail sur commande ou en sous-traitance');
INSERT INTO gifi (accno,description) VALUES ('9602','Ventes de bois');
INSERT INTO gifi (accno,description) VALUES ('9603','Courses de chevaux');
INSERT INTO gifi (accno,description) VALUES ('9604','Produits d''assurance');
INSERT INTO gifi (accno,description) VALUES ('9605','Ristournes');
INSERT INTO gifi (accno,description) VALUES ('9606','Revenu de location');
INSERT INTO gifi (accno,description) VALUES ('9607','Revenu en intérêt');
INSERT INTO gifi (accno,description) VALUES ('9608','Revenu de dividendes');
INSERT INTO gifi (accno,description) VALUES ('9609','Profits/pertes sur la disposition de biens');
INSERT INTO gifi (accno,description) VALUES ('9610','Gravier');
INSERT INTO gifi (accno,description) VALUES ('9611','Camionnage');
INSERT INTO gifi (accno,description) VALUES ('9612','Revente des denrées achetées');
INSERT INTO gifi (accno,description) VALUES ('9613','Contrat-location (carburant, huile, puits, superficie, etc.)');
INSERT INTO gifi (accno,description) VALUES ('9614','Location de machines');
INSERT INTO gifi (accno,description) VALUES ('9615','Revenus/pertes des sociétés de personnes agricoles');
INSERT INTO gifi (accno,description) VALUES ('9616','Revenus/pertes des coentreprises agricoles');
INSERT INTO gifi (accno,description) VALUES ('9650','Revenu non agricole');
INSERT INTO gifi (accno,description) VALUES ('9659','Total des revenus agricoles');
INSERT INTO gifi (accno,description) VALUES ('9660','Dépenses liées aux récoltes');
INSERT INTO gifi (accno,description) VALUES ('9661','Contenants, ficelles et fils pour emballage');
INSERT INTO gifi (accno,description) VALUES ('9662','Engrais et chaux');
INSERT INTO gifi (accno,description) VALUES ('9663','Pesticides');
INSERT INTO gifi (accno,description) VALUES ('9664','Semences et plantes');
INSERT INTO gifi (accno,description) VALUES ('9665','Primes d''assurance (récolte) CSRN SAR');
INSERT INTO gifi (accno,description) VALUES ('9710','Dépenses liées au bétail');
INSERT INTO gifi (accno,description) VALUES ('9711','Fourrage, suppléments, paille et litière');
INSERT INTO gifi (accno,description) VALUES ('9712','Achats de bétail');
INSERT INTO gifi (accno,description) VALUES ('9713','Frais de vétérinaire, de médicaments et de reproduction');
INSERT INTO gifi (accno,description) VALUES ('9714','Sel et minéraux');
INSERT INTO gifi (accno,description) VALUES ('9760','Dépenses liées aux machines');
INSERT INTO gifi (accno,description) VALUES ('9761','Assurance pour les machines');
INSERT INTO gifi (accno,description) VALUES ('9762','Plaques pour les machines');
INSERT INTO gifi (accno,description) VALUES ('9763','Réparation des machines');
INSERT INTO gifi (accno,description) VALUES ('9764','Carburant pour les machines');
INSERT INTO gifi (accno,description) VALUES ('9765','Contrat-location de machines');
INSERT INTO gifi (accno,description) VALUES ('9790','Dépenses agricoles générales');
INSERT INTO gifi (accno,description) VALUES ('9791','Amortissement des biens corporels');
INSERT INTO gifi (accno,description) VALUES ('9792','Publicité, promotion et dépenses de mise en marché');
INSERT INTO gifi (accno,description) VALUES ('9793','Mauvaises créances');
INSERT INTO gifi (accno,description) VALUES ('9794','Avantages sociaux liés aux salaires des employés');
INSERT INTO gifi (accno,description) VALUES ('9795','Réparations et entretien des bâtiments');
INSERT INTO gifi (accno,description) VALUES ('9796','Défrichage, nivellement et drainage de terrains');
INSERT INTO gifi (accno,description) VALUES ('9797','Primes d''assurance-récolte, de RARB et de');
INSERT INTO gifi (accno,description) VALUES ('9798','Travail sur commande ou en sous-traitance');
INSERT INTO gifi (accno,description) VALUES ('9799','Électricité');
INSERT INTO gifi (accno,description) VALUES ('9800','Réparations et entretien des clôtures');
INSERT INTO gifi (accno,description) VALUES ('9801','Fret et camionnage');
INSERT INTO gifi (accno,description) VALUES ('9802','Combustible pour chauffage et pour salaison');
INSERT INTO gifi (accno,description) VALUES ('9803','Remboursement de paiements en trop provenant');
INSERT INTO gifi (accno,description) VALUES ('9804','Autres primes d''assurance');
INSERT INTO gifi (accno,description) VALUES ('9805','Intérêts et frais bancaires');
INSERT INTO gifi (accno,description) VALUES ('9806','Droits versés à des offices de commercialisation');
INSERT INTO gifi (accno,description) VALUES ('9807','Frais d''adhésion');
INSERT INTO gifi (accno,description) VALUES ('9808','Dépenses de bureau');
INSERT INTO gifi (accno,description) VALUES ('9809','Honoraires professionnels');
INSERT INTO gifi (accno,description) VALUES ('9810','Taxes foncières');
INSERT INTO gifi (accno,description) VALUES ('9811','Location ­ terrain et bâtiments');
INSERT INTO gifi (accno,description) VALUES ('9812','Location ­ machines');
INSERT INTO gifi (accno,description) VALUES ('9813','Autres frais de location');
INSERT INTO gifi (accno,description) VALUES ('9814','Salaires et traitements');
INSERT INTO gifi (accno,description) VALUES ('9815','Salaires (autre que conjoint et personnes à charge)');
INSERT INTO gifi (accno,description) VALUES ('9816','Salaires versés aux personnes à charge');
INSERT INTO gifi (accno,description) VALUES ('9817','Coûts des ventes');
INSERT INTO gifi (accno,description) VALUES ('9818','Fournitures');
INSERT INTO gifi (accno,description) VALUES ('9819','Dépenses concernant les véhicules motorisés');
INSERT INTO gifi (accno,description) VALUES ('9820','Petit outillage');
INSERT INTO gifi (accno,description) VALUES ('9821','Analyses des sols');
INSERT INTO gifi (accno,description) VALUES ('9822','Entreposage/séchage');
INSERT INTO gifi (accno,description) VALUES ('9823','Licences/permis');
INSERT INTO gifi (accno,description) VALUES ('9824','Téléphone');
INSERT INTO gifi (accno,description) VALUES ('9825','Location de contingents (tabac, laitier)');
INSERT INTO gifi (accno,description) VALUES ('9826','Gravier');
INSERT INTO gifi (accno,description) VALUES ('9827','Achats de produits pour la revente');
INSERT INTO gifi (accno,description) VALUES ('9828','Salaires et traitements payés au conjoint');
INSERT INTO gifi (accno,description) VALUES ('9829','Coûts de location et intérêt sur un véhicule');
INSERT INTO gifi (accno,description) VALUES ('9830','Aliments préparés');
INSERT INTO gifi (accno,description) VALUES ('9831','Engraissement à forfait');
INSERT INTO gifi (accno,description) VALUES ('9832','Amortissement des biens incorporels');
INSERT INTO gifi (accno,description) VALUES ('9833','Amortissement de quote-part de lait');
INSERT INTO gifi (accno,description) VALUES ('9834','Frais de déplacement');
INSERT INTO gifi (accno,description) VALUES ('9835','Taxes d''affaires/sur le capital');
INSERT INTO gifi (accno,description) VALUES ('9850','Dépenses non agricoles');
INSERT INTO gifi (accno,description) VALUES ('9870','Régularisation des stocks');
INSERT INTO gifi (accno,description) VALUES ('9899','Total des revenus agricoles nets');
INSERT INTO gifi (accno,description) VALUES ('9970','Revenu net/perte nette avant impôts et éléments');
INSERT INTO gifi (accno,description) VALUES ('9975','Élément(s) extraordinaire(s)');
INSERT INTO gifi (accno,description) VALUES ('9976','Règlements juridiques');
INSERT INTO gifi (accno,description) VALUES ('9980','Profits/pertes non matérialisés');
INSERT INTO gifi (accno,description) VALUES ('9985','Éléments inhabituels');
INSERT INTO gifi (accno,description) VALUES ('9990','Impôts sur le revenu exigibles de l''exercice');
INSERT INTO gifi (accno,description) VALUES ('9995','Provision pour impôts sur le revenu différés');
INSERT INTO gifi (accno,description) VALUES ('9999','Revenu net/perte nette après impôts et éléments');
commit;
