version: '2.1'

services:

  chrome:
    image: selenium/node-chrome:3.141.59-20210607
    depends_on:
      - hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=hub
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5
      - GRID_DEBUG=true
