services:

  edge:
    image: selenium/node-edge
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5
      - GRID_DEBUG=true
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH=4442
      - SE_EVENT_BUS_SUBSCRIBE=4443
