version: '2.1'

services:

  firefox:
    image: selenium/node-firefox:3
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - NODE_MAX_SESSION=5
      - NODE_MAX_INSTANCES=5
      - GRID_DEBUG=true
