BEGIN;
-- Czech chart of accounts
-- Tomas.Fencl@centrum.cz
--
-- 3.3.2008
-- Vladimir Botka vlado@netng.org
-- customized for http://www.ledgersmb.org/
-- encoding UTF-8
--
-- Needs to be converted to use new framework.  Works, though, for now.
SELECT account_heading_save(NULL, '0000', '-----', NULL);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10001, '1000', 'Dlouhodobý nehmotný majetek', 'A', 'A', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10033, '3200', 'Umělecká díla a sbírky', 'A', 'A', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10005, '1200', 'Nehmotné výsledky výzkumu a vývoje', 'A', 'A', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10007, '1300', 'Software', 'A', 'A', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10009, '1400', 'Ocenitelná práva', 'A', 'A', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10011, '1800', 'Drobný dlouhodobý nehmotný majetek', 'A', 'A', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10013, '1900', 'Ostatní dlouhodobý nehmotný majetek', 'A', 'A', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10015, '2000', 'Dlouhodobý Hmotný majetek odpisovaný', 'H', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10017, '2100', 'Stavby', 'A', 'A', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10025, '2800', 'Drobný dlouhodobý hmotný majetek', 'A', 'A', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10027, '2900', 'Ostatní dlouhodobý hmotný majetek', 'A', 'A', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10029, '3000', 'Dlouhodobý hmotný majetek neodpisovaný', 'H', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10031, '3100', 'Pozemky', 'A', 'A', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10041, '5000', 'Poskytnuté zálohy na dlouhodobý nehmotný a hmotný majetek', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10043, '5100', 'Poskytnuté zálohy na dlouhodobý nehmotný majetek', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10045, '5200', 'Poskytnuté zálohy na dlouhodobý hmotný majetek', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10049, '6100', 'Podílové cenné papíry a vklady v podnicích s rozhodujícím', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10051, '6200', 'Podílové cenné papíry a vklady v podnicích s podstatným', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10053, '6300', 'Ostatní dlouhodobé cenné papíry a vklady', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10067, '7300', 'Oprávky k softwaru', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10071, '7800', 'Oprávky k drobnému dlouhodobému nehmotnému majetku', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10073, '7900', 'Oprávky k ostatnímu dlouhodobému nehmotnému majetku', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10075, '8000', 'Oprávky k dlouhodobému hmotnému majetku', 'H', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10077, '8100', 'Oprávky ke stavbám', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10085, '8800', 'Oprávky k drobnému dlouhodobému hmotnému majetku', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10087, '8900', 'Oprávky k ostatnímu dlouhodobému hmotnému majetku', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10107, '10000', 'Zásoby', 'H', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10109, '11000', 'Materiál', 'H', 'A', 'IC', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10117, '12000', 'Zásoby vlastní výroby', 'H', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10121, '12200', 'Polotovary vlastní výroby', 'A', 'A', 'IC', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10123, '12300', 'Výrobky', 'A', 'A', 'IC', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10151, '21000', 'Peníze', 'A', 'A', 'AR_paid:AP_paid', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10153, '21100', 'Pokladna', 'A', 'A', 'AR_paid:AP_paid', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10155, '21300', 'Ceniny', 'A', 'A', 'AR_paid:AP_paid', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10171, '24100', 'Emitované krátkodobé dluhopisy', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10177, '25100', 'Majetkové cenné papíry', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10179, '25200', 'Vlastní akcie a vlastní obchodní podíly', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10183, '25500', 'Vlastní dluhopisy', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10185, '25600', 'Ostatní cenné papíry', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10199, '31000', 'Pohledávky', 'H', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10205, '31300', 'Pohledávky za eskontované cenné papíry', 'A', 'A', 'AR', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10207, '31400', 'Poskytnuté provozní zálohy', 'A', 'A', 'AR', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10209, '31500', 'Ostatní pohledávky', 'A', 'A', 'AR', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10211, '32000', 'Závazky', 'H', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10213, '32100', 'Dodavatelé', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10219, '32500', 'Ostatní závazky', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10019, '2200', 'Samostatné movité věci a soubory movitých věcí', 'A', 'A', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10021, '2500', 'Pěstitelské celky trvalých porostů', 'A', 'A', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10023, '2600', 'Základní stádo a tažná zvířata', 'A', 'A', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10035, '4000', 'Pořízení dlouhodobého nehmotného a hmotného majetku', 'A', 'A', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10139, '19200', 'Opravná položka k nedokonèené výrobì', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10255, '34700', 'Ostatní dotace', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10261, '35300', 'Pohledávky za upsaný vlastní kapitál', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10283, '37000', 'Jiné pohledávky a závazky', 'H', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10287, '37300', 'Nakoupené opce', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10289, '37400', 'Prodané opce', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10295, '37800', 'Jiné pohledávky', 'A', 'A', 'AR', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10297, '37900', 'Jiné závazky', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10311, '38600', 'Kursové rozdíly aktivní', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10313, '38700', 'Kursové rozdíly pasívní', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10331, '41100', 'Základní kapitál', 'A', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10335, '41300', 'Ostatní kapitálové fondy', 'A', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10341, '42100', 'Zákonný rezervní fond', 'A', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10345, '42300', 'Statutární fondy', 'A', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10347, '42700', 'Ostatní fondy', 'A', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10357, '45000', 'Rezervy', 'H', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10359, '45100', 'Rezervy zákonné', 'A', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10361, '45400', 'Rezerva na kursové ztráty', 'A', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10363, '45900', 'Ostatní rezervy', 'A', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10369, '47000', 'Dlouhodobé závazky', 'H', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10373, '47300', 'Emitované dluhopisy', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10375, '47400', 'Závazky z pronájmu', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10381, '47900', 'Ostatní dlouhodobé závazky', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10383, '49000', 'Individuální podnikatel', 'A', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10401, '51200', 'Cestovné', 'A', 'E', 'AP_amount:IC_expense', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10403, '51300', 'Náklady na reprezentaci', 'A', 'E', 'AP_amount:IC_expense', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10407, '52000', 'Osobní náklady', 'A', 'E', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10409, '52100', 'Mzdové náklady', 'A', 'E', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10419, '52600', 'Sociální náklady individuálního podnikatele', 'A', 'E', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10421, '52700', 'Zákonné sociální náklady', 'A', 'E', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10423, '52800', 'Ostatní sociální náklady', 'A', 'E', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10433, '54000', 'Jiné provozní náklady', 'A', 'E', 'AP_amount:IC_expense', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10437, '54200', 'Prodaný materiál', 'A', 'E', 'IC_COGS', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10439, '54300', 'Dary', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10441, '54400', 'Smluvní pokuty a úroky z prodlení', 'A', 'E', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10443, '54500', 'Ostatní pokuty a penále', 'A', 'E', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10445, '54600', 'Odpis pohledávky', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10447, '54800', 'Ostatní provozní náklady', 'A', 'E', 'AP_amount:IC_expense', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10451, '55100', 'Odpisy dlouhodobého nehmotného a hmotného majetku', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10453, '55200', 'Tvorba zákonných rezerv', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10455, '55400', 'Tvorba ostatních rezerv', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10467, '56100', 'Prodané cenné papíry a vklady', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10469, '56200', 'Úroky', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10471, '56300', 'Kursové ztráty', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10477, '57400', 'Tvorba rezerv', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10487, '58400', 'Tvorba rezerv', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10529, '62000', 'Aktivace', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10537, '62400', 'Aktivace dlouhodobého hmotného majetku', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10539, '64000', 'Jiné provozní výnosy.', 'A', 'I', 'AR_amount:IC_sale:IC_Income', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10547, '64600', 'Výnosy z odepsaných pohledávek', 'A', 'I', 'AR_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10549, '64800', 'Jiné provozní výnosy', 'A', 'I', 'AR_amount:IC_sale:IC_Income', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10569, '66200', 'Úroky', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10571, '66300', 'Kursové zisky', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10243, '34311', 'DPH snížená vstup', 'A', 'L', 'AP_tax:IC_taxpart:IC_taxservice', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10245, '34312', 'DPH základní vstup', 'A', 'L', 'AP_tax:IC_taxpart:IC_taxservice', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10247, '34321', 'DPH snížená výstup', 'A', 'L', 'AR_tax:IC_taxpart:IC_taxservice', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10249, '34322', 'DPH základní výstup', 'A', 'L', 'AR_tax:IC_taxpart:IC_taxservice', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10003, '1100', 'Zřizovací výdaje', 'A', 'A', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10037, '4100', 'Pořízení dlouhodobého nehmotného majetku', 'A', 'A', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10039, '4200', 'Pořízení dlouhodobého hmotného majetku', 'A', 'A', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10047, '6000', 'Dlouhodobý finanční majetek', 'H', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10055, '6600', 'Pùjčky podnikùm ve skupinì', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10057, '6700', 'Ostatní pùjčky', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10059, '6900', 'Ostatní dlouhodobý finanční majetek', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10061, '7000', 'Oprávky k dlouhodobému nehmotnému majetku', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10063, '7100', 'Oprávky ke zřizovacím výdajùm', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10065, '7200', 'Oprávky k nehmotným výsledkům výzkumu a vývoje', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10069, '7400', 'Oprávky k ocenitelným právům', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10079, '8200', 'Oprávky k samostatným movitým věcem a souborùm movitých věcí', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10081, '8500', 'Oprávky k pěstitelským celkům trvalých porostů', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10083, '8600', 'Oprávky k základnímu stádu a tažným zvířatům', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10089, '9000', 'Opravné položky k dlouhodobému majetku', 'H', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10091, '9100', 'Opravná položka k dlouhodobému nehmotnému majetku', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10093, '9200', 'Opravná položka k dlouhodobému hmotnému majetku', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10095, '9300', 'Opravná položka k dlouhodobému nedokončenému nehmotnému', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10097, '9400', 'Opravná položka k dlouhodobému nedokončenému hmotnému', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10099, '9500', 'Opravná položka k poskytnutým zálohám', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10101, '9600', 'Opravná položka k dlouhodobému finančnímu majetku', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10103, '9700', 'Opravná položka k nabytému majetku', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10105, '9800', 'Oprávky k opravné položce k nabytému majetku', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10111, '11100', 'Pořízení materiálu', 'A', 'A', 'IC', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10113, '11200', 'Materiál na skladě', 'A', 'A', 'IC', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10115, '11900', 'Materiál na cestě', 'A', 'A', 'IC', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10119, '12100', 'Nedokončená výroba', 'A', 'A', 'IC', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10125, '12400', 'Zvířata', 'A', 'A', 'IC', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10127, '13000', 'Zboží', 'H', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10129, '13100', 'Pořízení zboží', 'A', 'A', 'IC', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10131, '13200', 'Zboží na skladě a v prodejnách', 'A', 'A', 'IC', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10133, '13900', 'Zboží na cestě', 'A', 'A', 'IC', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10135, '19000', 'Opravné položky k zásobám', 'H', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10137, '19100', 'Opravná položka k materiálu', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10141, '19300', 'Opravná položka k polotovarům vlastní výroby', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10143, '19400', 'Opravná položka k výrobkùm', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10145, '19500', 'Opravná položka ke zvířatům', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10147, '19600', 'Opravná položka ke zboží', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10149, '20000', 'Finanční účty', 'H', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10157, '22000', 'Účty v bankách', 'H', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10159, '22100', 'Bankovní účty', 'A', 'A', 'AR_paid:AP_paid', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10161, '22200', 'Bankovní účty klientù', 'A', 'A', 'AR_paid:AP_paid', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10163, '23000', 'Běžné bankovní úvěry', 'H', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10165, '23100', 'Krátkodobé bankovní úvěry', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10167, '23200', 'Eskontní úvěry', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10169, '24000', 'Jiné krátkodobé finanční výpomoci', 'H', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10173, '24900', 'Ostatní krátkodobé finanční výpomoci', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10175, '25000', 'Krátkodobý finanční majetek', 'H', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10181, '25300', 'Dlužné cenné papíry', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10187, '26000', 'Převody mezi finančními účty', 'H', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10189, '26100', 'Peníze na cestě', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10191, '29000', 'Opravné položky ke krátkodobému finančnímu majetku', 'H', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10193, '29100', 'Opravná položka k majetkovým cenným papírùm', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10195, '29300', 'Opravná položka k dlužným cenným papírům', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10197, '30000', 'Zúčtovací vztahy', 'H', 'H', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10201, '31100', 'Odběratelé', 'A', 'A', 'AR', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10203, '31200', 'Směnky k inkasu', 'A', 'A', 'AR', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10215, '32200', 'Směnky k úhradě', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10217, '32400', 'Přijaté zálohy', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10221, '32600', ' Závazky vůči klientům', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10223, '32700', ' Závazky vůči trhům', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10225, '33000', 'Zúčtování se zaměstnanci a institucemi', 'H', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10227, '33100', 'Zaměstnanci', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10229, '33300', 'Ostatní závazky vůči zaměstnancům', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10231, '33500', 'Pohledávky za zaměstnanci', 'A', 'A', 'AR', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10233, '33600', 'Zůčtování s institucemi sociálního zabezpečení a zp', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10235, '34000', 'Zůčtování daní a dotací', 'H', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10237, '34100', 'Daň z příjmu', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10239, '34200', 'Ostatní přímé daně', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10241, '34300', 'Daň z přidané hodnoty - zúčtování', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10251, '34500', 'Ostatní daně a poplatky', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10253, '34600', 'Dotace ze státního rozpočtu', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10257, '35000', 'Pohledávky ke společníkům a sdružení', 'H', 'A', 'AR', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10259, '35100', 'Pohledávky k podnikům ve skupině', 'A', 'A', 'AR', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10263, '35400', 'Pohledávky za společníky při úhradě ztráty', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10265, '35500', 'Ostatní pohledávky za společníky', 'A', 'A', 'AR', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10267, '35800', 'Pohledávky k účastníkùm sdružení', 'A', 'A', 'AR', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10269, '36000', 'Závazky ke společníkům a sdružení', 'H', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10271, '36100', 'Závazky k podnikům ve skupině', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10273, '36400', 'Závazky ke společníkům při rozdělování zisku', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10275, '36500', 'Ostatní závazky ke společníkům', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10277, '36600', 'Závazky ke společníkům a členům družstva ze závislé', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10279, '36700', 'Závazky z upsaných nesplacených cenných papírů a vkladů', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10281, '36800', 'Závazky k účastníkům sdružení', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10285, '37100', 'Odložená daňová pohledávka a závazek', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10291, '37500', 'Pohledávky z emitovaných dluhopisů', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10293, '37700', ' Zúčtování obchodů', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10299, '38000', 'Přechodné účty aktiv a pasiv', 'H', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10301, '38100', 'Náklady příštích období', 'A', 'A', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10303, '38200', 'Komplexní náklady příštích období', 'A', 'A', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10305, '38300', 'Výdaje příštích období', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10307, '38400', 'Výnosy příštích období', 'A', 'L', 'AR', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10309, '38500', 'Příjmy příštích období', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10315, '38800', 'Dohadné účty aktivní', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10317, '38900', 'Dohadné účty pasívní', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10319, '39000', 'Opravná položka k zúčtovacím vztahům a vnitřní zúčtování', 'H', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10321, '39100', 'Opravná položka k pohledávkám', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10323, '39500', 'Vnitřní zúčtování', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10325, '39800', 'Spojovací účet při sdružení', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10327, '40000', 'Kapitálové účty a dlouhodobé závazky', 'H', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10329, '41000', 'Základní kapitál a kapitálové fondy', 'H', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10333, '41200', 'Emisní ážio', 'A', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10337, '41400', 'Oceňovací rozdíly z přecenění majetku a závazků', 'A', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10339, '42000', 'Fondy ze zisku a převedené hospodářské výsledky', 'H', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10343, '42200', 'Nedělitelný fond', 'A', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10349, '42800', 'Nerozdělený zisk minulých let', 'A', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10351, '42900', 'Neuhrazená ztráta minulých let', 'A', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10353, '43000', 'Hospodářský výsledek', 'H', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10355, '43100', 'Hospodářský výsledek ve schvalovacím řízení', 'A', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10365, '46000', 'Bankovní úvěry', 'H', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10367, '46100', 'Bankovní úvěry', 'A', 'L', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10371, '47100', 'Dlouhodobé závazky k podnikům ve skupině', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10377, '47500', 'Dlouhodobé přijaté zálohy', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10379, '47800', 'Dlouhodobé směnky k úhradě', 'A', 'L', 'AP', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10385, '49100', 'Účet individuálního podnikatele', 'A', 'Q', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10387, '50000', 'Spotřebované nákupy', 'A', 'E', 'AP_amount:IC_COGS', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10389, '50100', 'Spotřeba materiálu', 'A', 'E', 'AP_amount:IC_COGS', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10391, '50200', 'Spotřeba energie', 'A', 'E', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10393, '50300', 'Spotřeba ostatních neskladovatelných dodávek', 'A', 'E', 'AP_amount:IC_COGS', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10395, '50400', 'Prodané zboží', 'A', 'E', 'AP_amount:IC_COGS', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10397, '51000', 'Služby', 'A', 'E', 'AP_amount:IC_expense', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10399, '51100', 'Opravy a udržování', 'A', 'E', 'AP_amount:IC_expense', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10405, '51800', 'Ostatní služby', 'A', 'E', 'AP_amount:IC_expense', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10411, '52200', 'Příjmy společníků a členů družstva ze závislé činnosti', 'A', 'E', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10413, '52300', 'Odměny členům orgánů společnosti a družstva', 'A', 'E', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10415, '52400', 'Zákonné sociální pojištění', 'A', 'E', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10417, '52500', 'Ostatní sociální pojištění', 'A', 'E', 'AP_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10425, '53000', 'Daně a poplatky', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10427, '53100', 'Daň silniční', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10429, '53200', 'Daň z nemovitostí', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10431, '53800', 'Ostatní daně a poplatky', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10435, '54100', 'Zůstatková cena prodaného dlouhodobého nehmotného a hmotného', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10449, '55000', 'Odpisy, rezervy a opravné položky provozních nákladů', 'H', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10457, '55500', 'Zúčtování komplexních nákladů příštích období', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10459, '55700', 'Zúčtování oprávky k opravné položce k nabytému majetku', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10461, '55800', 'Tvorba zákonných opravných položek', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10463, '55900', 'Tvorba opravných položek', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10465, '56000', 'Finanční náklady', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10473, '56800', 'Ostatní finanční náklady', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10475, '57000', 'Rezervy a opravné položky finančních nákladù', 'H', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10479, '57900', 'Tvorba opravných položek', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10481, '58000', 'Mimořádné náklady', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10483, '58100', 'Náklady na změnu metody', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10485, '58200', 'Manka a škody', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10489, '58800', 'Ostatní mimořádné náklady', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10491, '58900', 'Tvorba opravných položek', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10493, '59000', 'Daně z příjmù a převodové účty', 'H', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10495, '59100', 'Daň z příjmu z běžné činnosti - splatná', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10497, '59200', 'Daň z příjmu z běžné činnosti - odložená', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10499, '59300', 'Daň z příjmu z mimořádné činnosti - splatná', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10501, '59400', 'Daň z příjmu z mimořádné činnosti - odložená', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10503, '59500', 'Dodatečné odvody daně z příjmu', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10505, '59600', 'Převod podílu na hospodářském výsledku společníkùm', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10507, '59700', 'Převod provozních nákladů', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10509, '59800', 'Převod finančních nákladù', 'A', 'E', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10511, '60000', 'Tržby za vlastní výkony a zboží', 'A', 'I', 'AR_amount:IC_sale:IC_Income', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10513, '60100', 'Tržby za vlastní výrobky', 'A', 'I', 'AR_amount:IC_sale', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10515, '60200', 'Tržby z prodeje služeb', 'A', 'I', 'AR_amount:IC_income', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10517, '60400', 'Tržby za zboží', 'A', 'I', 'AR_amount:IC_sale', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10519, '61000', 'Změny stavu vnitropodnikových zásob', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10521, '61100', 'Změna stavu nedokončené výroby', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10523, '61200', 'Změna stavu polotovarů', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10525, '61300', 'Změna stavu výrobků', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10527, '61400', 'Změna stavu zvířat', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10531, '62100', 'Aktivace materiálu a zboží', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10533, '62200', 'Aktivace vnitropodnikových služeb', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10535, '62300', 'Aktivace dlouhodobého nehmotného majetku', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10541, '64100', 'Tržby z prodeje dlouhodobého nehmotného a hmotného majetku', 'A', 'I', 'AR_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10543, '64200', 'Tržby z prodeje materiálu', 'A', 'I', 'AR_amount:IC_sale', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10545, '64400', 'Smluvní pokuty a úroky z prodlení', 'A', 'I', 'AR_amount', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10551, '65000', 'Zúčtování rezerv a opravných položek provozních výnosů', 'H', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10553, '65200', 'Zúčtování zákonných rezerv', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10555, '65400', 'Zúčtování ostatních rezerv', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10557, '65500', 'Zúčtování komplexních nákladů příětích období', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10559, '65700', 'Zúčtování oprávky k opravné položce k nabytému majetku', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10561, '65800', 'Zúčtování zákonných opravných položek', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10563, '65900', 'Zúčtování opravných položek', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10565, '66000', 'Finanční výnosy', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10567, '66100', 'Tržby z prodeje cenných papírů a vkladů', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10573, '66500', 'Výnosy z dlouhodobého finančního majetku', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10575, '66600', 'Výnosy z krátkodobého finančního majetku', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10577, '66800', 'Ostatní finanční výnosy', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10579, '67000', 'Zúčtování rezerv a opravných položek finančních výnosů', 'H', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10581, '67400', 'Zúčtování rezerv', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10583, '67900', 'Zúčtování opravných položek', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10585, '68000', 'Mimořádné výnosy', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10587, '68100', 'Výnosy ze změny metody', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10589, '68400', 'Zúčtování rezerv', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10591, '68800', 'Ostatní mimořádné výnosy', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10593, '68900', 'Zúčtování opravných položek', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10595, '69000', 'Převodové účty', 'H', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10597, '69700', 'Převod provozních výnosů', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10599, '69800', 'Převod finančních výnosů', 'A', 'I', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10601, '70000', 'Účty rozvažné', 'H', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10603, '70100', 'Počáteční účet rozvažný', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10605, '70200', 'Konečný účet rozvažný', 'A', 'A', '', '', false);
INSERT INTO chart (id, accno, description, charttype, category, link, gifi_accno, contra) values (10607, '71000', 'Účet zisků a ztrát', 'A', 'A', '', '', false);
--
insert into tax (chart_id,rate) values ((select id from chart where accno = '34311'),0.05);
insert into tax (chart_id,rate) values ((select id from chart where accno = '34312'),0.19);
insert into tax (chart_id,rate) values ((select id from chart where accno = '34321'),0.05);
insert into tax (chart_id,rate) values ((select id from chart where accno = '34322'),0.19);
--
INSERT INTO defaults (setting_key, value) VALUES ('inventory_accno_id', (select id from chart where accno = '13200'));

INSERT INTO defaults (setting_key, value) VALUES ('income_accno_id', (select id from chart where accno = '60000'));

INSERT INTO defaults (setting_key, value) VALUES ('expense_accno_id', (select id from chart where accno = '50000'));

INSERT INTO defaults (setting_key, value) VALUES ('fxgain_accno_id', (select id from chart where accno = '99998'));

INSERT INTO defaults (setting_key, value) VALUES ('fxloss_accno_id', (select id from chart where accno = '99999'));

INSERT INTO defaults (setting_key, value) VALUES ('curr', 'CZK');

INSERT INTO defaults (setting_key, value) VALUES ('weightunit', 'kg');
--
commit;

--
UPDATE account
   SET tax = true
WHERE id
   IN (SELECT account_id
       FROM account_link
       WHERE description LIKE '%_tax');

