# See https://redocly.com/docs/cli/configuration/

apis:
  # Update the apiName with your actual API name, and the version with your actual API version.
  apiName@version:
    # Update the path to your OpenAPI root file
    root: ./openapi/openapi.yaml

lint:
  extends:
    - recommended
