openapi: 3.0.0
info:
  title: LedgerSMB Invoice management API
  version: 0.0.1
  description: |
    something


paths:
  /invoices:
    post:
      description: |
        something
      requestBody:
        description: ...
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InvoiceCreate'
      responses:
        '201':
          description: Created

  '/invoices/{id}':
    get:
      description: |
        hi
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Ok

components:
  schemas:
    InvoiceCreate:
      allOf:
        - $ref: '#/components/schemas/InvoiceRequiredFields'
        - $ref: '#/components/schemas/InvoiceOptionalFields'

    InvoiceRequiredFields:
      type: object
      required:
        - currency
        - account
        - eca
      properties:
        currency:
          type: string
        account:
          type: object
          required:
            - accno
          properties:
            accno:
              type: string
        eca:
          description: |
            haah
          oneOf:
            - type: object
              required:
                - type
                - number
              properties:
                type:
                  type: string
                  enum:
                    - customer
                    - vendor
                number:
                  type: string
            - type: object
              required:
                - id
              properties:
                id:
                  type: integer

    InvoiceOptionalFields:
      type: object
      properties:
        description:
          type: string
          nullable: true
        notes:
          type: string
          nullable: true
        internalNotes:
          type: number
          nullable: true
        invoiceNumber:
          type: string
          nullable: true
        orderNumber:
          type: string
          nullable: true
        poNumber:
          type: string
          nullable: true
        shipVia:
          type: string
          nullable: true
        shippingPoint:
          type: string
          nullable: true
        dates:
          type: object
          properties:
            due:
              type: string
              format: date
              nullable: true
            book:
              type: string
              format: date
              nullable: true
            created:
              type: string
              format: date
              nullable: true
        taxes:
          type: array
          items:
            $ref: '#/components/schemas/InvoiceTax'
        lines:
          type: array
          items:
            $ref: '#/components/schemas/InvoiceLineOptionalFields'

    InvoiceLineOptionalFields:
      type: object
      properties:
        description:
          type: string
          nullable: true
        price:
          type: number
          nullable: true
        priceFixated:
          type: boolean
          nullable: true
        unit:
          type: string
          nullable: true
        qty:
          type: number
          nullable: true
        discount:
          type: number
          nullable: true
        discountType:
          type: string
          enum:
            - '%'
          nullable: true
        taxform:
          type: boolean
          nullable: true
        deliverydate:
          type: string
          format: date
          nullable: true
        note:
          type: string
          nullable: true
        serialnumber:
          type: string
          nullable: true
        group:
          type: string
          nullable: true

    InvoiceTax:
      type: object
      required:
        - tax
      properties:
        baseAmount:
          type: number
          nullable: true
        amount:
          type: number
          nullable: true
        source:
          type: string
          nullable: true
        memo:
          type: string
          nullable: true
        calculatedAmount:
          type: number
          nullable: true
        tax:
          type: object
          required:
            - category
          properties:
            category:
              type: string
            rate:
              type: number
              nullable: true


