begin;
--Hungarian chart of accounts Complete
-- Magyar fõkönyvi számlák, amely majdnem teljes
--
SELECT account_heading_save(NULL, '1', 'BEFEKTETETT ESZKÖZÖK', NULL);
SELECT account_heading_save(NULL, '3', 'KÖVETELÉSEK', NULL);
SELECT account_heading_save(NULL, '8', 'RÁFORDÍTÁSOK', NULL);
SELECT account_heading_save(NULL, '9', 'BEVÉTELEK', NULL);
SELECT account_heading_save(NULL, '4', 'FORRÁSOK', NULL);
SELECT account_heading_save(NULL, '5', 'KÖLTSÉGNEMEK', NULL);
SELECT account_heading_save(NULL, '11', 'Immateriális javak', NULL);
SELECT account_heading_save(NULL, '12', 'Ingatlanok', NULL);
SELECT account_heading_save(NULL, '13', 'Műszaki gépek, berendezések, járművek', NULL);
SELECT account_heading_save(NULL, '14', 'Egyéb gépek, berendezések, járművek', NULL);
SELECT account_heading_save(NULL, '15', 'Beruházások', NULL);
SELECT account_heading_save(NULL, '114', 'Szellemi termékek', NULL);
SELECT account_heading_save(NULL, '117', 'Immateriális javak értékhelyesbítése', NULL);
SELECT account_heading_save(NULL, '118', 'Immateriális javak terven felüli értékcsökkenése', NULL);
SELECT account_heading_save(NULL, '119', 'Immateriális javak értékcsökkenése', NULL);
SELECT account_heading_save(NULL, '131', 'Termelő gépek, berendezések', NULL);
SELECT account_heading_save(NULL, '132', 'Járművek', NULL);
SELECT account_heading_save(NULL, '139', 'Mászeki gépek, berendezések, járművek értékcsökkenése', NULL);
SELECT account_heading_save(NULL, '137', 'Műszaki gépek, berendezések járművek értékhelyesbítése', NULL);
SELECT account_heading_save(NULL, '138', 'Műszaki gépek, berendezések, járművek terven felüli értékcsökkenése', NULL);
SELECT account_heading_save(NULL, '141', 'Egyéb gép, berendezés, szerszám', NULL);
SELECT account_heading_save(NULL, '142', 'Egyéb járművek', NULL);
SELECT account_heading_save(NULL, '143', 'Irodai, igazgatási berendezés, felszerelés', NULL);
SELECT account_heading_save(NULL, '145', 'Kisértékű tárgyi eszköz', NULL);
SELECT account_heading_save(NULL, '147', 'Egyéb gépek, berendezések, járművek értékhelyesbítése', NULL);
SELECT account_heading_save(NULL, '149', 'Egyéb gépek, berendezések, járművek elszámolt értékcsökkenése', NULL);
SELECT account_heading_save(NULL, '148', 'Egyéb gépek, berendezések, járművek terven felüli értékcsökkenése', NULL);
SELECT account_heading_save(NULL, '161', 'Befejezetlen beruházások', NULL);
SELECT account_heading_save(NULL, '21', 'Anyagok', NULL);
SELECT account_heading_save(NULL, '26', 'Kereskedelmi áruk', NULL);
SELECT account_heading_save(NULL, '31', 'Követelések áruszállításból, szolgáltatásból', NULL);
SELECT account_heading_save(NULL, '32', 'Követelések kapcsolt vállakozással szemben', NULL);
SELECT account_heading_save(NULL, '33', 'Követelések egyéb részesedési viszonyban lévő vállalkozással szemben', NULL);
SELECT account_heading_save(NULL, '34', 'Váltókövetelések', NULL);
SELECT account_heading_save(NULL, '35', 'Adott előlegek', NULL);
SELECT account_heading_save(NULL, '36', 'Egyéb követelések', NULL);
SELECT account_heading_save(NULL, '37', 'Értékpapirok', NULL);
SELECT account_heading_save(NULL, '38', 'Pénzeszközök', NULL);
SELECT account_heading_save(NULL, '39', 'Aktiv időbeli elhatárolások', NULL);
SELECT account_heading_save(NULL, '321', 'Követelések', NULL);
SELECT account_heading_save(NULL, '325', 'Jegyzett de be nem fizetett tőke', NULL);
SELECT account_heading_save(NULL, '329', 'Követelések értékvesztése', NULL);
SELECT account_heading_save(NULL, '331', 'Követelések egyéb részesedési viszonyban lévő vállalattal szemben', NULL);
SELECT account_heading_save(NULL, '332', 'Jegyzett, de még be nem fizetett tőke egyéb részesedési viszonyban lévő vállalkozástól', NULL);
SELECT account_heading_save(NULL, '339', 'Egyéb részesedési viszonyban lévő vállakozással szembeni követelés értékvesztése', NULL);
SELECT account_heading_save(NULL, '366', 'Rövid lejáratra adott pénzkölcsönök', NULL);
SELECT account_heading_save(NULL, '381', 'Pénztárak', NULL);
SELECT account_heading_save(NULL, '382', 'Valutapénztárak', NULL);
SELECT account_heading_save(NULL, '384', 'Elszámolási betétszámlák (Ft)', NULL);
SELECT account_heading_save(NULL, '386', 'Deviza betétszámlák', NULL);
SELECT account_heading_save(NULL, '389', 'Átvezetési számlák', NULL);
SELECT account_heading_save(NULL, '311', 'Belföldi vevők', NULL);
SELECT account_heading_save(NULL, '316', 'Külföldi vevők', NULL);
SELECT account_heading_save(NULL, '41', 'Saját tőke', NULL);
SELECT account_heading_save(NULL, '42', 'Céltartalékok', NULL);
SELECT account_heading_save(NULL, '43', 'Hátrasorolt kötelezettségek', NULL);
SELECT account_heading_save(NULL, '44', 'Hosszú lejáratú kötelezettségek', NULL);
SELECT account_heading_save(NULL, '442', 'Hosszú lejáratra kapott kölcsönök', NULL);
SELECT account_heading_save(NULL, '443', 'Beruházási fejlesztési hitelek', NULL);
SELECT account_heading_save(NULL, '444', 'Egyéb hosszú lejáratú hitelek', NULL);
SELECT account_heading_save(NULL, '447', 'Tartós kötelezettség egyéb vállalkozással szemben', NULL);
SELECT account_heading_save(NULL, '446', 'Tartós kötelezettség kapcsolt vállalkozással szemben', NULL);
SELECT account_heading_save(NULL, '449', 'Egyéb hosszú lejáratú kötelezettség', NULL);
SELECT account_heading_save(NULL, '45', 'Rövid lejáratú kötelezettségek', NULL);
SELECT account_heading_save(NULL, '451', 'Vevőktől kapott előlegek', NULL);
SELECT account_heading_save(NULL, '452', 'Rövid lejáratú kölcsönök', NULL);
SELECT account_heading_save(NULL, '453', 'Rövid lejáratú hitelek', NULL);
SELECT account_heading_save(NULL, '455', 'Pénzügyi lízing miatti kötelezettség', NULL);
SELECT account_heading_save(NULL, '456', 'Rövid lejáratú kötelezettség kapcsolt vállalkozással szemben', NULL);
SELECT account_heading_save(NULL, '457', 'Rövid lejáratú kötelezettség egyéb vállakozással szemben', NULL);
SELECT account_heading_save(NULL, '459', 'Egyéb rövid lejáratú kötelezettség', NULL);
SELECT account_heading_save(NULL, '46', 'Adóhatósággal szembeni kötelezettségek', NULL);
SELECT account_heading_save(NULL, '461', 'Társasági adó elszámolása', NULL);
SELECT account_heading_save(NULL, '462', 'SZJA elszámolás', NULL);
SELECT account_heading_save(NULL, '463', 'Költségvetési befizetési kötelezettség', NULL);
SELECT account_heading_save(NULL, '464', 'Költségvetési befizetési kötelezettség teljesitése', NULL);
SELECT account_heading_save(NULL, '465', 'VPOP elszámolási számla', NULL);
SELECT account_heading_save(NULL, '466', 'Előzetesen felszámítottt ÁFA', NULL);
SELECT account_heading_save(NULL, '467', 'Fizetendő ÁFA', NULL);
SELECT account_heading_save(NULL, '469', 'Helyi adók elszámolási számla', NULL);
SELECT account_heading_save(NULL, '47', 'Egyéb kötelezettségek', NULL);
SELECT account_heading_save(NULL, '471', 'Jövedelem elszámolási számla', NULL);
SELECT account_heading_save(NULL, '472', 'Fel nem vett járandóság', NULL);
SELECT account_heading_save(NULL, '473', 'Nyugdíj- és egészségbiztosítás', NULL);
SELECT account_heading_save(NULL, '4731', 'Nyugdíjbiztosítási Alap', NULL);
SELECT account_heading_save(NULL, '4732', 'Egészségbiztosítási Alap', NULL);
SELECT account_heading_save(NULL, '4733', 'Magánnyugdíjpénztár', NULL);
SELECT account_heading_save(NULL, '478', 'Osztalékelszámolási számla', NULL);
SELECT account_heading_save(NULL, '479', 'Egyéb rövid lejáratú kötelezettség', NULL);
SELECT account_heading_save(NULL, '48', 'Passzív időbeli elhatárolások', NULL);
SELECT account_heading_save(NULL, '49', 'Évi mérlegszámlák', NULL);
SELECT account_heading_save(NULL, '51', 'Anyagjellegű költségek', NULL);
SELECT account_heading_save(NULL, '52', 'Igénybevett szolgáltatások költségei', NULL);
SELECT account_heading_save(NULL, '521', 'Szállítási, rakodási költség', NULL);
SELECT account_heading_save(NULL, '524', 'Utazási és szállás költség', NULL);
SELECT account_heading_save(NULL, '525', 'Hirdetés és reklám költség', NULL);
SELECT account_heading_save(NULL, '526', 'Oktatás, továbbképzés költsége', NULL);
SELECT account_heading_save(NULL, '527', 'Posta költség', NULL);
SELECT account_heading_save(NULL, '528', 'Kommunikációs költségek', NULL);
SELECT account_heading_save(NULL, '529', 'Egyéb igénybevett szolgáltatások', NULL);
SELECT account_heading_save(NULL, '53', 'Egyéb szolgáltatások költségei', NULL);
SELECT account_heading_save(NULL, '531', 'Hatósági, igazgatási, szolg. illeték', NULL);
SELECT account_heading_save(NULL, '532', 'Bankköltség', NULL);
SELECT account_heading_save(NULL, '533', 'Biztosítási díjak', NULL);
SELECT account_heading_save(NULL, '539', 'Egyéb szolgáltatások ', NULL);
SELECT account_heading_save(NULL, '54', 'Bérköltség', NULL);
SELECT account_heading_save(NULL, '55', 'Személyi jellegű egyéb kifizetés', NULL);
SELECT account_heading_save(NULL, '56', 'Bérjárulékok', NULL);
SELECT account_heading_save(NULL, '561', 'Nyugdíj és egészségbiztosítás', NULL);
SELECT account_heading_save(NULL, '562', 'EHO', NULL);
SELECT account_heading_save(NULL, '57', 'Értékcsökkenési leirás', NULL);
SELECT account_heading_save(NULL, '81', 'Anyagjellegű ráforditások', NULL);
SELECT account_heading_save(NULL, '86', 'Egyéb ráforditások', NULL);
SELECT account_heading_save(NULL, '861', 'Értékesitett eszközök nyilvántartási értéke', NULL);
SELECT account_heading_save(NULL, '863', 'Egyéb eredményt csökkentő tételek', NULL);
SELECT account_heading_save(NULL, '864', 'Céltartalék képzése', NULL);
SELECT account_heading_save(NULL, '865', 'Értékvesztés, terven felüli értékcsökkenés', NULL);
SELECT account_heading_save(NULL, '866', 'Önkormányzatokkal elszámolt adók, illetékek', NULL);
SELECT account_heading_save(NULL, '868', 'Állami költségvetéssel elszámolt adók', NULL);
SELECT account_heading_save(NULL, '869', 'Különféle egyéb ráforditások', NULL);
SELECT account_heading_save(NULL, '87', 'Pénzügyi műveletek ráforditásai', NULL);
SELECT account_heading_save(NULL, '874', 'Fizetendő kamatok és kamatjellegű ráforditások', NULL);
SELECT account_heading_save(NULL, '876', 'Átváltáskori és értékesitéskori árfolyamveszteségek', NULL);
SELECT account_heading_save(NULL, '879', 'Egyéb pénzügyi ráforditások', NULL);
SELECT account_heading_save(NULL, '88', 'Rendkivüli ráforditások', NULL);
SELECT account_heading_save(NULL, '881', 'Térités nélkül átadott eszközök nyilvántartási értéke', NULL);
SELECT account_heading_save(NULL, '89', 'Nyereséget terhelő adók', NULL);
SELECT account_heading_save(NULL, '91', 'Értékesités árbevétele', NULL);
SELECT account_heading_save(NULL, '911', 'Belföldi értékesités árbevétele', NULL);
SELECT account_heading_save(NULL, '93', 'Export értékesités árbevétele', NULL);
SELECT account_heading_save(NULL, '96', 'Egyéb bevételek', NULL);
SELECT account_heading_save(NULL, '961', 'Értékesitett eszközök bevétele', NULL);
SELECT account_heading_save(NULL, '963', 'Egyéb eredményt növelő tételek', NULL);
SELECT account_heading_save(NULL, '964', 'Céltartalék képzése', NULL);
SELECT account_heading_save(NULL, '965', 'Értékvesztés, terven felüli érétkcsökkenés visszairása', NULL);
SELECT account_heading_save(NULL, '969', 'Különféle egyéb bevételek', NULL);
SELECT account_heading_save(NULL, '97', 'Pénzügyi bevételek', NULL);
SELECT account_heading_save(NULL, '974', 'Kapott kamatok és kamatjellegű ráforditások', NULL);
SELECT account_heading_save(NULL, '976', 'Átváltáskori és értékesitéskori árfolyamnyereség', NULL);
SELECT account_heading_save(NULL, '979', 'Egyéb pénzügyi bevételek', NULL);
SELECT account_heading_save(NULL, '98', 'Rendkivüli bevételek', NULL);
SELECT account_heading_save(NULL, '454', 'Kötelezettségek áruszállításból és szolgáltatás nyújtásából', NULL);
SELECT account_heading_save(NULL, '522', 'Bérleti díjak', NULL);
SELECT account_heading_save(NULL, '931', 'Export értékesités árbevétele', NULL);
SELECT account__save(NULL,'1111','Alapítás, átszervezés aktivált értéke','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1131','Vagyoni értékű jogok','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1141','Szellemi termékek','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1171','Immateriális javak értékhelyesbítése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1181','Immateriális javak terven felüli értékcsökkenése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1191','Alapitás, átszervezés elszámolt értékcsökkenése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1193','Vagyoni értékű jogok elszámolt értékcsökkenése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1194','Szellemi termékek elszámolt értékcsökkenése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1311','Termelő gépek, berendezések','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1321','Járművek','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1371','Műszaki gépek, berendezések, járművek értékhelyesbítése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1381','Műszaki gépek, berendezések, járművek tereven felüli értékcsökkenése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1391','Termelő gépek, berendezések elszámolt értékcsökkenése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1392','Járművek értékcsökkenése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1411','Egyéb gép, berendezése, szerszám','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1421','Egyéb járművek','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1431','Irodai, igazgatási berendezés, felszerelés','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1451','Kisértékű gép, berendezés, felszerelés','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1452','Kisértékű irodai, igazgatási berendezés, felszerelés','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1471','Egyéb gép, berendezés, szerszám értékhelyesbítése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1472','Egyéb járművek értékhelyesbítése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1473','Irodai, igazgatási berendezés, felszerelés értékhelyesbítése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1481','Egyéb gép, berendezés, felszerelés terven felüli értékcsökkenése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1482','Egyéb járművek terven felüli értékcsökkenése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1483','Irodai, igazgatási berendezések terven felüli értékcsökkenése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1491','Egyéb gép, berendezés, szerszám elszámolt értékcsökkenése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1492','Egyéb járművek elszámolt értékcsökkenése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1493','Irodai, igazgatási berendezés, felszerelés elszámolt értékcsökkenése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1495','Kisértékű tárgyi eszközök értékcsökkenése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3920','Költségek ráforditások aktiv időbeli elhatárolása','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3910','Bevételek aktiv időbeli elhatárolása','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '2', 'KÉSZLETEK', NULL);
SELECT account__save(NULL,'3930','Halasztott ráforditások','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3211','Követelések anyavállalattal szemben','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3251','Jegyzett, de még be nem fizetett tőke','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3291','Követelések értékvesztése ','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3311','Követelések egyéb részesedési viszonyban lévő vállalattal szemben','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3321','Jegyzett, de még be nem fizetett tőke','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3391','Egyéb részesedési viszonyban lévő vállakozással szembeni követelés értékvesztése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3410','Belföldi váltókövetelések','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3460','Külföldi váltókövetelések','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3510','Immateriális javakra adott előleg','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3520','Beruházásokra adott előleg','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3530','Készletekre adott előleg','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3540','Osztalék előleg','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3550','VPOP ÁFA elszámolási számla','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3560','Egyéb előlegek','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3610','Munkavállalókkal szembeni követelés','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3620','Költségvetési kiutálási igények','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3630','Költségvetési kiutalási igények teljesitése','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3640','Vevőtől kapott előleg ÁFÁ-ja','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3661','Rövid lejáratra adott pénzkölcsön','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3662','Rövid lejáratú betétek','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3710','Részesedés kapcsolt vállakozásban','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3720','Egyéb részesedés','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3680','Egyéb követelések','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3790','Értékpapirok értékvesztése és visszairása','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3690','Egyéb követelések értékvesztése és visszairása','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3811','Főpénztár','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'3822','USD valutapénztár','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'3821','EURO valutapénztár','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'3841','Bankszámla (Ft)','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'3861','Bankszámla (EUR)','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'3893','Átvezetés Bank (HUF) - Bank (EUR)','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'3891','Átvezetés Bank (HUF) - Pénztár (HUF)','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'3892','Átvezetés Bank (EUR) - Pénztár (EUR)','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'3894','Átvezetés Pénztár (HUF) - Pénztár (EUR)','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'3111','Belföldi vevők','A','', NULL, false, false, string_to_array('AR', ':'), false, false);
SELECT account__save(NULL,'3150','Belföldi követelések értékvesztése és visszairása','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3161','Külföldi vevők','A','', NULL, false, false, string_to_array('AR', ':'), false, false);
SELECT account__save(NULL,'3190','Külföldi követelések értékvesztése és visszairása','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4110','Jegyzett tőke','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4120','Tőketartalék','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4130','Eredménytartalék','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4140','Lekötött tartalék','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4170','Értékelési tartalék','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4190','Mérleg szerinti eredmény','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4210','Céltartalékok várható kötelezettségekre','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4220','Céltartalékok a jövőbeni költségekre','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4230','Egyéb céltartalékok','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4421','Hosszú lejáratra kapott kölcsönök','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4431','Beruházási és fejlesztési hitelek','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4441','Egyéb hosszú lejáratú hitel','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4461','Tartós kötelezettség','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4471','Tartós kötelezettség egyéb vállakozással szemben','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4491','Egyéb hosszú lejáratú kötelezettség','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4511','Vevőktől kapott előleg','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4541','Belföldi szállítók','L','', NULL, false, false, string_to_array('AP', ':'), false, false);
SELECT account__save(NULL,'4542','Külföldi szállítók','L','', NULL, false, false, string_to_array('AP', ':'), false, false);
SELECT account__save(NULL,'4551','Pénzügyi lízing (éven belüli)','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4561','Rövid lejáratú kötelezettség','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4571','Rövid lejáratú kötelezettség egyéb','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4591','Egyéb rövid lejáratú kötelezettség','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4611','Társasági adó','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4619','Társasági adó megfizetése','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4621','Munkaviszonyból származó SZJA','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4629','SZJA befizetés','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4631','Nyugdíjbiztosítás','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4632','Egészségbiztosítás','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4633','Munkaadói járulék','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4634','Munkavállalói járulék','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4635','Szakképzési hozzájárulás','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4636','Rehabilitációs hozzájárulás','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4637','EHO','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4638','Önellenörzési, késedelmi pótlék','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4641','Nyugdíjbiztosítás teljesitése','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4642','EEgészségbiztosítás teljesitése','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4643','Munkaadói járulék teljesitése','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4644','Munkavállalói járulék teljesitése','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4645','Szakképzési hozzájárulás teljesitése','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4646','Rehabilitációs hozzájárulás teljesitése','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4647','EHO teljesitése','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4648','Önellenörzési, késedelmi pótlék teljesitése','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4651','VPOP elszámolási számla','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4680','ÁFA elszámolási számla','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4691','Iparűzési adó','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4692','Gépjárműadó','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4693','Kommunális adó','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'47101','Jövedelem elszámolás január','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'47102','Jövedelem elszámolás február','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'47103','Jövedelem elszámolás március','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'47104','Jövedelem elszámolás április','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'47105','Jövedelem elszámolás május','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'47106','Jövedelem elszámolás június','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'47107','Jövedelem elszámolás július','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'47108','Jövedelem elszámolás augusztus','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'47109','Jövedelem elszámolás szeptember','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'47110','Jövedelem elszámolás október','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'47111','Jövedelem elszámolás november','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'47112','Jövedelem elszámolás december','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4721','Fel nem vett járandóság','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'47311','Nyugdíjbiztosítási Alap kötelezettség','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'47319','Nyugdíjbiztosítási Alap kötelezettség teljesitése','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'47321','Egészségbiztosítási Alap kötelezettség','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'47329','Egészségbiztosítási Alap kötelezettség teljesitése','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'47331','Magánnyugdíjpénztár','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4781','Osztalék','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4799','Technikai számla','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4810','Költségek, ráforditások passzív időbeli elhatárolása','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4820','Árbevételek passzív időbeli elhatárolása','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4830','Halasztott bevételek','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4910','Nyitómérleg számla','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4920','Záró mérleg számla','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4930','Adózott eredmény elszámolási számla','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5110','Anyagköltség','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5120','Energia, szemét, közüzemi díj','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5130','Üzemanyag','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5140','Nyomtatványok, irodaszerek','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5150','Tisztítószer','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5160','Szakkönyv, folyóirat','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5190','Egyéb anyagköltség','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5211','Belföldi szállítási költség','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5212','Külföldi szállítási költség','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5221','Irodabérleti díj','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5241','Belföldi utazási költség','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5242','Külföldi utazási költség','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5251','Reklám költség','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5252','Hirdetés költsége','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5261','Oktatás költsége','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5271','Posta költség','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5281','Telefonköltség','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5282','Internet költség','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'52901','Könyvvezetés költsége','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'52902','Ügyvédi költség','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5311','Illetékek, tagdíjak','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5321','Bankköltség','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5331','Vagyonbiztosítás','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5391','Faktordíj','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5410','Bérköltség (munkavállaló, tag)','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5420','Megbizási jogviszony költsége','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5450','Prémium','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5510','Étkezési jegy','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5520','Reprezentáció','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'5590','Egyéb személyi jellegű kifizetés','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5611','Nyugdíjbiztosítási járulék','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5612','Egészségbiztosítási járulék','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5621','Tételes EHO','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5622','Százalékos EHO','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5630','Munkaadói járulék','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5640','Szakképzési hozzájárulás','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5650','Rehabilitációs hozzájárulás','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5690','Egyéb bérjárulékok','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5710','Terv szerinti értékcsökkenési leirás','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5720','Kisértékű eszközök értékcsökkenése','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8110','Anyagköltség','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8120','Igénybevett szolgáltatás','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8130','Eladott szolgáltatások értéke','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8150','Eladott (közvetitett) szolgáltatás értéke','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8611','Értékesitett immateriális javak nyilvántartási értéke','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8612','Értékesitett tárgyi eszközök nyilvántartási értéke','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8631','késedelmi kamatok','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8641','Céltartalék képzése','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8651','Követelések értékvesztése','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8652','Immateriális javak terven felüli értékcsökkenése','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8653','Tárgyi eszközök terven felüli értékcsökkenése','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8661','Iparűzési adó','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8662','Gépjárműadó','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8663','Kommunális adó','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8681','Le nem vonható ÁFA','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8682','Önellenörzési pótlék','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8691','Káresemények','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8694','Előző évet terhelő ráforditások','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8699','Egyéb ráforditások','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8698','Kerekitési különbözet','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8710','Fizetett osztalék, részesedés','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8720','Részesedések, értékpapirok, bankbetétek értékvesztése','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8730','Befektett pénzügyi eszközök árfolyam vesztesége','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8741','Fizetett kamatok kapcsolt vállakozásnak','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8742','Fizetett kamatok egyéb vállakozásoknak','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8743','Pénzintézetnek fizetett kamatok','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8744','Magénszemélyeknek fizetett kamatok','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8761','Deviza és valutakészletek átváltási árfolyamvesztesége','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8762','Követelések és kötelezettségek árfolyamvesztesége','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8791','Faktordíj','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8820','Társaságba bevitt vagyontárgyak nyilvántartás szerinti értéke','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8830','Véglegesen átadott pénzeszköz','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8840','Elengedett követelés','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8890','Egyéb rendkívüli ráforditások','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8910','Társasági adó','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'8140','ELÁBÉ','E','', NULL, false, false, string_to_array('IC_cogs', ':'), false, false);
SELECT account__save(NULL,'9611','Értékesitett immateriális javak bevétele','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9612','Értékesitett tárgyi eszközök bevétele','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9631','Kapott késedelmi kamatok','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9641','Céltartalék képzése','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9651','Követelések értékvesztésének visszairása','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9652','Immateriális javak terven felüli értékcsökkenésének visszairása','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9653','Tárgyi eszközök terven felüli érétkcsökkenésének visszairása','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9691','Káresemények bevételei','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9698','Kerekítési különbözet','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9699','Egyéb bevételek','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9710','Kapott osztalék, részesedés','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9720','Részesedések, értékpapirok, bankbetétek értékvesztésének visszairása','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9730','Befektetett pénzügyi eszközök árfolyam nyeresége','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9741','Kapott kamatok kapcsolt vállalkozástól','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9742','Kapott kamatok egyéb vállakozástól','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9743','Kapott kamatok pénzintézettől','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9744','Magánszemélytől kapott kamatok','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9761','Deviza és valutakészlet átváltási árfolyamnyeresége','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9762','Követelések és kötelezettségek árfolyamnyeresége','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9791','Egyéb pénzügyi bevételek','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9810','Ellenérték nélkül kapott eszközök értéke','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9820','Társaságba bevitt vagyontárgyak szerződés szerinti értéke','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9830','Véglegesen kapott pénzeszköz','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9840','Elengedett kötelezettség','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'9890','Egyéb rendkívüli bevételek','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'52903','Tanácsadás','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'1611','Befejezetlen beruházás','A','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'3862','Deviza betétszámla USD','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'3895','Átvezetés Bank (HUF) - Bank (USD)','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'9112','Belföldi szolgáltatás árbevétele','I','', NULL, false, false, string_to_array('AR_amount:IC_income', ':'), false, false);
SELECT account__save(NULL,'9111','Belföldi termékértékesítés árbevétele','I','', NULL, false, false, string_to_array('AR_amount', ':'), false, false);
SELECT account__save(NULL,'9312','Export szolgáltatás árbevétele','I','', NULL, false, false, string_to_array('AR_amount:IC_income', ':'), false, false);
SELECT account__save(NULL,'5299','Egyéb igénybevett szolgáltatás','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'2690','Uton levo keszlet','A','', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'2610','Áruk beszerzési áron','A','', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'52904','Vámügyintézés','E','', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'3896','Bankkártya átvezetés','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'9311','Export termekértékesítés árbevétele','I','', NULL, false, false, string_to_array('AR_amount:IC_income', ':'), false, false);
SELECT account__save(NULL,'4661','Előzetesen felszámítottt ÁFA 20%','L','', NULL, false, false, string_to_array('AP_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'4662','Előzetesen felszámítottt ÁFA 5%','L','', NULL, false, false, string_to_array('AP_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'4663','Előzetesen felszámítottt ÁFA 0%','L','', NULL, false, false, string_to_array('AP_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'4664','Előzetesen felszámítottt ÁFA adómentes','L','', NULL, false, false, string_to_array('AP_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'4671','Fizetendő ÁFA 20%','L','', NULL, false, false, string_to_array('AR_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'4672','Fizetendő ÁFA 5%','L','', NULL, false, false, string_to_array('AR_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'4673','Fizetendő ÁFA 0%','L','', NULL, false, false, string_to_array('AR_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'4674','Fizetendő ÁFA adómentes','L','', NULL, false, false, string_to_array('AR_tax:IC_taxpart:IC_taxservice', ':'), false, false);

SELECT cr_coa_to_account_save(accno, accno || '--' || description)
FROM account WHERE id IN (select account_id FROM account_link
                           WHERE description = 'AP_paid');

INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM account WHERE accno='4661'),'0.20','VIS');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM account WHERE accno='4662'),'0.05','VIS');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM account WHERE accno='4663'),'0','VIS');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM account WHERE accno='4664'),'0','VIS');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM account WHERE accno='4671'),'0.20','FIZ');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM account WHERE accno='4672'),'0.05','FIZ');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM account WHERE accno='4673'),'0','FIZ');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM account WHERE accno='4674'),'0','FIZ');
--
INSERT INTO defaults (setting_key, value) VALUES ('inventory_accno_id',
(SELECT id FROM account WHERE accno = '2110'));

INSERT INTO defaults (setting_key, value) VALUES ('income_accno_id', (SELECT id FROM account WHERE accno = '9111'));
INSERT INTO defaults (setting_key, value) VALUES ('expense_accno_id', (SELECT id FROM account WHERE accno = '8140'));
INSERT INTO defaults (setting_key, value) VALUES ('fxgain_accno_id', (SELECT id FROM account WHERE accno = '9761'));
INSERT INTO defaults (setting_key, value) VALUES ('fxloss_accno_id', (SELECT id FROM account WHERE accno = '8761'));
INSERT INTO defaults (setting_key, value) VALUES ('curr', 'HUF:EUR:USD');
INSERT INTO defaults (setting_key, value) VALUES ('weightunit', 'kg');
UPDATE defaults SET value = 'VK00000' WHERE setting_key = 'glnumber';
UPDATE defaults SET value = 'VSZ10000' WHERE setting_key = 'sinumber';
UPDATE defaults SET value = 'SZSZ10000' WHERE setting_key = 'vinumber';
UPDATE defaults SET value = 'BR10000' WHERE setting_key = 'ponumber';
UPDATE defaults SET value = 'VR10000' WHERE setting_key = 'sonumber';
UPDATE defaults SET value = 'AA10000' WHERE setting_key = 'sqnumber';
UPDATE defaults SET value = 'AK10000' WHERE setting_key = 'rfqnumber';
UPDATE defaults SET value = 'ALK0000' WHERE setting_key = 'employeenumber';
UPDATE defaults SET value = 'VEVO10000' WHERE setting_key = 'customernumber';
UPDATE defaults SET value = 'SZALL10000' WHERE setting_key = 'vendornumber';
UPDATE defaults SET value = 'PROJ10000' WHERE setting_key = 'projectnumber';

commit;
UPDATE account
   SET tax = true
WHERE id
   IN (SELECT account_id
       FROM account_link
       WHERE description LIKE '%_tax');

