begin;
--Hungarian chart of accounts Complete
-- Magyar fõkönyvi számlák, amely majdnem teljes
--
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1111','Alapítás, átszervezés aktivált értéke','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1131','Vagyoni értékű jogok','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1141','Szellemi termékek','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1171','Immateriális javak értékhelyesbítése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1181','Immateriális javak terven felüli értékcsökkenése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1191','Alapitás, átszervezés elszámolt értékcsökkenése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1193','Vagyoni értékű jogok elszámolt értékcsökkenése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1194','Szellemi termékek elszámolt értékcsökkenése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1311','Termelő gépek, berendezések','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1321','Járművek','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1371','Műszaki gépek, berendezések, járművek értékhelyesbítése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1381','Műszaki gépek, berendezések, járművek tereven felüli értékcsökkenése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1391','Termelő gépek, berendezések elszámolt értékcsökkenése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1392','Járművek értékcsökkenése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1411','Egyéb gép, berendezése, szerszám','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1421','Egyéb járművek','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1431','Irodai, igazgatási berendezés, felszerelés','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1451','Kisértékű gép, berendezés, felszerelés','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1452','Kisértékű irodai, igazgatási berendezés, felszerelés','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1471','Egyéb gép, berendezés, szerszám értékhelyesbítése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1472','Egyéb járművek értékhelyesbítése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1473','Irodai, igazgatási berendezés, felszerelés értékhelyesbítése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1481','Egyéb gép, berendezés, felszerelés terven felüli értékcsökkenése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1482','Egyéb járművek terven felüli értékcsökkenése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1483','Irodai, igazgatási berendezések terven felüli értékcsökkenése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1491','Egyéb gép, berendezés, szerszám elszámolt értékcsökkenése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1492','Egyéb járművek elszámolt értékcsökkenése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1493','Irodai, igazgatási berendezés, felszerelés elszámolt értékcsökkenése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1495','Kisértékű tárgyi eszközök értékcsökkenése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3920','Költségek ráforditások aktiv időbeli elhatárolása','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3910','Bevételek aktiv időbeli elhatárolása','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2','KÉSZLETEK','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3930','Halasztott ráforditások','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3211','Követelések anyavállalattal szemben','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3251','Jegyzett, de még be nem fizetett tőke','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3291','Követelések értékvesztése ','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3311','Követelések egyéb részesedési viszonyban lévő vállalattal szemben','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3321','Jegyzett, de még be nem fizetett tőke','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3391','Egyéb részesedési viszonyban lévő vállakozással szembeni követelés értékvesztése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3410','Belföldi váltókövetelések','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3460','Külföldi váltókövetelések','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3510','Immateriális javakra adott előleg','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3520','Beruházásokra adott előleg','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3530','Készletekre adott előleg','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3540','Osztalék előleg','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3550','VPOP ÁFA elszámolási számla','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3560','Egyéb előlegek','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3610','Munkavállalókkal szembeni követelés','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3620','Költségvetési kiutálási igények','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3630','Költségvetési kiutalási igények teljesitése','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3640','Vevőtől kapott előleg ÁFÁ-ja','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3661','Rövid lejáratra adott pénzkölcsön','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3662','Rövid lejáratú betétek','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3710','Részesedés kapcsolt vállakozásban','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3720','Egyéb részesedés','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3680','Egyéb követelések','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3790','Értékpapirok értékvesztése és visszairása','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3690','Egyéb követelések értékvesztése és visszairása','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3811','Főpénztár','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3822','USD valutapénztár','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3821','EURO valutapénztár','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3841','Bankszámla (Ft)','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3861','Bankszámla (EUR)','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3893','Átvezetés Bank (HUF) - Bank (EUR)','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3891','Átvezetés Bank (HUF) - Pénztár (HUF)','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3892','Átvezetés Bank (EUR) - Pénztár (EUR)','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3894','Átvezetés Pénztár (HUF) - Pénztár (EUR)','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3111','Belföldi vevők','A','A','AR','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3150','Belföldi követelések értékvesztése és visszairása','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3161','Külföldi vevők','A','A','AR','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3190','Külföldi követelések értékvesztése és visszairása','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4110','Jegyzett tőke','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4120','Tőketartalék','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4130','Eredménytartalék','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4140','Lekötött tartalék','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4170','Értékelési tartalék','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4190','Mérleg szerinti eredmény','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4210','Céltartalékok várható kötelezettségekre','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4220','Céltartalékok a jövőbeni költségekre','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4230','Egyéb céltartalékok','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4421','Hosszú lejáratra kapott kölcsönök','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4431','Beruházási és fejlesztési hitelek','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4441','Egyéb hosszú lejáratú hitel','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4461','Tartós kötelezettség','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4471','Tartós kötelezettség egyéb vállakozással szemben','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4491','Egyéb hosszú lejáratú kötelezettség','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4511','Vevőktől kapott előleg','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4541','Belföldi szállítók','A','L','AP','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4542','Külföldi szállítók','A','L','AP','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4551','Pénzügyi lízing (éven belüli)','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4561','Rövid lejáratú kötelezettség','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4571','Rövid lejáratú kötelezettség egyéb','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4591','Egyéb rövid lejáratú kötelezettség','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4611','Társasági adó','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4619','Társasági adó megfizetése','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4621','Munkaviszonyból származó SZJA','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4629','SZJA befizetés','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4631','Nyugdíjbiztosítás','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4632','Egészségbiztosítás','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4633','Munkaadói járulék','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4634','Munkavállalói járulék','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4635','Szakképzési hozzájárulás','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4636','Rehabilitációs hozzájárulás','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4637','EHO','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4638','Önellenörzési, késedelmi pótlék','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4641','Nyugdíjbiztosítás teljesitése','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4642','EEgészségbiztosítás teljesitése','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4643','Munkaadói járulék teljesitése','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4644','Munkavállalói járulék teljesitése','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4645','Szakképzési hozzájárulás teljesitése','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4646','Rehabilitációs hozzájárulás teljesitése','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4647','EHO teljesitése','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4648','Önellenörzési, késedelmi pótlék teljesitése','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4651','VPOP elszámolási számla','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4680','ÁFA elszámolási számla','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4691','Iparűzési adó','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4692','Gépjárműadó','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4693','Kommunális adó','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('47101','Jövedelem elszámolás január','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('47102','Jövedelem elszámolás február','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('47103','Jövedelem elszámolás március','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('47104','Jövedelem elszámolás április','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('47105','Jövedelem elszámolás május','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('47106','Jövedelem elszámolás június','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('47107','Jövedelem elszámolás július','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('47108','Jövedelem elszámolás augusztus','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('47109','Jövedelem elszámolás szeptember','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('47110','Jövedelem elszámolás október','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('47111','Jövedelem elszámolás november','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('47112','Jövedelem elszámolás december','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4721','Fel nem vett járandóság','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('47311','Nyugdíjbiztosítási Alap kötelezettség','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('47319','Nyugdíjbiztosítási Alap kötelezettség teljesitése','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('47321','Egészségbiztosítási Alap kötelezettség','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('47329','Egészségbiztosítási Alap kötelezettség teljesitése','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('47331','Magánnyugdíjpénztár','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4781','Osztalék','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4799','Technikai számla','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4810','Költségek, ráforditások passzív időbeli elhatárolása','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4820','Árbevételek passzív időbeli elhatárolása','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4830','Halasztott bevételek','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4910','Nyitómérleg számla','A','C','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4920','Záró mérleg számla','A','C','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4930','Adózott eredmény elszámolási számla','A','C','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5110','Anyagköltség','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5120','Energia, szemét, közüzemi díj','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5130','Üzemanyag','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5140','Nyomtatványok, irodaszerek','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5150','Tisztítószer','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5160','Szakkönyv, folyóirat','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5190','Egyéb anyagköltség','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5211','Belföldi szállítási költség','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5212','Külföldi szállítási költség','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5221','Irodabérleti díj','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5241','Belföldi utazási költség','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5242','Külföldi utazási költség','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5251','Reklám költség','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5252','Hirdetés költsége','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5261','Oktatás költsége','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5271','Posta költség','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5281','Telefonköltség','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5282','Internet költség','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('52901','Könyvvezetés költsége','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('52902','Ügyvédi költség','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5311','Illetékek, tagdíjak','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5321','Bankköltség','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5331','Vagyonbiztosítás','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5391','Faktordíj','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5410','Bérköltség (munkavállaló, tag)','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5420','Megbizási jogviszony költsége','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5450','Prémium','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5510','Étkezési jegy','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5520','Reprezentáció','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5590','Egyéb személyi jellegű kifizetés','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5611','Nyugdíjbiztosítási járulék','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5612','Egészségbiztosítási járulék','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5621','Tételes EHO','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5622','Százalékos EHO','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5630','Munkaadói járulék','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5640','Szakképzési hozzájárulás','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5650','Rehabilitációs hozzájárulás','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5690','Egyéb bérjárulékok','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5710','Terv szerinti értékcsökkenési leirás','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5720','Kisértékű eszközök értékcsökkenése','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8110','Anyagköltség','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8120','Igénybevett szolgáltatás','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8130','Eladott szolgáltatások értéke','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8150','Eladott (közvetitett) szolgáltatás értéke','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8611','Értékesitett immateriális javak nyilvántartási értéke','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8612','Értékesitett tárgyi eszközök nyilvántartási értéke','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8631','késedelmi kamatok','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8641','Céltartalék képzése','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8651','Követelések értékvesztése','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8652','Immateriális javak terven felüli értékcsökkenése','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8653','Tárgyi eszközök terven felüli értékcsökkenése','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8661','Iparűzési adó','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8662','Gépjárműadó','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8663','Kommunális adó','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8681','Le nem vonható ÁFA','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8682','Önellenörzési pótlék','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8691','Káresemények','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8694','Előző évet terhelő ráforditások','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8699','Egyéb ráforditások','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8698','Kerekitési különbözet','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8710','Fizetett osztalék, részesedés','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8720','Részesedések, értékpapirok, bankbetétek értékvesztése','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8730','Befektett pénzügyi eszközök árfolyam vesztesége','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8741','Fizetett kamatok kapcsolt vállakozásnak','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8742','Fizetett kamatok egyéb vállakozásoknak','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8743','Pénzintézetnek fizetett kamatok','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8744','Magénszemélyeknek fizetett kamatok','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8761','Deviza és valutakészletek átváltási árfolyamvesztesége','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8762','Követelések és kötelezettségek árfolyamvesztesége','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8791','Faktordíj','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8820','Társaságba bevitt vagyontárgyak nyilvántartás szerinti értéke','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8830','Véglegesen átadott pénzeszköz','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8840','Elengedett követelés','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8890','Egyéb rendkívüli ráforditások','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8910','Társasági adó','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8140','ELÁBÉ','A','E','IC_cogs','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9611','Értékesitett immateriális javak bevétele','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9612','Értékesitett tárgyi eszközök bevétele','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9631','Kapott késedelmi kamatok','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9641','Céltartalék képzése','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9651','Követelések értékvesztésének visszairása','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9652','Immateriális javak terven felüli értékcsökkenésének visszairása','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9653','Tárgyi eszközök terven felüli érétkcsökkenésének visszairása','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9691','Káresemények bevételei','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9698','Kerekítési különbözet','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9699','Egyéb bevételek','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9710','Kapott osztalék, részesedés','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9720','Részesedések, értékpapirok, bankbetétek értékvesztésének visszairása','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9730','Befektetett pénzügyi eszközök árfolyam nyeresége','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9741','Kapott kamatok kapcsolt vállalkozástól','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9742','Kapott kamatok egyéb vállakozástól','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9743','Kapott kamatok pénzintézettől','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9744','Magánszemélytől kapott kamatok','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9761','Deviza és valutakészlet átváltási árfolyamnyeresége','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9762','Követelések és kötelezettségek árfolyamnyeresége','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9791','Egyéb pénzügyi bevételek','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9810','Ellenérték nélkül kapott eszközök értéke','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9820','Társaságba bevitt vagyontárgyak szerződés szerinti értéke','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9830','Véglegesen kapott pénzeszköz','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9840','Elengedett kötelezettség','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9890','Egyéb rendkívüli bevételek','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('52903','Tanácsadás','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1611','Befejezetlen beruházás','A','A','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3862','Deviza betétszámla USD','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3895','Átvezetés Bank (HUF) - Bank (USD)','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9112','Belföldi szolgáltatás árbevétele','A','I','AR_amount:IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9111','Belföldi termékértékesítés árbevétele','A','I','AR_amount:IC_sale','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9312','Export szolgáltatás árbevétele','A','I','AR_amount:IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5299','Egyéb igénybevett szolgáltatás','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2690','Uton levo keszlet','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2610','Áruk beszerzési áron','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('52904','Vámügyintézés','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3896','Bankkártya átvezetés','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9311','Export termekértékesítés árbevétele','A','I','AR_amount:IC_sale:IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1','BEFEKTETETT ESZKÖZÖK','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3','KÖVETELÉSEK','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8','RÁFORDÍTÁSOK','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9','BEVÉTELEK','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4','FORRÁSOK','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5','KÖLTSÉGNEMEK','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('11','Immateriális javak','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('12','Ingatlanok','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('13','Műszaki gépek, berendezések, járművek','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('14','Egyéb gépek, berendezések, járművek','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('15','Beruházások','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('114','Szellemi termékek','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('117','Immateriális javak értékhelyesbítése','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('118','Immateriális javak terven felüli értékcsökkenése','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('119','Immateriális javak értékcsökkenése','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('131','Termelő gépek, berendezések','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('132','Járművek','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('139','Mászeki gépek, berendezések, járművek értékcsökkenése','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('137','Műszaki gépek, berendezések járművek értékhelyesbítése','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('138','Műszaki gépek, berendezések, járművek terven felüli értékcsökkenése','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('141','Egyéb gép, berendezés, szerszám','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('142','Egyéb járművek','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('143','Irodai, igazgatási berendezés, felszerelés','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('145','Kisértékű tárgyi eszköz','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('147','Egyéb gépek, berendezések, járművek értékhelyesbítése','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('149','Egyéb gépek, berendezések, járművek elszámolt értékcsökkenése','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('148','Egyéb gépek, berendezések, járművek terven felüli értékcsökkenése','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('161','Befejezetlen beruházások','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('21','Anyagok','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('26','Kereskedelmi áruk','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('31','Követelések áruszállításból, szolgáltatásból','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('32','Követelések kapcsolt vállakozással szemben','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('33','Követelések egyéb részesedési viszonyban lévő vállalkozással szemben','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('34','Váltókövetelések','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('35','Adott előlegek','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('36','Egyéb követelések','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('37','Értékpapirok','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('38','Pénzeszközök','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('39','Aktiv időbeli elhatárolások','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('321','Követelések','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('325','Jegyzett de be nem fizetett tőke','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('329','Követelések értékvesztése','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('331','Követelések egyéb részesedési viszonyban lévő vállalattal szemben','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('332','Jegyzett, de még be nem fizetett tőke egyéb részesedési viszonyban lévő vállalkozástól','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('339','Egyéb részesedési viszonyban lévő vállakozással szembeni követelés értékvesztése','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('366','Rövid lejáratra adott pénzkölcsönök','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('381','Pénztárak','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('382','Valutapénztárak','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('384','Elszámolási betétszámlák (Ft)','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('386','Deviza betétszámlák','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('389','Átvezetési számlák','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('311','Belföldi vevők','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('316','Külföldi vevők','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('41','Saját tőke','H','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('42','Céltartalékok','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('43','Hátrasorolt kötelezettségek','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('44','Hosszú lejáratú kötelezettségek','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('442','Hosszú lejáratra kapott kölcsönök','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('443','Beruházási fejlesztési hitelek','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('444','Egyéb hosszú lejáratú hitelek','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('447','Tartós kötelezettség egyéb vállalkozással szemben','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('446','Tartós kötelezettség kapcsolt vállalkozással szemben','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('449','Egyéb hosszú lejáratú kötelezettség','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('45','Rövid lejáratú kötelezettségek','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('451','Vevőktől kapott előlegek','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('452','Rövid lejáratú kölcsönök','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('453','Rövid lejáratú hitelek','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('455','Pénzügyi lízing miatti kötelezettség','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('456','Rövid lejáratú kötelezettség kapcsolt vállalkozással szemben','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('457','Rövid lejáratú kötelezettség egyéb vállakozással szemben','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('459','Egyéb rövid lejáratú kötelezettség','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('46','Adóhatósággal szembeni kötelezettségek','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('461','Társasági adó elszámolása','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('462','SZJA elszámolás','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('463','Költségvetési befizetési kötelezettség','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('464','Költségvetési befizetési kötelezettség teljesitése','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('465','VPOP elszámolási számla','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('466','Előzetesen felszámítottt ÁFA','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('467','Fizetendő ÁFA','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('469','Helyi adók elszámolási számla','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('47','Egyéb kötelezettségek','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('471','Jövedelem elszámolási számla','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('472','Fel nem vett járandóság','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('473','Nyugdíj- és egészségbiztosítás','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4731','Nyugdíjbiztosítási Alap','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4732','Egészségbiztosítási Alap','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4733','Magánnyugdíjpénztár','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('478','Osztalékelszámolási számla','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('479','Egyéb rövid lejáratú kötelezettség','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('48','Passzív időbeli elhatárolások','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('49','Évi mérlegszámlák','H','C','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('51','Anyagjellegű költségek','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('52','Igénybevett szolgáltatások költségei','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('521','Szállítási, rakodási költség','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('524','Utazási és szállás költség','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('525','Hirdetés és reklám költség','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('526','Oktatás, továbbképzés költsége','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('527','Posta költség','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('528','Kommunikációs költségek','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('529','Egyéb igénybevett szolgáltatások','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('53','Egyéb szolgáltatások költségei','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('531','Hatósági, igazgatási, szolg. illeték','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('532','Bankköltség','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('533','Biztosítási díjak','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('539','Egyéb szolgáltatások ','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('54','Bérköltség','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('55','Személyi jellegű egyéb kifizetés','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('56','Bérjárulékok','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('561','Nyugdíj és egészségbiztosítás','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('562','EHO','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('57','Értékcsökkenési leirás','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('81','Anyagjellegű ráforditások','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('86','Egyéb ráforditások','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('861','Értékesitett eszközök nyilvántartási értéke','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('863','Egyéb eredményt csökkentő tételek','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('864','Céltartalék képzése','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('865','Értékvesztés, terven felüli értékcsökkenés','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('866','Önkormányzatokkal elszámolt adók, illetékek','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('868','Állami költségvetéssel elszámolt adók','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('869','Különféle egyéb ráforditások','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('87','Pénzügyi műveletek ráforditásai','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('874','Fizetendő kamatok és kamatjellegű ráforditások','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('876','Átváltáskori és értékesitéskori árfolyamveszteségek','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('879','Egyéb pénzügyi ráforditások','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('88','Rendkivüli ráforditások','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('881','Térités nélkül átadott eszközök nyilvántartási értéke','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('89','Nyereséget terhelő adók','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('91','Értékesités árbevétele','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('911','Belföldi értékesités árbevétele','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('93','Export értékesités árbevétele','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('96','Egyéb bevételek','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('961','Értékesitett eszközök bevétele','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('963','Egyéb eredményt növelő tételek','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('964','Céltartalék képzése','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('965','Értékvesztés, terven felüli érétkcsökkenés visszairása','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('969','Különféle egyéb bevételek','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('97','Pénzügyi bevételek','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('974','Kapott kamatok és kamatjellegű ráforditások','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('976','Átváltáskori és értékesitéskori árfolyamnyereség','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('979','Egyéb pénzügyi bevételek','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('98','Rendkivüli bevételek','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('454','Kötelezettségek áruszállításból és szolgáltatás nyújtásából','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('522','Bérleti díjak','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('931','Export értékesités árbevétele','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4661','Előzetesen felszámítottt ÁFA 20%','A','L','AP_tax:IC_taxpart:IC_taxservice:CT_tax','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4662','Előzetesen felszámítottt ÁFA 5%','A','L','AP_tax:IC_taxpart:IC_taxservice:CT_tax','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4663','Előzetesen felszámítottt ÁFA 0%','A','L','AP_tax:IC_taxpart:IC_taxservice:CT_tax','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4664','Előzetesen felszámítottt ÁFA adómentes','A','L','AP_tax:IC_taxpart:IC_taxservice:CT_tax','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4671','Fizetendő ÁFA 20%','A','L','AR_tax:IC_taxpart:IC_taxservice:CT_tax','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4672','Fizetendő ÁFA 5%','A','L','AR_tax:IC_taxpart:IC_taxservice:CT_tax','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4673','Fizetendő ÁFA 0%','A','L','AR_tax:IC_taxpart:IC_taxservice:CT_tax','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4674','Fizetendő ÁFA adómentes','A','L','AR_tax:IC_taxpart:IC_taxservice','');

INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM chart WHERE accno='4661'),'0.20','VIS');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM chart WHERE accno='4662'),'0.05','VIS');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM chart WHERE accno='4663'),'0','VIS');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM chart WHERE accno='4664'),'0','VIS');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM chart WHERE accno='4671'),'0.20','FIZ');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM chart WHERE accno='4672'),'0.05','FIZ');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM chart WHERE accno='4673'),'0','FIZ');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM chart WHERE accno='4674'),'0','FIZ');
--
INSERT INTO defaults (setting_key, value) VALUES ('inventory_accno_id', 
(SELECT id FROM chart WHERE accno = '2110'));

INSERT INTO defaults (setting_key, value) VALUES ('income_accno_id', (SELECT id FROM chart WHERE accno = '9111'));
INSERT INTO defaults (setting_key, value) VALUES ('expense_accno_id', (SELECT id FROM chart WHERE accno = '8140'));
INSERT INTO defaults (setting_key, value) VALUES ('fxgain_accno_id', (SELECT id FROM chart WHERE accno = '9761'));
INSERT INTO defaults (setting_key, value) VALUES ('fxloss_accno_id', (SELECT id FROM chart WHERE accno = '8761'));
INSERT INTO defaults (setting_key, value) VALUES ('curr', 'HUF:EUR:USD');
INSERT INTO defaults (setting_key, value) VALUES ('weightunit', 'kg');
UPDATE defaults SET value = 'VK00000' WHERE setting_key = 'glnumber';
UPDATE defaults SET value = 'VSZ10000' WHERE setting_key = 'sinumber';  
UPDATE defaults SET value = 'SZSZ10000' WHERE setting_key = 'vinumber';  
UPDATE defaults SET value = 'BR10000' WHERE setting_key = 'ponumber';  
UPDATE defaults SET value = 'VR10000' WHERE setting_key = 'sonumber';  
UPDATE defaults SET value = 'AA10000' WHERE setting_key = 'sqnumber';  
UPDATE defaults SET value = 'AK10000' WHERE setting_key = 'rfqnumber';  
UPDATE defaults SET value = 'ALK0000' WHERE setting_key = 'employeenumber';  
UPDATE defaults SET value = 'VEVO10000' WHERE setting_key = 'customernumber';  
UPDATE defaults SET value = 'SZALL10000' WHERE setting_key = 'vendornumber';  
UPDATE defaults SET value = 'PROJ10000' WHERE setting_key = 'projectnumber'; 

commit;
