begin;
SELECT account_heading_save(NULL, '2000', 'CURRENT LIABILITIES', NULL);
SELECT account_heading_save(NULL, '2600', 'LONG TERM LIABILITIES', NULL);
SELECT account_heading_save(NULL, '4000', 'SALES REVENUE', NULL);
SELECT account_heading_save(NULL, '5000', 'COST OF GOODS SOLD', NULL);
SELECT account_heading_save(NULL, '5400', 'PAYROLL EXPENSES', NULL);
SELECT account_heading_save(NULL, '5600', 'GENERAL & ADMINISTRATIVE EXPENSES', NULL);
SELECT account_heading_save(NULL, '6000', 'CAR EXPENSES', NULL);
SELECT account_heading_save(NULL, '4300', 'OTHER REVENUE', NULL);
SELECT account_save(NULL,'5470','Staff Amenities','','E', NULL, false,string_to_array('', ':'));
SELECT account_heading_save(NULL, '1500', 'STOCK ON HAND', NULL);
SELECT account_heading_save(NULL, '3300', 'EQUITY', NULL);
SELECT account_save(NULL,'1520','SOH / Leather','1500','A', NULL, false,string_to_array('IC', ':'));
SELECT account_heading_save(NULL, '1000', 'CURRENT ASSETS', NULL);
SELECT account_save(NULL,'1820','Plant & Equipment - at Cost','1800','A', NULL, false,string_to_array('AP_amount', ':'));
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('1825', 'Less: Accumulated Depreciation', 'A', 'A', '', '1800', '1');
SELECT account_save(NULL,'1840','Motor Vehicles - at Cost','1800','A', NULL, false,string_to_array('AP_amount', ':'));
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('1845', 'Less: Accumulated Depreciation', 'A', 'A', '', '1800', '1');
SELECT account_heading_save(NULL, '1800', 'CAPITAL ASSETS', NULL);
SELECT account_save(NULL,'1060','Cheque Account','1000','A', NULL, false,string_to_array('AR_paid:AP_paid', ':'));
SELECT account_save(NULL,'1205','Less: Provision Doubtful Debts','1000','A', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'1210','Trade Debtors / Australia - with GST','1000','A', NULL, false,string_to_array('AR', ':'));
SELECT account_save(NULL,'1220','Trade Debtors / Exports - GST free','1000','A', NULL, false,string_to_array('AR', ':'));
SELECT account_save(NULL,'1230','GST / Refund','1000','A', NULL, false,string_to_array('AR_tax:AP_tax:IC_taxpart:IC_taxservice', ':'));
SELECT account_save(NULL,'1530','SOH / PVC','1500','A', NULL, false,string_to_array('IC', ':'));
SELECT account_save(NULL,'1540','SOH / Fabrics','1500','A', NULL, false,string_to_array('IC', ':'));
SELECT account_save(NULL,'1550','SOH / Metal Hardware / Fasteners / Accessories','1500','A', NULL, false,string_to_array('IC', ':'));
SELECT account_save(NULL,'1560','SOH / Paint / Glue / Dye','1500','A', NULL, false,string_to_array('IC', ':'));
SELECT account_save(NULL,'1570','SOH / Threads / Tapes / Cords / Laces','1500','A', NULL, false,string_to_array('IC', ':'));
SELECT account_save(NULL,'1580','SOH / Other Goods','1500','A', NULL, false,string_to_array('IC', ':'));
SELECT account_save(NULL,'2100','Trade Creditors','2000','L', NULL, false,string_to_array('AP', ':'));
SELECT account_save(NULL,'2160','Taxation - Payable','2000','L', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'2210','Workers Compensation - Payable','2000','L', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'2250','Superannuation - Payable','2000','L', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'2260','Insurance - Payable','2000','L', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'2290','GST / Payable','2000','L', NULL, false,string_to_array('AR_tax:AP_tax:IC_taxpart:IC_taxservice', ':'));
SELECT account_save(NULL,'2300','GST Payments / Refunds','2000','L', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'2310','GST Adjustments','2000','L', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'3350','Issued & Paid up Capital','3300','Q', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'3370','Opening Account Balance','3300','Q', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'3380','Credit Payments / Holding Account','','Q', NULL, false,string_to_array('AR_paid', ':'));
SELECT account_save(NULL,'4020','Sales / Manufactured Products','4000','I', NULL, false,string_to_array('AR_amount:IC_sale', ':'));
SELECT account_save(NULL,'4030','Sales / General','4000','I', NULL, false,string_to_array('AR_amount:IC_sale:IC_income', ':'));
SELECT account_save(NULL,'4410','Shop Labour','4000','I', NULL, false,string_to_array('IC_income', ':'));
SELECT account_save(NULL,'4420','Design / Patternmaking','4000','I', NULL, false,string_to_array('IC_income', ':'));
SELECT account_save(NULL,'4430','Shipping & Handling','4000','I', NULL, false,string_to_array('IC_income', ':'));
SELECT account_save(NULL,'4440','Interest Received','4000','I', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'4450','Foreign Exchange Profit','4000','I', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'4460','Mark-Up / Price Adjustment','4000','I', NULL, false,string_to_array('IC_income', ':'));
SELECT account_save(NULL,'4470','Computer Consultancy / Training','4000','I', NULL, false,string_to_array('IC_income', ':'));
SELECT account_save(NULL,'2620','Bank Loans','2000','L', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'2640','Hire Purchase','2000','L', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'2650','Other Loans','2000','L', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'5020','COGS / Leather','5000','E', NULL, false,string_to_array('IC_cogs', ':'));
SELECT account_save(NULL,'5030','COGS / PVC','5000','E', NULL, false,string_to_array('IC_cogs', ':'));
SELECT account_save(NULL,'5040','COGS / Fabrics','5000','E', NULL, false,string_to_array('IC_cogs', ':'));
SELECT account_save(NULL,'5050','COGS / Metal Hardware / Fasteners / Accessories','5000','E', NULL, false,string_to_array('IC_cogs', ':'));
SELECT account_save(NULL,'5060','COGS / Paint / Glue / Dye','5000','E', NULL, false,string_to_array('IC_cogs', ':'));
SELECT account_save(NULL,'5070','COGS / Threads / Tapes / Cords / Laces','5000','E', NULL, false,string_to_array('IC_cogs', ':'));
SELECT account_save(NULL,'5080','COGS / Other Goods','5000','E', NULL, false,string_to_array('IC_cogs', ':'));
SELECT account_save(NULL,'5410','Wages','5000','E', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'5430','Superannuation','5000','E', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'5440','Workers Compensation','5000','E', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'5605','External labour costs','5000','E', NULL, false,string_to_array('AP_amount:IC_expense', ':'));
SELECT account_save(NULL,'5610','Accountancy','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5611','Legal Fees','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5613','Postage / Printing / Stationery','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5614','Freight and Cartage','5000','E', NULL, false,string_to_array('AP_amount:IC_expense', ':'));
SELECT account_save(NULL,'5615','Advertising & Promotions','5000','E', NULL, false,string_to_array('AP_amount:IC_expense', ':'));
SELECT account_save(NULL,'5620','Bad Debts','5000','E', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'5650','Capital Cost Allowance Expense','5000','E', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'5660','Interest Expenses','5000','E', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'5670','Depreciation Expenses','5000','E', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'5680','Taxation','5000','E', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'5685','Insurance','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5686','Security','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5690','Bank Fees And Charges','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5695','Other Fees And Charges','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5700','Office Supplies','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5760','Rent on Land & Buildings','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5765','Repairs & Maintenance','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5766','Fixtures & Fittings','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5770','Replacements (tools, etc)','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5780','Telephone','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5782','Computer Expenses','5000','E', NULL, false,string_to_array('AP_amount:IC_expense', ':'));
SELECT account_save(NULL,'5783','Research & Development','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5785','Travel, Accommodation & Conference','5000','E', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'5790','Hire / Rent of Plant & Equipment ','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5795','Registration & Insurance','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5800','Licenses','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5810','Foreign Exchange Loss','5000','E', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'5811','Electricity','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5812','Gas','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'5813','Sundry Expenses','5000','E', NULL, false,string_to_array('AP_amount:IC_expense', ':'));
SELECT account_save(NULL,'5820','Goods & Services for own Use','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'6010','M/V Commercial - Fuels / Oils / Parts','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'6020','M/V Commercial - Repairs','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'6040','M/V Commercial - Reg / Insurance','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'6080','M/V Private Use - Interest Expenses','5000','E', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'6090','M/V Private Use - Other Expenses','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'6070','M/V Private Use - Depreciation Expenses','5000','E', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'6050','M/V Commercial - Depreciation Expenses','5000','E', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'6060','M/V Commercial - Interest Expenses','5000','E', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'1065','Cash / Paid From Private Accounts','1000','Q', NULL, false,string_to_array('AR_paid:AP_paid', ':'));
SELECT account_save(NULL,'3360','Payments for G & S for own Use','3300','Q', NULL, false,string_to_array('AP_paid', ':'));
SELECT account_save(NULL,'5830','Discounts / Refunds / Rounding','5000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'3390','Retained Profits','3300','Q', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'5840','Fines - NON DEDUCTIBLE EXPENSES','','E', NULL, false,string_to_array('', ':'));
--
INSERT INTO tax (chart_id, rate, taxnumber) VALUES ((SELECT id FROM chart WHERE accno = '1230'), 0.1, '');
INSERT INTO tax (chart_id, rate, taxnumber) VALUES ((SELECT id FROM chart WHERE accno = '2290'), 0.1, '');
--
INSERT INTO defaults (setting_key, value) VALUES ('inventory_accno_id', (SELECT id FROM chart WHERE accno = '1520'));

 INSERT INTO defaults (setting_key, value) VALUES ('income_accno_id', (SELECT id FROM chart WHERE accno = '4020'));

 INSERT INTO defaults (setting_key, value) VALUES ('expense_accno_id', (SELECT id FROM chart WHERE accno = '5020'));

 INSERT INTO defaults (setting_key, value) VALUES ('fxgain_accno_id', (SELECT id FROM chart WHERE accno = '4450'));

 INSERT INTO defaults (setting_key, value) VALUES ('fxloss_accno_id', (SELECT id FROM chart WHERE accno = '5810'));

 INSERT INTO defaults (setting_key, value) VALUES ('curr', 'AUD');

 INSERT INTO defaults (setting_key, value) VALUES ('weightunit', 'kg');
--
commit;
