FROM        blueimp/chromedriver
MAINTAINER  LedgerSMB  devel@lists.ledgersmb.org

ENV LANG en_US.UTF-8

EXPOSE 4422
CMD ["--port=4422", "--whitelisted-ips=", "--log-level=WARNING", "--url-base=wd/hub"]
