
-- since we have so many tables now which refer transactions - none of
-- which is *originating* transactions anymore, drop the trigger.
-- Note: this trigger calls the (dropped) 'track_global_sequence()' trigger
drop trigger if exists gl_track_deleted_transaction on gl;

-- based on 'gl', 'ar' and 'ap', but those lose their roles here
drop view if exists file_tx_links cascade;

alter table trans_type
  add column details_table text;

update trans_type set details_table = 'gl' where code in ('gl', 'up');
update trans_type set details_table = 'mfg_lot' where code in ('as');
update trans_type set details_table = 'yearend' where code in ('ye');
update trans_type set details_table = 'inventory_report' where code in ('ia');
update trans_type set details_table = 'asset_report' where code in ('fa', 'fd');

comment on column trans_type.details_table is
  $$Contains the name of the table which contains (subledger) details of the transaction.$$;

insert into trans_type (code, details_table, description)
values ('ap', 'ap', 'The transaction is a regular Accounts Payable item'),
       ('ar', 'ar', 'The transaction is a regular Accounts Receivable item');

alter table transactions
  drop column table_name cascade,
  add column description text,
  add column trans_type_code char(2) references trans_type(code),
  add column entered_by int references entity(id),
  add column notes text;


update transactions txn
   set trans_type_code = 'ar'
 where txn.id in (select id from ar);

update transactions txn
   set trans_type_code = 'ap'
 where txn.id in (select id from ap);

update transactions txn
   set trans_type_code = gl.trans_type_code,
       entered_by = gl.person_id
  from gl
 where txn.id = gl.id;

alter table transactions
  alter column trans_type_code set not null;

update transactions txn
   set description = old.description,
       approved = old.approved,
       notes = old.intnotes
  from (
     select id, description, approved, intnotes from ar
      union all
     select id, description, approved, intnotes from ap
   ) old
 where txn.id = old.id;

update transactions txn
   set description = old.description,
       approved = old.approved,
       notes = old.notes
   from gl old
   where txn.id = old.id;

drop view if exists recon_payee cascade;

alter table ar
  alter column id drop default,
  drop column approved,
  drop column description,
  drop column intnotes,
  drop constraint ar_id_fkey,
  -- the on delete cascade prevents deletion of approved lots (= transactions)
  add constraint ar_id_fkey foreign key (id) references transactions (id) on delete cascade;

alter table ap
  alter column id drop default,
  drop column approved,
  drop column description,
  drop column intnotes,
  drop constraint ap_id_fkey,
  -- the on delete cascade prevents deletion of approved lots (= transactions)
  add constraint ap_id_fkey foreign key (id) references transactions (id) on delete cascade;

alter table gl
  alter column id drop default,
  drop column approved,
  drop column description,
  drop column notes,
  drop column trans_type_code,
  drop column reference,
  drop constraint gl_id_fkey,
  -- the on delete cascade prevents deletion of approved lots (= transactions)
  add constraint gl_id_fkey foreign key (id) references transactions (id) on delete cascade;

do $$
declare
  startval int;
begin
  select nextval('id') into startval;
  -- drop sequence so that it doesn't get recreated as _seq1
  drop sequence id;
  execute format(
    'alter table transactions
    alter column id add generated by default as identity (start with %s)',
    startval);
end;
  $$;

-- calls 'gl_audit_trail_append()'
-- which depends on gl.reference (which is no longer available)
alter table gl disable trigger gl_audit_trail;

alter table mfg_lot
  -- the on delete cascade prevents deletion of approved lots (= transactions)
  add column trans_id int references transactions(id) on delete cascade;

update mfg_lot
  set trans_id = (select id
                    from transactions
                   where reference = 'mfg-' || mfg_lot.id::text);

delete from gl
 where exists (select *
                 from mfg_lot ml where gl.id = ml.trans_id);

alter table asset_report
  -- the on delete cascade prevents deletion of approved lots (= transactions)
  add column trans_id int references transactions(id) on delete cascade;

update asset_report
   set trans_id = gl_id;

alter table asset_report
  drop column gl_id;

delete from gl
 where exists (select *
                 from asset_report ar where gl.id = ar.trans_id);

alter table inventory_report
  drop constraint inventory_report_trans_id_fkey,
  -- the on delete cascade prevents deletion of approved lots (= transactions)
  add constraint inventory_report_trans_id_fkey foreign key (trans_id) references transactions(id) on delete cascade;

delete from gl
 where exists (select *
                 from inventory_report ir where gl.id = ir.trans_id);

alter table payment
  add column trans_id int references transactions(id);

update payment
   set trans_id = gl_id;

drop view if exists overpayments cascade;

alter table payment
  drop column gl_id;

delete from gl
 where exists (select *
                 from payment p where gl.id = p.trans_id);

alter table yearend
  drop constraint yearend_trans_id_fkey,
  -- the on delete cascade prevents deletion of approved lots (= transactions)
  add constraint yearend_trans_id_fkey foreign key (trans_id) references transactions(id) on delete cascade;

delete from gl
 where exists (select *
                 from yearend ye where gl.id = ye.trans_id);

alter table gl enable trigger gl_audit_trail;

-- since we have so many tables now which refer transactions - none of
-- which is *originating* transactions anymore, drop the triggers.
drop trigger if exists gl_track_global_sequence on gl;
drop trigger if exists ap_track_global_sequence on ap;
drop trigger if exists ar_track_global_sequence on ar;

