
/*
 *
 *  THIS FILE NEEDS TO BE EXECUTED *AFTER*
 *
 *   overpayments-as-open-items.sql
 *
 *  because this file assumes overpayments do not exist,
 *  which is what that file is all about.
 *
 *  See ADR 0111 for context.
 *
 */


insert into trans_type (code, details_table, description)
values ('pa', 'payment', 'The transaction is generated by a payment/receipt');

create or replace function pg_temp.create_workflow(in_approved boolean)
returns int as
$sql$
  with new_workflow_item (workflow_id) as (
    insert into workflow (workflow_id, type, state, last_update)
    values (nextval('workflow_seq'), 'Payment', case when in_approved then 'POSTED' else 'SAVED' end, now())
    returning workflow_id
  )
  insert into workflow_history (
    workflow_hist_id,
    workflow_id,
    action, description,
    state, workflow_user,
    history_date, workflow_entity_id
  )
  values (
    nextval('workflow_history_seq'),
    (select workflow_id from new_workflow_item),
    'migrate', 'created during payments-as-first-order-transactions migration',
    case when in_approved then 'POSTED' else 'SAVED' end, SESSION_USER,
    now(), person__get_my_entity_id())
  returning workflow_id;
$sql$ language sql;

alter table payment
  drop constraint payment_trans_id_fkey,
  add constraint payment_trans_id_fkey foreign key (trans_id) references transactions (id) on delete cascade;

alter table payment
  add column account_id int references account(id);

comment on column payment.account_id is
  $$The account on which the payment was received.$$;

/*
 *                             MIGRATION
 *
 * ADR 0111 (~/doc/adr/0111-payment-overpayment-terminology.md) has a table
 * describing the migration performed below. That is: the migration below
 * realizes the step from the "Intemediate" to the "Target" state columns. The
 * "Intermediate" state is realized by the migration of Overpayments.
 *
 *
 *                         Required changes
 *
 * The migration impact table from ADR 0111 lists the following changes:
 *
 * - Splitting "Payment" journal lines from their AR/AP transactions into
 *   "Payment" transactions [Rows 1, 2, 7, 8, 13, 14, 19, 20]
 * - Replacing "Overpayment creation" (GL) transactions with "Payment"
 *   transactions [Rows 3, 4, 9, 10]
 * - Decommissioning of "payment links" and (on batches) "vouchers"
 *   [Payment links: rows 1, 9, 19(?); Vouchers: rows 13, ??]
 *
 * Important: The allocation side (which is where the balances of overpayments
 *            and invoices are maintained) was already handled when those were
 *            migrated to open items. This is *only* about collecting journal
 *            lines into payment transactions.
 *
 *                          Approach
 *
 * The migration needs to be executed in two steps:
 *
 * 1. Batch payments (vouchers types 3 & 4 and 6 & 7)
 *    a. For payments with a NULL trans_id, create new transactions
 *    b. Collect all journal lines into the transactions (new or existing)
 * 2. Single payments & overpayments (no vouchers)
 *    a. For payments with a NULL trans_id, create new transactions
 *    b. Collect all journal lines into the transactions (new or existing)
 *
 * Note 1: Single payments & overpayments may be combined into
 *         one "payment"
 */


-- STEP 1: Migration of batch payments (voucher types 3 & 4 and 6 & 7)
--
--

-- (i) Determine the relationship between vouchers and payments:
-- Note: a journal line can only be part of one voucher; if it's part
-- of a payment, it can't be part of any of the other voucher types...
create temporary table payment_vouchers as
  select payment_id, voucher_id,
         case
            when txn.trans_type_code = 'gl'
               then p.trans_id
            else null
         end as trans_id,
         bool_and(ac.approved) as approved
    from acc_trans ac
           join transactions txn
               on txn.id = ac.trans_id
           join payment_links pl
               on pl.entry_id = ac.entry_id
           join payment p
               on p.id = pl.payment_id
   where voucher_id is not null
   group by payment_id, voucher_id, txn.trans_type_code, p.trans_id;

create temporary table payment_batches as
  select pv.payment_id, v.batch_id, pv.trans_id,
         bool_and(ac.approved) as approved
    from payment_vouchers pv
           join voucher v
                on pv.voucher_id = v.id
           left join acc_trans ac
                on ac.voucher_id = v.id
  group by pv.payment_id, v.batch_id, pv.trans_id;

-- (ii) Create payment transactions
--### Above, we require a single payment account per payment. This was
-- unfortunately historically not required. What to do with these historical
-- transactions?
--
-- The approach will be to have a pre-migration check to merge the payments
-- multiple payment account amounts into a single line on an intermediate
-- account. The intermediate account can then be used as the payment account
-- in the allocation transaction (which will be a GL transaction, not a
-- payment).
-- This means that by the time we end up at this point, no payments with
-- multiple cash accounts will exist anymore.


alter table transactions disable trigger transactions_prevent_closed;

with payment_transactions as (
  update payment_batches
     set trans_id = nextval('transactions_id_seq')
   where trans_id is null
         returning payment_batches.*
)
insert into transactions (
  id, approved, transdate,
  workflow_id,
  reference,
  trans_type_code, entered_by,
  description
)
    overriding system value
select pt.trans_id, pt.approved, p.payment_date,
       pg_temp.create_workflow(pt.approved),
       p.reference,
       'pa', (select entity_id from person where id = p.employee_id),
       'Payments migration'
  from payment_transactions pt
         join payment p
             on p.id = pt.payment_id;

alter table transactions enable trigger transactions_prevent_closed;


-- (iii) Move all voucher-linked *and* all payment_linked acc_trans lines
--       into the new transactions
-- Note: Using only payment_links doesn't work, because there are cases
--       where vouchers link to all payment lines where the payment links
--       to a subset

update payment_vouchers pv
   set trans_id = pb.trans_id
       from payment_batches pb
 where pv.payment_id = pb.payment_id
   and pv.trans_id is null;

alter table acc_trans disable trigger acc_trans_prevent_closed;

update acc_trans ac
   set trans_id = pv.trans_id,
       voucher_id = null
       from payment_vouchers pv
 where ac.voucher_id = pv.voucher_id;

alter table acc_trans enable trigger acc_trans_prevent_closed;

-- payment_links will be used to map acc_trans lines to the new
--  transaction(s) below for step 1 & 2 combined

alter table transactions
  disable trigger transactions_prevent_closed;

update transactions txn
   set batch_id = v.batch_id
       from payment_vouchers pv
              join voucher v
                  on pv.voucher_id = v.id
 where txn.id = pv.trans_id;

alter table transactions
  enable trigger transactions_prevent_closed;


delete from voucher v
            using payment_vouchers pv
 where v.id = pv.voucher_id;

drop table payment_vouchers;
drop table payment_batches;

-- STEP 2: Migration of payments and overpayments
--
--

create temporary table payment_transactions as
  select p.id as payment_id, nextval('transactions_id_seq') as trans_id
    from payment p
   where p.trans_id is null
     and exists (select 1 from payment_links pl where pl.payment_id = p.id);

alter table transactions disable trigger transactions_prevent_closed;

insert into transactions (
  id, approved, transdate,
  workflow_id,
  reference,
  trans_type_code, entered_by,
  description
)
    overriding system value
select pt.trans_id, bool_and(ac.approved), p.payment_date,
       pg_temp.create_workflow( (select bool_and(ac.approved)) ),
       p.reference,
       'pa', (select entity_id from person where id = p.employee_id),
       'Payment migration'
  from payment_transactions pt
         join payment p
             on p.id = pt.payment_id
         join payment_links pl
             on p.id = pl.payment_id
         join acc_trans ac
             on ac.entry_id = pl.entry_id
 group by pt.trans_id, p.id;

update payment p
   set trans_id = pt.trans_id
       from payment_transactions pt
 where p.id = pt.payment_id;

update transactions txn
   set reversing = (select trans_id
                      from transactions tx
                             join payment p2
                                 on tx.id = p2.trans_id
                     where p2.id = p.reversing)
       from payment p
 where txn.id = p.trans_id
   and txn.reversing is null
   and p.reversing is not null;

alter table transactions enable trigger transactions_prevent_closed;



-- update trans_id in acc_trans for steps 1 and 2 all at once
alter table acc_trans disable trigger acc_trans_prevent_closed;

update acc_trans ac
   set trans_id = p.trans_id
       from payment p
             join payment_links pl
                 on pl.payment_id = p.id
 where ac.entry_id = pl.entry_id;

alter table acc_trans enable trigger acc_trans_prevent_closed;

update payment p
   set account_id = ac.chart_id
       from acc_trans ac
            join account_link al
               on ac.chart_id = al.account_id
 where p.trans_id = ac.trans_id
   and al.description in ('AR_paid', 'AP_paid', 'migration_payment_splitter');

delete from account_link
 where description = 'migration_payment_splitter';
delete from account_link_description
 where description = 'migration_payment_splitter';

drop table payment_links;

alter table payment
  drop column reversing,
  alter column account_id set not null,
  alter column trans_id set not null;
