
/*
 *
 *  THIS FILE NEEDS TO BE EXECUTED *AFTER*
 *
 *   overpayments-as-open-items.sql
 *
 *  because this file assumes overpayments do not exist,
 *  which is what that file is all about.
 */


insert into trans_type (code, description)
values ('pa', 'The transaction is generated by a payment/receipt');

create or replace function pg_temp.create_workflow(in_approved boolean)
returns int as
  $sql$
  with new_workflow_item (workflow_id) as (
    insert into workflow (workflow_id, type, state, last_update)
    values (nextval('workflow_seq'), 'Payment', case when in_approved then 'POSTED' else 'SAVED' end, now())
    returning workflow_id
  )
  insert into workflow_history (
    workflow_hist_id,
    workflow_id,
    action, description,
    state, workflow_user,
    history_date, workflow_entity_id
  )
  values (
    nextval('workflow_history_seq'),
    (select workflow_id from new_workflow_item),
    'migrate', 'created during payments-as-first-order-transactions migration',
    case when in_approved then 'POSTED' else 'SAVED' end, SESSION_USER,
    now(), person__get_my_entity_id())
  returning workflow_id;
  $sql$ language sql;

alter table payment
  drop constraint check_payment_trans_id_null,
  drop constraint payment_trans_id_fkey,
  add constraint payment_trans_id_fkey foreign key (trans_id) references transactions (id) on delete cascade;

alter table payment
  add column account_id int references account(id);


-- this doesn't work for payments where the AR_paid/AP_paid checkmark
-- has been removed from the cash account, but that breaks the entire
-- database/application, so not taking that into account...
create temporary table payments_migration as
  select p.id, array_agg(distinct ac.trans_id) as orig_trans_ids, ac.chart_id,
         row_number() over (partition by p.id) as row_num,
         row_number() over (partition by p.id) = 1 as reuse,
         nextval('transactions_id_seq') as trans_id,
         p.reversing as reversing_payment_id,
         null::int as reversing_trans_id,
         bool_and(ac.approved) as approved
    from payment p
           join payment_links pl
               on p.id = pl.payment_id
           join acc_trans ac
               on pl.entry_id = ac.entry_id
           join account_link al
               on ac.chart_id = al.account_id
   where al.description in ('AR_paid', 'AP_paid', 'AR_overpayment', 'AP_overpayment')
   group by p.id, ac.chart_id;

update payments_migration pmo
   set reversing_trans_id = (
     select trans_id
       from payments_migration pmi
      where pmo.reversing_payment_id = pmi.id
        and pmo.chart_id = pmi.chart_id
   );

insert into transactions (
  id, table_name, approved, transdate,
  workflow_id, reversing,
  reference,
  trans_type_code, entered_by,
  description
  )
            overriding system value
select pm.trans_id, 'payment', pm.approved, p.payment_date,
       pg_temp.create_workflow(pm.approved), pm.reversing_trans_id,
       case when pm.reuse then p.reference else p.reference || '/' || pm.row_num end,
       'pa', (select entity_id from person where id = p.employee_id),
       'Payments migration'
  from payments_migration pm
         join payment p
             on pm.id = p.id;


-- fails if there are two or more cash accounts in a payment
-- which *was* supported by the single payments UI...
update payment p
   set account_id = pm.chart_id,
       trans_id   = pm.trans_id
       from payments_migration pm
 where p.id = pm.id
   and pm.reuse;

insert into payment (reference, payment_class, payment_date,
                     closed, entity_credit_id, employee_id,
                     currency,
                     notes,
                     reversing, trans_id, account_id)
select p.reference || '/' || pm.row_num,
       p.payment_class, p.payment_date,
       p.closed, p.entity_credit_id, p.employee_id,
       p.currency,
       E'this transaction was synthesized during payments-as-first-order-transactions migration\n\nOriginal notes:\n' || p.notes,
       p.reversing, pm.trans_id, pm.chart_id
  from payments_migration pm
         join payment p
             on pm.id = p.id
 where not pm.reuse;

alter table acc_trans disable trigger acc_trans_prevent_closed;

-- reassigning payment journal lines from ar/ap transactions
-- to payment transactions. One current (non-transactional)
-- payment may need to be split in multiple new (transactional)
-- payments, because current payments *can* have multiple cash
-- accounts, while transactional payments must have exactly one
--
-- To that extent: map payment-linked journal lines taking their
-- original (ar/ap) transaction into account to accomodate for
-- separate payment accounts
update acc_trans ac
   set trans_id = pm.trans_id
       from payments_migration pm
            join payment_links pl
                 on pm.id = pl.payment_id
 where pl.entry_id = ac.entry_id
   and ac.trans_id = ANY(pm.orig_trans_ids);

alter table acc_trans enable trigger acc_trans_prevent_closed;

drop table payment_links;

-- there are 8 'payment' rows in my real-life data set which don't have payment_links
-- resulting in records where there is on 'trans_id' value
delete from payment
 where trans_id is null;

alter table payment
  alter column account_id set not null;
