begin;
-- Latvian COA
-- prepared by Kaspars Melkis <info@isolis.lv>
-- Sept. 14, 2003
-- checked and edited Sept. 20, 2003, D. Simader
--
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1','Ilgtermiòa ieguldîjumi','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2','Apgrozâmie lîdzekïi','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('11','Nemateriâlie ieguldîjumi','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('12','Pamatlîdzekïi','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1210','Zemes gabali, çkas, bûves, ilggadîgie stâdîjumi un citi nekustamâ îpaðuma objekti','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1290','Pamatlîdzekïu nolietojums (pasîvâ)','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('13','Ilgtermiòa finansu ieguldîjumi','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('21','Krâjumi','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2130','Gatavâs preces pârdoðanai','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2310','Norçíini ar pircçjiem un pasûtîtâjiem','A','L','AP','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('23','Norçíini par prasîbâm (ar debitoriem)','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2350','Norçíini ar citiem debitoriem','A','A','AR_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('26','Naudas lîdzekïi','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2610','Kase','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1380','Aizdevumi uzòçmuma dalîbniekiem un valdei','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1310','Lîdzdalîba meitas uzòçmumu kapitâlâ','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1340','Aizdevumi saistîtajiem uzòçmumiem','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1350','Pârçjie vçrtspapîri','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5','Kreditori','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1370','Paðu akcijas un daïas','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2210','Pieauguðie produktîvie lopi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3350','Statûtos paredzçtâs rezerves','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2220','Jaunlopi un sîkie dzîvnieki','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2320','Par piegâdçm un pasûtîjumiem saòemtie vekseïi','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2140','Nepabeigtie pasûtîjumi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2370','Îstermiòa aizdevumi sabiedrîbâm dalîbniekiem un vadîbai','A','A','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1360','Pârçjie aizdevumi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2120','Nepabeigtie raþojumi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2330','Meitas uzòçmumu parâdi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2340','Saistîto uzòçmumu parâdi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2380','Norçíini par prasîbâm pret personâlu un îstermiòa aizdevumi personâlam','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2410','Nâkamo periodu izdevumi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2420','Akciju emisijas  nocenojums (disagio)','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('25','Vçrtspapîri apgrozâmo lîdzekïu sastâvâ un îstermiòa lîdzdalîba kapitâlos','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2510','Meitas  uzòçmuma akcijas un daïas ','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2520','Saistîto uzòçmuma akcijas un daïas ','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2530','Paðu  uzòçmuma akcijas un daïas ','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2540','Pârçjie vçrtspapîri un lîdzdalîba kapitâlos','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2640','Akreditîvi, èeki un îpaðu norçíina  formu konti','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2650','Citi konti bankâs','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2670','Pârçjie naudas lîdzekïi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3','Paðu kapitâls','H','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3130','Ilgtermiòa ieguldîjuma pârvçrtçðanas rezerve','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3120','Akciju emisijas uzcenojums (agio)','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('32','Privâtkonti','H','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3210','Privâtiem nolûkiem izòemtie lîdzekïi','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('33','Rezerves ','H','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3310','Rezerves kapitâls','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3330','Citas likumâ paredzçtâs  rezerves','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3340','Rezerves paðu akcijâm un daïâm','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3360','Pârçjâs rezerves','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('34','Nesadalîtâ peïòa vai nesegtie zaudçjumi','H','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3410','Pârskata gada nesadalîtâ peïòa','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3420','Iepriekðçjo gadu nesadalîtâ peïòa','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4','Uzkrâjumi','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4110','Uzkrâjumi pensijâm pielîdzinâtâm saistîbâm','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4310','Citi uzkrâjumi','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('41','Uzkrâjumi pensijâm pielîdzinâmâtâm saistîbâm','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('43','Citi uzkrâjumi','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('42','Uzkrâjumi paredzamiem nodokïiem','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('51','Norçíini par aizòçmumiem','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5110','Aizòçmumi pret obligâcijâm','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5120','Akcijâs pârvçðamie aizòçmumi','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5130','Aizòçmumi ar lîdzdalîbu peïòâ','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5140','Citi aizòçmumi','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5150','Îstermiòa aizòçmumi  no kredîtiestâdçm','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5160','Ilgtermiòa aizòçmumi no kredîtiestâdçm','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5170','Aizòçmumi no kredîtiestâdçm bez norâdîtâ termiòa','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('52','Norçíini par saòemtajiem avansiem','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5210','Norçíini par saòemtiem avansiem','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('54','Maksâjamie vekseïi','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('53','Norçíini par piegâdâtâjiem un darbuzòçmçjiem','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5310','Norçíini par piegâdâtâjiem un darbuzòçmçjiem','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5410','Norçíini par paðu izdotajiem vekseïiem','A','L','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5510','Norçíini par parâdiem meitas uzòçmumiem','A','L','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5540','Norçíini par parâdiem citiem uzòçmumiem un dalîbniekiem','A','L','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5550','Norçíini par parâdiem personâlam','A','L','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5520','Norçíini par parâdiem saistîtiem uzòçmumiem','A','L','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5530','Norçíini par parâdiem uzòçmumiem, ar kuriem ir lîgums par lîdzdalîbu','A','L','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('57','Norçíini par nodokïiem','H','L','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('58','Norçíini par  dividendçm','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('61','Ieòçmumi no pârdoðanas, kas apliekami ar nodokïiem vispârçjâ kârtîbâ','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('62','Ieòçmumi no pârdoðanas, kas citâdi  apliekami ar nodokïiem','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6220','Ar îpaðiem nodokïiem apliekamie pârdoðanas ieòçmumi','A','I','AR_amount:IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('63','Komisijas, starpniecîbas un citi ieòçmumi','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6310','Komisijas un starpniecîbas ieòçmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6320','Ieòçmumi no atkritumu pârstrâdes un realizâcijas','A','I','AR_amount:IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6330','Ieòçmumi no taras realizâcijas','A','I','AR_amount:IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6340','Ar nodokïiem neapliekamie apgrozîjumi','A','I','AR_amount:IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('64','Ieòçmumus samazinoðas atlaides','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6410','Pieðíirtâs skonto atlaides','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6420','Pieðíirtie bonusi','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('59','Nâkamo periodu ieòçmumi','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('65','Pârçjie uzòçmuma ieòçmumi','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6510','Ieòçmumi no vçrtspapîru kursa paaugstinâðanâs','A','I','AR_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6530','Ieòçmumi no zemes gabalu iznomâðanas','A','I','AR_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6540','Ieòçmumi no apgrozâmo lîdzekïu pârdoðanas','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6550','Ieòçmumi no pamatlîdzekïu iznomâðanas','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6560','Ieòçmumos pârskaitîtais rezervju un uzkrâjumu samazinâjums','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6570','Iepriekðçjo gadu nodokïu samazinâjums','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6580','Papildus  ieguldîjumi un citi ieòçmumi','A','I','AR_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6590','Paðu uzòçmuma kapitâlieguldîjumiem izpildîtie darbi','A','I','AR_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('67','Citu periodu ieòçmumi, kas attiecas uz pârskata periodu','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6710','Citu periodu ieòçmumi, kas attiecas uz pârskata periodu','A','I','AR_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('69','Sociâlâs infrastruktûras iestâþu un pasâkumu ieòçmumi','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6930','Sadzîves paklpojumu ieòçmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6920','Komunâlâs  saimniecîbas ieòçmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('66','Gatavâs produkcijas  un nepabeigto  raþojumu krâjumu un vçrtîbas  izmaiòas','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6610','Gatavâs produkcijas krâjumu un vçrtîbas izmaiòas','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6620','Nepabeigto raþojumu krâjumu un vçrtîbas  izmaiòas','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6630','Nepabeigto pasûtîjumu atlikumu un vçtîbas izmaiòas','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6640','Produktîvo  un darba dzîvnieku ganâmpulka vçrtîbas izmaiòas','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6940','Sabiedriskâs çdinâðanas ieòçmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6950','Izglîtîbas iestâþu ieòçmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6960','Medicînas iestâþu ieòçmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6970','Kultûras un sporta ietâþu un pasâkumu ieòçmumi','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6980','Pârçjie sociâlâs infrastruktûras iestâþu un pasâkumu ieòçmumi','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7','Saimnieciskâs darbîbas izdevumi','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('71','Izdevumi izejvielu, materiâlu un preèu iepirkðanai','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7110','Izejvielu un materiâlu iepirkðanas un piegâdes izdevumi','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7120','Preèu iepirkðanas un piegâdes izdevumi','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7130','Saòemtâs atlaides','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7140','Taras izdevumi','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7150','Muitas un ievednodevas','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7160','Pârçjie ârçjie izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7170','Samaksa par darbiem un pakalpojumiem no ârienes','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7190','Pirkto materiâlu un preèu krâjumu un vçrtîbas izmaiòas','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('72','Personâla izmaksas','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7210','Strâdnieku algas','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7230','Sociâlâs  infrastruktûras  iestâþu un pasâkumu darbinieku algas','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('73','Sociâlâs nodevas un izmaksas','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7320','Pârçjâs sociâlâs izmaksas','A','E','AP_tax','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('74','Pamatlîdzekïu nolietojums un citu ieguldîjumu vçrtîbas norakstîjumi','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7410','Nemateriâlo ieguldîjumu vçrtîbas norakstîðana','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('75','Pârçjie saimnieciskâs darbîbas  izdevumi','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7510','Dabas aizsardzîbas izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7530','Nodevas par raþoðanâ izmantotiem zemes gabaliem','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7440','Apgrozâmo lîdzekïu vçrtîbas norakstîðana','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7540','Apdroðinnâðanas maksâjumi (izòemot darbinieku apdroðinâðanu)','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7550','Pârçjie saimnieciskâs darbîbas izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7560','Strâdnieku vervçðanas un apmâcîbas izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('76','Preèu pârdoðanas izdevumi','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7610','Iesaiòojamais materiâls, tara','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7620','Preèu transporta izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7630','Preèu transporta apdroðinâðana','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7640','Samaksâtâs komisijas naudas','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7650','Citi pârdoðanas izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('77','Administrâcijas izdevumi','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7710','Sakaru izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7720','Kantora (biroja) izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7730','Juristu pakalpojumu apmaksa','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7740','Gada pârskata un revîzijas izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7750','Naudas apgrozîjuma blakus izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7760','Transporta izdevumi administrâcijas vajadzîbâm','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7770','Citi vadîðanas un administrâcijas izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('78','Pârskata periodâ iekïaujamie iepriekðçjo periodu izdevumi','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7810','Pârskata periodâ iekïaujamie iepriekðçjo periodu izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('79','Sociâlâs  infrastruktûras uzturçðanas izdevumi','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7920','Komuâlâs saimniecîbas izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7940','Sabiedriskâs çdinâðanas izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7950','Izglîtîbas iestâþu izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8','Daþâdi ieòçmumi un izdevumi, peïòa un zaudçjumi','H','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('81','Daþâdi ieòçmumi','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8110','Ieòçmumi no lîdzdalîbas, vçrtspapîriem un aizdevumiem','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8120','Pârçjie ieòçmumi no procentiem un tiem pielîdzinâmi ieòçmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7910','Dzîvokïu saimniecîbas izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8130','Vekseïu diskonta ieòçmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8150','Ienâkumi no valûtas kursa paaugstinâðanâs','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8160','Saòemtâs soda naudas un lîgumsodi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8170','Peïòa no ârzemju valûtas pârdoðanas vai pirkðanas','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8190','Citi ieòçmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('82','Daþâdi izdevumi','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8210','Îstermiòa finansu ieguldîjumu vçrtîbas norakstîðana','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8220','Samaksâtie procenti un tiem pielîdzinâmie izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8230','Vekseïu diskonta izmaksas','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8240','Ilgtermiòa aizdevumu procentu samaksa','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8260','Samaksâtâs soda naudas un lîgumsodi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8270','Zaudçjumi no ârzemju valûtas pirkðanas un pârdoðanas','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8290','Citi izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('83','Ârkârtas ieòçmumi','H','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8310','Ârkârtas ieòçmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('84','Ârkârtas izdevumi','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8410','Ârkârtas izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('86','Peïòa vai zaudçjumi','H','I','IC_income:IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8610','Peïòa vai zaudçjumi','A','I','IC_income:IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3220','Privâtie ieguldîjumi','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6110','Ieòçmumi no pamatdarbîbas  produkcijas un pakalpojumu pârdoðanas','A','I','AR_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1220','Tehnoloìiskâs  iekârtas un maðînas','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1240','Pamatlîdzekïu izveidoðana un nepabeigto celtniecîbas objektu izmaksas','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1320','Aizdevumi meitas uzòçmumam','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2110','Izejvielas un materiâli','A','A','AP','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2190','Avansa maksâjumi par precçm','A','A','AR','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1130','Uzòçmuma nemateriâlâ vçrtîba','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1180','Avansa maksâjumi par nemateriâliem aktîviem','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1190','Nemateriâlo ieguldîjumu vçrtîbas norakstîtâ daïa (pasîvâ)','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('22','Produktîvie un darba dzîvnieki','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2230','Darba lopi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2290','Darba lopu norakstîtâ vçrtîba (pasîvâ)','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2360','Norçíini par parakstîtâ sabiedrîbas kapitâlâ neiemaksâtâm summâm','A','A','AR_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('24','Nâkamo periodu izdevumi','H','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2620','Norçíinu konti bankâ','A','A','AR_paid:AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3110','Pamatkapitâls vai lîdzdalîbas kapitâls','A','Q','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('55','Norçíini ar uzòçmumiem, dalîbniekiem un personâlu','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('56','Norçíini  par darba samaksu  un ieturçjumiem (izòemot nodokïus)','H','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5610','Norçíini par darba algu','A','E','AP_amount','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5620','Norçíini par ieturçjumiem no darba algas (izòemot nodokïus)','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5820','Norçíini par iepriekðçjo gadu neizmaksâtajâm dividendçm','A','L','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5810','Norçíini par pârskata gada dividendçm','A','L','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5910','Nâkamo periodu ieòçmumi','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6','Ieòçmumi no uzòçmuma saimnieciskâs darbîbas','H','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6210','Ar nodokïiem neapliekamie pârdoðanas ieòçmumi','A','I','AR_amount:IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6430','Pieðíirtie rabati un citas tirdzniecîbas  atlaides','A','I','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('6910','Dzîvokïu saimniecîbas ieòçmumi','A','I','AR_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7180','Pârçjie materiâlie izdevumi (nodoklis par dabas resursu izmantoðanu, celmu nauda u.c.)','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7240','Pârçjâs personâla izmaksas','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7220','Pârvaldes personâla un administratîvâ personâla algas','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7420','Pamatlîdzekïu nolietojums','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7570','Komandçjuma izdevumi','A','E','AP_paid','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7930','Sadzîves pakalpojumu izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7960','Medicîniskâs apkalpoðanas izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7970','Kultûras un sporta iestâþu un pasâkumu izdevumi','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8140','Ziedojumi un citi tiem pielîdzinâmi ieòçmumi','A','I','IC_income','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8250','Zaudçjumi no valûtu  kursa pazeminâðanâs','A','E','IC_expense','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7980','Pârçjie sociâlâs infrastruktûras uzturçðanas izdevumi','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('87','Peïòas izlietojums (bez nodokïiem)','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('88','Nodoïi no peïòas un citi saimnieciskâs darbîbas izdevumos neiekïaujamie nodokïi','H','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1110','Pçtniecîbas un uzòçmuma attîstîbas izmaksas','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1120','Koncesijas, patenti, licences, tirdzniecîbas zîmes un lîdzîgas tiesîbas; datoru programmas','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1230','Pârçjie pamatlîdzekïi un inventârs','A','A','IC','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5710','Norçíini par peïòas nodokli','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2390','Pârmaksâtie nodokïi, iepriekð samaksâtie nodokïi','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4210','Uzkrâjumi paredzamiem nodokïiem','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('5720','Norçíini par citiem nodokïiem, nodevâm un maksâjumiem budþetam','A','L','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('7310','Sociâlais nodoklis','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8710','Peïòas izlietojums','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8830','Nodoklis par zemi','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8840','Citi saimnieciskâs darbîbas izmaksâs neiekïaujamie nodokïi','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8820','Nodoklis par dabas resursu izmantoðanu no peïòas  maksâjamâ daïâ','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8810','Nodoklis no peïòas','A','E','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1330','Lîdzdalîbas saistîto uzòçmumu kapitâlâ','A','A','','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2354','PVN samaksâts 18%','A','E','AP_tax:IC_taxpart:IC_taxservice','');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2352','PVN ieòemtais 18%','A','L','AR_tax:IC_taxpart:IC_taxservice','');
--
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM chart where accno = '2352'),'0.18','');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM chart where accno = '2354'),'0.18','');
--
INSERT INTO defaults (setting_key, value) VALUES ('inventory_accno_id', (select id from chart where accno = '1230'));

 INSERT INTO defaults (setting_key, value) VALUES ('income_accno_id', (select id from chart where accno = '6010'));

 INSERT INTO defaults (setting_key, value) VALUES ('expense_accno_id', (select id from chart where accno = '7110'));

 INSERT INTO defaults (setting_key, value) VALUES ('fxgain_accno_id', (select id from chart where accno = '8170'));

 INSERT INTO defaults (setting_key, value) VALUES ('fxloss_accno_id', (select id from chart where accno = '8270'));

 INSERT INTO defaults (setting_key, value) VALUES ('curr', 'LVL');

 INSERT INTO defaults (setting_key, value) VALUES ('weightunit', 'kg');

commit;
