
INSERT INTO trans_type (code, description)
   VALUES ('fa', 'The transaction is generated by fixed assets depreciation'),
          ('fd', 'The transaction is generated by fixed assets disposal'),
          ('ye', 'The transaction is generated by Year-End processes');

