INSERT INTO country(short_name,name) VALUES ('BL','St. Barthelemy');
INSERT INTO country(short_name,name) VALUES ('BQ','Caribbean Netherlands');
INSERT INTO country(short_name,name) VALUES ('CW','Curacao');
INSERT INTO country(short_name,name) VALUES ('DG','Diego Garcia');
INSERT INTO country(short_name,name) VALUES ('EA','Ceuta & Melilla');
INSERT INTO country(short_name,name) VALUES ('GG','Guernsey');
INSERT INTO country(short_name,name) VALUES ('IC','Canary Islands');
INSERT INTO country(short_name,name) VALUES ('ME','Montenegro');
INSERT INTO country(short_name,name) VALUES ('MF','St. Martin');
INSERT INTO country(short_name,name) VALUES ('SS','South Sudan');
INSERT INTO country(short_name,name) VALUES ('SX','Sint Maarten');
INSERT INTO country(short_name,name) VALUES ('TL','Timor-Leste');
INSERT INTO country(short_name,name) VALUES ('XK','Kosovo');
