begin;
-- Latvian COA
-- prepared by Kaspars Melkis <info@isolis.lv>
-- Sept. 14, 2003
-- checked and edited Sept. 20, 2003, D. Simader
-- modified by Janeks Kamerovskis <sags@apollo.lv>
-- Nov. 5, 2009

INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1','Ilgtermiņa ieguldījumi','H','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2','Apgrozāmie līdzekļi','H','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('11','Nemateriālie ieguldījumi','H','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('12','Pamatlīdzekļi','H','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1210','Zemes gabali,ēkas,būves,ilggadīgie stādījumi un citi nekustamā īpašuma objekti','A','A','IC','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1290','Pamatlīdzekļu nolietojums (pasīvā)','A','A','IC','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('13','Ilgtermiņa finansu ieguldījumi','H','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('21','Krājumi','H','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2130','Gatavās preces pārdošanai','A','A','IC','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2310','Norēķini ar pircējiem un pasūtītājiem','A','L','AP','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('23','Norēķini par prasībām (ar debitoriem)','H','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2350','Norēķini ar citiem debitoriem','A','A','AR_amount','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('26','Naudas līdzekļi','H','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2610','Kase','A','A','AR_paid:AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1380','Aizdevumi uzņēmuma dalībniekiem un valdei','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1310','Līdzdalība meitas uzņēmumu kapitālā','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1340','Aizdevumi saistītajiem uzņēmumiem','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1350','Pārējie vērtspapīri','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5','Kreditori','H','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1370','Pašu akcijas un daļas','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2210','Pieaugušie produktīvie lopi','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3350','Statūtos paredzētās rezerves','A','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2220','Jaunlopi un sīkie dzīvnieki','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2320','Par piegādēm un pasūtījumiem saņemtie vekseļi','A','A','IC','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2140','Nepabeigtie pasūtījumi','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2370','Îstermiņa aizdevumi sabiedrībām dalībniekiem un vadībai','A','A','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1360','Pārējie aizdevumi','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2120','Nepabeigtie ražojumi','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2330','Meitas uzņēmumu parādi','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2340','Saistīto uzņēmumu parādi','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2380','Norēķini par prasībām pret personālu un īstermiņa aizdevumi personālam','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2410','Nākamo periodu izdevumi','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2420','Akciju emisijas  nocenojums (disagio)','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('25','Vērtspapīri apgrozāmo līdzekļu sastāvā un īstermiņa līdzdalība kapitālos','H','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2510','Meitas  uzņēmuma akcijas un daļas ','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2520','Saistīto uzņēmuma akcijas un daļas ','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2530','Pašu  uzņēmuma akcijas un daļas ','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2540','Pārējie vērtspapīri un līdzdalība kapitālos','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2640','Akreditīvi,èeki un īpašu norēķina  formu konti','A','A','AR_paid:AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2650','Citi konti bankās','A','A','AR_paid:AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2670','Pārējie naudas līdzekļi','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3','Pašu kapitāls','H','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3130','Ilgtermiņa ieguldījuma pārvērtēšanas rezerve','A','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3120','Akciju emisijas uzcenojums (agio)','A','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('32','Privātkonti','H','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3210','Privātiem nolūkiem izņemtie līdzekļi','A','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('33','Rezerves ','H','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3310','Rezerves kapitāls','A','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3330','Citas likumā paredzētās  rezerves','A','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3340','Rezerves pašu akcijām un daļām','A','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3360','Pārējās rezerves','A','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('34','Nesadalītā peļņa vai nesegtie zaudējumi','H','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3410','Pārskata gada nesadalītā peļņa','A','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3420','Iepriekšējo gadu nesadalītā peļņa','A','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4','Uzkrājumi','H','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4110','Uzkrājumi pensijām pielīdzinātām saistībām','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4310','Citi uzkrājumi','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('41','Uzkrājumi pensijām pielīdzināmātām saistībām','H','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('43','Citi uzkrājumi','H','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('42','Uzkrājumi paredzamiem nodokļiem','H','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('51','Norēķini par aizņēmumiem','H','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5110','Aizņēmumi pret obligācijām','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5120','Akcijās pārvēšamie aizņēmumi','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5130','Aizņēmumi ar līdzdalību peļņā','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5140','Citi aizņēmumi','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5150','Îstermiņa aizņēmumi  no kredītiestādēm','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5160','Ilgtermiņa aizņēmumi no kredītiestādēm','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5170','Aizņēmumi no kredītiestādēm bez norādītā termiņa','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('52','Norēķini par saņemtajiem avansiem','H','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5210','Norēķini par saņemtiem avansiem','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('54','Maksājamie vekseļi','H','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('53','Norēķini par piegādātājiem un darbuzņēmējiem','H','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5310','Norēķini par piegādātājiem un darbuzņēmējiem','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5410','Norēķini par pašu izdotajiem vekseļiem','A','L','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5510','Norēķini par parādiem meitas uzņēmumiem','A','L','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5540','Norēķini par parādiem citiem uzņēmumiem un dalībniekiem','A','L','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5550','Norēķini par parādiem personālam','A','L','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5520','Norēķini par parādiem saistītiem uzņēmumiem','A','L','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5530','Norēķini par parādiem uzņēmumiem,ar kuriem ir līgums par līdzdalību','A','L','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('57','Norēķini par nodokļiem','H','L','AP_amount','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('58','Norēķini par  dividendēm','H','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('61','Ieņēmumi no pārdošanas,kas apliekami ar nodokļiem vispārējā kārtībā','H','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('62','Ieņēmumi no pārdošanas,kas citādi  apliekami ar nodokļiem','H','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6220','Ar īpašiem nodokļiem apliekamie pārdošanas ieņēmumi','A','I','AR_amount:IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('63','Komisijas,starpniecības un citi ieņēmumi','H','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6310','Komisijas un starpniecības ieņēmumi','A','I','IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6320','Ieņēmumi no atkritumu pārstrādes un realizācijas','A','I','AR_amount:IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6330','Ieņēmumi no taras realizācijas','A','I','AR_amount:IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6340','Ar nodokļiem neapliekamie apgrozījumi','A','I','AR_amount:IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('64','Ieņēmumus samazinošas atlaides','H','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6410','Piešķirtās skonto atlaides','A','I','IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6420','Piešķirtie bonusi','A','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('59','Nākamo periodu ieņēmumi','H','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('65','Pārējie uzņēmuma ieņēmumi','H','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6510','Ieņēmumi no vērtspapīru kursa paaugstināšanās','A','I','AR_amount','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6530','Ieņēmumi no zemes gabalu iznomāšanas','A','I','AR_amount','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6540','Ieņēmumi no apgrozāmo līdzekļu pārdošanas','A','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6550','Ieņēmumi no pamatlīdzekļu iznomāšanas','A','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6560','Ieņēmumos pārskaitītais rezervju un uzkrājumu samazinājums','A','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6570','Iepriekšējo gadu nodokļu samazinājums','A','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6580','Papildus  ieguldījumi un citi ieņēmumi','A','I','AR_amount','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6590','Pašu uzņēmuma kapitālieguldījumiem izpildītie darbi','A','I','AR_amount','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('67','Citu periodu ieņēmumi,kas attiecas uz pārskata periodu','H','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6710','Citu periodu ieņēmumi,kas attiecas uz pārskata periodu','A','I','AR_amount','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('69','Sociālās infrastruktūras iestāžu un pasākumu ieņēmumi','H','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6930','Sadzīves paklpojumu ieņēmumi','A','I','IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6920','Komunālās  saimniecības ieņēmumi','A','I','IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('66','Gatavās produkcijas  un nepabeigto  ražojumu krājumu un vērtības  izmaiņas','H','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6610','Gatavās produkcijas krājumu un vērtības izmaiņas','A','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6620','Nepabeigto ražojumu krājumu un vērtības  izmaiņas','A','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6630','Nepabeigto pasūtījumu atlikumu un vētības izmaiņas','A','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6640','Produktīvo  un darba dzīvnieku ganāmpulka vērtības izmaiņas','A','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6940','Sabiedriskās ēdināšanas ieņēmumi','A','I','IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6950','Izglītības iestāžu ieņēmumi','A','I','IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6960','Medicīnas iestāžu ieņēmumi','A','I','IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6970','Kultūras un sporta ietāžu un pasākumu ieņēmumi','A','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6980','Pārējie sociālās infrastruktūras iestāžu un pasākumu ieņēmumi','A','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7','Saimnieciskās darbības izdevumi','H','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7130','Saņemtās atlaides','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7140','Taras izdevumi','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7160','Pārējie ārējie izdevumi','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('72','Personāla izmaksas','H','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7210','Strādnieku algas','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7230','Sociālās  infrastruktūras  iestāžu un pasākumu darbinieku algas','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('73','Sociālās nodevas un izmaksas','H','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7320','Pārējās sociālās izmaksas','A','E','AP_tax','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('74','Pamatlīdzekļu nolietojums un citu ieguldījumu vērtības norakstījumi','H','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7410','Nemateriālo ieguldījumu vērtības norakstīšana','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('75','Pārējie saimnieciskās darbības  izdevumi','H','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7510','Dabas aizsardzības izdevumi','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7530','Nodevas par ražošanā izmantotiem zemes gabaliem','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7440','Apgrozāmo līdzekļu vērtības norakstīšana','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7540','Apdrošinnāšanas maksājumi (izņemot darbinieku apdrošināšanu)','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7550','Pārējie saimnieciskās darbības izdevumi','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7560','Strādnieku vervēšanas un apmācības izdevumi','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7120','Preču iepirkšanas un piegādes izdevumi','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7610','Iesaiņojamais materiāls,tara','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7190','Pirkto materiālu un preču krājumu un vērtības izmaiņas','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7640','Samaksātās komisijas naudas','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7650','Citi pārdošanas izdevumi','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('77','Administrācijas izdevumi','H','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7710','Sakaru izdevumi','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7720','Kantora (biroja) izdevumi','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7730','Juristu pakalpojumu apmaksa','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7740','Gada pārskata un revīzijas izdevumi','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7750','Naudas apgrozījuma blakus izdevumi','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7760','Transporta izdevumi administrācijas vajadzībām','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7770','Citi vadīšanas un administrācijas izdevumi','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('78','Pārskata periodā iekļaujamie iepriekšējo periodu izdevumi','H','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7810','Pārskata periodā iekļaujamie iepriekšējo periodu izdevumi','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('79','Sociālās  infrastruktūras uzturēšanas izdevumi','H','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7920','Komuālās saimniecības izdevumi','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7940','Sabiedriskās ēdināšanas izdevumi','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7950','Izglītības iestāžu izdevumi','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8','Dažādi ieņēmumi un izdevumi,peļņa un zaudējumi','H','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('81','Dažādi ieņēmumi','H','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8110','Ieņēmumi no līdzdalības,vērtspapīriem un aizdevumiem','A','I','IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8120','Pārējie ieņēmumi no procentiem un tiem pielīdzināmi ieņēmumi','A','I','IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7910','Dzīvokļu saimniecības izdevumi','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8130','Vekseļu diskonta ieņēmumi','A','I','IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8150','Ienākumi no valūtas kursa paaugstināšanās','A','I','IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8160','Saņemtās soda naudas un līgumsodi','A','I','IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8170','Peļņa no ārzemju valūtas pārdošanas vai pirkšanas','A','I','IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8190','Citi ieņēmumi','A','I','IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('82','Dažādi izdevumi','H','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8210','Îstermiņa finansu ieguldījumu vērtības norakstīšana','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8220','Samaksātie procenti un tiem pielīdzināmie izdevumi','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8230','Vekseļu diskonta izmaksas','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8240','Ilgtermiņa aizdevumu procentu samaksa','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8260','Samaksātās soda naudas un līgumsodi','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8270','Zaudējumi no ārzemju valūtas pirkšanas un pārdošanas','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8290','Citi izdevumi','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('83','Ârkārtas ieņēmumi','H','I','IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8310','Ârkārtas ieņēmumi','A','I','IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('84','Ârkārtas izdevumi','H','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8410','Ârkārtas izdevumi','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('86','Peļņa vai zaudējumi','H','I','IC_income:IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8610','Peļņa vai zaudējumi','A','I','IC_income:IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3220','Privātie ieguldījumi','A','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7630','Preču transporta apdrošināšana','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7110','Izejvielu un materiālu iepirkšanas un piegādes izdevumi','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7150','Muitas un ievednodevas','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7170','Samaksa par darbiem un pakalpojumiem no ārienes','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('71','Izdevumi izejvielu,materiālu un preču iepirkšanai','H','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6110','Ieņēmumi no pamatdarbības  produkcijas un pakalpojumu pārdošanas','A','I','AR_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1220','Tehnoloìiskās  iekārtas un mašīnas','A','A','IC','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1240','Pamatlīdzekļu izveidošana un nepabeigto celtniecības objektu izmaksas','A','A','IC','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1320','Aizdevumi meitas uzņēmumam','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2110','Izejvielas un materiāli','A','A','AP','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2190','Avansa maksājumi par precēm','A','A','AR','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1130','Uzņēmuma nemateriālā vērtība','A','A','IC','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1180','Avansa maksājumi par nemateriāliem aktīviem','A','A','IC','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1190','Nemateriālo ieguldījumu vērtības norakstītā daļa (pasīvā)','A','A','IC','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('22','Produktīvie un darba dzīvnieki','H','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2230','Darba lopi','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2290','Darba lopu norakstītā vērtība (pasīvā)','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2360','Norēķini par parakstītā sabiedrības kapitālā neiemaksātām summām','A','A','AR_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('24','Nākamo periodu izdevumi','H','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2620','Norēķinu konti bankā','A','A','AR_paid:AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3110','Pamatkapitāls vai līdzdalības kapitāls','A','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('55','Norēķini ar uzņēmumiem,dalībniekiem un personālu','H','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('56','Norēķini  par darba samaksu  un ieturējumiem (izņemot nodokļus)','H','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5610','Norēķini par darba algu','A','E','AP_amount','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5620','Norēķini par ieturējumiem no darba algas (izņemot nodokļus)','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5820','Norēķini par iepriekšējo gadu neizmaksātajām dividendēm','A','L','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5810','Norēķini par pārskata gada dividendēm','A','L','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5910','Nākamo periodu ieņēmumi','A','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6','Ieņēmumi no uzņēmuma saimnieciskās darbības','H','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6210','Ar nodokļiem neapliekamie pārdošanas ieņēmumi','A','I','AR_amount:IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6430','Piešķirtie rabati un citas tirdzniecības  atlaides','A','I','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6910','Dzīvokļu saimniecības ieņēmumi','A','I','AR_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7180','Pārējie materiālie izdevumi (nodoklis par dabas resursu izmantošanu,celmu nauda u.c.)','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7240','Pārējās personāla izmaksas','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7220','Pārvaldes personāla un administratīvā personāla algas','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7420','Pamatlīdzekļu nolietojums','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7570','Komandējuma izdevumi','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7930','Sadzīves pakalpojumu izdevumi','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7960','Medicīniskās apkalpošanas izdevumi','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7970','Kultūras un sporta iestāžu un pasākumu izdevumi','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8140','Ziedojumi un citi tiem pielīdzināmi ieņēmumi','A','I','IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8250','Zaudējumi no valūtu  kursa pazemināšanās','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7980','Pārējie sociālās infrastruktūras uzturēšanas izdevumi','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('87','Peļņas izlietojums (bez nodokļiem)','H','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('88','Nodoļi no peļņas un citi saimnieciskās darbības izdevumos neiekļaujamie nodokļi','H','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1110','Pētniecības un uzņēmuma attīstības izmaksas','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1120','Koncesijas,patenti,licences,tirdzniecības zīmes un līdzīgas tiesības; datoru programmas','A','A','IC','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5710','Norēķini par peļņas nodokli','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2390','Pārmaksātie nodokļi,iepriekš samaksātie nodokļi','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4210','Uzkrājumi paredzamiem nodokļiem','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5720','Norēķini par citiem nodokļiem,nodevām un maksājumiem budžetam','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7310','Sociālais nodoklis','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8710','Peļņas izlietojums','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8830','Nodoklis par zemi','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8840','Citi saimnieciskās darbības izmaksās neiekļaujamie nodokļi','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8820','Nodoklis par dabas resursu izmantošanu no peļņas  maksājamā daļā','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8810','Nodoklis no peļņas','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1330','Līdzdalības saistīto uzņēmumu kapitālā','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2354','PVN samaksāts 18%','A','E','AP_tax:IC_taxpart:IC_taxservice','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2352','PVN ieņemtais 18%','A','L','AR_tax:IC_taxpart:IC_taxservice','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('76','Preču pārdošanas izdevumi','H','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7620','Preču transporta izdevumi','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2353','PVN ieņemtais 21%','A','L','AR_tax:IC_taxpart:IC_taxservice','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2355','PVN samaksāts 21%','A','E','AP_tax:IC_taxpart:IC_taxservice','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1231','Pārējie pamatlīdzekļi','A','A','IC','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1232','Datu uzkrāšanas iekārtas','A','A','IC','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5311','Norēķini ar piegādātājiem','A','L','AP','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1292','Pārējo pamatlīdzekļu nolietojums','A','A','IC','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1291','Datu uzkrāšanas iekārtu nolietojums','A','A','IC','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2312','PVN par precēm ES','A','L','AP','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2361','Norēķini par kapitālā neiemaksātām daļām','A','A','AR_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2411','Nākamo periodu izdevumi','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2611','Kase LVL','A','A','AR_paid:AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2621','SEB LVL','A','A','AR_paid:AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2622','Swedbank LVL','A','A','AR_paid:AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3111','Pamatkapitāls','A','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3411','Pārskata gada nesadalītā peļņa','A','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('3412','Iepriekšējo gadu nesadalītā peļņa','A','Q','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('4311','Uzkrājumi UIEN','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5312','Norēķini ar piegādātājiem preces ES','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5611','Darba samaksa','A','E','AP_amount','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5711','Uzņēmuma ienākuma nodoklis','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5721','PVN','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('57212','PVN 18 % ES par precēm','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5723','Norēķini par VSAOI','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5724','Norēķini par IIEN','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5727','Norēķini par UDRVN','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7111','Materiāli','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7311','VSAOI','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7421','Pamatlīdzekļu amortizācija','A','E','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7541','Apdrošināšanas izdevumi','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('6111','Ieņēmumi no pakalpojumiem','A','I','AR_amount:IC_income:IC_sale','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2311','Norēķini ar pircējiem','A','L','AR','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7211','Darba samaksa','A','E','AP_paid:IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('1230','Pārējie pamatlīdzekļi un inventārs','A','A','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7555','Saimnieciskie izdevumi','A','E','AP_amount:IC_expense:IC_cogs','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('57211','PVN 18 %','A','L','AR_tax:AP_tax:IC_taxpart:IC_taxservice','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7571','Komandējuma izdevumi','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7622','Dīzeļdegvielas izdevumi','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7624','Pārējie transporta izdevumi','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7731','Juristu,advokātu,notāru pakalpojumi','A','E','AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7772','Uzņēmējdarbības riska valsts nodeva','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7773','Valsts nodevas','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7778','Reprezentācijas izdevumi','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8121','Bankas % ieņēmumi','A','I','IC_income','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8291','Citi izdevumi','A','E','IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('8611','Peļņa vai zaudējumi','A','I','IC_income:IC_expense','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2111','Materiāli','A','A','AP','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('57213','PVN 21 %','A','L','AR_tax:AP_tax:IC_taxpart:IC_taxservice','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2381','Norēķini ar J.Bērziņš','A','A','AR_paid:AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7441','Inventārs','A','E','AP_amount:IC_expense:IC_cogs','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7721','Biroja izdevumi','A','E','AP_amount:IC_expense:IC_cogs','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7771','Citi administrācijas izdevumi','A','E','AP_amount:IC_expense:IC_cogs','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7741','Grāmatvedības pakalpojumi','A','E','AP_amount:IC_expense:IC_cogs','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7711','Sakaru izdevumi','A','E','AP_amount:IC_expense:IC_cogs','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7623','Rezerves daļas','A','E','AP_amount:IC_expense:IC_cogs','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7625','Auto uzturēšanas izdevumi','A','E','AP_amount:IC_expense:IC_cogs','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7660','Reklāmas izdevumi','A','E','AP_amount:IC_expense:IC_cogs','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7751','Bankas pakalpojumi','A','E','AP_amount:IC_expense:IC_cogs','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7621','Benzīna izdevumi','A','E','AP_amount:IC_expense:IC_cogs','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('5729','Norēķini PVN ar budžetu','A','L','','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('2382','Norēķini ar G.Ozolu','A','A','AR_paid:AP_paid','',false);
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno,contra) VALUES ('7553','Elektrības izdevumi','A','E','AP_amount:IC_expense:IC_cogs','',false);
--
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM chart where accno = '2352'),'0.18','');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM chart where accno = '2354'),'0.18','');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM chart where accno = '2353'),'0.21','');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM chart where accno = '2355'),'0.21','');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM chart where accno = '57211'),'0.18','');
INSERT INTO tax (chart_id,rate,taxnumber) VALUES ((SELECT id FROM chart where accno = '57213'),'0.21','');
--
INSERT INTO defaults (setting_key, value) VALUES ('inventory_accno_id', (select id from chart where accno = '1230'));

 INSERT INTO defaults (setting_key, value) VALUES ('income_accno_id', (select id from chart where accno = '6010'));

 INSERT INTO defaults (setting_key, value) VALUES ('expense_accno_id', (select id from chart where accno = '7110'));

 INSERT INTO defaults (setting_key, value) VALUES ('fxgain_accno_id', (select id from chart where accno = '8170'));

 INSERT INTO defaults (setting_key, value) VALUES ('fxloss_accno_id', (select id from chart where accno = '8270'));

 INSERT INTO defaults (setting_key, value) VALUES ('curr', 'LVL');

 INSERT INTO defaults (setting_key, value) VALUES ('weightunit', 'kg');

commit;

 	  	 
