begin;
-- Johan Hambraeus
-- May 7, 2006
--
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1','Tillgångar','H','','','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('10','Immateriella anläggningstillgångar','H','','','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1010','Balanserade utgifter','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1019','Ack avskriningar balanserade utg','A','','C','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1060','Hyresrätt','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1069','Ack avskrivn hyresrätt','A','','C','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('11','Byggnader och mark','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1110','Byggnader','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1119','Ack avskrivn byggnader','A','','C','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1130','Mark','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1140','Tomter, markomr obebyggda','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1150','Markanläggningar','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1159','Ack avskrivn markanläggn','A','','C','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1190','Övriga byggnader och mark','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('12','Maskiner och inventarier','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1230','Installationer','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1238','Ack nedskrivn installationer','A','','C','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1239','Ack avskrivn installationer','A','','C','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1250','Datorer','A','','A','IC');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1259','Ack avskrivn datorer','A','','C','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('13','Finansiella anläggningstillgångar','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1370','Uppskjuten skattefordran','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1380','Långfristiga fordringar','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1400','Fordran hos EFS Gafsele','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1405','Fordran hos EFS Hälla','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('15','Kundfordringar','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1500','Kundfordringar','A','','A','AR');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('16','Övriga kortfristiga fordringar','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1600','Övr kortfristiga fordr','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1710','Förutbetalda hyror','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1730','Förutbet försäkringspremier','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1740','Förutbet ränteutgifter','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1750','Upplupna hyresinkomster','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1760','Upplupna inkomsträntor','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1790','Övr interimsfordringar','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('19','Kassa och Bank','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1910','Kassa','A','','A','AR_paid:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1920','Postgiro','A','','A','AR_paid:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1930','Checkräkningskonto','A','','A','AR_paid:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1940','Övriga bankkonto','A','','A','AR_paid:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1941','Nordea värdepappersfond','A','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('1942','Nordea girokapitalkonto','A','','A','AR_paid:AP_paid');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2','Eget kapital och skulder','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('20','Eget kapital','H','','A','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2000','Eget kapital EFS Åsele','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2005','Eget kapital EFS Gafsele','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2010','Eget kapital EFS Hälla','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2070','Ändamålsbestämda medel','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2091','Balanserad vinst/förlust','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2098','Vinst/förlust föreg år','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2099','Redovisat resultat','A','','Q','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('22','Avsättningar','H','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2250','Avsättning för skatter','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2290','Övriga avsättningar','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('23','Skulder','H','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2300','Skuld till EFS Gafsele','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2310','Skuld till EFS Hälla','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2320','Skuld till fam Norlin','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2330','Checkräkningskredit','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2399','Övr långfristiga skulder','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2440','Leverantörsskulder','A','','L','AP');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2499','Övr kortfristiga skulder','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2960','Upplupna utgiftsräntor','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2971','Förutbetalda hyresintäkter','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2972','Förutbetalda medlemsavgifter','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2979','Övriga förutbetalda intäkter','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2990','Övr interimsskulder','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('2999','Övr uppl kostn/förutbet intäkter','A','','L','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3','Intäkter','H','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('30','Allmänna gåvor','H','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3000','Gåvor via konto','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3005','Minnesgåvor','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3010','Gudstjänstkollekter','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3015','Fika/kaffe/fester - gåvor','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('31','Öronmärkta gåvor','H','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3100','Öronmärkta gåvor','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3101','Gåvor barnarbete','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3102','Gåvor körsång','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3103','Gåvor bönegrupper','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3104','Gåvor Alfa-grupper','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3105','Övrigt lokalt arbete','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3106','Gåvor till fastighet mm','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3109','Gåvor Åsele allkristna gemenskap','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3110','Gåvor EFS Västerbotten','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3111','Gåvor distriktskonferens','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3112','Gåvor Scoutverksamhet','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3120','Gåvor EFS riks','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3121','Gåvor EFS riks konferens','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3122','Gåvor EFS Inre mission','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3123','Gåvor EFS Yttre mission','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3130','Gåvor Barn i alla länder','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3131','Gåvor Johannelundsinsamling','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3132','Gåvor Påskinsamling','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3133','Gåvor Flodvågens offer','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('33','Försäljningsintäkter','H','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3300','Försäljning bokbordet','A','','I','IC_sale');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3350','Försäljning fika mm','A','','I','IC_sale');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('34','Medlemsavgifter','H','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3400','Medlemsavgifter','A','','I','IC_income');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3405','Medlemsavgifter Solglimten','A','','I','IC_income');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('345','Hyresintäkter','H','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3450','Hyresintäkter, hyreskontrakt','A','','I','IC_income');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3460','Hyresintäkter, enstaka tillfälle','A','','I','IC_income');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3470','Hyresint Ersättning telefonkostnad','A','','I','IC_income');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('35','Bidrag','H','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3510','Erhållna statliga bidrag','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3520','Erhållna kommunala bidrag','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3530','Bidrag Svenska kyrkan','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3590','Övriga erhållna bidrag','A','','I','AR_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('36','Övriga intäkter','H','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3690','Övriga sidointäker','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3731','Kassarabatter','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3740','Öresutjämning','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3960','Valuta kursvinst','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3972','Vinst avyttr fastigheter','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3973','Vinst avyttr maskiner/inv','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3990','Övr ersättn och intäker','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('3994','Försäkringsersättningar','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4','Utgifter','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4000','Kostnad för predikant','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4050','Reskostnader för predikant','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('41','Utgifter öronmärkta gåvor','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4100','Kostnad öronmärkta gåvor','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4101','Kostnad barnarbete','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4102','Kostnad körer','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4103','Kostnad bönegrupper','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4104','Kostnad Alfa','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4105','Kostnad Övrigt lokalt arbete','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4106','Kostnad Fastighet (särskilt)','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4107','Kostnad scouting barnarbete','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4109','Åsele allkristna gemenskap','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4110','EFS Västerbotten','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4111','distriktskonferens','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4120','EFS riks','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4121','EFS riks konferensinsamling','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4122','EFS inre mission','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4123','EFS yttre mission','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4130','Barn i alla länder','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4131','Johannelundinsamling','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4132','Påskinsamling','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4133','Till Flodvågens offer','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('43','Inköpskostnader mm','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4300','Inköp bokbord','A','','E','IC_cogs');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4350','Inköp matr fika mm','A','','E','IC_cogs');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4400','Pren Vårt budskap (distr tidning)','A','','E','IC_expense');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4600','Inhyrda predikanter/föreläsare','A','','E','AP_amount');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4700','Tidningar, facklitteratur','A','','E','IC_expense');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('4900','Föreningsavgifter','A','','E','IC_expense');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('50','Lokalkostnader hyrd lokal','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5010','Lokalhyra','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5020','El','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5030','Värme hyrd lokal','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5050','Lokaltillbehör hyrd lokal','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5060','Städning, renhållning hyrd lokal','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5070','Reparationer hyrd lokal','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5090','Övr kostnader hyrd lokal','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('51','Lokalkostnader egen lokal','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5120','Belysning','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5130','Värme','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5132','Sotning','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5140','Vatten och avlopp','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5160','Renhålln och städning','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5170','Rep och underhåll fastighet','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5191','Fastighetsskatt','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5192','Försäkringsprem fastighet','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5193','Fastighetsskötsel och förvaltning','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5199','Övr fastighetskostnader','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('52','Övriga kostnader','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5210','Hyra arbetsmaskiner','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5220','Hyra inventarier','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5290','Övr hyreskostn anl tillg','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5390','Övriga bränslen','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5410','Förbrukningsinventarier','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5460','Förbrukningsmaterial','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5480','Arbetskläder o skyddsmtrl','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5500','Reparation och underhåll','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5710','Frakt och transport','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5800','Resekostnader','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5910','Annonsering','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5930','Reklamtrycksaker','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('5990','Övrig reklam','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6110','Kontorsmaterial','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6150','Trycksaker','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6210','Telefon','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6250','Porto','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6310','Försäkringar','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6320','Självrisker','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6340','Lämnade skadestånd','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('64','Förvaltningskostnader','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6490','Övr förvaltningskostnader','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6530','Redovisningstjänster','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6540','IT-tjänster','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6550','Konsultarvoden','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('65','Bankkostnader','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6570','Bankkostnader, Nordea','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6571','Bankkostnader, Postgirot','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6572','Bankkostnader, Bankgiro','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6573','Bankkostnader, Föreningssparbank','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('658','Främmande tjänster','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6580','Advokatkostnader','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('6590','Övr främmande tjänster','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7','Avskrivningar och engångskostn','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7780','Avskrivningar enligt plan','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7811','Avskrivningar balanserade utgifter','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7820','Avskrivningar byggnader/mark','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7821','Avskrivn byggnader','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7822','Avskrivn byggnadsinv','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7824','Avskrivn markanläggn','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7829','Avskrivningar övr byggnader','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7832','Avskrivn inventarier','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7833','Avskrivningar installationer','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7835','Avskrivningar datorer','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7921','Kostn av engångskaraktär ','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('7960','Valutakursförlust','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('8','Financiella intäkter o kostnader','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('83','Ränteintäkter','H','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('8300','Ränteintäkter ','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('8390','Övr finansiella intäkter','A','','I','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('84','Räntekostnader','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('8400','Räntekostnader','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('8490','Övr finansiella kostnader','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('891','Skatter','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('8910','Årets skattekostnad','A','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('899','Redovisat resultat','H','','E','');
insert into chart (accno,description,charttype,gifi_accno,category,link) values ('8999','Redovisat resultat','A','','E','');
--
INSERT INTO defaults (setting_key, value) VALUES ('inventory_accno_id', (select id from chart where accno ='1130'));

 INSERT INTO defaults (setting_key, value) VALUES ('income_accno_id', (select id from chart where accno = '3400'));

 INSERT INTO defaults (setting_key, value) VALUES ('expense_accno_id', (select id from chart where accno = '4400'));

 INSERT INTO defaults (setting_key, value) VALUES ('fxgain_accno_id', (select id from chart where accno = '3960'));

 INSERT INTO defaults (setting_key, value) VALUES ('fxloss_accno_id', (select id from chart where accno = '7960'));

 INSERT INTO defaults (setting_key, value) VALUES ('curr', 'SEK:EUR:USD');

 INSERT INTO defaults (setting_key, value) VALUES ('weightunit', 'kg');

commit;
