begin;
-- AFIP Argentina
-- CODIGO ACTIVIDADES 3 DIGITOS (SIC)
INSERT INTO sic (code, description) VALUES ('001', 'Cultivos agrícolas');
INSERT INTO sic (code, description) VALUES ('002', 'Cría de animales');
INSERT INTO sic (code, description) VALUES ('003', 'Servicios agrícolas y pecuarios, excepto los veterinarios');
INSERT INTO sic (code, description) VALUES ('004', 'Caza  y captura de animales vivos, repoblación  de animales de caza y servicios conexos');
INSERT INTO sic (code, description) VALUES ('005', 'Silvicultura, extracción de madera y servicios conexos');
INSERT INTO sic (code, description) VALUES ('006', 'Pesca y servicios conexos');
INSERT INTO sic (code, description) VALUES ('007', 'Extracción y aglomeración de carbón');
INSERT INTO sic (code, description) VALUES ('008', 'Extracción y aglomeración de lignito');
INSERT INTO sic (code, description) VALUES ('009', 'Extracción y aglomeración de turba');
INSERT INTO sic (code, description) VALUES ('010', 'Extracción de petróleo crudo y gas natural');
INSERT INTO sic (code, description) VALUES ('011', 'Actividades  de servicios relacionadas con la extracción de petróleo y gas, excepto las actividades de prospección');
INSERT INTO sic (code, description) VALUES ('012', 'Extracción de minerales y concentrados de uranio y torio');
INSERT INTO sic (code, description) VALUES ('013', 'Extracción de minerales de hierro');
INSERT INTO sic (code, description) VALUES ('014', 'Extracción de minerales metalíferos no ferrosos, excepto minerales de uranio y torio');
INSERT INTO sic (code, description) VALUES ('015', 'Extracción de piedra, arena y arcillas');
INSERT INTO sic (code, description) VALUES ('016', 'Explotación de minas y canteras n.c.p.');
INSERT INTO sic (code, description) VALUES ('017', 'Producción y procesamiento de carne, pescado, frutas, legumbres, hortalizas, aceites y grasas');
INSERT INTO sic (code, description) VALUES ('018', 'Elaboración de productos lácteos');
INSERT INTO sic (code, description) VALUES ('019', 'Elaboración de productos de molinería, almidones y productos derivados del almidón y de alimentos preparados para animales');
INSERT INTO sic (code, description) VALUES ('020', 'Elaboración de productos alimenticios n.c.p.');
INSERT INTO sic (code, description) VALUES ('021', 'Elaboración de bebidas');
INSERT INTO sic (code, description) VALUES ('022', 'Elaboración de productos de tabaco');
INSERT INTO sic (code, description) VALUES ('023', 'Fabricación  de hilados y  tejidos, acabado de productos textiles');
INSERT INTO sic (code, description) VALUES ('024', 'Fabricación de productos textiles n.c.p.');
INSERT INTO sic (code, description) VALUES ('025', 'Fabricación de tejidos de punto y artículos de punto y ganchillo');
INSERT INTO sic (code, description) VALUES ('026', 'Confección de prendas de vestir, excepto prendas de piel');
INSERT INTO sic (code, description) VALUES ('027', 'Curtido y terminación de cueros; fabricación de artículos de marroquinería y talabartería');
INSERT INTO sic (code, description) VALUES ('028', 'Fabricación de calzado y de sus partes');
INSERT INTO sic (code, description) VALUES ('029', 'Aserrado y cepillado de madera');
INSERT INTO sic (code, description) VALUES ('030', 'Fabricación de productos de madera, corcho, paja y materiales trenzables');
INSERT INTO sic (code, description) VALUES ('031', 'Fabricación de papel y de productos de papel');
INSERT INTO sic (code, description) VALUES ('032', 'Edición');
INSERT INTO sic (code, description) VALUES ('033', 'Impresión y servicios conexos');
INSERT INTO sic (code, description) VALUES ('034', 'Reproducción de grabaciones');
INSERT INTO sic (code, description) VALUES ('035', 'Fabricación de productos de hornos de coque');
INSERT INTO sic (code, description) VALUES ('036', 'Fabricación de productos de la refinación del petróleo');
INSERT INTO sic (code, description) VALUES ('037', 'Elaboración de combustible nuclear');
INSERT INTO sic (code, description) VALUES ('038', 'Fabricación de sustancias químicas básicas');
INSERT INTO sic (code, description) VALUES ('039', 'Fabricación de productos químicos n.c.p.');
INSERT INTO sic (code, description) VALUES ('040', 'Fabricación de fibras manufacturadas');
INSERT INTO sic (code, description) VALUES ('041', 'Fabricación de productos de caucho');
INSERT INTO sic (code, description) VALUES ('042', 'Fabricación de productos de plástico');
INSERT INTO sic (code, description) VALUES ('043', 'Fabricación de vidrio y productos de vidrio');
INSERT INTO sic (code, description) VALUES ('044', 'Fabricación de productos minerales no metálicos n.c.p.');
INSERT INTO sic (code, description) VALUES ('045', 'Industrias básicas de hierro y acero');
INSERT INTO sic (code, description) VALUES ('046', 'Fabricación de productos primarios de metales preciosos y metales no ferrosos');
INSERT INTO sic (code, description) VALUES ('047', 'Fundición de metales');
INSERT INTO sic (code, description) VALUES ('048', 'Fabricación de productos metálicos para uso estructural, tanques, depósitos y generadores de vapor');
INSERT INTO sic (code, description) VALUES ('049', 'Fabricación de productos elaborados de metal n.c.p.; servicios de trabajo de metales');
INSERT INTO sic (code, description) VALUES ('050', 'Fabricación de maquinaria de uso general');
INSERT INTO sic (code, description) VALUES ('051', 'Fabricación de maquinaria de uso especial');
INSERT INTO sic (code, description) VALUES ('052', 'Fabricación de aparatos de uso doméstico n.c.p.');
INSERT INTO sic (code, description) VALUES ('053', 'Fabricación de maquinaria de oficina, contabilidad e informática');
INSERT INTO sic (code, description) VALUES ('054', 'Fabricación de motores, generadores y transformadores eléctricos');
INSERT INTO sic (code, description) VALUES ('055', 'Fabricación de aparatos de distribución y control de la energía eléctrica');
INSERT INTO sic (code, description) VALUES ('056', 'Fabricación de hilos y cables aislados');
INSERT INTO sic (code, description) VALUES ('057', 'Fabricación de acumuladores y de pilas y baterías primarias');
INSERT INTO sic (code, description) VALUES ('058', 'Fabricación de lámparas eléctricas y equipo de iluminación');
INSERT INTO sic (code, description) VALUES ('059', 'Fabricación  de equipo eléctrico n.c.p.');
INSERT INTO sic (code, description) VALUES ('060', 'Fabricación de tubos, válvulas  y otros  componentes electrónicos');
INSERT INTO sic (code, description) VALUES ('061', 'Fabricación de transmisores de radio y televisión y de aparatos para telefonía y telegrafía con hilos');
INSERT INTO sic (code, description) VALUES ('062', 'Fabricación de receptores de radio y televisión, aparatos de grabación y reproducción de sonido y video, y productos conexos');
INSERT INTO sic (code, description) VALUES ('063', 'Fabricación de aparatos e instrumentos médicos y de aparatos para medir, verificar, ensayar, navegar y otros fines, excepto instrumentos de óptica');
INSERT INTO sic (code, description) VALUES ('064', 'Fabricación de instrumentos de óptica y equipo fotográfico');
INSERT INTO sic (code, description) VALUES ('065', 'Fabricación de relojes');
INSERT INTO sic (code, description) VALUES ('066', 'Fabricación de vehículos automotores');
INSERT INTO sic (code, description) VALUES ('067', 'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques');
INSERT INTO sic (code, description) VALUES ('068', 'Fabricación de partes; piezas y accesorios para vehículos automotores y sus motores');
INSERT INTO sic (code, description) VALUES ('069', 'Construcción y reparación de buques y embarcaciones n.c.p.');
INSERT INTO sic (code, description) VALUES ('070', 'Fabricación de locomotoras y de material rodante para ferrocarriles y tranvías');
INSERT INTO sic (code, description) VALUES ('071', 'Fabricación y reparación de aeronaves');
INSERT INTO sic (code, description) VALUES ('072', 'Fabricación de equipo de transporte n.c.p.');
INSERT INTO sic (code, description) VALUES ('073', 'Fabricación de muebles y colchones');
INSERT INTO sic (code, description) VALUES ('074', 'Industrias manufactureras n.c.p.');
INSERT INTO sic (code, description) VALUES ('075', 'Reciclamiento de desperdicios y desechos metálicos');
INSERT INTO sic (code, description) VALUES ('076', 'Reciclamiento de desperdicios y desechos no metálicos');
INSERT INTO sic (code, description) VALUES ('077', 'Generación, transporte y distribución de energía eléctrica');
INSERT INTO sic (code, description) VALUES ('078', 'Fabricación de gas y distribución de combustibles gaseosos por tuberías');
INSERT INTO sic (code, description) VALUES ('079', 'Suministro de vapor y agua caliente');
INSERT INTO sic (code, description) VALUES ('080', 'Captación, depuración y distribución de agua');
INSERT INTO sic (code, description) VALUES ('081', 'Preparación de terrenos para obras');
INSERT INTO sic (code, description) VALUES ('082', 'Construcción de edificios y sus partes y obras de ingeniería civil');
INSERT INTO sic (code, description) VALUES ('083', 'Instalaciones para edificios y obras de ingeniería civil');
INSERT INTO sic (code, description) VALUES ('084', 'Terminación de edificios y obras de ingeniería civil');
INSERT INTO sic (code, description) VALUES ('085', 'Alquiler de equipo de construcción o demolición dotado de operarios');
INSERT INTO sic (code, description) VALUES ('086', 'Venta de vehículos automotores, excepto motocicletas');
INSERT INTO sic (code, description) VALUES ('087', 'Mantenimiento y reparación de vehículos automotores, excepto motocicletas');
INSERT INTO sic (code, description) VALUES ('088', ' Venta de partes, piezas y accesorios de vehículos automotores');
INSERT INTO sic (code, description) VALUES ('089', 'Venta, mantenimiento y reparación de motocicletas y de sus partes, piezas y accesorios');
INSERT INTO sic (code, description) VALUES ('090', 'Venta al por menor de combustible para vehículos automotores y motocicletas');
INSERT INTO sic (code, description) VALUES ('091', 'Venta al por mayor en comisión o consignación');
INSERT INTO sic (code, description) VALUES ('092', 'Venta al por mayor de materias primas agropecuarias, de animales vivos, alimentos, bebidas y tabaco, excepto en comisión o consignación');
INSERT INTO sic (code, description) VALUES ('093', 'Venta al por mayor de artículos de uso doméstico y/o personal');
INSERT INTO sic (code, description) VALUES ('094', 'Venta al por mayor de productos intermedios, desperdicios y desechos no agropecuarios');
INSERT INTO sic (code, description) VALUES ('095', 'Venta al por mayor de máquinas, equipo y materiales conexos');
INSERT INTO sic (code, description) VALUES ('096', 'Venta al por mayor de mercancías n.c.p.');
INSERT INTO sic (code, description) VALUES ('097', 'Venta al por menor excepto la especializada');
INSERT INTO sic (code, description) VALUES ('098', 'Venta al por menor de productos alimentarios, bebidas y tabaco en comercios especializados');
INSERT INTO sic (code, description) VALUES ('099', 'Venta al por menor de productos n.c.p. excepto los usados, en comercios especializados');
INSERT INTO sic (code, description) VALUES ('100', 'Venta al por menor de artículos usados excluidos automotores y motocicletas');
INSERT INTO sic (code, description) VALUES ('101', 'Venta al por menor no realizada en establecimientos');
INSERT INTO sic (code, description) VALUES ('102', 'Reparación de efectos personales y enseres domésticos');
INSERT INTO sic (code, description) VALUES ('103', 'Servicios de alojamiento en hoteles, campamentos y otros tipos de hospedaje temporal');
INSERT INTO sic (code, description) VALUES ('104', 'Servicios de expendio de comidas y bebidas');
INSERT INTO sic (code, description) VALUES ('105', 'Servicio de transporte ferroviario');
INSERT INTO sic (code, description) VALUES ('106', 'Servicio de transporte automotor');
INSERT INTO sic (code, description) VALUES ('107', 'Servicio de transporte por tuberías');
INSERT INTO sic (code, description) VALUES ('108', 'Servicio de transporte marítimo');
INSERT INTO sic (code, description) VALUES ('109', 'Servicio de transporte fluvial');
INSERT INTO sic (code, description) VALUES ('110', 'Servicio de transporte aéreo de cargas');
INSERT INTO sic (code, description) VALUES ('111', 'Servicio de transporte aéreo de pasajeros');
INSERT INTO sic (code, description) VALUES ('112', 'Servicios de manipulación de carga');
INSERT INTO sic (code, description) VALUES ('113', 'Servicios de almacenamiento y depósito');
INSERT INTO sic (code, description) VALUES ('114', 'Servicios complementarios para el transporte');
INSERT INTO sic (code, description) VALUES ('115', 'Servicios de agencias de viaje y otras actividades complementarias de apoyo turístico');
INSERT INTO sic (code, description) VALUES ('116', 'Servicios de gestión y logística para el transporte de mercaderías');
INSERT INTO sic (code, description) VALUES ('117', 'Servicios de correos');
INSERT INTO sic (code, description) VALUES ('118', 'Servicios de telecomunicaciones');
INSERT INTO sic (code, description) VALUES ('119', 'Intermediación monetaria y financiera de la banca central');
INSERT INTO sic (code, description) VALUES ('120', 'Intermediación monetaria y financiera de las entidades financieras bancarias y no bancarias');
INSERT INTO sic (code, description) VALUES ('121', 'Servicios financieros excepto los de la banca central y las entidades financieras');
INSERT INTO sic (code, description) VALUES ('122', 'Servicios de seguros');
INSERT INTO sic (code, description) VALUES ('123', 'Servicios de administración de fondos de jubilaciones y pensiones');
INSERT INTO sic (code, description) VALUES ('124', 'Servicios auxiliares a la actividad financiera, excepto a los servicios de seguros y de administración de fondos de jubilaciones y pensiones');
INSERT INTO sic (code, description) VALUES ('125', 'Servicios auxiliares a los servicios de seguros y de administración de fondos de jubilaciones y pensiones');
INSERT INTO sic (code, description) VALUES ('126', 'Servicios inmobiliarios realizados por cuenta propia, con bienes propios o arrendados');
INSERT INTO sic (code, description) VALUES ('127', 'Servicios inmobiliarios realizados a cambio de una retribución o por contrata');
INSERT INTO sic (code, description) VALUES ('128', 'Alquiler de equipo de transporte');
INSERT INTO sic (code, description) VALUES ('129', 'Alquiler de maquinaria y equipo n.c.p.');
INSERT INTO sic (code, description) VALUES ('130', 'Alquiler de efectos personales y enseres domésticos n.c.p.');
INSERT INTO sic (code, description) VALUES ('131', 'Servicios de consultores en equipo de informática');
INSERT INTO sic (code, description) VALUES ('132', 'Servicios de consultores en informática y suministros de programas de informática');
INSERT INTO sic (code, description) VALUES ('133', 'Procesamiento de datos');
INSERT INTO sic (code, description) VALUES ('134', 'Servicios relacionados con bases de datos');
INSERT INTO sic (code, description) VALUES ('135', 'Mantenimiento y reparación de maquinaria de oficina, contabilidad e informática');
INSERT INTO sic (code, description) VALUES ('136', 'Actividades de informática n.c.p.');
INSERT INTO sic (code, description) VALUES ('137', 'Investigación  y desarrollo experimental en el campo de la ingeniería y de las ciencias exactas y naturales');
INSERT INTO sic (code, description) VALUES ('138', 'Investigación  y desarrollo experimental en el campo de las ciencias sociales y las humanidades');
INSERT INTO sic (code, description) VALUES ('139', 'Servicios jurídicos y de contabilidad, teneduría de libros y auditoría; asesoramiento en materia de impuestos; estudios de mercados y realización de encuestas de opinión pública; asesoramiento empresarial y en materia de gestión');
INSERT INTO sic (code, description) VALUES ('140', 'Servicios de arquitectura e ingeniería y servicios técnicos n.c.p.');
INSERT INTO sic (code, description) VALUES ('141', 'Servicios de publicidad');
INSERT INTO sic (code, description) VALUES ('142', 'Servicios empresariales n.c.p.');
INSERT INTO sic (code, description) VALUES ('143', 'Servicios de la administración pública');
INSERT INTO sic (code, description) VALUES ('144', 'Prestación pública de servicios a la comunidad en general');
INSERT INTO sic (code, description) VALUES ('145', 'Servicios de la seguridad social obligatoria');
INSERT INTO sic (code, description) VALUES ('146', 'Enseñanza inicial y primaria');
INSERT INTO sic (code, description) VALUES ('147', 'Enseñanza secundaria');
INSERT INTO sic (code, description) VALUES ('148', 'Enseñanza superior y formación de postgrado');
INSERT INTO sic (code, description) VALUES ('149', 'Enseñanza para adultos y  servicios de enseñanza n.c.p.');
INSERT INTO sic (code, description) VALUES ('150', 'Servicios relacionados con la salud humana');
INSERT INTO sic (code, description) VALUES ('151', 'Servicios veterinarios');
INSERT INTO sic (code, description) VALUES ('152', 'Servicios sociales');
INSERT INTO sic (code, description) VALUES ('153', 'Eliminación de desperdicios y aguas residuales, saneamiento y servicios similares');
INSERT INTO sic (code, description) VALUES ('154', 'Servicios de organizaciones empresariales, profesionales y de empleadores');
INSERT INTO sic (code, description) VALUES ('155', 'Servicios de sindicatos');
INSERT INTO sic (code, description) VALUES ('156', 'Servicios de asociaciones n.c.p.');
INSERT INTO sic (code, description) VALUES ('157', 'Servicios de cinematografía, radio y televisión y servicios de espectáculos artísticos y de diversión n.c.p.');
INSERT INTO sic (code, description) VALUES ('158', 'Servicios de agencias de noticias');
INSERT INTO sic (code, description) VALUES ('159', 'Servicios de bibliotecas, archivos y museos y  servicios culturales n.c.p.');
INSERT INTO sic (code, description) VALUES ('160', 'Servicios para la práctica deportiva y de entretenimiento n.c.p.');
INSERT INTO sic (code, description) VALUES ('161', 'Servicios n.c.p.');
INSERT INTO sic (code, description) VALUES ('162', 'Servicios de hogares privados que contratan servicio doméstico');
INSERT INTO sic (code, description) VALUES ('163', 'Servicios de organizaciones y órganos extraterritoriales');
commit;
