begin;
--
-- Plan único de Cuentas de Colombia, elaborado por Rene Real Hernandez (SDI S.A.), Francico Padilla (SDI S.A.),
-- Silfredo Godoy Chavez (CaribeNet S.A.),
-- Lourdes Mejía Martinez (CaribeNet S.A.) y Dirk Enrique Seiffert (CaribeNet S.A.)
-- Si quieres aportar: Contactenos www.caribenet.com - info@caribenet.com
--

SELECT account_heading_save(NULL, '1', 'ACTIVO', NULL);
SELECT account_heading_save(NULL, '11', 'ACTIVO DISPONIBLE', NULL);
SELECT account_heading_save(NULL, '1105', 'CAJA', NULL);
SELECT account_heading_save(NULL, '110505', 'CAJA GENERAL', NULL);
SELECT account_heading_save(NULL, '110510', 'CAJAS MENORES', NULL);
SELECT account_heading_save(NULL, '1110', 'BANCOS', NULL);
SELECT account_heading_save(NULL, '111005', 'BANCOS MONEDA NACIONAL', NULL);
SELECT account_heading_save(NULL, '1120', 'CUENTAS DE AHORRO', NULL);
SELECT account_heading_save(NULL, '112005', 'CUENTAS DE AHORRO EN BANCOS', NULL);
SELECT account_heading_save(NULL, '12', 'INVERSIONES', NULL);
SELECT account_heading_save(NULL, '1205', 'ACCIONES', NULL);
SELECT account_heading_save(NULL, '1210', 'CUOTAS PARTES DE INTERES SOCIAL', NULL);
SELECT account_heading_save(NULL, '1215', 'BONOS', NULL);
SELECT account_heading_save(NULL, '1220', 'CEDULAS', NULL);
SELECT account_heading_save(NULL, '1225', 'CERTIFICADOS', NULL);
SELECT account_heading_save(NULL, '1230', 'PAPELES COMERCIALES', NULL);
SELECT account_heading_save(NULL, '1235', 'TITULOS', NULL);
SELECT account_heading_save(NULL, '1240', 'ACEPTACIONES BANCARIAS O FINANCI', NULL);
SELECT account_heading_save(NULL, '1245', 'DERECHOS FIDUCIARIOS', NULL);
SELECT account_heading_save(NULL, '13', 'CUENTAS POR COBRAR', NULL);
SELECT account_heading_save(NULL, '1305', 'CUENTAS POR COBRAR CLIENTES', NULL);
SELECT account_heading_save(NULL, '130505', 'CLIENTES NACIONALES', NULL);
SELECT account_heading_save(NULL, '130510', 'CLIENTES DEL EXTERIOR', NULL);
SELECT account_heading_save(NULL, '1310', 'CUENTAS CORRIENTES COMERCIALES', NULL);
SELECT account_heading_save(NULL, '1330', 'ANTICIPO Y AVANCES', NULL);
SELECT account_heading_save(NULL, '133005', 'ANTICIPO A PROVEEDORES', NULL);
SELECT account_heading_save(NULL, '133010', 'ANTICIPO A CONTRATISTAS', NULL);
SELECT account_heading_save(NULL, '133015', 'ANTICIPO A TRABAJADORES', NULL);
SELECT account_heading_save(NULL, '1340', 'PROMESAS DE COMPRAVENTA', NULL);
SELECT account_heading_save(NULL, '134005', 'DE BIENES RAICES', NULL);
SELECT account__save(NULL,'1340050001','Promesas Compra Venta Bienes Rai','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '1345', 'INGRESOS POR COBRAR', NULL);
SELECT account_heading_save(NULL, '1350', 'RETENCIONES SOBRE CONTRATOS', NULL);
SELECT account_heading_save(NULL, '135005', 'DE CONTRATOS DE CONSTRUCCION', NULL);
SELECT account_heading_save(NULL, '135010', 'DE PRESTACION DE SERVICIOS', NULL);
SELECT account_heading_save(NULL, '135095', 'RETENCION SOBRE OTROS CONTRATOS', NULL);
SELECT account_heading_save(NULL, '1355', 'ANTICIPO DE IMPUESTOS', NULL);
SELECT account_heading_save(NULL, '135505', 'ANTICIPO DE IMPUESTO DE RENTA', NULL);
SELECT account__save(NULL,'1355050001','Anticipo de Impuesto de Renta','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '135510', 'ANTICIPO DE IMPTO DE IND. Y CCIO', NULL);
SELECT account__save(NULL,'1355100001','Anticipo de Industria y Comercio','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '135515', 'RETENCION EN LA FUENTE', NULL);
SELECT account__save(NULL,'1355150002','Retefuente 10% Honorarios','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1355150004','Retefuente Alquiler Bienes R. 4%','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1355150005','Retefuente Obras Civiles 1%','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1355150006','Retefuente 6% servicios','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1355150007','Retencion en la fuente 3.5%','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '135517', 'IMPUESTO A LAS VENTAS RETENIDO', NULL);
SELECT account_heading_save(NULL, '135518', 'IMPUESTO DE IND. Y CCIO RETENIDO', NULL);
SELECT account__save(NULL,'1355180001','Ica Retenido','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '135520', 'SOBRANTE EN LIQUIDACION PRIVADA', NULL);
SELECT account__save(NULL,'1355200001','Saldo a Favor en Renta','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1355200002','Sobrante en Declaracion de IVA','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '1380', 'DEUDORES VARIOS', NULL);
SELECT account_heading_save(NULL, '138020', 'CUENTAS POR COBRAR A TERCEROS', NULL);
SELECT account__save(NULL,'1380200001','Cuentas por Cobrar a Terceros','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '138095', 'OTROS DEUDORES VARIOS', NULL);
SELECT account__save(NULL,'1380950001','Deudores Varios Otros','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '1390', 'DEUDAS DE DIFICIL COBRO', NULL);
SELECT account_heading_save(NULL, '1399', 'PROVISIONES', NULL);
SELECT account_heading_save(NULL, '139905', 'PROVISION CLIENTES', NULL);
SELECT account__save(NULL,'1399050001','Provision cartera Dificil Cobro','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '14', 'INVENTARIOS', NULL);
SELECT account_heading_save(NULL, '1410', 'PRODUCTOS EN PROCESO', NULL);
SELECT account_heading_save(NULL, '141005', 'PRODUCTOS EN PROCESO', NULL);
SELECT account_heading_save(NULL, '141099', 'AJ. POR INFLACION INV. EN PROCES', NULL);
SELECT account_heading_save(NULL, '1415', 'OBRAS DE CONSTRUCCION EN CURSO', NULL);
SELECT account_heading_save(NULL, '1420', 'CONTRATOS EN EJECUCION', NULL);
SELECT account_heading_save(NULL, '142099', 'AJ.POR INFLACION CTOS EN EJECUCI', NULL);
SELECT account_heading_save(NULL, '1430', 'PRODUCTOS TERMINADOS', NULL);
SELECT account_heading_save(NULL, '143005', 'PRODUCTOS MANUFACTURADOS', NULL);
SELECT account_heading_save(NULL, '143099', 'AJ.POR INFLACION INV.PROD.TERMIN', NULL);
SELECT account_heading_save(NULL, '1435', 'MERCANCIAS NO FABRICADAS', NULL);
SELECT account_heading_save(NULL, '143505', 'MCIA NO FABRICADA POR LA EMPRESA', NULL);
SELECT account_heading_save(NULL, '143599', 'AJ.POR INFL.MCIA NO FAB.EMPRESA', NULL);
SELECT account_heading_save(NULL, '1465', 'INVENTARIOS EN TRANSITO', NULL);
SELECT account_heading_save(NULL, '146505', 'INVENTARIOS EN TRANSITO', NULL);
SELECT account_heading_save(NULL, '146599', 'AJ.POR INFLACION INV.EN TRANSITO', NULL);
SELECT account_heading_save(NULL, '15', 'PROPIEDAD PLANTA Y EQUIPO', NULL);
SELECT account_heading_save(NULL, '1504', 'TERRENOS', NULL);
SELECT account_heading_save(NULL, '1508', 'CONSTRUCCIONES EN CURSO', NULL);
SELECT account_heading_save(NULL, '1512', 'MAQUINARIA Y EQUIPO EN MONTAJE', NULL);
SELECT account_heading_save(NULL, '1516', 'CONSTRUCCIONES Y EDIFICACIONES', NULL);
SELECT account_heading_save(NULL, '151610', 'OFICINAS', NULL);
SELECT account_heading_save(NULL, '151699', 'AJUSTES POR INFLACION CONSTRUCCI', NULL);
SELECT account_heading_save(NULL, '15169910', 'AJ. INFL. OFICINAS - LOCALES', NULL);
SELECT account_heading_save(NULL, '1520', 'MAQUINARIA Y EQUIPO', NULL);
SELECT account_heading_save(NULL, '152001', 'CONTRATOS YOPAL', NULL);
SELECT account_heading_save(NULL, '152002', 'BODEGA', NULL);
SELECT account_heading_save(NULL, '152099', 'AJUSTES POR INFLACION', NULL);
SELECT account_heading_save(NULL, '15209902', 'AJUSTES POR INFLACION EQ.BODEGA', NULL);
SELECT account_heading_save(NULL, '1524', 'EQUIPOS DE OFICINA', NULL);
SELECT account_heading_save(NULL, '152405', 'MUEBLES Y ENSERES', NULL);
SELECT account_heading_save(NULL, '152410', 'EQUIPOS', NULL);
SELECT account_heading_save(NULL, '152499', 'AJUSTES POR INFLACION', NULL);
SELECT account_heading_save(NULL, '15249910', 'AJUSTES POR INFLACION', NULL);
SELECT account_heading_save(NULL, '1528', 'EQUIPOS DE COMPUTACION Y COMUNIC', NULL);
SELECT account_heading_save(NULL, '152805', 'EQUIPOS DE PROCESAMIENTO DE DATO', NULL);
SELECT account__save(NULL,'1528050001','Cinco Computadores','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '152899', 'AJUSTES POR INFLACION', NULL);
SELECT account_heading_save(NULL, '15289905', 'AJ. INFL. EQ. PROCESAMIENTO DATO', NULL);
SELECT account__save(NULL,'1528990501','Aj. por Inflac. Cinco Computador','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '1540', 'FLOTA Y EQUIPO DE TRANSPORTE', NULL);
SELECT account_heading_save(NULL, '154005', 'AUTOS, CAMIONETAS Y CAMPEROS', NULL);
SELECT account_heading_save(NULL, '154099', 'AJUSTES POR INFLACION', NULL);
SELECT account_heading_save(NULL, '15409905', 'AJ. INFL. AUTOS CAMPEROS CMIONET', NULL);
SELECT account__save(NULL,'1540990501','Aj. Infl. Autos y Camperos','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '1592', 'DEPRECIACION ACUMULADA', NULL);
SELECT account_heading_save(NULL, '159205', 'DEPREC.DE CONSTRUCCIONES Y EDIFI', NULL);
SELECT account_heading_save(NULL, '159210', 'DEPREC. MAQUINARIA Y EQUIPO', NULL);
SELECT account_heading_save(NULL, '159215', 'DEPRECIACION EQUIPO DE OFICINA', NULL);
SELECT account_heading_save(NULL, '159220', 'DEPRECIACION EQ. COMPUTACION Y C', NULL);
SELECT account__save(NULL,'1592200001','Depreciacion Cinco Computadores','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '159235', 'DEPRECIACION FLOTA DE TRANSPORTE', NULL);
SELECT account_heading_save(NULL, '159299', 'AJUSTES POR INFLACION', NULL);
SELECT account__save(NULL,'1592990005','Aj.Infl. Construc. y Edificacion','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1592990010','Aj.Infl. Maquinaria y Equipo','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1592990015','Aj. Infl. Equipos de Oficina','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1592990020','Aj. Infl. Eq. Computac. y Comuni','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1592990035','Aj. Infl. Flota y Eq. de transpo','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '19', 'VALORIZACIONES', NULL);
SELECT account_heading_save(NULL, '1905', 'VALORIZACIONES DE INVERSIONES', NULL);
SELECT account_heading_save(NULL, '1910', 'DE PROPIEDAD PLANTA Y EQUIPOS', NULL);
SELECT account_heading_save(NULL, '191008', 'DE CONSTRUCCIONES Y EDIFICACIONE', NULL);
SELECT account_heading_save(NULL, '1995', 'VALORIZACION DE OTROS ACTIVOS', NULL);
SELECT account_heading_save(NULL, '2', 'PASIVOS', NULL);
SELECT account_heading_save(NULL, '21', 'OBLIGACIONES FINANCIERAS', NULL);
SELECT account_heading_save(NULL, '2105', 'BANCOS NACIONALES', NULL);
SELECT account_heading_save(NULL, '210505', 'SOBREGIROS', NULL);
SELECT account__save(NULL,'2105050001','Sobregiros Bancarios','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '210510', 'PAGARES', NULL);
SELECT account__save(NULL,'2105100001','Pagares','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '2130', 'ENTIDADES FINANCIERAS DEL EXTERI', NULL);
SELECT account_heading_save(NULL, '2145', 'OBLIGACIONES GUBERNAMENTALES', NULL);
SELECT account_heading_save(NULL, '2195', 'OTRAS OBLIGACIONES', NULL);
SELECT account_heading_save(NULL, '219505', 'OBLIGACIONES CON PARTICULARES', NULL);
SELECT account__save(NULL,'2195050001','Otras obligaciones con Particula','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '219510', 'OBLIGACIONES COMPA?IAS VINCULADA', NULL);
SELECT account_heading_save(NULL, '22', 'PROVEEDORES', NULL);
SELECT account_heading_save(NULL, '2205', 'PROVEEDORES NACIONALES', NULL);
SELECT account_heading_save(NULL, '220505', 'PROVEEDORES NACIONALES', NULL);
SELECT account_heading_save(NULL, '23', 'CUENTAS POR PAGAR', NULL);
SELECT account_heading_save(NULL, '2320', 'CUENTAS POR PAGAR A CONTRATISTAS', NULL);
SELECT account_heading_save(NULL, '232005', 'CUENTAS POR PAGAR A CONTRATISTAS', NULL);
SELECT account_heading_save(NULL, '2335', 'COSTOS Y GASTOS POR PAGAR', NULL);
SELECT account_heading_save(NULL, '233505', 'GASTOS FINANCIEROS', NULL);
SELECT account_heading_save(NULL, '233510', 'GASTOS LEGALES', NULL);
SELECT account_heading_save(NULL, '233515', 'LIBROS SUSCRIPCIONES PERIODICOS', NULL);
SELECT account_heading_save(NULL, '233520', 'COMISIONES', NULL);
SELECT account_heading_save(NULL, '233525', 'HONORARIOS', NULL);
SELECT account_heading_save(NULL, '233530', 'SERVICIOS TECNICOS', NULL);
SELECT account_heading_save(NULL, '233535', 'SERVICIOS DE MANTENIMIENTO', NULL);
SELECT account_heading_save(NULL, '233540', 'ARRENDAMIENTOS', NULL);
SELECT account_heading_save(NULL, '233545', 'TRANSPORTES FLETES Y ACARREOS', NULL);
SELECT account_heading_save(NULL, '233550', 'SERVICIOS PUBLICOS', NULL);
SELECT account_heading_save(NULL, '233555', 'SEGUROS', NULL);
SELECT account_heading_save(NULL, '233560', 'GASTOS DE VIAJE', NULL);
SELECT account_heading_save(NULL, '233565', 'GASTOS DE REPRESENTACION Y RELAC', NULL);
SELECT account_heading_save(NULL, '233570', 'SERVICIOS ADUANEROS', NULL);
SELECT account_heading_save(NULL, '233595', 'OTROS COSTOS Y GASTOS POR PAGAR', NULL);
SELECT account_heading_save(NULL, '2355', 'DEUDAS CON SOCIOS Y ACCIONISTAS', NULL);
SELECT account_heading_save(NULL, '235505', 'ACCIONISTAS', NULL);
SELECT account_heading_save(NULL, '235510', 'SOCIOS', NULL);
SELECT account_heading_save(NULL, '2360', 'DIVIDENDOS O PARTICIPACION POR P', NULL);
SELECT account_heading_save(NULL, '236005', 'DIVIDENDOS POR PAGAR', NULL);
SELECT account_heading_save(NULL, '236010', 'PARTICIPACIONES POR PAGAR', NULL);
SELECT account_heading_save(NULL, '2365', 'RETENCION EN LA FUENTE', NULL);
SELECT account_heading_save(NULL, '236505', 'SALARIOS Y PAGOS LABORALES', NULL);
SELECT account_heading_save(NULL, '236510', 'DIVIDENDO Y/O PARTICIPACIONES', NULL);
SELECT account_heading_save(NULL, '236515', 'HONORARIOS', NULL);
SELECT account_heading_save(NULL, '236520', 'COMISIONES', NULL);
SELECT account_heading_save(NULL, '236525', 'SERVICIOS', NULL);
SELECT account__save(NULL,'2365250002','Servicios Hoteleros 3.5%','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '236530', 'ARRENDAMIENTOS', NULL);
SELECT account__save(NULL,'2365300002','Arriendo Inmuebles 4%','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '236535', 'RENDIMIENTOS FINANCIERSO', NULL);
SELECT account_heading_save(NULL, '236540', 'RETENCION POR COMPRAS', NULL);
SELECT account_heading_save(NULL, '2368', 'IMPTO DE IND. Y CCIO RETENIDO', NULL);
SELECT account_heading_save(NULL, '236801', 'SECTOR INDUSTRIAL', NULL);
SELECT account__save(NULL,'2368010003','Demas Activ. Industriales 7xmil','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '236802', 'SECTOR COMERCIAL', NULL);
SELECT account__save(NULL,'2368020004','Demas Activ. Comerciales 7xmil','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '236803', 'SECTOR SERVICIOS', NULL);
SELECT account__save(NULL,'2368030001','Retencin ICA 6xMil','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'2368030009','Demas Activ. Servicios 8xmil','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '2370', 'RETENCIONES Y APORTES DE NOMINA', NULL);
SELECT account_heading_save(NULL, '237005', 'APORTES A EPS', NULL);
SELECT account__save(NULL,'2370050001','Aportes a EPS','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '237006', 'APORTES A ARP', NULL);
SELECT account_heading_save(NULL, '237010', 'APORTES A IDBF, SENA Y CAJAS COM', NULL);
SELECT account_heading_save(NULL, '2380', 'ACREEDORES VARIOS', NULL);
SELECT account_heading_save(NULL, '238030', 'FONDOS DE CESANTIAS Y/O PENSION', NULL);
SELECT account_heading_save(NULL, '238095', 'VARIOS', NULL);
SELECT account_heading_save(NULL, '24', 'IMPUESTOS GRAVAMENES Y TASAS', NULL);
SELECT account_heading_save(NULL, '2404', 'IMPUESTO DE RENTA', NULL);
SELECT account_heading_save(NULL, '240405', 'VIGENCIA FISCAL CORRIENTE', NULL);
SELECT account__save(NULL,'2404050001','IMPORENTA VIGENCIA ACTUAL','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '240410', 'VIGENCIAS FISCALES ANTERIORES', NULL);
SELECT account__save(NULL,'2404100001','IMPORENTA VIGENCIA ANTERIORES','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '2408', 'IMPUESTO A LAS VENTAS POR PAGAR', NULL);
SELECT account_heading_save(NULL, '240805', 'IVA DESCONTABLE', NULL);
SELECT account_heading_save(NULL, '240810', 'IVA GENERADO EN VENTAS', NULL);
SELECT account_heading_save(NULL, '240815', 'IMPUESTOS POR PAGAR ANTERIORES', NULL);
SELECT account__save(NULL,'2408150001','ViGencia Fiscal Anterior','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '2412', 'IMPUESTO DE IND. Y COMERCIO', NULL);
SELECT account_heading_save(NULL, '241205', 'VIGENCIA FISCAL CORRIENTE', NULL);
SELECT account__save(NULL,'2412050001','ICA POR PAGAR','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '241210', 'VIGENCIAS FISCALES ANTERIORES', NULL);
SELECT account_heading_save(NULL, '25', 'OBLIGACIONES LABORALES', NULL);
SELECT account_heading_save(NULL, '2505', 'SALARIOS POR PAGAR', NULL);
SELECT account_heading_save(NULL, '250505', 'NOMINA POR PAGAR', NULL);
SELECT account_heading_save(NULL, '2510', 'CESANTIAS CONSOLIDADAS', NULL);
SELECT account_heading_save(NULL, '2515', 'INTERESES SOBRE CESANTIAS', NULL);
SELECT account_heading_save(NULL, '2520', 'PRIMA DE SERVICIOS', NULL);
SELECT account_heading_save(NULL, '2525', 'VACACIONES CONSOLIDADAS', NULL);
SELECT account_heading_save(NULL, '2530', 'PRESTACIONES EXTRALEGALES', NULL);
SELECT account_heading_save(NULL, '26', 'PASIVOS ESTIMADOS Y PROVISIONES', NULL);
SELECT account_heading_save(NULL, '2605', 'PARA COSTOS Y GASTOS', NULL);
SELECT account_heading_save(NULL, '260515', 'HONORARIOS', NULL);
SELECT account_heading_save(NULL, '260525', 'TRANSPORTES FLETES Y ACARREOS', NULL);
SELECT account_heading_save(NULL, '260530', 'GASTOS DE VIAJE', NULL);
SELECT account_heading_save(NULL, '2610', 'PARA OBLIGACIONES LABORALES', NULL);
SELECT account_heading_save(NULL, '261005', 'CESANTIAS', NULL);
SELECT account_heading_save(NULL, '261010', 'INTERESES SOBRE CESANTIAS', NULL);
SELECT account_heading_save(NULL, '261015', 'VACACIONES', NULL);
SELECT account_heading_save(NULL, '261020', 'PRIMA DE SERVICIOS', NULL);
SELECT account_heading_save(NULL, '2615', 'PARA OBLIGACIONES FISCALES', NULL);
SELECT account_heading_save(NULL, '261505', 'DE RENTA Y COMPLEMENTARIOS', NULL);
SELECT account__save(NULL,'2615050001','Impuesto de Renta y Complementar','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '261510', 'DE INDUSTRIA Y COMERCIO', NULL);
SELECT account_heading_save(NULL, '261595', 'OTROS', NULL);
SELECT account_heading_save(NULL, '2630', 'PARA MANTENIMIENTO Y REPARACION', NULL);
SELECT account_heading_save(NULL, '2635', 'PARA CONTINGENCIAS', NULL);
SELECT account_heading_save(NULL, '263505', 'MULTAS SANCIONES Y LITIGIOS', NULL);
SELECT account_heading_save(NULL, '263510', 'INTERESES POR MULTAS Y SANCIONES', NULL);
SELECT account_heading_save(NULL, '28', 'OTROS PASIVOS', NULL);
SELECT account_heading_save(NULL, '2805', 'ANTICIPOS Y AVANCES RECIBIDOS', NULL);
SELECT account_heading_save(NULL, '280505', 'DE CLIENTES', NULL);
SELECT account_heading_save(NULL, '280510', 'SOBRE CONTRATOS', NULL);
SELECT account__save(NULL,'2805100001','Anticipo Recibido Sobre Contrato','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '280515', 'PARA OBRAS EN PROCESO', NULL);
SELECT account_heading_save(NULL, '2815', 'INGRESOS RECIBIDOS PARA TERCEROS', NULL);
SELECT account_heading_save(NULL, '281505', 'VALORES RECIBIDOS PARA TERCEROS', NULL);
SELECT account_heading_save(NULL, '281510', 'VENTA POR CUENTA DE TERCEROS', NULL);
SELECT account_heading_save(NULL, '2825', 'RETENCION A TERCEROS SOBRE CONTR', NULL);
SELECT account_heading_save(NULL, '282505', 'CUMPLIMIENTO OBLIGACIONES LABORA', NULL);
SELECT account_heading_save(NULL, '3', 'PATRIMONIO', NULL);
SELECT account_heading_save(NULL, '31', 'CAPITAL SOCIAL', NULL);
SELECT account_heading_save(NULL, '3105', 'CAPITAL SUSCRITO Y PAGADO', NULL);
SELECT account_heading_save(NULL, '310505', 'CAPITAL AUTORIZADO', NULL);
SELECT account__save(NULL,'3105050001','Capital Suscrito y Pagado','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '310510', 'CAPITAL POR SUSCRIBIR (DB)', NULL);
SELECT account_heading_save(NULL, '310515', 'CAPITAL SUSCRITO POR COBRAR (DB)', NULL);
SELECT account_heading_save(NULL, '3115', 'APORTES SOCIALES', NULL);
SELECT account_heading_save(NULL, '33', 'RESERVAS', NULL);
SELECT account_heading_save(NULL, '3305', 'RESERVAS OBLIGATORIAS', NULL);
SELECT account_heading_save(NULL, '330505', 'RESERVA LEGAL', NULL);
SELECT account__save(NULL,'3305050001','Reserva Legal','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '3310', 'RESERVAS ESTATUTARIAS', NULL);
SELECT account_heading_save(NULL, '3315', 'RESERVAS OCASIONALES', NULL);
SELECT account_heading_save(NULL, '34', 'REVALORIZACION DEL PATRIMONIO', NULL);
SELECT account_heading_save(NULL, '3405', 'AJUSTES POR INFLACION', NULL);
SELECT account_heading_save(NULL, '340505', 'DE CAPITAL SOCIAL', NULL);
SELECT account__save(NULL,'3405050001','AxI CAPITAL','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '340510', 'DE SUPERAVIT DE CAPITAL', NULL);
SELECT account_heading_save(NULL, '340515', 'DE RESERVAS', NULL);
SELECT account__save(NULL,'3405150001','AxI RESERVA LEGAL','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '340520', 'DE RESULTADO DE EJERC. ANTERIORE', NULL);
SELECT account__save(NULL,'3405200001','AxI RESULTADOS ANTERIORES','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '340525', 'DE ACTIVOS DE PERIODO IMPRODUCTI', NULL);
SELECT account_heading_save(NULL, '340530', 'DE SANEAMIENTO FISCAL', NULL);
SELECT account_heading_save(NULL, '340535', 'DE AJUSTES DECRETO 3019 DE 1989', NULL);
SELECT account_heading_save(NULL, '340540', 'DE DIVIDENDOS Y PARTICIPACIONES', NULL);
SELECT account_heading_save(NULL, '340545', 'SUPERAVIT METODO DE PARTICIPACIO', NULL);
SELECT account_heading_save(NULL, '36', 'RESULTADOS DE EJERCICIO', NULL);
SELECT account_heading_save(NULL, '3605', 'UTILIDAD DEL EJERCICIO', NULL);
SELECT account_heading_save(NULL, '360505', 'UTILIDAD DEL EJERCICIO', NULL);
SELECT account__save(NULL,'3605050001','Utilidad del Ejercicio','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3605050002','Utilidad de Ajustes por Inflacio','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '3610', 'PERDIDAS DEL EJERCICIO', NULL);
SELECT account_heading_save(NULL, '361005', 'PERDIDA DEL EJERCICIO', NULL);
SELECT account__save(NULL,'3610050001','Perdida del Ejercicio','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '37', 'RESULTADOS EJERCICIOS ANRERIORES', NULL);
SELECT account_heading_save(NULL, '3705', 'UTILIDADES ACUMULADAS', NULL);
SELECT account_heading_save(NULL, '370510', 'UTILIDADES ACUMULADAS', NULL);
SELECT account__save(NULL,'3705100001','Utilidades Acumuladas','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '3710', 'PERDIDAS ACUMULADAS', NULL);
SELECT account_heading_save(NULL, '371010', 'PERDIDAS ACUMULADAS', NULL);
SELECT account__save(NULL,'3710100001','Perdidas Acumuladas','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '38', 'SUPERAVIT POR VALORIZACIONES', NULL);
SELECT account_heading_save(NULL, '3805', 'DE INVERSIONES', NULL);
SELECT account_heading_save(NULL, '380505', 'DE ACCIONES', NULL);
SELECT account_heading_save(NULL, '380510', 'CUOTAS O PARTES DE INTERES SOCIA', NULL);
SELECT account_heading_save(NULL, '3810', 'DE PROPIEDAD PLANTA Y EQUIPO', NULL);
SELECT account_heading_save(NULL, '381008', 'CONSTRUCCIONES Y EDIFICACIONES', NULL);
SELECT account__save(NULL,'3810080001','Superavit por Valorizacion C y E','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '3895', 'DE OTROS ACTIVOS', NULL);
SELECT account_heading_save(NULL, '4', 'INGRESOS', NULL);
SELECT account_heading_save(NULL, '41', 'INGRESOS OPERACIONALES', NULL);
SELECT account_heading_save(NULL, '4120', 'INDUSTRIA MANUFACTURERA', NULL);
SELECT account_heading_save(NULL, '4130', 'CONSTRUCCION', NULL);
SELECT account_heading_save(NULL, '413005', 'PREPARACION DE TERRENOS', NULL);
SELECT account_heading_save(NULL, '413010', 'CONSTRUCCION Y OBRAS CIVILES', NULL);
SELECT account_heading_save(NULL, '413025', 'ALQUILER DE EQUIPOS CON OPERARIO', NULL);
SELECT account_heading_save(NULL, '413095', 'ACTIVIDADES CONEXAS', NULL);
SELECT account_heading_save(NULL, '4135', 'COMERCIO AL POR MAYOR', NULL);
SELECT account_heading_save(NULL, '413595', 'ACTIVIDADES CONEXAS', NULL);
SELECT account_heading_save(NULL, '4150', 'ACTIVIDAD FINANCIERA', NULL);
SELECT account_heading_save(NULL, '415030', 'COMISIONES', NULL);
SELECT account_heading_save(NULL, '4175', 'DEVOLUCIONES EN VENTAS', NULL);
SELECT account_heading_save(NULL, '417505', 'DEVOLUCIONES EN VENTAS', NULL);
SELECT account__save(NULL,'4175050001','Devoluciones en Ventas','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4175050002','Descuento en Ventas','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '42', 'INGRESOS NO OPERACIONALES', NULL);
SELECT account_heading_save(NULL, '4205', 'OTRAS VENTAS', NULL);
SELECT account_heading_save(NULL, '420505', 'MATERIA PRIMA', NULL);
SELECT account_heading_save(NULL, '420510', 'MATERIAL DE DESECHO', NULL);
SELECT account_heading_save(NULL, '4210', 'INGRESOS FINANCIEROS', NULL);
SELECT account_heading_save(NULL, '421005', 'INTERESES', NULL);
SELECT account_heading_save(NULL, '421040', 'DESCUENTOS COMERCIALES CONDICION', NULL);
SELECT account__save(NULL,'4210400001','Descuentos Financieros','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '4215', 'DIVIDENDOS Y PARTICIPACIONES', NULL);
SELECT account_heading_save(NULL, '4220', 'ARRENDAMIENTOS', NULL);
SELECT account_heading_save(NULL, '422010', 'CONSTRUCCIONES Y EDIFICACIONES', NULL);
SELECT account_heading_save(NULL, '422015', 'MAQUINARIA Y EQUIPOS', NULL);
SELECT account_heading_save(NULL, '4225', 'COMISIONES', NULL);
SELECT account_heading_save(NULL, '4230', 'HONORARIOS', NULL);
SELECT account_heading_save(NULL, '4235', 'SERVICIOS', NULL);
SELECT account_heading_save(NULL, '423595', 'OTROS SERVICIOS', NULL);
SELECT account_heading_save(NULL, '4240', 'UTILIDAD EN VENTA DE INVERSIONES', NULL);
SELECT account_heading_save(NULL, '4245', 'UTIL.EN VENTA PROP.PLANTA Y EQUI', NULL);
SELECT account_heading_save(NULL, '4250', 'RECUPERACIONES', NULL);
SELECT account_heading_save(NULL, '425005', 'DEUDAS MALAS', NULL);
SELECT account_heading_save(NULL, '425015', 'RECLAMOS', NULL);
SELECT account_heading_save(NULL, '4255', 'INDEMNIZACIONES', NULL);
SELECT account_heading_save(NULL, '4260', 'PARTICIPACION EN CONCESIONES', NULL);
SELECT account_heading_save(NULL, '4265', 'INGRESOS DE EJERCICIOS ANTERIORE', NULL);
SELECT account_heading_save(NULL, '4275', 'DEVOLUCIONES EN OTRAS VENTAS', NULL);
SELECT account_heading_save(NULL, '4295', 'DIVERSOS', NULL);
SELECT account_heading_save(NULL, '429503', 'CERT', NULL);
SELECT account_heading_save(NULL, '429505', 'APROVECHAMIENTOS', NULL);
SELECT account_heading_save(NULL, '429507', 'AUXILIOS', NULL);
SELECT account_heading_save(NULL, '429533', 'MULTAS Y RECARGOS', NULL);
SELECT account_heading_save(NULL, '429535', 'PREAVISOS DESCONTADOS', NULL);
SELECT account_heading_save(NULL, '429537', 'RECLAMOS', NULL);
SELECT account_heading_save(NULL, '429553', 'SOBRANTES DE CAJA', NULL);
SELECT account_heading_save(NULL, '429581', 'AJUSTE AL PESO', NULL);
SELECT account_heading_save(NULL, '429583', 'LLAMADAS TELEFONICAS', NULL);
SELECT account_heading_save(NULL, '47', 'AJUSTES POR INFLACION', NULL);
SELECT account_heading_save(NULL, '4705', 'CORRECCION MONETARIA', NULL);
SELECT account_heading_save(NULL, '470505', 'INVERSIONES (CR)', NULL);
SELECT account_heading_save(NULL, '470510', 'INVENTARIOS (CR)', NULL);
SELECT account__save(NULL,'4705100005','Inventario Materia Prima','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4705100010','Inventario Productos en Proceso','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4705100015','Obras de construccion en curso','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4705100020','Inventario contratos en ejecucio','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4705100030','Inventario Producto terminado','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4705100035','Inv. Mercancia no Fabricada','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4705100065','Inventarios en transito','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '470515', 'PROPIEDAD PLANTA Y EQUIPO (CR)', NULL);
SELECT account__save(NULL,'4705150001','Terrenos','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4705150003','Construcciones en Curso','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4705150004','Maquinaria y Equipo en Montaje','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4705150005','Construcciones y Edificaciones','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4705150006','Maquinaria y Equipos','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4705150007','Equipos de Oficina','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4705150008','Equipos de Computacion y comunic','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4705150011','Flota y Equipo de transporte','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '470540', 'PATRIMONIO', NULL);
SELECT account__save(NULL,'4705400001','Aj. por Infl. Patrimonio','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '470545', 'DEPRECIACION ACUMULADA (DB)', NULL);
SELECT account__save(NULL,'4705450001','Depreciacion Acumulada (DB)','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '470550', 'DEPRECIACION DIFERIDA (CR)', NULL);
SELECT account_heading_save(NULL, '470560', 'AMORTIZACION ACUMULADA (DB)', NULL);
SELECT account_heading_save(NULL, '5', 'GASTOS', NULL);
SELECT account_heading_save(NULL, '51', 'GASTOS OPERACIONALES DE ADMON.', NULL);
SELECT account_heading_save(NULL, '5105', 'GASTOS DE PERSONAL', NULL);
SELECT account_heading_save(NULL, '510548', 'BONIFICACION', NULL);
SELECT account_heading_save(NULL, '52', 'GASTOS OPERACIONALES DE VENTAS', NULL);
SELECT account_heading_save(NULL, '5205', 'GASTOS DE PERSONAL', NULL);
SELECT account_heading_save(NULL, '520506', 'SUELDOS', NULL);
SELECT account_heading_save(NULL, '520527', 'AUXILIO DE TRANSPORTE', NULL);
SELECT account_heading_save(NULL, '520530', 'CESANTIAS', NULL);
SELECT account_heading_save(NULL, '520533', 'INTERESES SOBRE CESANTIAS', NULL);
SELECT account__save(NULL,'5205330001','Intereses Sobre Cesantias','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '520536', 'PRIMAS DE SERVICIOS', NULL);
SELECT account_heading_save(NULL, '520539', 'VACACIONES', NULL);
SELECT account_heading_save(NULL, '520548', 'BONIFICACIONES', NULL);
SELECT account__save(NULL,'5205480001','Bonificaciones a Empleados','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '520563', 'CAPACITACION AL PERSONAL', NULL);
SELECT account__save(NULL,'5205630001','Capacitacion al Personal','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '520568', 'APORTES ARP', NULL);
SELECT account_heading_save(NULL, '520569', 'APORTES EPS', NULL);
SELECT account_heading_save(NULL, '520570', 'APORTES A FONDO DE PENSIONES/CES', NULL);
SELECT account_heading_save(NULL, '520572', 'APORTES CAJAS DE COMPENSACION', NULL);
SELECT account_heading_save(NULL, '520575', 'APORTES ICBF', NULL);
SELECT account_heading_save(NULL, '520578', 'APORTES SENA', NULL);
SELECT account_heading_save(NULL, '520595', 'OTROS GASTOS DE PERSONAL', NULL);
SELECT account__save(NULL,'5205950001','Otros Gastos de personal','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '5210', 'HONORARIOS', NULL);
SELECT account_heading_save(NULL, '521005', 'JUNTA DIRECTIVA', NULL);
SELECT account_heading_save(NULL, '521010', 'REVISORIA FISCAL', NULL);
SELECT account_heading_save(NULL, '521015', 'AUDITORIA EXTERNA', NULL);
SELECT account_heading_save(NULL, '521025', 'ASESORIA JURIDICA', NULL);
SELECT account_heading_save(NULL, '521030', 'ASESORIA FINANCIERA', NULL);
SELECT account_heading_save(NULL, '521035', 'ASESORIA TECNICA', NULL);
SELECT account_heading_save(NULL, '521095', 'OTROS HONORARIOS', NULL);
SELECT account__save(NULL,'5210950001','Estudio y Diseño de Planos','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '5215', 'IMPUESTOS', NULL);
SELECT account_heading_save(NULL, '521505', 'INDUSTRIA Y COMERCIO', NULL);
SELECT account__save(NULL,'5215050001','Impuesto de Industria y Comercio','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '521510', 'DE TIMBRES', NULL);
SELECT account__save(NULL,'5215100001','Impuesto de Timbre','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '521515', 'IMPUESTOS A LA PROPIEDAD RAIZ', NULL);
SELECT account__save(NULL,'5215200001','DERECHOS SOBRE INSTRUMENTOS PUBL','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '521540', 'IMPUESTOS SOBRE VEHICULOS', NULL);
SELECT account__save(NULL,'5215400001','Impuestos Sobre Vehiculos','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '521595', 'OTROS IMPUESTOS', NULL);
SELECT account_heading_save(NULL, '5220', 'ARRENDAMIENTOS', NULL);
SELECT account_heading_save(NULL, '522010', 'CONSTRUCCIONES U EDIFICACIONES', NULL);
SELECT account_heading_save(NULL, '522015', 'MAQUINARIA Y EQUIPO', NULL);
SELECT account__save(NULL,'5220150001','Arriendo Maquinaria y Equipo','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '522025', 'EQUIPOS DE COMPUTACION Y COMUNIC', NULL);
SELECT account__save(NULL,'5220250001','Alquiler Eq. Computacion y Comun','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '522040', 'FLOTA Y EQUIPO DE TRANSPORTE', NULL);
SELECT account__save(NULL,'5220400001','Alquiler de Vehiculos y Camiones','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '5230', 'SEGUROS', NULL);
SELECT account_heading_save(NULL, '523005', 'MANEJO', NULL);
SELECT account_heading_save(NULL, '523010', 'CUMPLIMIENTO', NULL);
SELECT account__save(NULL,'5230100001','Polizas de Cumplimiento','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '523040', 'FLOTA Y EQUIPO DE TRANSPORTE', NULL);
SELECT account_heading_save(NULL, '523075', 'OBLIGATORIO ACCIDENTES DE TRANSI', NULL);
SELECT account_heading_save(NULL, '5235', 'SERVICIOS', NULL);
SELECT account_heading_save(NULL, '523505', 'ASEO Y VIGILANCIA', NULL);
SELECT account_heading_save(NULL, '523515', 'ASSITENCIA TECNICA', NULL);
SELECT account_heading_save(NULL, '523520', 'PROCESAMIENTO ELECTRONICO DE DAT', NULL);
SELECT account__save(NULL,'5235200001','Procesamiento electronico de Dat','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '523525', 'ACUEDUCTO Y ALCANTARILLADO', NULL);
SELECT account_heading_save(NULL, '523530', 'ENERGIA ELECTRICA', NULL);
SELECT account_heading_save(NULL, '523535', 'TELEFONO', NULL);
SELECT account_heading_save(NULL, '523540', 'CORREO PORTES Y TELEGRAMAS', NULL);
SELECT account_heading_save(NULL, '523545', 'FAX Y TELEX', NULL);
SELECT account__save(NULL,'5235450001','fax y Telex','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '523550', 'TRANSPORTES FLETES Y ACARREOS', NULL);
SELECT account_heading_save(NULL, '523555', 'GAS', NULL);
SELECT account_heading_save(NULL, '523560', 'PUBLICIDAD PROPAGANDA Y PROMOCIO', NULL);
SELECT account__save(NULL,'5235600001','Publicidad Propaganda y Promocio','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '523595', 'OTROS SERVICIOS', NULL);
SELECT account__save(NULL,'5235950002','Fabricacion  y Elaboracion','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5235950004','Capacitacion a Contratistas','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5235950007','Digitación y archivo documentos','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '5240', 'GASTOS LEGALES', NULL);
SELECT account_heading_save(NULL, '524005', 'NOTARIALES', NULL);
SELECT account_heading_save(NULL, '524010', 'REGISTRO MERCANTIL', NULL);
SELECT account__save(NULL,'5240100001','Registro Mercantil','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '524015', 'TRAMITES Y LICENCIAS', NULL);
SELECT account_heading_save(NULL, '524095', 'OTROS GASTOS LEGALES', NULL);
SELECT account__save(NULL,'5240950001','Tramite de Vehiculos','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5240950003','Sobretasa','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5240950004','Dcmtos Varios en Camara Comercio','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5240950005','Floio para Libros Legales','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5240950006','Impuesto para preservar la Segur','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '5245', 'MANTENIMIENTO Y REPARACIONES', NULL);
SELECT account_heading_save(NULL, '524510', 'CONSTRUCCIONES Y EDIFICACIONES', NULL);
SELECT account__save(NULL,'5245100001','Construcciones y Edificaciones','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '524515', 'MAQUINARIA Y EQUIPOS', NULL);
SELECT account__save(NULL,'5245150001','Equipo de Refrigeracion','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5245150002','Equipos de Ingenieria Civil','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5245150003','Repuestos y Herramientas','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '524520', 'EQUIPO DE OFICINA', NULL);
SELECT account__save(NULL,'5245200001','Equipo de Oficina','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '524525', 'EQUIPO DE COMPUTACION Y COMUNICA', NULL);
SELECT account__save(NULL,'5245250001','Mtto y Rep. Eq. Computacion y Co','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '524540', 'FLOTA Y EQUIPO DE TRANSPORTE', NULL);
SELECT account__save(NULL,'5245400001','Mantenimiento de Vehiculos','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '5250', 'ADECUACION E INSTALACION', NULL);
SELECT account_heading_save(NULL, '525005', 'INSTALACIONES ELECTRICAS', NULL);
SELECT account__save(NULL,'5250050001','Instalaciones Electricas','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '525010', 'ARREGLOS ORNAMENTALES', NULL);
SELECT account_heading_save(NULL, '525015', 'REPARACIONES LOCATIVAS', NULL);
SELECT account_heading_save(NULL, '525095', 'OTROS ADECUACIONES E INSTALACION', NULL);
SELECT account_heading_save(NULL, '5255', 'GASTOS DE VIAJE', NULL);
SELECT account_heading_save(NULL, '525505', 'ALOJAMIENTO Y MANUTENCION', NULL);
SELECT account_heading_save(NULL, '525515', 'PASAJES AEREOS', NULL);
SELECT account_heading_save(NULL, '525520', 'PASAJES TERRESTRES', NULL);
SELECT account__save(NULL,'5255200001','Pasajes Terrestres','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '525595', 'OTROS GASTOS DE VIAJE', NULL);
SELECT account__save(NULL,'5255950002','Llamadas Telefonicas en Viajes','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '5260', 'DEPRECIACIONES', NULL);
SELECT account_heading_save(NULL, '526005', 'CONSTRUCCIONES Y EDIFICACIONES', NULL);
SELECT account__save(NULL,'5260050001','Depreciacion Locales Tequendama','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '526010', 'MAQUINARIA Y EQUIPO', NULL);
SELECT account__save(NULL,'5260100001','Depreciacion de maq. y Equipos','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '526015', 'EQUIPOS DE OFICINA', NULL);
SELECT account__save(NULL,'5260150001','Depreciacion Equipos de Oficina','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '526020', 'EQUIPOS DE COMPUTACION Y COMUNIC', NULL);
SELECT account__save(NULL,'5260200001','Depreciacion Eq. de Computacion','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '526035', 'FLOTA Y EQUIPO DE TRANSPORTE', NULL);
SELECT account__save(NULL,'5260350001','Depreciacion de Vehiculos','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '526099', 'AJUSTES POR INLFACION', NULL);
SELECT account__save(NULL,'5260990005','Aj. Infl. Construcciones y Edif.','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5260990010','Aj. Infl. Maquinaria y Equipo','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5260990015','Aj. Infl. Equipos de Oficina','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5260990020','Aj. Infl. Eq. Computacion y Com.','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5260990035','Aj. Infl. Vehiculos','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '5295', 'GASTOS DIVERSOS', NULL);
SELECT account_heading_save(NULL, '529505', 'COMISIONES', NULL);
SELECT account_heading_save(NULL, '529510', 'LIBROS SUSCRIPCIONES PERIODICOS', NULL);
SELECT account__save(NULL,'5295100001','Libros Suscripciones periodicos','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '529520', 'GASTOS DE REPRESENTACION Y REL.P', NULL);
SELECT account__save(NULL,'5295200001','Gastos de Representacion y Rel.P','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '529525', 'ELEMENTOS DE ASEO Y CAFETERIA', NULL);
SELECT account_heading_save(NULL, '529530', 'UTILES PAPELERIA Y FOTOCOPIAS', NULL);
SELECT account_heading_save(NULL, '529535', 'COMBUSTIBLES Y LUBRICANTES', NULL);
SELECT account_heading_save(NULL, '529545', 'TAXIS Y BUSES', NULL);
SELECT account_heading_save(NULL, '529550', 'ESTAMPILLAS', NULL);
SELECT account__save(NULL,'5295500001','Estampillas','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '529560', 'CASINO Y RESTAURANTE', NULL);
SELECT account_heading_save(NULL, '529565', 'PARQUEADEROS', NULL);
SELECT account__save(NULL,'5295650001','Parqueaderos','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '529595', 'OTROS GASTOS DIVERSOS', NULL);
SELECT account__save(NULL,'5295950001','Cargue y Decargue de Materiales','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5295950002','Autenticaciones','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5295950004','Ajuste al Peso','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '5299', 'PROVISIONES', NULL);
SELECT account_heading_save(NULL, '529910', 'DEUDORES', NULL);
SELECT account__save(NULL,'5299100001','Provision Deudas Dificil Recaudo','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '53', 'GASTOS NO OPERACIONALES', NULL);
SELECT account_heading_save(NULL, '5305', 'GASTOS FINANCIEROS', NULL);
SELECT account_heading_save(NULL, '530505', 'GASTOS BANCARIOS', NULL);
SELECT account__save(NULL,'5305050001','Gastos Bancarios','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '530515', 'COMISIONES', NULL);
SELECT account__save(NULL,'5305150001','Comisiones Bancarias','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '530520', 'INTERESES', NULL);
SELECT account__save(NULL,'5305200001','Intereses Corriente Ptmos Bancar','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5305200002','Intereses por Sobregiro Bancario','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5305200003','Intereses de Mora','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '5315', 'GASTOS EXTRAORDINARIOS', NULL);
SELECT account_heading_save(NULL, '531520', 'IMPUESTOS ASUMIDOS', NULL);
SELECT account__save(NULL,'5315200001','Impuestos Asumidos','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '531595', 'OTROS GASTOS EXTRAORDINARIOS', NULL);
SELECT account_heading_save(NULL, '5395', 'GASTOS DIVERSOS', NULL);
SELECT account_heading_save(NULL, '539520', 'MULTAS SANCIONES Y LITIGIOS', NULL);
SELECT account__save(NULL,'5395200001','Multas Sanciones y Litigios','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '54', 'IMPUESTO DE RENTA Y COMPLEMENTAR', NULL);
SELECT account_heading_save(NULL, '5405', 'IMPUESTO DE RENTA Y COMPLEMENTAR', NULL);
SELECT account_heading_save(NULL, '540505', 'IMPUESTO DE RENTA Y COMPLEMENTAR', NULL);
SELECT account__save(NULL,'5405050001','Impuesto de Renta y Complementar','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '6', 'COSTO DE VENTA', NULL);
SELECT account_heading_save(NULL, '61', 'COSTO DE VENTAS Y PREST. SERVICI', NULL);
SELECT account_heading_save(NULL, '6135', 'COMERCIO AL POR MAYOR Y MENOR', NULL);
SELECT account_heading_save(NULL, '613554', 'VTA MAQ. EQ. OFIC. Y SOFTWARE', NULL);
SELECT account__save(NULL,'6135540001','Costo de Ventas','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '62', 'COMPRAS', NULL);
SELECT account_heading_save(NULL, '6205', 'COMPRA DE MERCANCIA', NULL);
SELECT account_heading_save(NULL, '6210', 'COMPRA DE MATERIA PRIMA', NULL);
SELECT account_heading_save(NULL, '621001', 'COMPRA DE MATERIA PRIMA', NULL);
SELECT account__save(NULL,'1305050002','Clientes Nacionales','A','', NULL, false, false, string_to_array('AR', ':'), false, false);
SELECT account__save(NULL,'2408050001','Iva Descontable en compras 16%','L','', NULL, false, false, string_to_array('AR_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2408050002','Iva Descontable en servicios 16%','L','', NULL, false, false, string_to_array('AR_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2408050003','Iva Descontable Arri. y Hotel 7%','L','', NULL, false, false, string_to_array('AR_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2408050004','Iva Descontable en Tiquetes 8%','L','', NULL, false, false, string_to_array('AR_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2408050005','Iva Descontable en Servicios 20%','L','', NULL, false, false, string_to_array('AR_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2408050010','Iva Descon. Reg. Simplif. 12%','L','', NULL, false, false, string_to_array('AR_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'1305050001','Clientes Nacionales','A','', NULL, false, false, string_to_array('AR', ':'), false, false);
SELECT account__save(NULL,'1330050001','Anticipo a Proveedores','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1350950001','Contratos de Consultoria','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1465050001','Inventarios en Transito','A','', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'2205050002','Proveedores Nacionales','L','', NULL, false, false, string_to_array('AP', ':'), false, false);
SELECT account__save(NULL,'2320050001','Cuentas por pagar a Contratistas','L','', NULL, false, false, string_to_array('AP', ':'), false, false);
SELECT account_heading_save(NULL, '2315', 'A COMPA??AS VINCULADAS', NULL);
SELECT account__save(NULL,'2335950001','Gastos Causados por Pagar','L','', NULL, false, false, string_to_array('AP', ':'), false, false);
SELECT account__save(NULL,'2205050001','Proveedores Nacionales','L','', NULL, false, false, string_to_array('AP', ':'), false, false);
SELECT account__save(NULL,'2365150002','Honorarios Persona Natural 11%','L','', NULL, false, false, string_to_array('AP_tax:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2365150003','Honorarios Persona Juridica 10%','L','', NULL, false, false, string_to_array('AP_tax:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'5105480001','Bonificaciones a Empleados','E','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '142005', 'CONTRATOS EN EJECUCION', NULL);
SELECT account__save(NULL,'5220100001','Arriendo Casa','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5255950001','Taxis y Buses','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5235550001','Gas','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5255150001','Pasajes Aereos','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5235250001','Acueducto y Alcantarilldo','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'2368030002','Retencion ICA 8xMil','L','', NULL, false, false, string_to_array('AP_tax:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2380950001','Cuentas por pagar','L','', NULL, false, false, string_to_array('AP', ':'), false, false);
SELECT account__save(NULL,'1330100001','Anticipo a Contratistas','A','', NULL, false, false, string_to_array('AR', ':'), false, false);
SELECT account__save(NULL,'2408050006','IVA Descontable en compras 20% ','L','', NULL, false, false, string_to_array('IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'5295950003','Compra de Medicina Contratistas','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5295600001','Casino y Restaurante','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5295450001','Taxis y Buses Urbanos','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5295350001','Combustibles y lubricantes','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5295050001','Comisiones','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5255950003','Tasa Aeroportuaria','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5255050001','Alojamiento y Manutencion','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5250150001','Reparaciones Locativas','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5240950002','Exp. Certif. Libertad y tradicio','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5240150001','Tramites y Licencias','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5235950006','Mano de Obra OBRAS CIVILES','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5235950005','Jardineria','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5235950003','Digitacion de Planos','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5235950001','Pintura','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5235500001','Transportes Fletes y Acarreos','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5235400001','Correo Portes y Telegramas','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5235150001','Asistencia tecnica','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5235050001','Aseo y Vigilancia','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5215950001','Impuesto de 3 por Mil','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5215150001','Impuestos a la Propiedad raiz','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5210950003','Asesoria Administrativa y de Mer','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5210950002','Asesoria Contable','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5210250001','Asesorias Juridicas','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5205780001','Aportes SENA','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5205750001','Aportes ICBF','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5205720001','Aportes cajas de Compensacion','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5205700001','Aportes fondo de Pensiones y Ces','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5205690001','Aportes EPS','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5205680001','Aportes ARP','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5205390001','Vacaciones','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5205360001','Primas de Servicios','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5205300001','Cesantias','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'5205270001','Auxilio de transporte','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'4295050001','Aprovechamiento Material Sobrant','I','', NULL, false, false, string_to_array('IC_sale:IC_income', ':'), false, false);
SELECT account__save(NULL,'4210050001','Intereses por Rendimientos Finan','I','', NULL, false, false, string_to_array('IC_income', ':'), false, false);
SELECT account__save(NULL,'2408100001','Iva Generado por Ingresos 16%','L','', NULL, false, false, string_to_array('AR_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2408100002','Iva Generado por Ingresos 7%','L','', NULL, false, false, string_to_array('AR_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'6210010001','Compra de Materia Prima','E','', NULL, false, false, string_to_array('IC_cogs', ':'), false, false);
SELECT account__save(NULL,'2365400002','Compra Combustibles y Lub. 0.1%','L','', NULL, false, false, string_to_array('IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2365400001','Compras en General 3.5%','L','', NULL, false, false, string_to_array('IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2365300004','Arriendo Maq. Obra Civil 2%','L','', NULL, false, false, string_to_array('IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2365300003','Arriendo Bienes Muebles 4%','L','', NULL, false, false, string_to_array('IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2365300001','Arriendo Inmuebles 3.5%','L','', NULL, false, false, string_to_array('IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2365250004','Construccion Obra Civil 1%','L','', NULL, false, false, string_to_array('IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2365250003','Transporte de Carga 1%','L','', NULL, false, false, string_to_array('IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2365250001','Servicios en General 6%','L','', NULL, false, false, string_to_array('IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2365200001','Retencion Comision del 11%','L','', NULL, false, false, string_to_array('IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2365150001','Honorarios Persona Natural 10%','L','', NULL, false, false, string_to_array('AP_tax:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'5295300001','Utiles Papeleria y Fotocopias','E','', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'5295250001','Elementos de Aseo y Cafeteria','E','', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'5235300001','Energia Electrica','E','', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'5235350001','Telefono','E','', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'1355150003','Retefuente 7% Rendimientos Finan','A','', NULL, false, false, string_to_array('IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'1355150001','Retefuente 2% Factor multiplicad','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1355170001','Iva Retenido 75% de 16%','A','', NULL, false, false, string_to_array('IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2365150004','Honorarios Persona Juridica 11%','L','', NULL, false, false, string_to_array('AR_tax:AP_tax', ':'), false, false);
SELECT account__save(NULL,'2367050001','Iva retenido reg simplif 12% ','L','', NULL, false, false, string_to_array('AP_tax', ':'), false, false);
SELECT account_heading_save(NULL, '236710', 'IVA RETENIDO AL REGIMEN COMUN ', NULL);
SELECT account_heading_save(NULL, '236705', 'IVA RETENIDO AL REGIMEN SIMPLIF. ', NULL);
SELECT account_heading_save(NULL, '2367', 'IMPUESTO A LAS VENTAS RETENIDO', NULL);
SELECT account__save(NULL,'4295810001','Ajuste al Peso','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5240050001','Gastos Notariales','E','', NULL, false, false, string_to_array('IC_expense', ':'), false, false);
SELECT account__save(NULL,'429581001','Ajuste','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4130950001','Consultorias','I','', NULL, false, false, string_to_array('AR_amount:IC_income', ':'), false, false);
SELECT account__save(NULL,'4130100001','Ingresos por Obras Civiles','I','', NULL, false, false, string_to_array('AR_amount:IC_income', ':'), false, false);
SELECT account__save(NULL,'4130950002','Interventorias','I','', NULL, false, false, string_to_array('AR_amount:IC_income', ':'), false, false);
SELECT account__save(NULL,'4220100001','Arriendo de locales y oficinas','I','', NULL, false, false, string_to_array('AR_amount:IC_income', ':'), false, false);
SELECT account__save(NULL,'4220150001','Arriendo de Maquinaria y Equipos','I','', NULL, false, false, string_to_array('AR_amount:IC_income', ':'), false, false);
select account__save(NULL, '4235950001', 'Algo', 'I','', null, false, false, string_to_array('AR_amount:IC_income', ':'), false, false);
SELECT account__save(NULL,'5205060001','Sueldos de Personal','E','', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'2370060001','Aportes a ARP','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'2380950002','Otros Acreedores Varios','L','', NULL, false, false, string_to_array('AP', ':'), false, false);
SELECT account__save(NULL,'2335300001','Servicios Tecnicos','L','', NULL, false, false, string_to_array('AP', ':'), false, false);
SELECT account__save(NULL,'2370100001','Aportes a Sena, icbf y Cajas com','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'2380300001','Fondos de Cesantias y/o Pension','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'2505050001','Salarios por Pagar','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'2610050001','Cesantias','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'2610100001','Intereses Sobre Cesantias','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'2610150001','Vacaciones','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'2610200001','Prima de Servicios','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'2367100001','Iva retenido al reg comun 16% ','L','', NULL, false, false, string_to_array('AR_tax:AP_tax', ':'), false, false);
SELECT account__save(NULL,'2367050002','Iva retenido Reg Simp.del 7% ','L','', NULL, false, false, string_to_array('IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2367100002','Iva retenido al reg comun 20% ','L','', NULL, false, false, string_to_array('IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'2367100003','Iva retenido al reg comun del 7% ','L','', NULL, false, false, string_to_array('AR_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'1410990001','Aj. por Inflacion Inv. en Proces','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1465990001','Aj.por Infl. Inv. en Transito','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1330150001','Anticipo a Trabajadores','A','', NULL, false, false, string_to_array('AR', ':'), false, false);
SELECT account__save(NULL,'1420990001','Aj.por Inflacion Ctos en Ejecuci','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1430990001','Aj.por Inflacion Inv.Prod.Termin','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1435990001','Aj.por Infl.Mcia No Fab.Empresa','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1105050001','Caja Mayor','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'1105100001','Caja Menor 1','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'1105100002','Caja Menor 2','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'1105100003','Caja Menor 3','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'1105100004','Caja menor 4','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'1105100005','Caja menor 5','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);

SELECT account__save(NULL,'1110050013','Banco Ganadero Cta.Cte.xxxxxxxx','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'1110050029','Tequendama Cte. #xxxxxxxx','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'1120050013','Banco Ganadero Ahorro xxxxxxxx','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'1120050019','Banco Colpatria Ahor. xxxxxxxxx','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'1120051302','Bco Ganadero Ahorro xxxxxxxxxx','A','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'1355150020','Retencion en la Fuente Año Anter','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1410050001','Muebles','A','', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'1410050002','Inventario 1','A','', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'1410050003','Inventario 2','A','', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'1410050004','Inventario 3','A','', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'1410050005','Inventario 4','A','', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'1410050010','Inventario 5','A','', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'1420050001','Lokesea','A','', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'1430050001','Lokesea','A','', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'1435050001','Lokesea','A','', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'1420050002','Lokesea','A','', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'1516100001','Local #1','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1516100002','Local #2','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1516100003','Local #3','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1516990001','Aj. Infl. Local #1','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1435050099','Cuenta Inventario para Lokesea','A','', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'1516991001','Aj. Infl. Local #1','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1516991002','Aj. Infl. Local #2','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1516991003','Aj. Infl. Local #3','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1520020001','Lokesea del Inventario','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1520020002','Equipo de Lokeasea','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1520990201','Aj. por Inflacion Lokesea','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1520990202','Aj.x Infl. Otro Lokesea','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1524100001','Aire Acondicionado LG','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1524991001','Aj. por Inflac. Aire Acond. LG','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1592100001','Depreciacion Lokesea','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1540050001','Mazda Blanco Placa ALGO0815','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1592050001','Local #1','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1592050002','Local #2','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1592050003','Local #3','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1592100002','Deprec. Otro Lokesea','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1592150001','Depreciacion Aire LG','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1592350001','Mazda Balnco Placa ALGO0815','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1910080001','Local #1','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1910080002','Local #2','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'1910080003','Local #3','A','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'2335950002','Cuentas por pagar CaribeNet S.A. (www.caribenet.com)','L','', NULL, false, false, string_to_array('AP', ':'), false, false);
SELECT account__save(NULL,'3115050001','Yo','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'3115050002','Tu','Q','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4120270001','Lokeproducimos','I','', NULL, false, false, string_to_array('AR_amount:IC_income', ':'), false, false);
SELECT account__save(NULL,'4130950003','En que ganamos?','I','', NULL, false, false, string_to_array('AR_amount:IC_income', ':'), false, false);
SELECT account__save(NULL,'4135950001','Loquevendomos','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'4150300001','Vendo hasta mi mama!','I','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'5230750001','Soat - Seguro Obligatorio Vehiculos','E','', NULL, false, false, string_to_array('', ':'), false, false);
--
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '1355150003'), -0.07);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '1355170001'), -0.12);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2365150001'), -0.1);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2365150002'), -0.11);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2365150003'), -0.1);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2365150004'), -0.11);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2365200001'), -0.11);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2365250001'), -0.06);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2365250003'), -0.01);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2365250004'), -0.01);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2365300001'), -0.035);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2365300003'), -0.04);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2365300004'), -0.02);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2365400001'), -0.035);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2365400002'), -0.001);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2367050001'), -0.12);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2367050002'), -0.0525);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2367100001'), -0.12);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2367100002'), -0.15);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2367100003'), -0.0525);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2368030002'), -0.008);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2408050001'), 0.16);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2408050002'), 0.16);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2408050003'), 0.07);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2408050004'), 0.08);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2408050005'), 0.2);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2408050006'), 0.2);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2408050010'), 0.12);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2408100001'), 0.16);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '2408100002'), 0.07);

 INSERT INTO defaults (setting_key, value) VALUES ('expense_accno_id', (SELECT id FROM account WHERE accno = '5250150001'));

 INSERT INTO defaults (setting_key, value) VALUES ('fxgain_accno_id', (SELECT id FROM account WHERE accno = '4705400001'));


INSERT INTO currency (curr, description)
   VALUES
      ('COP', 'COP');
INSERT INTO defaults (setting_key, value) VALUES ('curr', 'COP');


 INSERT INTO defaults (setting_key, value) VALUES ('weightunit', 'kg');

SELECT cr_coa_to_account_save(accno, accno || '--' || description)
FROM account WHERE id IN (select account_id FROM account_link
                           WHERE description = 'AP_paid');
commit;
UPDATE account
   SET tax = true
WHERE id
   IN (SELECT account_id
       FROM account_link
       WHERE description LIKE '%_tax');

