#!/bin/sh

if test -d .git
then
    git_id=-`git log 2>/dev/null | head -1 | sed -e 's/commit \(.......\).*/-\1/'`
else
    git_id=-undef
fi
version_id=`grep '$VERSION =' lib/LedgerSMB.pm | sed -e "s/.*['\"]\(.*\)['\"].*/\1/"`

echo "$version_id$git_id"

exit 0
