default:
   includes:
      - xt/lib
      - lib
      - old/lib
   extensions:
      Pherkin::Extension::LedgerSMB:
         db_name: postgres
      Pherkin::Extension::Weasel:
         default_session: selenium
         screenshots_dir: screens
         screenshot_events:
           pre-step: 0
           post-step: 0
           pre-scenario: 0
           post-scenario: 0
         sessions:
           selenium:
             base_url: ${LSMB_BASE_URL}
             page_class: PageObject::Root
             # Need a long retry timeout because instrumenting
             # old code takes loooong when running coverage testing
             retry_timeout: 30
             driver:
                drv_name: Weasel::Driver::Selenium2
                wait_timeout: 3000
                window_size:  1024x1280
                caps:
                  port: 4422
                  remote_server_addr: ${REMOTE_SERVER_ADDR}
                  browser_name: ${BROWSER}
      Pherkin::Extension::PageObject:
         dummy: 1
