begin;
-- selon PLAN COMPTABLE MINIMUM NORMALISE BELGE
-- contribu. par Jens-Ingo Brodesser, jens-ingo@all2all.org
-- verified May 19, 2006
--
SELECT account_heading_save(NULL, '000', '', NULL);
SELECT account__save(NULL,'756000','Produits financiers divers','I','75', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'555000','DEX02','A','55', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'499200','Compte de repartition NDC - Verdelingsrekening CN','L','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'460','Acomptes reçus sur commandes','L','46', NULL, false, false, string_to_array('AR_paid', ':'), false, false);
SELECT account__save(NULL,'4168','Rabais, ristournes, remises à obtenir et autres avoirs non encore reçus','A','416', NULL, false, false, string_to_array('AP_paid', ':'), false, false);
SELECT account_heading_save(NULL, '43', 'Dettes financières - Financiële schulden', NULL);
SELECT account__save(NULL,'2400','Mobilier - Meubilair','A','24', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'240190','Matériel bureau amort. anterieurs - Afschr. op bureaumaterieel vorig boekj.','A','24', NULL, true, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'221900','Constructions amort. anterieurs - Afschr. op gebouwen vorig boekj.','A','22', NULL, true, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'221910','Constructions amort. de l''exercice - Afschr. op gebouwen dit boekj.','A','22', NULL, true, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '75', 'Produits financiers - Financiële opbrengsten', NULL);
SELECT account__save(NULL,'230900','Inst. techniques amort. anterieurs - Afschr. op installaties vorig boekj.','A','23', NULL, true, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'240090','Mobilier amort. anter. - Afschr. op meubilair vorig boekj.','A','24', NULL, true, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'240091','Mobilier amort. exercice - Afschr. op meubilair dit boekj.','A','24', NULL, true, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'240191','Matériel bureau amort. exercice - Afschr. op bureaumaterieel dit boekj.','A','24', NULL, true, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'240290','Materiel Informatique amort. anter. - Afschr. op hardware vorig boekj.','A','24', NULL, true, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'240291','Mat. informat. amort. exercice - Afschr. op hardware dit boekj.','A','24', NULL, true, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'241900','Voiture amort. anter. - Afschr. op wagen vorig boekj.','A','24', NULL, true, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'241910','Voiture amort. exercice - Afschr. op wagen dit boekj. ','A','24', NULL, true, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'260900','Amen. loc. loués amort. anter. - Inrichtingskost. vorig boekj.','A','26', NULL, true, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'230910','Inst. techniques amort. exercice - Afschr. op installaties dit boekj.','A','23', NULL, true, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'231900','Mach. et gros mat. amort. anterieurs - Afschr. op machines vorig boekj.','A','23', NULL, true, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'231910','Mach. et gros mat. amort. exercice - Afschr. op machines dit boekj.','A','23', NULL, true, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'237900','Outillage amort. anterieurs - Afschr. op uitrusting vorig boekj.','A','23', NULL, true, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'237910','Outillage amort. exercice - Afschr. op uitrusting dit boekj.','A','23', NULL, true, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'260910','Amen. loc. loués amort. exercice - Inrichtingskost. dit boekj.','A','26', NULL, true, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'451541','TVA DUE VENTES 21%','L','451', NULL, false, false, string_to_array('AR_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'612200','Carburants voitures','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'630','Dotations amort., réduction valeur s/immo. - Afschr., waardeverm. op v. a., toevoeging','E','63', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'613210','Honoraires avocats','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'712','Des encours de fabrication - In de vooraad goederen in bewerking','I','71', NULL, false, false, string_to_array('IC_sale', ':'), false, false);
SELECT account__save(NULL,'600','Achats matières premières - Aankopen van grondstoffen','E','60', NULL, false, false, string_to_array('IC_cogs', ':'), false, false);
SELECT account__save(NULL,'614400','Entrée aux foires','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'742','Plus-values créances com. - Meerwaarden realis. handelsvorderingen','I','74', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'613304','Traiteurs-réception clientèle','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account_heading_save(NULL, '64', 'Autres charges exploitation - Andere bedrijfskosten', NULL);
SELECT account_heading_save(NULL, '76', 'Produits exceptionnels - Uitzonderlijke opbrengsten', NULL);
SELECT account__save(NULL,'743000','Ventes diverses - Diverse bedrijfsopbrengsten','I','74', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'760100','sur immobilisations corp. - op materiële vaste activa','I','760', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'611150','Charges locatives voitures','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'771200','Reprises de provisions fiscales - Terugn. fiscale voorz.','I','771', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'794','Intervention associé perte - Tussenkomst vennoten verlies','I','79', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'404','Produits à recevoir - Te innen opbrengsten','A','40', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'500','Action propres - Eigen aandelen','A','50', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '41', 'Autres créances - Overige vorderingen', NULL);
SELECT account__save(NULL,'407','Créances douteuses - Dubieuze debiteuren','A','40', NULL, false, false, string_to_array('AR_paid', ':'), false, false);
SELECT account__save(NULL,'442001','Fournisseurs essence','L','44', NULL, false, false, string_to_array('AP', ':'), false, false);
SELECT account__save(NULL,'608','Remises ristournes rabais obtenus - Ontvangen kortingen ristorno''s en rabatten (-)','E','60', NULL, false, false, string_to_array('IC_cogs', ':'), false, false);
SELECT account__save(NULL,'612140','Internet','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account_heading_save(NULL, '50', 'Actions propres - Eigen aandelen', NULL);
SELECT account_heading_save(NULL, '6', 'CLASSE 6 -- CHARGES - KOSTEN', NULL);
SELECT account__save(NULL,'611350','Entr. & Repar. Voitures & Veh. Mixtes','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'655000','Ecarts de conversion de devises','E','65', NULL, false, false, string_to_array('AR_paid:IC_sale:IC_expense', ':'), false, false);
SELECT account__save(NULL,'451560','TVA DUE CO-CONTRACTANT','L','451', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'609000','de matières premières - van grondstofen','E','60', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'411590','TVA ACHATS 6%','A','411', NULL, false, false, string_to_array('AP_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'411591','TVA ACHATS 21%','A','411', NULL, false, false, string_to_array('AP_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'411620','TVA à régulariser (case 62)','A','411', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '411', 'TVA A RECUPERER - TERUG TE VORDEREN BTW', NULL);
SELECT account_heading_save(NULL, '44', 'Dettes commerciales - Handelsschulden', NULL);
SELECT account__save(NULL,'409','Réductions de valeur actées (-) - Geboekte waardevermindering','A','40', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'451540','TVA DUE VENTES 6%','L','451', NULL, false, false, string_to_array('AR_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'640','Charges fiscales de l''exploitation - Bedrijfsbelastingen','E','64', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'713','Des Produits finis - In de voorraad gereed product','I','71', NULL, false, false, string_to_array('IC_sale', ':'), false, false);
SELECT account__save(NULL,'750','Produits immo. financières - Opbrengsten financiële vaste activa','I','75', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'656500','Intérêts retards sociaux - Sociale achterst. interest','E','65', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'755000','Ecarts de convers. devises - Resultats omrekening vreemde valuta','I','75', NULL, false, false, string_to_array('IC_sale:IC_income', ':'), false, false);
SELECT account__save(NULL,'754000','Différence de change - Wisselresultaten','I','75', NULL, false, false, string_to_array('AR_amount:IC_income', ':'), false, false);
SELECT account__save(NULL,'761','Reprises réduct. valeur immo. fin. - Terugneming waardeverm. fin. v. a.','I','76', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'773','Impôts étrangers s/résultat - Buitenl. belasting op resultaat','I','77', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '77', 'Régularisation d''impôts, reprises provisions fiscales - Regul. belastingen en terugneming fiscale voorz.', NULL);
SELECT account_heading_save(NULL, '7', 'CLASSE 7 -- PRODUITS - OPBRENGSTEN', NULL);
SELECT account__save(NULL,'411640','TVA à recupérer s/NDC émises (case 64)','A','411', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'612300','Abonnements & Documentations','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'410','Capital appelé, non versé - Opgevraagd, niet-gestort kapitaal','A','41', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'417','Créances douteuses - Dubieuze debiteuren','A','416', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '451', 'TVA A PAYER - TE BETALEN BTW', NULL);
SELECT account__save(NULL,'499000','Compte d''attente - Wachtrekening','L','', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'455','Rémunerations - Bezoldigingen','L','45', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'601','Achat des fournitures - Aankoop van hulpstoffen','E','60', NULL, false, false, string_to_array('IC_cogs', ':'), false, false);
SELECT account_heading_save(NULL, '49', 'Comptes de régularisation - Overlopende- en wachtrekeningen', NULL);
SELECT account__save(NULL,'613220','Honoraires notaires','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'414100','Indeminités s/sinistres à recevoir - Te ontvang. schadevergoed.','A','41', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '42', 'Dettes à plus d''un an écheant dans l''année - Schulden op meer dan één jaar die binnen het jaar verfallen', NULL);
SELECT account__save(NULL,'613311','Deplacements étranger train, taxi, etc','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'611151','Charges locatives camions/camionnettes','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'432','Etabli. crédit, crédits d''acceptation - Acceptkrediten','L','43', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'433','Etabl. crédit, dettes cpt. courant - Schulden rekening courant','L','43', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'705100','DNS REGISTRY','I','70', NULL, false, false, string_to_array('AR_amount:IC_income', ':'), false, false);
SELECT account__save(NULL,'609100','de fourniture - van hulpstoffen','E','60', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'656100','Frais de banque','E','65', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'620000','Administrateurs ou gérants - Bestuurders of zaakvoerders','E','62', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'618','Divers','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account_heading_save(NULL, '65', 'Charges financières', NULL);
SELECT account__save(NULL,'442004','VISA - décompte mensuel','L','44', NULL, false, false, string_to_array('AP_paid', ':'), false, false);
SELECT account__save(NULL,'620100','Personnel de direction - Directiepersoneel','E','62', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'617','Personnel intérimaire - Uitzendkrachten','E','61', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'440','Fournisseurs - Leveranciers','L','44', NULL, false, false, string_to_array('AP', ':'), false, false);
SELECT account_heading_save(NULL, '52', 'Titres à revenu fixe - Vastrentende Effecten', NULL);
SELECT account_heading_save(NULL, '4529', '453 - 459 Dettes salariales et sociales - Bezoldigingen en sociale schulden', NULL);
SELECT account__save(NULL,'620','Rémunerations et avant. sociaux directs - Bezolgingen en rechts. sociale voordelen','E','62', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'602','Achats services, travaux, études - Aankopen diensten, werk, studies','E','60', NULL, false, false, string_to_array('IC_cogs', ':'), false, false);
SELECT account__save(NULL,'612000','Eau','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'611351','Pneus Voitures & Vehic. Mixtes','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'641','Moins-values s/réalis. cour. d''immo. corp. - Minderwa. courante realis. vaste activa','E','64', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'715','Des immeubles constr. dest. à la vente - In de voorr. onroe. goederen best. v. verkoop','I','71', NULL, false, false, string_to_array('IC_sale', ':'), false, false);
SELECT account__save(NULL,'612400','Imprimés & fournitures de bureau','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'414200','Subsides en capital à recevoir - Te ontv. kapitaalsubsidies','A','41', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '66', 'Charges exceptionnelles', NULL);
SELECT account__save(NULL,'613230','Honoraires huissiers de justice','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'613313','Restaurants étranger','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account_heading_save(NULL, '74', 'Autres produits exploitation - Andere bedrijfsopbrengsten', NULL);
SELECT account__save(NULL,'610','Loyers et charges locatives','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account_heading_save(NULL, '70', 'Chiffre d''affaires - Omzet', NULL);
SELECT account__save(NULL,'751','Produits actifs circulants - Opbrengsten uit vlottende activa','I','75', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'705200','WEB HOSTING','I','70', NULL, false, false, string_to_array('AR_amount:IC_income', ':'), false, false);
SELECT account__save(NULL,'442005','AMERICAN EXPRESS - décompte mensuel','L','44', NULL, false, false, string_to_array('AP_paid', ':'), false, false);
SELECT account__save(NULL,'762','Reprises provisions risq. charg. except. - Terugn. voorz. uitz. risico en kosten','I','76', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'780','Prélèvements s/impôts différés - Onttrekking a. uitgesteld. belast.','I','78', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '78', 'Prélèvements réserves immunisées et impôts différés - Onttrek. belast.vrije reserves en de uitgestelde belastingen', NULL);
SELECT account_heading_save(NULL, '53', 'Dépôts à terme - Termijndeposito''s', NULL);
SELECT account__save(NULL,'614100','Catalogues et imprimées','I','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'451500','TVA DUE ACHATS INCO','L','451', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'613110','Assurance vol','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'451543','TVA due 2e trimestre','L','451', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'609400','de marchandises - van handelsgoederen','E','60', NULL, false, false, string_to_array('AP_amount:IC_sale', ':'), false, false);
SELECT account__save(NULL,'613305','Collations','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'612010','Chauffage','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'612410','Fournitures informatiques','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'613250','Honoraires sécretariat social','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'611362','Control technique voitures','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'482200','ASSOCIES - MEMBRES','L','48', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'612530','Petit outillage & petit matériel','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'613400','Seminaires & Recyclages','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'612540','Petit matériel informatique','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'603','Sous-traitances générales - Algemene onderaanemingen','E','60', NULL, false, false, string_to_array('IC_cogs', ':'), false, false);
SELECT account__save(NULL,'743200','COTISATION DE MEMBRE','I','74', NULL, false, false, string_to_array('AR_amount:IC_income', ':'), false, false);
SELECT account__save(NULL,'601000','Emballages perdus','E','60', NULL, false, false, string_to_array('IC_cogs', ':'), false, false);
SELECT account__save(NULL,'230010','Inst. techniques acquis. exercice - Installaties m.b.t. dit boekj.','A','23', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'570000','CAISSE ESPECES - CONTANTEN','A','57', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'451544','TVA due 3e trimestre','L','451', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'411000','Cpt. curr. TVA à récuperer - Terug te vord. BTW: saldo BTW r/c','A','411', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'611152','Locations machines et outils','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account_heading_save(NULL, '56', 'Office des chèques postaux - Postchèque en girodienst', NULL);
SELECT account__save(NULL,'411593','TVA RECUP. 1ER TRIMESTRE TOTAL (case 59)','A','411', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '51', 'Actions et parts - Aandelen', NULL);
SELECT account__save(NULL,'510010','Montants non-appelés (-) - Niet opgevraagde bedragen aan. (-)','A','51', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'609500','d''immeubles achétés destinés à vente - van gek. onroer. goederen best. v. verkoop','E','60', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '58', 'Virements interns - Interne overboekingen', NULL);
SELECT account_heading_save(NULL, '416', 'Créances diverses - Diverse vorderingen ', NULL);
SELECT account__save(NULL,'416200','Cpt. courant associés - Rekening-courant vennoten','A','416', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'418','Cautionnements versés en numéraire - Borgtochten betaald in contanten','A','416', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '67', 'Impôt sur le résultat', NULL);
SELECT account__save(NULL,'654','Différence de change','E','65', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'642','Moins-values s/réalis. créances com. - Minderwa. realis. handelsvorderingen','E','64', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'717','Des commandes en cours exécution - In de bestelling in uitvoering','I','71', NULL, false, false, string_to_array('IC_sale', ':'), false, false);
SELECT account__save(NULL,'752','Plus-values réalis. d''actifs circulants - Meerwaar. realis. v. vlottende activa','I','75', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'763','Plus-values s/réalis. actifs immo. - Meerwaar. realis. vaste a.','I','76', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'789','Prélèvements s/réserves immunisées - Onttrekking a. belast.vrije reserves','I','78', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '79', 'Affectations et prélèvements - Resultaatverwerking', NULL);
SELECT account__save(NULL,'412','Impôts, précomptes à récupérer - Terug te vorderen belast. en voorheffingen','A','41', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'120','Plus-values de réévaluation sur immo. incorp. - Herwaarderingsmeerwaarde','L','12', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'121','Plus-values de réévaluation sur immo. corp. - Herwaarderingsmeerwaarde','L','12', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'122','Plus-values de réévaluation sur immo. financiers - Herwaarderingsmeerwaarde','L','12', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'123','Plus-values de réévaluation sur stocks - Herwaarderingsmeerwaarde','L','12', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'124','Reprises de réduction de valeur sur placements trésorerie - Herwaarderingsmeerwaarde','L','12', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '12', 'Plus-values de réévaluation - Herwaarderingsmeerwaarde', NULL);
SELECT account__save(NULL,'110','Primes d''émission - Uitgiftepremies','L','11', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '11', 'Primes d''émission - Uitgiftepremies', NULL);
SELECT account_heading_save(NULL, '643', '643-648 Charges d''exploitation diverses - Diverse berijfskosten', NULL);
SELECT account__save(NULL,'612100','Telephone','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account_heading_save(NULL, '10', 'Capital - Kapitaal', NULL);
SELECT account_heading_save(NULL, '1', 'CLASSE 1 -- CAPITAL PROPRE, ... - EIGEN VERMOGEN, ...', NULL);
SELECT account_heading_save(NULL, '60', 'Approv. et marchandises', NULL);
SELECT account__save(NULL,'717000','Valeur d''acquisition - Aanschaffingswaarde','I','717', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '68', 'Transferts comptes immunisées et impôts différés', NULL);
SELECT account__save(NULL,'130','Réserve légale - Wettelijke reserve','L','13', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'131100','Autres réserves indisponibles - Andere onbeschikbare reserves','L','13', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'132','Réserves immunisées - Belastingvrije reserves','L','13', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'131000','Réserves pour actions propres - Reserve voor eigen aandelen','L','13', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'133','Réserves disponibles - Beschikbare reserves','L','13', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'101','Capital non appelé (-) - Niet opgevraagd kapitaal (-)','L','10', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '14', 'Bénéfice/perte reporté(e) - Overgedragen winst/verlies', NULL);
SELECT account__save(NULL,'100','Capital souscrit - Geplaatst kapitaal','L','10', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'601010','Emballages recuperables','E','60', NULL, false, false, string_to_array('IC_cogs', ':'), false, false);
SELECT account__save(NULL,'140','Bénéfice/perte reporté(e) - Overgedragen winst/verlies','Q','14', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '15', 'Subsides en capital - Kapitaalsubsidies', NULL);
SELECT account__save(NULL,'419','Réductions de valeur actées (-) - Geboekte waardevermindering (-)','A','416', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'612450','Photocopies-Photographies','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'131','Réserves indisponibles - Onbeschikbare reserves','L','13', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '16', 'Provisions et impôts différés - Voorz. en uitgestelde belastingen', NULL);
SELECT account__save(NULL,'160','Provisions pensions et obligations - Voorz. pensioenen en soortg. verplichtingen','L','16', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'161','Provisions charges fiscales - Voorz. belastingen','L','16', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'162','Provisions gros entretiens et réparations - Voorz. grote herstel/onderh.','L','16', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'163','Provisions autres risques-charges - Voorzieningen voor Lijfrente','L','16', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'753','Subsides en capital et intérêts - Kapitaal- en interestsubsidies','I','75', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'705000','Prestations de services - Verkopen en dienstprestaties','I','70', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '764', '764-769 Autres produits execptionnels - Andere uitz. opbrengsten', NULL);
SELECT account__save(NULL,'790','Bénéfice reporté exercice précéd. - Overgedragen winst vorige boekj.','I','79', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'168200','Impôts diff. s/+value immo. corp. - Uitg. belast./meerwa./mat. v.a.','L','16', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'604','Achats marchandises - Aankopen van handelsgoederen','E','60', NULL, false, false, string_to_array('IC_cogs', ':'), false, false);
SELECT account__save(NULL,'168000','Impôts diff. s/subsides en capital - Uitgest. belast./Kapitaalsubsidie','L','16', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'613265','Honoraires d''autres','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'620800','Assurance revenus garantis','E','62', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'168800','Impôts différés étrangers - Uitg. belast. buitenland','L','16', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '17', 'Dettes à plus d''un an - Schulden op meer dan een jaar', NULL);
SELECT account__save(NULL,'150','Montants obtenus - Kapitaalsubsidies','L','15', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'172000','Dettes location fin. et assimilées - Leasingschuld. van vaste activa','L','17', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'231010','Mach. et gros mat. acquis. exercice - Machines m.b.t. dit boekj.','A','23', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'451610','TVA à régulariser (case 61)','L','45', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'456','Pécules de vacances - Vakantiegeld','L','45', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'176','Acomptes reçus sur commandes','L','17', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '47', 'Dettes affectation résultat - Schulden besteming resultaat', NULL);
SELECT account__save(NULL,'620200','Employés - Bedienden','E','62', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'178','Cautionnements reçu en numéraire - Borgtocht. ontvang. in contanten','L','17', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'179','Dettes diverses - Overige schulden','L','17', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'174','Autres emprunts - Overige schulden','L','17', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '2', 'CLASSE 2 -- FRAIS D''ETABLISSEMENT, ACTIFS IMMOBILISES, ... - OPRICHTINGSKOSTEN, VASTE ACTIVA, ...', NULL);
SELECT account_heading_save(NULL, '20', 'Frais d''établissement - Oprichtingskosten', NULL);
SELECT account__save(NULL,'200','Frais de constitution - Kosten van oprichting','A','20', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'200000','Fr. const. acquis. anterieurs - Kost. opricht./kapitaalverhoging','A','20', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'605','Achats d''immeubles destinés vente - Aankopen onroer. goederen bestemd v. verkoop','E','60', NULL, false, false, string_to_array('IC_cogs', ':'), false, false);
SELECT account_heading_save(NULL, '61', 'Services et biens divers', NULL);
SELECT account_heading_save(NULL, '69', 'Affectations et prélèvements', NULL);
SELECT account__save(NULL,'200900','Fr. const. amort. anterieur - Afschr. kost. opricht./kap.verh. vorig','A','20', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'200910','Fr. const. amort. de l''exercice - Afschr. kost. opricht./kap.verh. dit','A','20', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'612020','Electricité','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'202','Autres frais d''établissement - Overige oprichtingskosten','A','20', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'204','Frais de restructuration - Herstructureringskosten','A','20', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'201','Frais d''émission d''emprunts - Kosten bij uitgifte van leningen','A','20', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '21', 'Immobilisations incorporelles - Immateriele vaste activa', NULL);
SELECT account__save(NULL,'211','Concessions, brevets, licences, ... - Consessies, octrooien, licenties, ...','A','21', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'210','Frais de recherches et developpement - Kosten van onderzoek en ontwikkeling','A','21', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'212','Goodwill','A','21', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'213','Acomptes versés - Vooruitbetalingen','A','21', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'214','Surprix afférents acquisition d''une participation','A','21', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '22', 'Terrains et constructions - Terreinen en gebouwen', NULL);
SELECT account_heading_save(NULL, '743', '743-749 Produits d''exploitation divers - Diverse bedrijfsopbrengsten', NULL);
SELECT account__save(NULL,'580000','TRANSFERTS INTERNES DES FONDS - TRANSFERTEN','A','58', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'221','Constructions - Gebouwen','A','22', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'717100','Bénéfice pris en compte - Toegerekende winst','I','717', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '756', '756-759 Produits financiers divers - Diverse financiële opbrengsten', NULL);
SELECT account__save(NULL,'222','Terrains bâtis - Bebouwde terreinen','A','22', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '13', 'Réserves - Reserves', NULL);
SELECT account__save(NULL,'223','Autres droits réels sur immeubles - Overige zakelijke rechten op onroe.','A','22', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'221000','Constructions acquis. anterieurs - Geb. aanschaffingsprijs vorig. boekj.','A','22', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'411594','TVA RECUP. 2E TRIMESTRE TOTAL','A','411', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'771','Impôts belges sur le résultat - Belgische belasting op het resultaat','I','77', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '23', 'Installations, machines et outillage - Installaties, machines en uitrusting', NULL);
SELECT account__save(NULL,'230','Installations - Installaties','A','23', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'230000','Inst. techniques acquis. anterieurs - Installaties m.b.t. vorig boekj.','A','23', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'620300','Ouvriers - Arbeiders','E','62', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'231','Machines','A','23', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'791','Prélèvement s/capital et primes émissions - Onttrek. kapitaal e. uitgiftepre.','I','79', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'220','Terrains - Terreinen','A','22', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'237','Outillage - Uitrusting','A','23', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'231000','Mach. et gros mat. acquis anterieurs - Machines m.b.t. vorig boekj.','A','23', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'613100','Assurance incendie','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'613275','Publications légales','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'237000','Outillage acquis. anterieurs - Uitrusting m.b.t. vorig boekj.','A','23', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '24', 'Mobilier et matériel roulant - Meubilair en rollend materieel', NULL);
SELECT account__save(NULL,'2401','Matériel de bureau - Bureaumaterieel','A','24', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'2402','Matériel informatique - Hardware','A','24', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'241','Voiture - Rollend materieel (wagen)','A','24', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '62', 'Rémunérations, charges sociales et pensions', NULL);
SELECT account_heading_save(NULL, '25', 'Immobilis. en loc-financement - Vaste activa in leasing of op grond', NULL);
SELECT account__save(NULL,'612120','GSM','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'242','Camions - Rollend materieel (vrachtwagen)','A','24', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'250','Terreins loc-fin - Terreinen in leasing','A','25', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'251','Install., machines loc-fin - Installaties, machines in leasing','A','25', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'309','Réduction val. act. mat. premières (-) - Geboekte waardev. grondst. (-)','A','30', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'253','Matériel en loc-fin - Uitrusting in leasing','A','25', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'254','Mat. inform. en loc-fin- Hardware in leasing','A','25', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'255','Mat. roulant en loc-fin - Rollend materieel leasing','A','25', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '26', 'Autres immobilisations corp. - Andere materiele vaste activa', NULL);
SELECT account__save(NULL,'260','Amenagement locaux loués - Inrichtingskost. gehuurde gebouw','A','26', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'613130','Assurance crédit','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'300','Approv. matière première - Grondstoffen','A','30', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'411595','TVA RECUP. 3E TRIMESTRE TOTAL','A','411', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '48', 'Dettes diverses - Diverse schulden', NULL);
SELECT account__save(NULL,'270','Immo. corp. en cours et acomptes versés - V. activa in aanbouw en vooruit','A','27', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'613300','Deplacements Belg. train, taxi, etc','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account_heading_save(NULL, '27', 'Immo. corp. en cours et acomptes versés - V. activa in aanbouw en vooruit ', NULL);
SELECT account__save(NULL,'252','Mobilier en loc-fin - Meubilair in leasing','A','25', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'168100','Impôts diff. s/+value immo. incorp. - Uitg. belast./meerwa./immat. v.a.','L','16', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'168700','Impôts diff. s/+value fonds publ. belges - Uitg. bel./meerwa./belg. effecten','L','16', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '28', 'Immobilisations financiers - Financiele vaste activa', NULL);
SELECT account__save(NULL,'620400','Autres membres du personnel - Andere personeelsleden','E','62', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'649','Ch. exploit. portées actif c. frais de restruct. (-) - Als herstruct.kost. geactiv. bedrijfsk. (-)','E','64', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '71', 'Variation stocks et commandes en cours - Wijzigingen vorraden en in de bestellingen in uitvoering', NULL);
SELECT account__save(NULL,'740','Subsides et montants compensat. - Subsidies en compens. bedragen','I','74', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'760','Reprises amort. et réduct. valeur - Terugneming afschr. en waardeverm.','E','76', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'280','Participations entreprises liées - Aanschaffingsw. deeln. verb. ond.','A','28', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'771000','Régularisations impôts dus versés - Regularisiering versch. of betaal. belast.','I','771', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'281','Créances s/entreprises liées - Vorderingen op rekening','A','28', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'283','Créances s/entr. avec lien de part.','A','28', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'284','Autres actions et parts - Aanschaffingsw. and. aand.','A','28', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'285','Autres créances -  Overige vorderingen','A','28', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'288','Cautions versés en numeraire - Borgtocht. betaald in contanten','A','28', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'792','Prélèvements réserves - Onttrekking reserves','I','79', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'173100','Promesses banque - Promessen bank','L','17', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'290','Créances commerciales - Commerciele vorderingen','A','29', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'441','Effets à payer - Te betalen wissels','L','44', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'430','Emprunts en compte à terme fixe - Leningen op rekeningen vaste termijn','L','43', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'451630','TVA sur NDC reçues (case 63)','L','45', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '29', 'Créances à plus d''un an - Vorderingen op meer dan een jaar', NULL);
SELECT account_heading_save(NULL, '45', 'Dettes fiscales, salariales, sociales - Schulden m. betrekking tot belastingen, bezoldingen en sociale lasten', NULL);
SELECT account__save(NULL,'452','Impôts et taxes à payer','L','45', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'290000','Clients > 1 an - Handelsdebiteuren > 1 jaar','A','29', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'290100','Effects à recevoir >1 an - Te innen wissels > 1 jaar','A','29', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'290600','Acptes versés s/immo. financ. > 1 an - Vooruitbetalingen > 1 jaar','A','29', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'290700','Créances douteuses - Dubieuze debiteuren >1 jaar','A','29', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'290900','Réduction valeur actée cr.dout. - Geboekte waardevermindering (-)','A','29', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'291','Autres Créances > 1 an - Over. vorderingen op rekening > 1 j.','A','29', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '30', 'Approv. matières premières - Grondstoffen', NULL);
SELECT account_heading_save(NULL, '3', 'CLASSE 3 -- STOCK ET COMMANDES EN COURS - GRONDSTOFFEN', NULL);
SELECT account__save(NULL,'453','Précompte retenus - Ingehouden voorheffingen','L','45', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'459','Autres dettes sociales - Andere sociale schulden','L','45', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '31', 'Approv. et fournitures - Hulpstoffen', NULL);
SELECT account__save(NULL,'431','Etabli. crédit, promesses - Kreditinstellingen, promessen','L','43', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'400','Clients - Handelsdebiteuren','A','40', NULL, false, false, string_to_array('AR', ':'), false, false);
SELECT account__save(NULL,'319','Réduction valeur actées (-) - Geboekte waardev. hulpstoffen (-)','A','31', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '32', 'Encours de fabrication - Goederen in bewerking', NULL);
SELECT account__save(NULL,'708','Remis. rabais ristourn. accordés (-) - Toegek. korting. ristorno''s rabat. (-) ','I','70', NULL, false, false, string_to_array('AR_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'741','Plus-values réalis. cour. immo. corp. -  Meerwaar. cour. realis. materiële v.a.','I','74', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '33', 'Produits finis - Gereed Product', NULL);
SELECT account_heading_save(NULL, '72', 'Production immobilisée - Geproduceerde vaste activa', NULL);
SELECT account__save(NULL,'656600','Intérêts rétards com. - Com. achterst. interest','E','65', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account_heading_save(NULL, '34', 'Marchandises - Handelsgoederen', NULL);
SELECT account__save(NULL,'221010','Construction acquis. de l''exercice - Geb. aanschaffingsprijs dit boekj.','A','22', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'760000','sur immobilisations incorp. - op immateriële vaste activa','I','760', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '35', 'Immeubles destinés vente - Onroerende goederen bestemd. v. verk.', NULL);
SELECT account__save(NULL,'771100','Régul. d''impôts estimés - Regul. geraamde belasting','I','771', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'793','Perte à reporter - Over te dragen verlies','I','79', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '4', 'CLASSE 4 -- CREANCES ET DETTES A UN AN AU PLUS - VORDERINGEN EN SCHULDEN OP TEN HOOGTE EEN JAAR', NULL);
SELECT account__save(NULL,'552000','KBC56','A','55', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'411596','TVA RECUP. 4E TRIMESTRE TOTAL','A','411', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'444','Factures à recevoir - Te ontvangen facturen','L','44', NULL, false, false, string_to_array('AP_paid', ':'), false, false);
SELECT account_heading_save(NULL, '40', 'Créances commerciales - Handelsvorderingen', NULL);
SELECT account__save(NULL,'329','Réduction valuer actée (-) - Geboekte waardeverminderingen (-) ','A','32', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'339','Réductions de valeur actées (-) - Geboekte waardeverminderingen (-) ','A','33', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'340','Marchandises - Handelsgoederen','A','34', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'451000','COMPTE COURANT TVA DUE','L','451', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'349','Réduct. valeur actées (-) - Geboekte waardeverminderingen (-) ','A','34', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'359','Réductions valeur actées (-) - Geboekte waardeverminderingen (-) ','A','35', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'613150','Assurance tous risques matériel élec.','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account_heading_save(NULL, '63', 'Amortissements, réd. val., provi. risques et charges - Afschrijvingen waardevermin. en voorzieningen v. risico''s kost.', NULL);
SELECT account__save(NULL,'510000','Titres cotés - Aandelen op beurs','A','51', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '5', 'CLASSE 5 - PLACEMENTS DE TRESORIERIE - LIQUIDE MIDDELEN / GELDBELEGGINGEN', NULL);
SELECT account_heading_save(NULL, '54', 'Valeurs échues à encaissement - Te incasseren verfallen waarden', NULL);
SELECT account_heading_save(NULL, '55', 'Banque - Rekening-courant', NULL);
SELECT account__save(NULL,'613303','Restaurants','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'310','Valeur d''acquisition - Aanschaffingswaarde hulpstoffen','A','31', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'320','Valeur d''acquisition - Aanschaffingsw. goed. bewerking','A','32', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'330','Produits finis - Gereed product','A','33', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'350','Immeubles - Aanschaffingsw. onr. goed. verkoop','A','35', NULL, false, false, string_to_array('IC', ':'), false, false);
SELECT account__save(NULL,'609','Variation de stock - Voorraadwijzigingen','E','60', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'621','Cotisation patronales d''assur. sociales - Werkgeversbijdragen soc. verzekeringen','E','62', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'451640','TVA à recupérer s/NDC émises','L','45', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'454','O.N.S.S. - R.S.Z.','L','45', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'640700','TVA non-deductible','E','64', NULL, false, false, string_to_array('AP_tax:IC_taxpart:IC_taxservice', ':'), false, false);
SELECT account__save(NULL,'401','Effets à recevoir - Te innen wissels','A','40', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'414','Produits à recevoir - Te innen opbrengsten','A','41', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'450','Dettes fiscales estimées - Geramd bedrag der belastingschulden','L','45', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account_heading_save(NULL, '46', 'Acomptes reçus sur commandes', NULL);
SELECT account__save(NULL,'499100','Compte de repartition - Verdelingsrekening','L','', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'553000','KBC40','A','55', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'613180','Assurance RC professionnelle','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'452500','Précompte immobilier - Onroerende voorhoeffing','L','45', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'554000','KBC83','A','55', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'612150','Frais postaux','E','61', NULL, false, false, string_to_array('AP_amount:IC_cogs:IC_expense', ':'), false, false);
SELECT account__save(NULL,'451545','TVA due 4e trimestre','L','451', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'200010','Fr. const. acquis. de l''exercice - Kost. opricht./kap.verh. dit boekjaar','A','20', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'451542','TVA due 1er trimestre (case 54)','L','451', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'451570','TVA DUE SUR IMPORTATIONS','L','451', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'540','Chèques à encaisser - Te incasseren chèques','A','54', NULL, false, false, string_to_array('AR_paid:AP_paid', ':'), false, false);
SELECT account__save(NULL,'611340','Entretiens & réparations locaux','E','61', NULL, false, false, string_to_array('AR_amount:AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'665000','Pertes et charges diverses','E','66', NULL, false, false, string_to_array('AR_paid:AP_amount', ':'), false, false);
SELECT account__save(NULL,'665200','Perte définitive créance douteuse','E','66', NULL, false, false, string_to_array('AP_amount', ':'), false, false);
SELECT account__save(NULL,'237010','Outillage acquisition exercice - Uitrusting m.b.t. dit boekj.','A','23', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'623600','Vêtements de travail employés','E','62', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'612520','Emballages perdus','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'240200','Mat. informatique acquis anterieurs - Hardware m.b.t. vorig boekj.','A','24', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'240210','Matériel informatique acquis. exercice - Hardware m.b.t. dit boekj.','A','24', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'260000','Amenagement locaux loués acquis anterieurs - Inrichtingskost. m.b.t. vorig boekj.','A','26', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'240000','Mobilier acquis. anterieurs - Meubilair m.b.t. vorig boekj.','A','24', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'240010','Mobilier acquis. exercice - Meubilair m.b.t. dit boekj.','A','24', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'240110','Mat. bureau acquis. exercice - Bureaumaterieel m.b.t. dit boekj.','A','24', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'240100','Mat. bureau acquis. anterieurs - Bureaumaterieel m.b.t. vorig boekj.','A','24', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'241000','Voiture acquis. anterieurs - Wagen m.b.t. vorig boekj.','A','24', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'241010','Voiture acquis. exercice - Wagen m.b.t. dit boekj. ','A','24', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account_heading_save(NULL, '57', 'Caisses - Kassen', NULL);
SELECT account__save(NULL,'510200','Titrés non-cotés - Aandelen niet op beurs','A','51', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'510090','Réduct. valeur actées (-) - Geb. waardev. aandelen (-)','A','51', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'510210','	Montants non-appelés (-) - Niet opgevraagde bedragen aan. (-)','A','51', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'510290','Réduct. valeur actées (-) - Geb. waardev. aandelen (-) ','A','51', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'614700','Frais de bonne politique','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'615000','Sous-traitants','E','61', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'630000','Amort.s/frais.constit.&aug.capi - Afschr.o.opricht./kapitaalverhoging','E','63', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'630210','Amort.s/constructions - Afschr. op gebouwen','E','63', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'630200','Amort.s/installations - Afschr. op installaties','E','63', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'630220','Amort.s/machines - Afschr. op machines','E','63', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'630221','Amort.s/outillage - Afschr. op uitrusting','E','63', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'630222','Amort.s/mobilier - Afschr. op meubilair','E','63', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'630223','Amort.s/mat.bureau - Afschr. op bureaumaterieel','E','63', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'630224','Amort.s/mat.informatique - Afschr. op hardware','E','63', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'630230','Amort.s/voitures - Afschr. op wagens','E','63', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'640000','Taxes circl. voitures - Belasting wagens','E','64', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'652000','Moins-value sur réalisation d''actifs circulants','E','65', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'640020','Précompte immoblier - Onroerende voorhoeffing','E','64', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'640100','Timbres fiscaux','E','64', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'640230','Raccordement aux egouts','E','64', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'640310','Cotisation dépannage','E','64', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'630225','Amort.s/amén. locaux - Afschr. op inrichtingskost','E','63', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'650000','Intérêts comm. & frais s/decouvert','E','65', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'656300','Intérêts de retards fiscaux - Fiscale achterst. interest','E','65', NULL, false, false, string_to_array('AP_amount:IC_expense', ':'), false, false);
SELECT account__save(NULL,'693000','Bénéfice à reporter','E','69', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'663750','-Val.s/materiel informatique','E','66', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'743300','Intervention assurance salaires garant.','I','74', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'763750','+Val.s/mat.informatique','I','76', NULL, false, false, string_to_array('', ':'), false, false);
SELECT account__save(NULL,'406','Acomptes versés - Vooruitbetalingen','A','40', NULL, false, false, string_to_array('AP_paid', ':'), false, false);
--
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '411590'), 0.06);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '411591'), 0.21);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '451540'), 0.06);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '451541'), 0.21);
INSERT INTO tax (chart_id, rate) VALUES ((SELECT id FROM account WHERE accno = '640700'), 0.21);
--
INSERT INTO defaults (setting_key, value) VALUES ('inventory_accno_id', (SELECT
id FROM account WHERE accno = '340'));

 INSERT INTO defaults (setting_key, value) VALUES ('income_accno_id', (SELECT id FROM account WHERE accno = '743200'));

 INSERT INTO defaults (setting_key, value) VALUES ('expense_accno_id', (SELECT id FROM account WHERE accno = '604'));

 INSERT INTO defaults (setting_key, value) VALUES ('fxgain_accno_id', (SELECT id FROM account WHERE accno = '755000'));

 INSERT INTO defaults (setting_key, value) VALUES ('fxloss_accno_id', (SELECT id FROM account WHERE accno = '655000'));

 INSERT INTO defaults (setting_key, value) VALUES ('weightunit', 'kg');
 INSERT INTO defaults (setting_key, value) VALUES ('curr', 'EUR:USD');

commit;
UPDATE account
   SET tax = true
WHERE id
   IN (SELECT account_id
       FROM account_link
       WHERE description LIKE '%_tax');

SELECT cr_coa_to_account_save(accno, accno || '--' || description)
FROM account WHERE accno = '55';

