begin;
-- General COA
--
SELECT account_save(NULL,'420','Büroeinrichtung','420','A', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'430','Ladeneinrichtung','430','A', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'440','Werkzeuge','440','A', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'450','Einbauten','450','A', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'460','Gerüst- und Schalungsmaterial','460','A', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'480','Geringwertige Wirtschaftsgüter bis DM 800,-','480','A', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'490','Sonstige Betriebs- und Geschäftsausstattung','490','A', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'650','Verb. gg. Kreditinstituten - Restlaufz. größer 5 Jahre','650','L', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'1000','Kasse','1000','A', NULL, false,string_to_array('AR_paid:AP_paid', ':'));
SELECT account_save(NULL,'1200','Bank-Giro','1200','A', NULL, false,string_to_array('AR_paid:AP_paid', ':'));
SELECT account_save(NULL,'1400','Forderungen aus Lief. und Leist. Kundengruppe 0','1400','A', NULL, false,string_to_array('AR', ':'));
SELECT account_save(NULL,'1540','Steuerüberzahlungen','1540','A', NULL, false,string_to_array('AR', ':'));
SELECT account_save(NULL,'1542','Steuererstattungsansprüche gg. anderen EU-Ländern','1542','A', NULL, false,string_to_array('AR', ':'));
SELECT account_save(NULL,'1545','Umsatzsteuerforderungen','1545','A', NULL, false,string_to_array('AR', ':'));
SELECT account_save(NULL,'1548','Vorsteuer im Folgejahr abziehbar','1548','A', NULL, false,string_to_array('AR', ':'));
SELECT account_save(NULL,'1570','Abziehbare Vorsteuer','1570','A', NULL, false,string_to_array('AR_tax:AP_tax', ':'));
SELECT account_save(NULL,'1571','Abziehbare Vorsteuer, 7%','1571','A', NULL, false,string_to_array('AR_tax:AP_tax:IC_taxpart:IC_taxservice', ':'));
SELECT account_save(NULL,'1575','Abziehbare Vorsteuer, 16%','1575','A', NULL, false,string_to_array('AR_tax:AP_tax:IC_taxpart:IC_taxservice', ':'));
SELECT account_save(NULL,'1576','Abziehbare Vorsteuer, 15%','1576','A', NULL, false,string_to_array('AR_tax:AP_tax:IC_taxpart:IC_taxservice', ':'));
SELECT account_save(NULL,'1577','Vorsteuer nach allg. Durchschnittssätzen UStVA KZ 63','1577','A', NULL, false,string_to_array('AR_tax:AP_tax', ':'));
SELECT account_save(NULL,'1775','Umsatzsteuer, 16%','1775','L', NULL, false,string_to_array('AR_tax:AP_tax:IC_taxpart:IC_taxservice', ':'));
SELECT account_save(NULL,'1776','Umsatzsteuer, 15%','1776','L', NULL, false,string_to_array('AR_tax:AP_tax:IC_taxpart:IC_taxservice', ':'));
SELECT account_save(NULL,'1780','Umsatzsteuer - Vorauszahlungen','1780','L', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'1781','Umsatzsteuer - Vorauszahlungen 1/11','1781','L', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'1782','Nachsteuer, UStVA KZ 65','1782','L', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'1789','Umsatzsteuer laufendes Jahr','1789','L', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'1790','Umsatzsteuer Vorjahr','1790','L', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'1791','Umsatzsteuer frühere Jahre','1791','L', NULL, false,string_to_array('', ':'));
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1820','Sonderausg. beschr. abzugsf. (Privat Vollhaft./Einzelu.)','A','','','1820');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1830','Sonderausg. unbeschr. abzugsf. (Privat Vollhaft./Einzelu.)','A','','','1830');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1840','Privatspenden (Privat Vollhafter / Einzelunternehmer)','A','','','1840');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1850','Außergewöhnliche Belastungen (Privat Vollhaft. / Einzelunt.)','A','','','1850');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('1890','Privateinlagen (Privat Vollhafter / Einzelunternehmer)','A','','','1890');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2010','Betriebsfremde Aufw. (soweit nicht außerordentlich)','A','','','2010');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2020','Periodenfremde Aufw. (soweit nicht außerordentlich)','A','','','2020');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2100','Zinsen und ähnliche Aufwendungen','A','','','2100');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2103','Steuerlich abzugsfähige, andere Nebenleistungen zu Steuern','A','','','2103');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2104','Steuerlich nicht abzugsfähige, andere Nebenleistungen zu Steuern','A','','','2104');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2107','Zinsaufwendungen §233a AO betriebliche Steuern','A','','','2107');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2108','Zinsaufw. §233a, §234, §237 AO Personenst. §8 GewStG','A','','','2108');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2109','Zinsaufwendungen an verbundene Unternehmen','A','','','2109');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('2110','Zinsaufwendungen für kurzfristige Verbindlichkeiten','A','','','2110');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3410','Wareneingang, 16% Vorsteuer','A','','','3410');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3736','Erhaltene Skonti, 16% Vorsteuer','A','','','3736');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3740','Erhaltene Boni','A','','','3740');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3750','Erhaltene Boni,   7% Vorsteuer','A','','','3750');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3760','Erhaltene Boni, 15%+16% Vorsteuer','A','','','3760');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3762','Erhaltene Boni, 16% Vorsteuer','A','','','3762');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3764','Erhaltene Boni, 15% Vorsteuer','A','','','3764');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3800','Anschaffungsnebenkosten','A','','','3800');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3830','Leergut','A','','','3830');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3850','Zölle und Einfuhrabgaben','A','','','3850');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3960','Bestandsv. Roh-, Hilfs- u. Betriebsstoffe / bezogene Waren','A','','','3960');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3970','Bestand Roh-, Hilfs- und Betriebsstoffe','A','','','3970');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3980','Bestand Waren','A','','','3980');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('3990','Verrechnete Stoffkosten','A','','','3990');
SELECT account_save(NULL,'4000','Material- und Stoffverbrauch','4000','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4100','Löhne und Gehälter','4100','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4110','Löhne','4110','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4120','Gehälter','4120','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4124','Geschäftsführergehälter der GmbH-Gesellschafter','4124','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4125','Ehegattengehalt','4125','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4126','Tantiemen','4126','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4127','Geschäftsführergehälter','4127','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4128','Vergütungen an angestellte Mitunternehmer §15 EStG','4128','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4130','Gesetzliche soziale Aufwendungen','4130','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4137','Gesetzliche soziale Aufw. für Mitunternehmer §15 EStG','4137','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4138','Beiträge zur Berufsgenossenschaft','4138','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'1360','Geldtransit Bank 1','1360','A', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'4140','Freiw. soziale Aufwendungen (lohnsteuerfrei)','4140','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4145','Freiw. soziale Aufwendungen (lohnsteuerpflichtig)','4145','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4149','Pauschale Lohnsteuer auf s. Bezüge (z.B. Fahrtkostenzuschuß)','4149','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4150','Krankengeldzuschüsse','4150','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4160','Versorgungskassen','4160','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4165','Aufwendungen für die Altersversorgung','4165','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4167','Pauschale Lohnsteuer auf s. Bezüge (z.B. Direktversicherung)','4167','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4168','Aufw. f. die Altersversorgung f. Mitunternehmer §15 EStG','4168','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4169','Aufwendungen für Unterstützung','4169','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4170','Vermögenswirksame Leistungen','4170','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4175','Fahrtkostenerstattung - Wohnung / Arbeitsstätte','4175','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4180','Bedienungsgelder','4180','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4190','Aushilfslöhne','4190','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4199','Lohnsteuer für Aushilfen','4199','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4200','Raumkosten','4200','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4210','Miete','4210','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4218','Gewerbesteuerlich zu berücks. Miete §8 GewStG','4218','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4219','Vergütung an Mitu. f. mietw. Überl. v. Wirtschaftsg. §15EStG','4219','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4220','Pacht','4220','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4228','Gewerbesteuerlich zu berücks. Pacht §8 GewStG','4228','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4229','Vergütung an Mitu. f. pachtw. Überl. v. Wirtschaftsg.§15EStG','4229','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4230','Heizung','4230','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4240','Gas, Strom, Wasser (Verwaltung, Vertrieb)','4240','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4250','Reinigung','4250','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4260','Instandhaltung betrieblicher Räume','4260','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4270','Abgaben für betrieblich genutzten Grundbesitz','4270','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4280','Sonstige Raumkosten','4280','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4320','Gewerbesteuer (Vorauszahlung)','4320','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4330','Gewerbeertragsteuer','4330','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4335','Gewerbekapitalsteuer','4335','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4340','Sonstige Betriebsteuern','4340','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4350','Verbrauchsteuer','4350','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4360','Versicherungen','4360','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4380','Beiträge','4380','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4390','Sonstige Abgaben','4390','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4396','Steuerlich abzugsfähige Verspätungszuschläge und Zwangsgelder','4396','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4397','Steuerlich nicht abzugsfähige Verspätungszuschläge und Zwangsgelder','4397','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4400','Besondere Kosten (zur freien Verfügung)','4400','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4500','Fahrzeugkosten','4500','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4510','Kfz-Steuern','4510','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4520','Kfz-Versicherungen','4520','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4530','Laufende Kfz-Betriebskosten','4530','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4540','Kfz-Reparaturen','4540','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4550','Garagenmieten','4550','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4570','Fremdfahrzeuge','4570','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4580','Sonstige Kfz-Kosten','4580','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4600','Werbe- und Reisekosten','4600','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4610','Werbekosten','4610','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4630','Geschenke bis DM 75,00','4630','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4635','Geschenke über DM 75,00','4635','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4638','Geschenke ausschließlich betrieblich genutzt','4638','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4640','Repräsentationskosten','4640','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4650','Bewirtungskosten','4650','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4653','Aufwerksamkeiten','4653','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4654','Nicht abzugsfähige Bewirtungskosten','4654','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4655','Nicht abzugsfähige Betriebsausgaben','4655','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4660','Reisekosten Arbeitnehmer','4660','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4666','Reisekost. Arbeitn., 12,3%/13,1% VSt  Verpfl.Mehr- / Übern.Aufw.','4666','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4667','Reisekost. Arbeitn., 9,8%/10,5% VSt Gesamtpauschal.','4667','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4670','Reisekosten Unternehmer','4670','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4675','Reisekosten Unternehmer, 9,8/10,5% VSt sonst.Gesamtpauschal.','4675','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4676','Reisekost. Untern., 12,3%/13,1% VSt Verpfl.Mehr- / Übern.Aufw.','4676','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4677','Reisekosten Unternehmer, 9,8%/10,5% VSt Verpfl.Mehraufw. Gesamtpauschal.','4677','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4678','Km-Geld Erstattung, Unternehmer, 5,7%/6,1% VSt','4678','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4685','Km-Geld-Erstattung, Arbeitnehmer  8,2%/8,7% VSt','4685','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4700','Kosten der Warenabgabe','4700','E', NULL, false,string_to_array('AP_amount:IC_expense:IC_cogs', ':'));
SELECT account_save(NULL,'4710','Verpackungsmaterial','4710','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4730','Ausgangsfrachten','4730','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4750','Transportversicherungen','4750','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4760','Verkaufsprovisionen','4760','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4780','Fremdarbeiten','4780','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4790','Aufwand für Gewährleistungen','4790','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4800','Reparat. u. Inst. v. Maschinen u. technischen Anlagen','4800','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4805','Reparat. u. Inst. v. and. Anl. d. Betr.- u. Geschäftsausst.','4805','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4809','Sonstige Reparaturen und Instandhaltungen','4809','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4810','Mietleasing','4810','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4815','Kaufleasing','4815','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4820','Abschr. a. Aufw. f.d. Ingangs. u. Erw. des Geschäftsbetr.','4820','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4822','Abschr. a. immaterielle Vermögensgegenstände','4822','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4824','Abschreibung auf den Geschäfts- oder Firmenwert','4824','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4826','Außerplanm. Abschr. a. immaterielle Vermögensgegenstände','4826','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4830','Abschreibungen auf Sachanlagen','4830','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4840','Außerplanm. Abschreibungen auf Sachanlagen','4840','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4850','Abschr. a. Sachanl. aufgrund steuerl. Sondervorschriften','4850','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4855','Sofortabschreibung geringwertiger Wirtschaftsgüter','4855','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4860','Abschreibung auf aktivierte, geringwertige Wirtschaftsgüter','4860','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4865','Außerplanmäßige Abschr. a. aktivierte GWG','4865','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4870','Abschreibungen auf Finanzanlagen','4870','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4872','Abschr. aufgrund v. Verlustant. an Mitunt. §8 GewStG','4872','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4874','Abschr. a. Finanzanl. aufgrund steuerl. Sondervorschriften','4874','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4875','Abschreibungen auf Wertpapiere des Umlaufvermögens','4875','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4880','Abschr. a. Umlaufv. ohne Wertpapiere (soweit unübl. Höhe)','4880','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4882','Abschr. a. Umlaufv. steuerrechtl. bedingt (unübl. Höhe)','4882','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4887','Abschr. a. Umlaufv., steuerrechtlich bedingt (übl. Höhe)','4887','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4890','Vorwegn. künftiger Wertschw. im Umlaufv. (unübl. Höhe)','4890','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4900','Sonstige betriebliche Aufwendungen','4900','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4905','Sonstige Aufwendungen betrieblich und regelmäßig','4905','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4910','Porto','4910','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4920','Telefon','4920','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4925','Telefax, Fernschreiber','4925','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4930','Bürobedarf','4930','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4940','Zeitschriften, Bücher','4940','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4945','Fortbildungskosten','4945','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4946','Freiwillige Sozialleistungen','4946','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4948','Vergütungen an freiberufliche Mitunternehmer §15 EStG','4948','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4950','Rechts- und Beratungskosten','4950','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4955','Buchführungskosten','4955','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4957','Abschluß- und Prüfungskosten','4957','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4960','Mieten für Einrichtungen','4960','E', NULL, false,string_to_array('AP_amount', ':'));
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4968','Gewerbest. zu berücks. Miete f. Einrichtungen §8 GewStG','A','','','4968');
SELECT account_save(NULL,'4969','Aufwendungen für Abraum- und Abfallbeseitigung','4969','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4970','Nebenkosten des Geldverkehrs','4970','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4980','Betriebsbedarf','4980','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4985','Werkzeuge und Kleingeräte','4985','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4996','Herstellungskosten','4996','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4997','Verwaltungskosten','4997','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'4998','Vertriebskosten','4998','E', NULL, false,string_to_array('AP_amount', ':'));
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('4999','Gegenkonto 49960-49980','A','','','4999');
SELECT account_save(NULL,'7140','Fertige Waren (Bestand)','7140','A', NULL, false,string_to_array('IC', ':'));
SELECT account_save(NULL,'8100','Steuerfreie Umsätze o. VSt-Abzug §4 Nr.8 ff. UStG','8100','I', NULL, false,string_to_array('AR_amount:IC_sale', ':'));
SELECT account_save(NULL,'8500','Provisionserlöse','8500','I', NULL, false,string_to_array('AR_amount:IC_sale', ':'));
SELECT account_save(NULL,'8504','Provisionserlöse steuerfrei (§4 Nr.8ff UStG)','8504','I', NULL, false,string_to_array('AR_amount:IC_sale', ':'));
SELECT account_save(NULL,'8505','Provisionserlöse steuerfrei (§4 Nr.5 UStG)','8505','I', NULL, false,string_to_array('AR_amount:IC_sale', ':'));
SELECT account_save(NULL,'8506','Provisionserlöse,  7% USt','8506','I', NULL, false,string_to_array('AR_amount:IC_sale', ':'));
SELECT account_save(NULL,'8507','Provisionserlöse, 15% Ust','8507','I', NULL, false,string_to_array('AR_amount:IC_sale', ':'));
SELECT account_save(NULL,'8508','Provisionserlöse, 15%/16% USt','8508','I', NULL, false,string_to_array('AR_amount:IC_sale', ':'));
SELECT account_save(NULL,'8509','Provisionserlöse, 16% Ust','8509','I', NULL, false,string_to_array('AR_amount:IC_sale', ':'));
SELECT account_save(NULL,'8591','Sachbezüge,   7% USt (Waren)','8591','I', NULL, false,string_to_array('AR_amount:IC_sale', ':'));
SELECT account_save(NULL,'8595','Sachbezüge, 15%/16% USt (Waren)','8595','I', NULL, false,string_to_array('AR_amount:IC_sale', ':'));
SELECT account_save(NULL,'8596','Sachbezüge, 16% USt (Waren)','8596','I', NULL, false,string_to_array('AR_amount:IC_sale', ':'));
SELECT account_save(NULL,'8597','Sachbezüge, 15% USt (Waren)','8597','I', NULL, false,string_to_array('AR_amount:IC_sale', ':'));
SELECT account_save(NULL,'8630','Sonstige Erlöse betrieblich und regelmäßig, 7% USt','8630','I', NULL, false,string_to_array('AR_amount:IC_sale', ':'));
SELECT account_save(NULL,'8645','Sonstige Erlöse betrieblich und regelmäßig, 16% Ust','8645','I', NULL, false,string_to_array('AR_amount:IC_sale', ':'));
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8730','Gewährte Skonti','A','','','8730');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8731','Gewährte Skonti,  7% USt','A','','','8731');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8735','Gewährte Skonti, 16% Ust','A','','','8735');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8740','Gewährte Boni','A','','','8740');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8750','Gewährte Boni,  7% USt','A','','','8750');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8762','Gewährte Boni, 16% Ust','A','','','8762');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8770','Gewährte Rabatte','A','','','8770');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8780','Gewährte Rabatte,  7% USt','A','','','8780');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8792','Gewährte Rabatte, 16% Ust','A','','','8792');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8800','Erlöse aus Anlagenverkäufen','A','','','8800');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8801','Erlöse aus Anlagenverkäufen 15%/16% USt (bei Buchverlust)','A','','','8801');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8810','Erlöse aus Anlagenverkäufen 16% USt (bei Buchverlust)','A','','','8810');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8815','Erlöse aus Anlagenverkäufen 15% USt (bei Buchverlust)','A','','','8815');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8820','Erlöse aus Anlagenverkäufen 15%/16% USt (bei Buchgewinn)','A','','','8820');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8829','Erlöse aus Anlagenverkäufen (bei Buchgewinn)','A','','','8829');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8830','Erlöse aus Anlagenverkäufen 16% USt (bei Buchgewinn)','A','','','8830');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8835','Erlöse aus Anlagenverkäufen 15% USt (bei Buchgewinn)','A','','','8835');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8900','Eigenverbrauch','A','','','8900');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8905','Entnahme Gegenstände ohne USt','A','','','8905');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8908','Entnahme von Gegenstände, 16% USt §1 Abs.1 Nr.2a UStG','A','','','8908');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8909','Entnahme von Gegenstände, 15% USt §1 Abs.1 Nr.2a UStG','A','','','8909');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8910','Entnahme von Gegenstände, 15%/16% USt §1 Abs.1 Nr.2a UStG','A','','','8910');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8915','Entnahme von Gegenstände, 7% USt §1 Abs.1 Nr.2a UStG','A','','','8915');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8920','Entnahme v. sonst. Leist., 15%/16% USt §1 A.1 Nr.2b UStG','A','','','8920');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8930','Entnahme v. sonst. Leist., 7% USt §1 A.1 Nr.2b UStG','A','','','8930');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8937','Entnahme v. sonst. Leist., 16% USt §1 A.1 Nr.2b UStG','A','','','8937');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8938','Entnahme v. sonst. Leist., 15% USt §1 A.1 Nr.2b UStG','A','','','8938');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8939','Entnahme v. sonst. Leist., ohne USt §1 A.1 Nr.2b UStG','A','','','8939');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8941','Eigenverbr., 7% Ust §4 A.1 Nr.5 1-7, A.7 EStG','A','','','8941');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8942','Eigenverbr., 16% Ust  §4 A.1 Nr.5 1-7, A.7 EStG','A','','','8942');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8944','Eigenverbr., ohne Ust §4 A.1 Nr.5 1-7, A.7 EStG','A','','','8944');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8950','Nicht steuerbare Umsätze','A','','','8950');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8955','Umsatzsteuervergütungen','A','','','8955');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8960','Bestandsveränd. - unfertige Erzeugnisse','A','','','8960');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8970','Bestandsveränd. - unfertige Leistungen','A','','','8970');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8975','Bestandsveränd. - in Ausführung befindliche Bauaufträge','A','','','8975');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8977','Bestandsveränd. - in Arbeit befindliche Aufträge','A','','','8977');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8980','Bestandsveränd. - fertige Erzeugnisse','A','','','8980');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('8990','Bestandsveränd. - andere aktivierte Eigenleistungen','A','','','8990');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9000','Saldenvorträge Sachkonten','A','','','9000');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9008','Saldenvorträge Debitoren','A','','','9008');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9009','Saldenvorträge Kreditoren','A','','','9009');
INSERT INTO chart (accno,description,charttype,category,link,gifi_accno) VALUES ('9100','Saldovortragskonto der Statistikkonten','A','','','9100');
SELECT account_save(NULL,'1800','Privatentn. allg. (Privat Vollhafter / Einzelunternehmer)','1800','Q', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'2000','Außerordentliche Aufwendungen','2000','A', NULL, false,string_to_array('', ':'));
SELECT account_save(NULL,'1600','Verb. aus Lief. und Leist. Lieferantengruppe 0','1600','L', NULL, false,string_to_array('AP', ':'));
SELECT account_save(NULL,'3400','Wareneingang, 16% Vorsteuer','3400','E', NULL, false,string_to_array('AP_amount', ':'));
SELECT account_save(NULL,'8400','Umsatzerlöse 16%','8400','I', NULL, false,string_to_array('AR_amount:IC_sale', ':'));
SELECT account_save(NULL,'8840','Erträge aus Kursdifferenzen','8840','I', NULL, false,string_to_array('AR_amount:IC_sale:IC_income', ':'));
--
insert into tax (chart_id,rate) values ((select id from chart where accno = '1571'),0.07);
insert into tax (chart_id,rate) values ((select id from chart where accno = '1575'),0.16);
insert into tax (chart_id,rate) values ((select id from chart where accno = '1576'),0.15);
insert into tax (chart_id,rate) values ((select id from chart where accno = '1775'),0.16);
insert into tax (chart_id,rate) values ((select id from chart where accno = '1776'),0.15);
insert into tax (chart_id,rate) values ((select id from chart where accno = '3400'),0.16);
insert into tax (chart_id,rate) values ((select id from chart where accno = '8400'),0.16);
--
INSERT INTO defaults (setting_key, value) VALUES ('inventory_accno_id', (select id from chart where accno = '7140'));

 INSERT INTO defaults (setting_key, value) VALUES ('income_accno_id', (select id from chart where accno = '8400'));

 INSERT INTO defaults (setting_key, value) VALUES ('expense_accno_id', (select id from chart where accno = '4700'));

 INSERT INTO defaults (setting_key, value) VALUES ('fxgain_accno_id', (select id from chart where accno = '8840'));

 INSERT INTO defaults (setting_key, value) VALUES ('fxloss_accno_id', (select id from chart where accno = '8840'));

 INSERT INTO defaults (setting_key, value) VALUES ('curr', 'EUR:USD');

 INSERT INTO defaults (setting_key, value) VALUES ('weightunit', 'kg');
--
commit;
