begin;
-- selon PLAN COMPTABLE MINIMUM NORMALISE BELGE
-- contribu. par Jens-Ingo Brodesser, jens-ingo@all2all.org
-- verified May 19, 2006
--
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('756000', 'Produits financiers divers', 'A', 'I', 'AR_paid:AP_paid', '75', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('555000', 'DEX02', 'A', 'A', 'AR_paid:AP_paid', '55', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('499200', 'Compte de repartition NDC - Verdelingsrekening CN', 'A', 'L', 'AR_paid:AP_paid', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('460', 'Acomptes reçus sur commandes', 'A', 'L', 'AR_paid', '46', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('4168', 'Rabais, ristournes, remises à obtenir et autres avoirs non encore reçus', 'A', 'A', 'AP_paid', '416', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('43', 'Dettes financières - Financiële schulden', 'H', 'L', '', '43', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('2400', 'Mobilier - Meubilair', 'A', 'A', '', '24', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('240190', 'Matériel bureau amort. anterieurs - Afschr. op bureaumaterieel vorig boekj.', 'A', 'A', '', '24', '1');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('221900', 'Constructions amort. anterieurs - Afschr. op gebouwen vorig boekj.', 'A', 'A', '', '22', '1');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('221910', 'Constructions amort. de l''exercice - Afschr. op gebouwen dit boekj.', 'A', 'A', '', '22', '1');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('75', 'Produits financiers - Financiële opbrengsten', 'H', 'I', '', '75', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('230900', 'Inst. techniques amort. anterieurs - Afschr. op installaties vorig boekj.', 'A', 'A', '', '23', '1');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('240090', 'Mobilier amort. anter. - Afschr. op meubilair vorig boekj.', 'A', 'A', '', '24', '1');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('240091', 'Mobilier amort. exercice - Afschr. op meubilair dit boekj.', 'A', 'A', '', '24', '1');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('240191', 'Matériel bureau amort. exercice - Afschr. op bureaumaterieel dit boekj.', 'A', 'A', '', '24', '1');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('240290', 'Materiel Informatique amort. anter. - Afschr. op hardware vorig boekj.', 'A', 'A', '', '24', '1');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('240291', 'Mat. informat. amort. exercice - Afschr. op hardware dit boekj.', 'A', 'A', '', '24', '1');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('241900', 'Voiture amort. anter. - Afschr. op wagen vorig boekj.', 'A', 'A', '', '24', '1');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('241910', 'Voiture amort. exercice - Afschr. op wagen dit boekj. ', 'A', 'A', '', '24', '1');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('260900', 'Amen. loc. loués amort. anter. - Inrichtingskost. vorig boekj.', 'A', 'A', '', '26', '1');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('230910', 'Inst. techniques amort. exercice - Afschr. op installaties dit boekj.', 'A', 'A', '', '23', '1');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('231900', 'Mach. et gros mat. amort. anterieurs - Afschr. op machines vorig boekj.', 'A', 'A', '', '23', '1');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('231910', 'Mach. et gros mat. amort. exercice - Afschr. op machines dit boekj.', 'A', 'A', '', '23', '1');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('237900', 'Outillage amort. anterieurs - Afschr. op uitrusting vorig boekj.', 'A', 'A', '', '23', '1');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('237910', 'Outillage amort. exercice - Afschr. op uitrusting dit boekj.', 'A', 'A', '', '23', '1');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('260910', 'Amen. loc. loués amort. exercice - Inrichtingskost. dit boekj.', 'A', 'A', '', '26', '1');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('451541', 'TVA DUE VENTES 21%', 'A', 'L', 'AR_tax:IC_taxpart:IC_taxservice', '451', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('612200', 'Carburants voitures', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('630', 'Dotations amort., réduction valeur s/immo. - Afschr., waardeverm. op v. a., toevoeging', 'A', 'E', '', '63', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('613210', 'Honoraires avocats', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('712', 'Des encours de fabrication - In de vooraad goederen in bewerking', 'A', 'I', 'IC_sale', '71', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('600', 'Achats matières premières - Aankopen van grondstoffen', 'A', 'E', 'IC_cogs', '60', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('614400', 'Entrée aux foires', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('742', 'Plus-values créances com. - Meerwaarden realis. handelsvorderingen', 'A', 'I', '', '74', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('613304', 'Traiteurs-réception clientèle', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('64', 'Autres charges exploitation - Andere bedrijfskosten', 'H', 'E', '', '64', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('76', 'Produits exceptionnels - Uitzonderlijke opbrengsten', 'H', 'I', '', '76', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('743000', 'Ventes diverses - Diverse bedrijfsopbrengsten', 'A', 'I', '', '74', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('760100', 'sur immobilisations corp. - op materiële vaste activa', 'A', 'I', '', '760', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('611150', 'Charges locatives voitures', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('771200', 'Reprises de provisions fiscales - Terugn. fiscale voorz.', 'A', 'I', '', '771', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('794', 'Intervention associé perte - Tussenkomst vennoten verlies', 'A', 'I', '', '79', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('404', 'Produits à recevoir - Te innen opbrengsten', 'A', 'A', '', '40', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('500', 'Action propres - Eigen aandelen', 'A', 'A', '', '50', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('41', 'Autres créances - Overige vorderingen', 'H', 'A', '', '41', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('407', 'Créances douteuses - Dubieuze debiteuren', 'A', 'A', 'AR_paid', '40', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('442001', 'Fournisseurs essence', 'A', 'L', 'AP', '44', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('608', 'Remises ristournes rabais obtenus - Ontvangen kortingen ristorno''s en rabatten (-)', 'A', 'E', 'IC_cogs', '60', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('612140', 'Internet', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('50', 'Actions propres - Eigen aandelen', 'H', 'A', '', '50', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('6', 'CLASSE 6 -- CHARGES - KOSTEN', 'H', 'E', '', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('611350', 'Entr. & Repar. Voitures & Veh. Mixtes', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('655000', 'Ecarts de conversion de devises', 'A', 'E', 'AR_paid:IC_sale:IC_expense', '65', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('451560', 'TVA DUE CO-CONTRACTANT', 'A', 'L', '', '451', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('609000', 'de matières premières - van grondstofen', 'A', 'E', '', '60', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('411590', 'TVA ACHATS 6%', 'A', 'A', 'AP_tax:IC_taxpart:IC_taxservice', '411', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('411591', 'TVA ACHATS 21%', 'A', 'A', 'AP_tax:IC_taxpart:IC_taxservice', '411', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('411620', 'TVA à régulariser (case 62)', 'A', 'A', '', '411', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('411', 'TVA A RECUPERER - TERUG TE VORDEREN BTW', 'H', 'A', '', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('44', 'Dettes commerciales - Handelsschulden', 'H', 'L', '', '44', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('409', 'Réductions de valeur actées (-) - Geboekte waardevermindering', 'A', 'A', '', '40', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('451540', 'TVA DUE VENTES 6%', 'A', 'L', 'AR_tax:IC_taxpart:IC_taxservice', '451', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('640', 'Charges fiscales de l''exploitation - Bedrijfsbelastingen', 'A', 'E', '', '64', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('713', 'Des Produits finis - In de voorraad gereed product', 'A', 'I', 'IC_sale', '71', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('750', 'Produits immo. financières - Opbrengsten financiële vaste activa', 'A', 'I', '', '75', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('656500', 'Intérêts retards sociaux - Sociale achterst. interest', 'A', 'E', 'AP_amount:IC_expense', '65', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('755000', 'Ecarts de convers. devises - Resultats omrekening vreemde valuta', 'A', 'I', 'IC_sale:IC_income', '75', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('754000', 'Différence de change - Wisselresultaten', 'A', 'I', 'AR_amount:IC_income', '75', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('761', 'Reprises réduct. valeur immo. fin. - Terugneming waardeverm. fin. v. a.', 'A', 'I', '', '76', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('773', 'Impôts étrangers s/résultat - Buitenl. belasting op resultaat', 'A', 'I', '', '77', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('77', 'Régularisation d''impôts, reprises provisions fiscales - Regul. belastingen en terugneming fiscale voorz.', 'H', 'I', '', '77', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('7', 'CLASSE 7 -- PRODUITS - OPBRENGSTEN', 'H', 'I', '', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('411640', 'TVA à recupérer s/NDC émises (case 64)', 'A', 'A', '', '411', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('612300', 'Abonnements & Documentations', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('410', 'Capital appelé, non versé - Opgevraagd, niet-gestort kapitaal', 'A', 'A', '', '41', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('417', 'Créances douteuses - Dubieuze debiteuren', 'A', 'A', '', '416', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('451', 'TVA A PAYER - TE BETALEN BTW', 'H', 'L', '', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('499000', 'Compte d''attente - Wachtrekening', 'A', 'L', '', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('455', 'Rémunerations - Bezoldigingen', 'A', 'L', '', '45', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('601', 'Achat des fournitures - Aankoop van hulpstoffen', 'A', 'E', 'IC_cogs', '60', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('49', 'Comptes de régularisation - Overlopende- en wachtrekeningen', 'H', 'L', '', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('613220', 'Honoraires notaires', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('414100', 'Indeminités s/sinistres à recevoir - Te ontvang. schadevergoed.', 'A', 'A', '', '41', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('42', 'Dettes à plus d''un an écheant dans l''année - Schulden op meer dan één jaar die binnen het jaar verfallen', 'H', 'L', '', '42', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('613311', 'Deplacements étranger train, taxi, etc', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('611151', 'Charges locatives camions/camionnettes', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('432', 'Etabli. crédit, crédits d''acceptation - Acceptkrediten', 'A', 'L', '', '43', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('433', 'Etabl. crédit, dettes cpt. courant - Schulden rekening courant', 'A', 'L', '', '43', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('705100', 'DNS REGISTRY', 'A', 'I', 'AR_amount:IC_income', '70', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('609100', 'de fourniture - van hulpstoffen', 'A', 'E', '', '60', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('656100', 'Frais de banque', 'A', 'E', 'AP_amount:IC_expense', '65', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('620000', 'Administrateurs ou gérants - Bestuurders of zaakvoerders', 'A', 'E', '', '62', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('618', 'Divers', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('65', 'Charges financières', 'H', 'E', '', '65', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('442004', 'VISA - décompte mensuel', 'A', 'L', 'AP_paid', '44', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('620100', 'Personnel de direction - Directiepersoneel', 'A', 'E', '', '62', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('617', 'Personnel intérimaire - Uitzendkrachten', 'A', 'E', '', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('440', 'Fournisseurs - Leveranciers', 'A', 'L', 'AP', '44', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('52', 'Titres à revenu fixe - Vastrentende Effecten', 'H', 'A', '', '52', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('4529', '453 - 459 Dettes salariales et sociales - Bezoldigingen en sociale schulden', 'H', 'L', '', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('620', 'Rémunerations et avant. sociaux directs - Bezolgingen en rechts. sociale voordelen', 'A', 'E', '', '62', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('602', 'Achats services, travaux, études - Aankopen diensten, werk, studies', 'A', 'E', 'IC_cogs', '60', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('612000', 'Eau', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('611351', 'Pneus Voitures & Vehic. Mixtes', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('641', 'Moins-values s/réalis. cour. d''immo. corp. - Minderwa. courante realis. vaste activa', 'A', 'E', '', '64', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('715', 'Des immeubles constr. dest. à la vente - In de voorr. onroe. goederen best. v. verkoop', 'A', 'I', 'IC_sale', '71', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('612400', 'Imprimés & fournitures de bureau', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('414200', 'Subsides en capital à recevoir - Te ontv. kapitaalsubsidies', 'A', 'A', '', '41', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('66', 'Charges exceptionnelles', 'H', 'E', '', '66', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('613230', 'Honoraires huissiers de justice', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('613313', 'Restaurants étranger', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('74', 'Autres produits exploitation - Andere bedrijfsopbrengsten', 'H', 'I', '', '74', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('610', 'Loyers et charges locatives', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('70', 'Chiffre d''affaires - Omzet', 'H', 'I', '', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('751', 'Produits actifs circulants - Opbrengsten uit vlottende activa', 'A', 'I', '', '75', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('705200', 'WEB HOSTING', 'A', 'I', 'AR_amount:IC_income', '70', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('442005', 'AMERICAN EXPRESS - décompte mensuel', 'A', 'L', 'AP_paid', '44', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('762', 'Reprises provisions risq. charg. except. - Terugn. voorz. uitz. risico en kosten', 'A', 'I', '', '76', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('780', 'Prélèvements s/impôts différés - Onttrekking a. uitgesteld. belast.', 'A', 'I', '', '78', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('78', 'Prélèvements réserves immunisées et impôts différés - Onttrek. belast.vrije reserves en de uitgestelde belastingen', 'H', 'I', '', '78', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('53', 'Dépôts à terme - Termijndeposito''s', 'H', 'A', '', '53', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('614100', 'Catalogues et imprimées', 'A', 'I', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('451500', 'TVA DUE ACHATS INCO', 'A', 'L', '', '451', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('613110', 'Assurance vol', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('451543', 'TVA due 2e trimestre', 'A', 'L', '', '451', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('609400', 'de marchandises - van handelsgoederen', 'A', 'E', 'AP_amount:IC_sale', '60', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('613305', 'Collations', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('612010', 'Chauffage', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('612410', 'Fournitures informatiques', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('613250', 'Honoraires sécretariat social', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('611362', 'Control technique voitures', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('482200', 'ASSOCIES - MEMBRES', 'A', 'L', '', '48', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('612530', 'Petit outillage & petit matériel', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('613400', 'Seminaires & Recyclages', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('612540', 'Petit matériel informatique', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('603', 'Sous-traitances générales - Algemene onderaanemingen', 'A', 'E', 'IC_cogs', '60', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('743200', 'COTISATION DE MEMBRE', 'A', 'I', 'AR_amount:IC_income', '74', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('601000', 'Emballages perdus', 'A', 'E', 'IC_cogs', '60', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('230010', 'Inst. techniques acquis. exercice - Installaties m.b.t. dit boekj.', 'A', 'A', 'AP_amount:IC_expense', '23', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('570000', 'CAISSE ESPECES - CONTANTEN', 'A', 'A', 'AR_paid:AP_paid', '57', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('451544', 'TVA due 3e trimestre', 'A', 'L', '', '451', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('411000', 'Cpt. curr. TVA à récuperer - Terug te vord. BTW: saldo BTW r/c', 'A', 'A', '', '411', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('611152', 'Locations machines et outils', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('56', 'Office des chèques postaux - Postchèque en girodienst', 'H', 'A', '', '56', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('411593', 'TVA RECUP. 1ER TRIMESTRE TOTAL (case 59)', 'A', 'A', '', '411', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('51', 'Actions et parts - Aandelen', 'H', 'A', '', '51', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('510010', 'Montants non-appelés (-) - Niet opgevraagde bedragen aan. (-)', 'A', 'A', '', '51', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('609500', 'd''immeubles achétés destinés à vente - van gek. onroer. goederen best. v. verkoop', 'A', 'E', '', '60', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('58', 'Virements interns - Interne overboekingen', 'H', 'A', '', '58', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('416', 'Créances diverses - Diverse vorderingen ', 'H', 'A', '', '416', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('416200', 'Cpt. courant associés - Rekening-courant vennoten', 'A', 'A', '', '416', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('418', 'Cautionnements versés en numéraire - Borgtochten betaald in contanten', 'A', 'A', '', '416', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('67', 'Impôt sur le résultat', 'H', 'E', '', '67', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('654', 'Différence de change', 'A', 'E', 'AP_amount', '65', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('642', 'Moins-values s/réalis. créances com. - Minderwa. realis. handelsvorderingen', 'A', 'E', '', '64', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('717', 'Des commandes en cours exécution - In de bestelling in uitvoering', 'A', 'I', 'IC_sale', '71', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('752', 'Plus-values réalis. d''actifs circulants - Meerwaar. realis. v. vlottende activa', 'A', 'I', '', '75', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('763', 'Plus-values s/réalis. actifs immo. - Meerwaar. realis. vaste a.', 'A', 'I', '', '76', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('789', 'Prélèvements s/réserves immunisées - Onttrekking a. belast.vrije reserves', 'A', 'I', '', '78', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('79', 'Affectations et prélèvements - Resultaatverwerking', 'H', 'I', '', '79', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('412', 'Impôts, précomptes à récupérer - Terug te vorderen belast. en voorheffingen', 'A', 'A', '', '41', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('120', 'Plus-values de réévaluation sur immo. incorp. - Herwaarderingsmeerwaarde', 'A', 'L', '', '12', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('121', 'Plus-values de réévaluation sur immo. corp. - Herwaarderingsmeerwaarde', 'A', 'L', '', '12', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('122', 'Plus-values de réévaluation sur immo. financiers - Herwaarderingsmeerwaarde', 'A', 'L', '', '12', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('123', 'Plus-values de réévaluation sur stocks - Herwaarderingsmeerwaarde', 'A', 'L', '', '12', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('124', 'Reprises de réduction de valeur sur placements trésorerie - Herwaarderingsmeerwaarde', 'A', 'L', '', '12', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('12', 'Plus-values de réévaluation - Herwaarderingsmeerwaarde', 'H', 'L', '', '12', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('110', 'Primes d''émission - Uitgiftepremies', 'A', 'L', '', '11', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('11', 'Primes d''émission - Uitgiftepremies', 'H', 'L', '', '11', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('643', '643-648 Charges d''exploitation diverses - Diverse berijfskosten', 'H', 'E', '', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('612100', 'Telephone', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('10', 'Capital - Kapitaal', 'H', 'L', '', '10', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('1', 'CLASSE 1 -- CAPITAL PROPRE, ... - EIGEN VERMOGEN, ...', 'H', 'L', '', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('60', 'Approv. et marchandises', 'H', 'E', '', '60', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('717000', 'Valeur d''acquisition - Aanschaffingswaarde', 'A', 'I', '', '717', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('68', 'Transferts comptes immunisées et impôts différés', 'H', 'E', '', '68', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('130', 'Réserve légale - Wettelijke reserve', 'A', 'L', '', '13', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('131100', 'Autres réserves indisponibles - Andere onbeschikbare reserves', 'A', 'L', '', '13', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('132', 'Réserves immunisées - Belastingvrije reserves', 'A', 'L', '', '13', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('131000', 'Réserves pour actions propres - Reserve voor eigen aandelen', 'A', 'L', '', '13', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('133', 'Réserves disponibles - Beschikbare reserves', 'A', 'L', '', '13', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('101', 'Capital non appelé (-) - Niet opgevraagd kapitaal (-)', 'A', 'L', '', '10', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('14', 'Bénéfice/perte reporté(e) - Overgedragen winst/verlies', 'H', 'L', '', '14', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('100', 'Capital souscrit - Geplaatst kapitaal', 'A', 'L', '', '10', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('601010', 'Emballages recuperables', 'A', 'E', 'IC_cogs', '60', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('140', 'Bénéfice/perte reporté(e) - Overgedragen winst/verlies', 'A', 'Q', '', '14', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('15', 'Subsides en capital - Kapitaalsubsidies', 'H', 'L', '', '15', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('419', 'Réductions de valeur actées (-) - Geboekte waardevermindering (-)', 'A', 'A', '', '416', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('612450', 'Photocopies-Photographies', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('131', 'Réserves indisponibles - Onbeschikbare reserves', 'A', 'L', '', '13', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('16', 'Provisions et impôts différés - Voorz. en uitgestelde belastingen', 'H', 'L', '', '16', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('160', 'Provisions pensions et obligations - Voorz. pensioenen en soortg. verplichtingen', 'A', 'L', '', '16', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('161', 'Provisions charges fiscales - Voorz. belastingen', 'A', 'L', '', '16', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('162', 'Provisions gros entretiens et réparations - Voorz. grote herstel/onderh.', 'A', 'L', '', '16', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('163', 'Provisions autres risques-charges - Voorzieningen voor Lijfrente', 'A', 'L', '', '16', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('753', 'Subsides en capital et intérêts - Kapitaal- en interestsubsidies', 'A', 'I', '', '75', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('705000', 'Prestations de services - Verkopen en dienstprestaties', 'A', 'I', '', '70', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('764', '764-769 Autres produits execptionnels - Andere uitz. opbrengsten', 'H', 'I', '', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('790', 'Bénéfice reporté exercice précéd. - Overgedragen winst vorige boekj.', 'A', 'I', '', '79', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('168200', 'Impôts diff. s/+value immo. corp. - Uitg. belast./meerwa./mat. v.a.', 'A', 'L', '', '16', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('604', 'Achats marchandises - Aankopen van handelsgoederen', 'A', 'E', 'IC_cogs', '60', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('168000', 'Impôts diff. s/subsides en capital - Uitgest. belast./Kapitaalsubsidie', 'A', 'L', '', '16', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('613265', 'Honoraires d''autres', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('620800', 'Assurance revenus garantis', 'A', 'E', 'AP_amount:IC_expense', '62', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('168800', 'Impôts différés étrangers - Uitg. belast. buitenland', 'A', 'L', '', '16', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('17', 'Dettes à plus d''un an - Schulden op meer dan een jaar', 'H', 'L', '', '17', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('150', 'Montants obtenus - Kapitaalsubsidies', 'A', 'L', '', '15', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('172000', 'Dettes location fin. et assimilées - Leasingschuld. van vaste activa', 'A', 'L', '', '17', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('231010', 'Mach. et gros mat. acquis. exercice - Machines m.b.t. dit boekj.', 'A', 'A', 'AP_amount:IC_expense', '23', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('451610', 'TVA à régulariser (case 61)', 'A', 'L', '', '45', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('456', 'Pécules de vacances - Vakantiegeld', 'A', 'L', '', '45', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('176', 'Acomptes reçus sur commandes', 'A', 'L', '', '17', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('47', 'Dettes affectation résultat - Schulden besteming resultaat', 'H', 'L', '', '47', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('620200', 'Employés - Bedienden', 'A', 'E', '', '62', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('178', 'Cautionnements reçu en numéraire - Borgtocht. ontvang. in contanten', 'A', 'L', '', '17', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('179', 'Dettes diverses - Overige schulden', 'A', 'L', '', '17', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('174', 'Autres emprunts - Overige schulden', 'A', 'L', '', '17', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('2', 'CLASSE 2 -- FRAIS D''ETABLISSEMENT, ACTIFS IMMOBILISES, ... - OPRICHTINGSKOSTEN, VASTE ACTIVA, ...', 'H', 'A', '', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('20', 'Frais d''établissement - Oprichtingskosten', 'H', 'A', '', '20', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('200', 'Frais de constitution - Kosten van oprichting', 'A', 'A', '', '20', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('200000', 'Fr. const. acquis. anterieurs - Kost. opricht./kapitaalverhoging', 'A', 'A', '', '20', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('605', 'Achats d''immeubles destinés vente - Aankopen onroer. goederen bestemd v. verkoop', 'A', 'E', 'IC_cogs', '60', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('61', 'Services et biens divers', 'H', 'E', '', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('69', 'Affectations et prélèvements', 'H', 'E', '', '69', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('200900', 'Fr. const. amort. anterieur - Afschr. kost. opricht./kap.verh. vorig', 'A', 'A', '', '20', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('200910', 'Fr. const. amort. de l''exercice - Afschr. kost. opricht./kap.verh. dit', 'A', 'A', '', '20', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('612020', 'Electricité', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('202', 'Autres frais d''établissement - Overige oprichtingskosten', 'A', 'A', '', '20', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('204', 'Frais de restructuration - Herstructureringskosten', 'A', 'A', '', '20', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('201', 'Frais d''émission d''emprunts - Kosten bij uitgifte van leningen', 'A', 'A', '', '20', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('21', 'Immobilisations incorporelles - Immateriele vaste activa', 'H', 'A', '', '21', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('211', 'Concessions, brevets, licences, ... - Consessies, octrooien, licenties, ...', 'A', 'A', '', '21', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('210', 'Frais de recherches et developpement - Kosten van onderzoek en ontwikkeling', 'A', 'A', '', '21', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('212', 'Goodwill', 'A', 'A', '', '21', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('213', 'Acomptes versés - Vooruitbetalingen', 'A', 'A', '', '21', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('214', 'Surprix afférents acquisition d''une participation', 'A', 'A', '', '21', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('22', 'Terrains et constructions - Terreinen en gebouwen', 'H', 'A', '', '22', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('743', '743-749 Produits d''exploitation divers - Diverse bedrijfsopbrengsten', 'H', 'I', '', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('580000', 'TRANSFERTS INTERNES DES FONDS - TRANSFERTEN', 'A', 'A', 'AR_paid:AP_paid', '58', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('221', 'Constructions - Gebouwen', 'A', 'A', '', '22', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('717100', 'Bénéfice pris en compte - Toegerekende winst', 'A', 'I', '', '717', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('756', '756-759 Produits financiers divers - Diverse financiële opbrengsten', 'H', 'I', '', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('222', 'Terrains bâtis - Bebouwde terreinen', 'A', 'A', '', '22', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('13', 'Réserves - Reserves', 'H', 'L', '', '13', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('223', 'Autres droits réels sur immeubles - Overige zakelijke rechten op onroe.', 'A', 'A', '', '22', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('221000', 'Constructions acquis. anterieurs - Geb. aanschaffingsprijs vorig. boekj.', 'A', 'A', '', '22', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('411594', 'TVA RECUP. 2E TRIMESTRE TOTAL', 'A', 'A', '', '411', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('771', 'Impôts belges sur le résultat - Belgische belasting op het resultaat', 'A', 'I', '', '77', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('23', 'Installations, machines et outillage - Installaties, machines en uitrusting', 'H', 'A', '', '23', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('230', 'Installations - Installaties', 'A', 'A', '', '23', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('230000', 'Inst. techniques acquis. anterieurs - Installaties m.b.t. vorig boekj.', 'A', 'A', '', '23', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('620300', 'Ouvriers - Arbeiders', 'A', 'E', '', '62', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('231', 'Machines', 'A', 'A', '', '23', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('791', 'Prélèvement s/capital et primes émissions - Onttrek. kapitaal e. uitgiftepre.', 'A', 'I', '', '79', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('220', 'Terrains - Terreinen', 'A', 'A', '', '22', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('237', 'Outillage - Uitrusting', 'A', 'A', '', '23', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('231000', 'Mach. et gros mat. acquis anterieurs - Machines m.b.t. vorig boekj.', 'A', 'A', '', '23', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('613100', 'Assurance incendie', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('613275', 'Publications légales', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('237000', 'Outillage acquis. anterieurs - Uitrusting m.b.t. vorig boekj.', 'A', 'A', '', '23', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('24', 'Mobilier et matériel roulant - Meubilair en rollend materieel', 'H', 'A', '', '24', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('2401', 'Matériel de bureau - Bureaumaterieel', 'A', 'A', '', '24', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('2402', 'Matériel informatique - Hardware', 'A', 'A', '', '24', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('241', 'Voiture - Rollend materieel (wagen)', 'A', 'A', '', '24', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('62', 'Rémunérations, charges sociales et pensions', 'H', 'E', '', '62', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('25', 'Immobilis. en loc-financement - Vaste activa in leasing of op grond', 'H', 'A', '', '25', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('612120', 'GSM', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('242', 'Camions - Rollend materieel (vrachtwagen)', 'A', 'A', '', '24', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('250', 'Terreins loc-fin - Terreinen in leasing', 'A', 'A', '', '25', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('251', 'Install., machines loc-fin - Installaties, machines in leasing', 'A', 'A', '', '25', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('309', 'Réduction val. act. mat. premières (-) - Geboekte waardev. grondst. (-)', 'A', 'A', '', '30', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('253', 'Matériel en loc-fin - Uitrusting in leasing', 'A', 'A', '', '25', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('254', 'Mat. inform. en loc-fin- Hardware in leasing', 'A', 'A', '', '25', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('255', 'Mat. roulant en loc-fin - Rollend materieel leasing', 'A', 'A', '', '25', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('26', 'Autres immobilisations corp. - Andere materiele vaste activa', 'H', 'A', '', '26', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('260', 'Amenagement locaux loués - Inrichtingskost. gehuurde gebouw', 'A', 'A', '', '26', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('613130', 'Assurance crédit', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('300', 'Approv. matière première - Grondstoffen', 'A', 'A', 'IC', '30', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('411595', 'TVA RECUP. 3E TRIMESTRE TOTAL', 'A', 'A', '', '411', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('48', 'Dettes diverses - Diverse schulden', 'H', 'L', '', '48', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('270', 'Immo. corp. en cours et acomptes versés - V. activa in aanbouw en vooruit', 'A', 'A', '', '27', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('613300', 'Deplacements Belg. train, taxi, etc', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('27', 'Immo. corp. en cours et acomptes versés - V. activa in aanbouw en vooruit ', 'H', 'A', '', '27', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('252', 'Mobilier en loc-fin - Meubilair in leasing', 'A', 'A', '', '25', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('168100', 'Impôts diff. s/+value immo. incorp. - Uitg. belast./meerwa./immat. v.a.', 'A', 'L', '', '16', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('168700', 'Impôts diff. s/+value fonds publ. belges - Uitg. bel./meerwa./belg. effecten', 'A', 'L', '', '16', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('28', 'Immobilisations financiers - Financiele vaste activa', 'H', 'A', '', '28', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('620400', 'Autres membres du personnel - Andere personeelsleden', 'A', 'E', '', '62', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('649', 'Ch. exploit. portées actif c. frais de restruct. (-) - Als herstruct.kost. geactiv. bedrijfsk. (-)', 'A', 'E', '', '64', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('71', 'Variation stocks et commandes en cours - Wijzigingen vorraden en in de bestellingen in uitvoering', 'H', 'I', '', '71', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('740', 'Subsides et montants compensat. - Subsidies en compens. bedragen', 'A', 'I', '', '74', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('760', 'Reprises amort. et réduct. valeur - Terugneming afschr. en waardeverm.', 'A', 'E', '', '76', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('280', 'Participations entreprises liées - Aanschaffingsw. deeln. verb. ond.', 'A', 'A', '', '28', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('771000', 'Régularisations impôts dus versés - Regularisiering versch. of betaal. belast.', 'A', 'I', '', '771', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('281', 'Créances s/entreprises liées - Vorderingen op rekening', 'A', 'A', '', '28', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('283', 'Créances s/entr. avec lien de part.', 'A', 'A', '', '28', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('284', 'Autres actions et parts - Aanschaffingsw. and. aand.', 'A', 'A', '', '28', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('285', 'Autres créances -  Overige vorderingen', 'A', 'A', '', '28', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('288', 'Cautions versés en numeraire - Borgtocht. betaald in contanten', 'A', 'A', '', '28', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('792', 'Prélèvements réserves - Onttrekking reserves', 'A', 'I', '', '79', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('173100', 'Promesses banque - Promessen bank', 'A', 'L', '', '17', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('290', 'Créances commerciales - Commerciele vorderingen', 'A', 'A', '', '29', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('441', 'Effets à payer - Te betalen wissels', 'A', 'L', '', '44', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('430', 'Emprunts en compte à terme fixe - Leningen op rekeningen vaste termijn', 'A', 'L', '', '43', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('451630', 'TVA sur NDC reçues (case 63)', 'A', 'L', '', '45', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('29', 'Créances à plus d''un an - Vorderingen op meer dan een jaar', 'H', 'A', '', '29', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('45', 'Dettes fiscales, salariales, sociales - Schulden m. betrekking tot belastingen, bezoldingen en sociale lasten', 'H', 'L', '', '45', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('452', 'Impôts et taxes à payer', 'A', 'L', '', '45', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('290000', 'Clients > 1 an - Handelsdebiteuren > 1 jaar', 'A', 'A', '', '29', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('290100', 'Effects à recevoir >1 an - Te innen wissels > 1 jaar', 'A', 'A', '', '29', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('290600', 'Acptes versés s/immo. financ. > 1 an - Vooruitbetalingen > 1 jaar', 'A', 'A', '', '29', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('290700', 'Créances douteuses - Dubieuze debiteuren >1 jaar', 'A', 'A', '', '29', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('290900', 'Réduction valeur actée cr.dout. - Geboekte waardevermindering (-)', 'A', 'A', '', '29', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('291', 'Autres Créances > 1 an - Over. vorderingen op rekening > 1 j.', 'A', 'A', '', '29', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('30', 'Approv. matières premières - Grondstoffen', 'H', 'A', '', '30', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('3', 'CLASSE 3 -- STOCK ET COMMANDES EN COURS - GRONDSTOFFEN', 'H', 'A', '', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('453', 'Précompte retenus - Ingehouden voorheffingen', 'A', 'L', '', '45', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('459', 'Autres dettes sociales - Andere sociale schulden', 'A', 'L', '', '45', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('31', 'Approv. et fournitures - Hulpstoffen', 'H', 'A', '', '31', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('431', 'Etabli. crédit, promesses - Kreditinstellingen, promessen', 'A', 'L', '', '43', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('400', 'Clients - Handelsdebiteuren', 'A', 'A', 'AR', '40', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('319', 'Réduction valeur actées (-) - Geboekte waardev. hulpstoffen (-)', 'A', 'A', '', '31', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('32', 'Encours de fabrication - Goederen in bewerking', 'H', 'A', '', '32', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('708', 'Remis. rabais ristourn. accordés (-) - Toegek. korting. ristorno''s rabat. (-) ', 'A', 'I', 'AR_amount:IC_expense', '70', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('741', 'Plus-values réalis. cour. immo. corp. -  Meerwaar. cour. realis. materiële v.a.', 'A', 'I', '', '74', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('33', 'Produits finis - Gereed Product', 'H', 'A', '', '33', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('72', 'Production immobilisée - Geproduceerde vaste activa', 'H', 'I', '', '72', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('656600', 'Intérêts rétards com. - Com. achterst. interest', 'A', 'E', 'AP_amount:IC_expense', '65', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('34', 'Marchandises - Handelsgoederen', 'H', 'A', '', '34', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('221010', 'Construction acquis. de l''exercice - Geb. aanschaffingsprijs dit boekj.', 'A', 'A', 'AP_amount:IC_expense', '22', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('760000', 'sur immobilisations incorp. - op immateriële vaste activa', 'A', 'I', '', '760', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('35', 'Immeubles destinés vente - Onroerende goederen bestemd. v. verk.', 'H', 'A', '', '35', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('771100', 'Régul. d''impôts estimés - Regul. geraamde belasting', 'A', 'I', '', '771', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('793', 'Perte à reporter - Over te dragen verlies', 'A', 'I', '', '79', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('4', 'CLASSE 4 -- CREANCES ET DETTES A UN AN AU PLUS - VORDERINGEN EN SCHULDEN OP TEN HOOGTE EEN JAAR', 'H', 'A', '', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('552000', 'KBC56', 'A', 'A', 'AR_paid:AP_paid', '55', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('411596', 'TVA RECUP. 4E TRIMESTRE TOTAL', 'A', 'A', '', '411', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('444', 'Factures à recevoir - Te ontvangen facturen', 'A', 'L', 'AP_paid', '44', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('40', 'Créances commerciales - Handelsvorderingen', 'H', 'A', '', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('329', 'Réduction valuer actée (-) - Geboekte waardeverminderingen (-) ', 'A', 'A', '', '32', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('339', 'Réductions de valeur actées (-) - Geboekte waardeverminderingen (-) ', 'A', 'A', '', '33', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('340', 'Marchandises - Handelsgoederen', 'A', 'A', 'IC', '34', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('451000', 'COMPTE COURANT TVA DUE', 'A', 'L', '', '451', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('349', 'Réduct. valeur actées (-) - Geboekte waardeverminderingen (-) ', 'A', 'A', '', '34', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('359', 'Réductions valeur actées (-) - Geboekte waardeverminderingen (-) ', 'A', 'A', '', '35', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('613150', 'Assurance tous risques matériel élec.', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('63', 'Amortissements, réd. val., provi. risques et charges - Afschrijvingen waardevermin. en voorzieningen v. risico''s kost.', 'H', 'E', '', '63', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('510000', 'Titres cotés - Aandelen op beurs', 'A', 'A', '', '51', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('5', 'CLASSE 5 - PLACEMENTS DE TRESORIERIE - LIQUIDE MIDDELEN / GELDBELEGGINGEN', 'H', 'L', '', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('54', 'Valeurs échues à encaissement - Te incasseren verfallen waarden', 'H', 'A', '', '54', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('55', 'Banque - Rekening-courant', 'H', 'A', '', '55', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('613303', 'Restaurants', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('310', 'Valeur d''acquisition - Aanschaffingswaarde hulpstoffen', 'A', 'A', 'IC', '31', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('320', 'Valeur d''acquisition - Aanschaffingsw. goed. bewerking', 'A', 'A', 'IC', '32', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('330', 'Produits finis - Gereed product', 'A', 'A', 'IC', '33', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('350', 'Immeubles - Aanschaffingsw. onr. goed. verkoop', 'A', 'A', 'IC', '35', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('609', 'Variation de stock - Voorraadwijzigingen', 'A', 'E', '', '60', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('621', 'Cotisation patronales d''assur. sociales - Werkgeversbijdragen soc. verzekeringen', 'A', 'E', '', '62', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('451640', 'TVA à recupérer s/NDC émises', 'A', 'L', '', '45', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('454', 'O.N.S.S. - R.S.Z.', 'A', 'L', '', '45', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('640700', 'TVA non-deductible', 'A', 'E', 'AP_tax:IC_taxpart:IC_taxservice', '64', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('401', 'Effets à recevoir - Te innen wissels', 'A', 'A', '', '40', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('414', 'Produits à recevoir - Te innen opbrengsten', 'A', 'A', '', '41', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('450', 'Dettes fiscales estimées - Geramd bedrag der belastingschulden', 'A', 'L', '', '45', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('46', 'Acomptes reçus sur commandes', 'H', 'L', '', '46', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('499100', 'Compte de repartition - Verdelingsrekening', 'A', 'L', 'AR_paid:AP_paid', '', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('553000', 'KBC40', 'A', 'A', 'AR_paid:AP_paid', '55', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('613180', 'Assurance RC professionnelle', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('452500', 'Précompte immobilier - Onroerende voorhoeffing', 'A', 'L', '', '45', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('554000', 'KBC83', 'A', 'A', 'AR_paid:AP_paid', '55', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('612150', 'Frais postaux', 'A', 'E', 'AP_amount:IC_cogs:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('451545', 'TVA due 4e trimestre', 'A', 'L', '', '451', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('200010', 'Fr. const. acquis. de l''exercice - Kost. opricht./kap.verh. dit boekjaar', 'A', 'A', 'AP_amount', '20', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('451542', 'TVA due 1er trimestre (case 54)', 'A', 'L', '', '451', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('451570', 'TVA DUE SUR IMPORTATIONS', 'A', 'L', '', '451', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('540', 'Chèques à encaisser - Te incasseren chèques', 'A', 'A', 'AR_paid:AP_paid', '54', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('611340', 'Entretiens & réparations locaux', 'A', 'E', 'AR_amount:AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('665000', 'Pertes et charges diverses', 'A', 'E', 'AR_paid:AP_amount', '66', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('665200', 'Perte définitive créance douteuse', 'A', 'E', 'AP_amount', '66', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('237010', 'Outillage acquisition exercice - Uitrusting m.b.t. dit boekj.', 'A', 'A', 'AP_amount:IC_expense', '23', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('623600', 'Vêtements de travail employés', 'A', 'E', 'AP_amount:IC_expense', '62', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('612520', 'Emballages perdus', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('240200', 'Mat. informatique acquis anterieurs - Hardware m.b.t. vorig boekj.', 'A', 'A', '', '24', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('240210', 'Matériel informatique acquis. exercice - Hardware m.b.t. dit boekj.', 'A', 'A', 'AP_amount:IC_expense', '24', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('260000', 'Amenagement locaux loués acquis anterieurs - Inrichtingskost. m.b.t. vorig boekj.', 'A', 'A', '', '26', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('240000', 'Mobilier acquis. anterieurs - Meubilair m.b.t. vorig boekj.', 'A', 'A', '', '24', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('240010', 'Mobilier acquis. exercice - Meubilair m.b.t. dit boekj.', 'A', 'A', 'AP_amount:IC_expense', '24', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('240110', 'Mat. bureau acquis. exercice - Bureaumaterieel m.b.t. dit boekj.', 'A', 'A', 'AP_amount:IC_expense', '24', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('240100', 'Mat. bureau acquis. anterieurs - Bureaumaterieel m.b.t. vorig boekj.', 'A', 'A', '', '24', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('241000', 'Voiture acquis. anterieurs - Wagen m.b.t. vorig boekj.', 'A', 'A', '', '24', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('241010', 'Voiture acquis. exercice - Wagen m.b.t. dit boekj. ', 'A', 'A', 'AP_amount:IC_expense', '24', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('57', 'Caisses - Kassen', 'H', 'A', '', '57', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('510200', 'Titrés non-cotés - Aandelen niet op beurs', 'A', 'A', '', '51', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('510090', 'Réduct. valeur actées (-) - Geb. waardev. aandelen (-)', 'A', 'A', '', '51', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('510210', '	Montants non-appelés (-) - Niet opgevraagde bedragen aan. (-)', 'A', 'A', '', '51', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('510290', 'Réduct. valeur actées (-) - Geb. waardev. aandelen (-) ', 'A', 'A', '', '51', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('614700', 'Frais de bonne politique', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('615000', 'Sous-traitants', 'A', 'E', 'AP_amount:IC_expense', '61', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('630000', 'Amort.s/frais.constit.&aug.capi - Afschr.o.opricht./kapitaalverhoging', 'A', 'E', '', '63', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('630210', 'Amort.s/constructions - Afschr. op gebouwen', 'A', 'E', '', '63', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('630200', 'Amort.s/installations - Afschr. op installaties', 'A', 'E', '', '63', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('630220', 'Amort.s/machines - Afschr. op machines', 'A', 'E', '', '63', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('630221', 'Amort.s/outillage - Afschr. op uitrusting', 'A', 'E', '', '63', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('630222', 'Amort.s/mobilier - Afschr. op meubilair', 'A', 'E', '', '63', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('630223', 'Amort.s/mat.bureau - Afschr. op bureaumaterieel', 'A', 'E', '', '63', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('630224', 'Amort.s/mat.informatique - Afschr. op hardware', 'A', 'E', '', '63', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('630230', 'Amort.s/voitures - Afschr. op wagens', 'A', 'E', '', '63', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('640000', 'Taxes circl. voitures - Belasting wagens', 'A', 'E', '', '64', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('652000', 'Moins-value sur réalisation d''actifs circulants', 'A', 'E', '', '65', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('640020', 'Précompte immoblier - Onroerende voorhoeffing', 'A', 'E', '', '64', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('640100', 'Timbres fiscaux', 'A', 'E', '', '64', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('640230', 'Raccordement aux egouts', 'A', 'E', '', '64', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('640310', 'Cotisation dépannage', 'A', 'E', '', '64', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('630225', 'Amort.s/amén. locaux - Afschr. op inrichtingskost', 'A', 'E', '', '63', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('650000', 'Intérêts comm. & frais s/decouvert', 'A', 'E', 'AP_amount:IC_expense', '65', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('656300', 'Intérêts de retards fiscaux - Fiscale achterst. interest', 'A', 'E', 'AP_amount:IC_expense', '65', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('693000', 'Bénéfice à reporter', 'A', 'E', '', '69', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('663750', '-Val.s/materiel informatique', 'A', 'E', '', '66', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('743300', 'Intervention assurance salaires garant.', 'A', 'I', '', '74', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('763750', '+Val.s/mat.informatique', 'A', 'I', '', '76', '0');
INSERT INTO chart (accno, description, charttype, category, link, gifi_accno, contra) VALUES ('406', 'Acomptes versés - Vooruitbetalingen', 'A', 'A', 'AP_paid', '40', '0');
--
INSERT INTO tax (chart_id, rate, taxnumber) VALUES ((SELECT id FROM chart WHERE accno = '411590'), 0.06);
INSERT INTO tax (chart_id, rate, taxnumber) VALUES ((SELECT id FROM chart WHERE accno = '411591'), 0.21);
INSERT INTO tax (chart_id, rate, taxnumber) VALUES ((SELECT id FROM chart WHERE accno = '451540'), 0.06);
INSERT INTO tax (chart_id, rate, taxnumber) VALUES ((SELECT id FROM chart WHERE accno = '451541'), 0.21);
INSERT INTO tax (chart_id, rate, taxnumber) VALUES ((SELECT id FROM chart WHERE accno = '640700'), 0.21);
--
INSERT INTO defaults (setting_key, value) VALUES ('inventory_accno_id', (SELECT 
id FROM chart WHERE accno = '340'));

 INSERT INTO defaults (setting_key, value) VALUES ('income_accno_id', (SELECT id FROM chart WHERE accno = '743200'));

 INSERT INTO defaults (setting_key, value) VALUES ('expense_accno_id', (SELECT id FROM chart WHERE accno = '604'));

 INSERT INTO defaults (setting_key, value) VALUES ('fxgain_accno_id', (SELECT id FROM chart WHERE accno = '755000'));

 INSERT INTO defaults (setting_key, value) VALUES ('fxloss_accno_id', (SELECT id FROM chart WHERE accno = '655000'));

 INSERT INTO defaults (setting_key, value) VALUES ('weightunit', 'kg');
 INSERT INTO defaults (setting_key, value) VALUES ('curr', 'EUR:USD');

commit;
