INSERT INTO gifi (accno, description) VALUES ('PartIV-B,82b', 'Part IV-B, 82b');
INSERT INTO gifi (accno, description) VALUES ('10a&102', 'Line 10a & 102');
INSERT INTO gifi (accno, description) VALUES ('10b&102', 'Line 10b & 102');
INSERT INTO gifi (accno, description) VALUES ('11&103', 'Line 11 & 103');
INSERT INTO gifi (accno, description) VALUES ('16', 'Line 16');
INSERT INTO gifi (accno, description) VALUES ('1a&(9a)', 'Line 1a & (9a)');
INSERT INTO gifi (accno, description) VALUES ('1a', 'Line 1a');
INSERT INTO gifi (accno, description) VALUES ('1b', 'Line 1b');
INSERT INTO gifi (accno, description) VALUES ('1c', 'Line 1c');
INSERT INTO gifi (accno, description) VALUES ('1d', 'Line 1d');
INSERT INTO gifi (accno, description) VALUES ('2&93(a)', 'Line 2 & 93(a)');
INSERT INTO gifi (accno, description) VALUES ('2&93(g)', 'Line 2 & 93(g)');
INSERT INTO gifi (accno, description) VALUES ('2&93f', 'Line 2 & 93f');
INSERT INTO gifi (accno, description) VALUES ('20', 'Line 20');
INSERT INTO gifi (accno, description) VALUES ('21&67', 'Line 21 & 67');
INSERT INTO gifi (accno, description) VALUES ('21&68', 'Line 21 & 68');
INSERT INTO gifi (accno, description) VALUES ('21&69', 'Line 21 & 69');
INSERT INTO gifi (accno, description) VALUES ('22', 'Line 22');
INSERT INTO gifi (accno, description) VALUES ('23', 'Line 23');
INSERT INTO gifi (accno, description) VALUES ('24', 'Line 24');
INSERT INTO gifi (accno, description) VALUES ('25', 'Line 25');
INSERT INTO gifi (accno, description) VALUES ('26', 'Line 26');
INSERT INTO gifi (accno, description) VALUES ('27', 'Line 27');
INSERT INTO gifi (accno, description) VALUES ('28', 'Line 28');
INSERT INTO gifi (accno, description) VALUES ('29', 'Line 29');
INSERT INTO gifi (accno, description) VALUES ('3&94', 'Line 3 & 94');
INSERT INTO gifi (accno, description) VALUES ('30', 'Line 30');
INSERT INTO gifi (accno, description) VALUES ('31', 'Line 31');
INSERT INTO gifi (accno, description) VALUES ('32', 'Line 32');
INSERT INTO gifi (accno, description) VALUES ('33', 'Line 33');
INSERT INTO gifi (accno, description) VALUES ('34', 'Line 34');
INSERT INTO gifi (accno, description) VALUES ('35', 'Line 35');
INSERT INTO gifi (accno, description) VALUES ('36', 'Line 36');
INSERT INTO gifi (accno, description) VALUES ('37', 'Line 37');
INSERT INTO gifi (accno, description) VALUES ('38', 'Line 38');
INSERT INTO gifi (accno, description) VALUES ('39', 'Line 39');
INSERT INTO gifi (accno, description) VALUES ('4&95', 'Line 4 & 95');
INSERT INTO gifi (accno, description) VALUES ('40', 'Line 40');
INSERT INTO gifi (accno, description) VALUES ('41', 'Line 41');
INSERT INTO gifi (accno, description) VALUES ('42', 'Line 42');
INSERT INTO gifi (accno, description) VALUES ('43', 'Line 43');
INSERT INTO gifi (accno, description) VALUES ('45', 'Line 45');
INSERT INTO gifi (accno, description) VALUES ('46', 'Line 46');
INSERT INTO gifi (accno, description) VALUES ('47a', 'Line 47a');
INSERT INTO gifi (accno, description) VALUES ('47b', 'Line 47b');
INSERT INTO gifi (accno, description) VALUES ('48a', 'Line 48a');
INSERT INTO gifi (accno, description) VALUES ('48b', 'Line 48b');
INSERT INTO gifi (accno, description) VALUES ('49', 'Line 49');
INSERT INTO gifi (accno, description) VALUES ('5&96', 'Line 5 & 96');
INSERT INTO gifi (accno, description) VALUES ('50', 'Line 50');
INSERT INTO gifi (accno, description) VALUES ('51a', 'Line 51a');
INSERT INTO gifi (accno, description) VALUES ('51b', 'Line 51b');
INSERT INTO gifi (accno, description) VALUES ('52', 'Line 52');
INSERT INTO gifi (accno, description) VALUES ('53', 'Line 53');
INSERT INTO gifi (accno, description) VALUES ('54', 'Line 54');
INSERT INTO gifi (accno, description) VALUES ('55a', 'Line 55a');
INSERT INTO gifi (accno, description) VALUES ('55b', 'Line 55b');
INSERT INTO gifi (accno, description) VALUES ('56', 'Line 56');
INSERT INTO gifi (accno, description) VALUES ('57a', 'Line 57a');
INSERT INTO gifi (accno, description) VALUES ('57b', 'Line 57b');
INSERT INTO gifi (accno, description) VALUES ('58', 'Line 58');
INSERT INTO gifi (accno, description) VALUES ('60', 'Line 60');
INSERT INTO gifi (accno, description) VALUES ('61', 'Line 61');
INSERT INTO gifi (accno, description) VALUES ('62', 'Line 62');
INSERT INTO gifi (accno, description) VALUES ('63', 'Line 63');
INSERT INTO gifi (accno, description) VALUES ('64a', 'Line 64a');
INSERT INTO gifi (accno, description) VALUES ('64b', 'Line 64b');
INSERT INTO gifi (accno, description) VALUES ('65', 'Line 65');
INSERT INTO gifi (accno, description) VALUES ('6a&97a', 'Line 6a & 97a');
INSERT INTO gifi (accno, description) VALUES ('6a&97b', 'Line 6a & 97b');
INSERT INTO gifi (accno, description) VALUES ('6a&98', 'Line 6a & 98');
INSERT INTO gifi (accno, description) VALUES ('6b&97a', 'Line 6b & 97a');
INSERT INTO gifi (accno, description) VALUES ('6b&97b', 'Line 6b & 97b');
INSERT INTO gifi (accno, description) VALUES ('6b&98', 'Line 6b & 98');
INSERT INTO gifi (accno, description) VALUES ('7&99', 'Line 7 & 99');
INSERT INTO gifi (accno, description) VALUES ('8a-(A)&100', 'Line 8a-(A) & 100');
INSERT INTO gifi (accno, description) VALUES ('8a-(B)&100', 'Line 8a-(B) & 100');
INSERT INTO gifi (accno, description) VALUES ('8b-(A)&100', 'Line 8b-(A) & 100');
INSERT INTO gifi (accno, description) VALUES ('8b-(B)&100', 'Line 8b-(B) & 100');
INSERT INTO gifi (accno, description) VALUES ('9a&101', 'Line 9a & 101');
INSERT INTO gifi (accno, description) VALUES ('PartIV-A&82b', 'Part IV-A & 82b');
INSERT INTO gifi (accno, description) VALUES ('PartIV-A', 'Part IV-A');
INSERT INTO gifi (accno, description) VALUES ('capitalized', 'capitalized');
INSERT INTO gifi (accno, description) VALUES ('contra1a', 'contra Line 1a');
